### ISSUE TITLE
Alfa AWUS036NHR and Alfa AWUS036H

### ISSUE THREAD

**Issue by djdisikd** [wifiphisher/wifiphisher#1003]
Do they both support AP mode and monitor mode?

Which one is the best option?

**Comment by sophron** [comment]
You can find a list of cards that appear to be working for other users: https://github.com/wifiphisher/wifiphisher/issues/558

**Comment by djdisikd** [comment]
Alfa AWUS036H and Alfa AWUS036HR are both the same?
