### ISSUE TITLE
"Handshake capture does not exist."

### ISSUE THREAD

**Issue by zppinto** [wifiphisher/wifiphisher#1016]
When setting up a handshake with "-hC" option it always show the message "Handshake capture does not exist."
I already tried with 2 different handshakes from different networks and the same message is shown.
I analysed both handshakes and they contain a valid handshake.

```
root@kali:~/wifiphisher/bin# ./wifiphisher -hC capture.cap 
[*] Starting Wifiphisher 1.4GIT ( https://wifiphisher.org ) at 2018-10-11 14:36
[+] Timezone detected. Setting channel range to 1-13
[-] Handshake capture does not exist.

```

**Comment by JetseVerschuren** [comment]
Can you post your capture file?

**Comment by zppinto** [comment]
Of course.
[handshake_capture.cap.zip](https://github.com/wifiphisher/wifiphisher/files/2469424/handshake_capture.cap.zip)

**Comment by sophron** [comment]
Thanks for posting this. I'll have a look soon.

**Comment by anakin1028** [comment]
@zppinto : can you give the full path of the file to the program. From the code:
```python
if args.handshake_capture and not os.path.isfile(
                args.handshake_capture):
            sys.exit('[' + constants.R + '-' + constants.W +
                     '] Handshake capture does not exist.')

```
This error message means the program doesn't find your capture file rather than not containing the correct handshake. And I have checked your captured file, it looks for me. So try to give full path of the capture file, and run the program again. See if this works for you. Thanks.

**Comment by zppinto** [comment]
@anakin1028 you're absolutely right! I just tried with the full path to handshake file and the program runs as expected. No more handshake error!
Thank you very much for your help.
Although as suggestion to the developer, a full path example should be given in the Readme example. Or even better... instead of a path to file in the code, the current folder path should be considered.
