### ISSUE TITLE
Turkish Language Support for Fake Wifi Connect?

### ISSUE THREAD

**Issue by hasanalizxc** [wifiphisher/wifiphisher#1022]
Dear Creator,

Hope you are fine. Does it have TR language support for Wifi Login page?

Thanks in advance.

**Comment by sophron** [comment]
Thank you.

We don't offer a language option. A user may manually edit the HTML files accordingly.

**Comment by hasanalizxc** [comment]
Which file or files should i need for wifi login page and other scenarios? I will make all of them.

**Comment by sophron** [comment]
You will find the HTML files under `wifiphisher/data/phishing-pages`.

**Comment by hasanalizxc** [comment]
I found them despite i am newbie.
