### ISSUE TITLE
Android Pie has a problem with Popup Login Phishing Page, it does not show "Login to network connection"

### ISSUE THREAD

**Issue by BinJeremy** [wifiphisher/wifiphisher#1030]
I use android 9 and try wifiphisher but it not show popup " Login to connect " phising page , how to fix it with android 9 ?

**Comment by BinJeremy** [comment]
Anybody help me ? Please

**Comment by sophron** [comment]
You need to provide more details. I'm not sure I understand what exactly were you expecting to happen. 

As I mentioned on #1029 different OS react on a different ways. If you connect to the same Evil Twin twice, it may not prompt the user to follow the captive portal.

**Comment by sophron** [comment]
Is your issue the same as #1029 or are you describing something different?

**Comment by BinJeremy** [comment]
> Is your issue the same as #1029 or are you describing something different?

It's the same

**Comment by sophron** [comment]
Let's continue there then.
