### ISSUE TITLE
adding a malicious apk taking  wifi  password  Scenario ?

### ISSUE THREAD

**Issue by minanagehsalalma** [wifiphisher/wifiphisher#1031]
like

1- we asks him to download the wifi password in the captive portal page
2- he downloads the password.apk
3- installs it
4- we get the session in the meterpreter
5- automatically turn on keylogging and removes the target network from his saved wifis list
6- we disconnects him from our network
7- he tries to type his password on his network
8- he auto connects to our network so we get the meterpreter session again so we can try the keylogged password on the handshake if it's correct we turn off the rouge ap ... if it's wrong we disconnects him again from our network after deleting his network from the saved list

or

8 (2) - after step number five we turn off our fake AP and definitely he will type the correct password on his AP... then we get back the password after he gets the internet connection back
.
even an [qr code that downloads the apk may help](https://youtu.be/upvkwPPDZYk?t=153)
case it's a well known thing by now that you can connect to wifi by scanning qr codes 
thanks for reading my suggestion :)

**Comment by sophron** [comment]
I am not sure I understand what you want to achieve. 

We have a guide on how to create a custom phishing scenario: https://wifiphisher.readthedocs.io/en/latest/custom_phishing_scenario.html
