### ISSUE TITLE
[*] Starting Wifiphisher 1.4GIT ( https://wifiphisher.org ) at 2018-11-08 19:13 [+] Timezone detected. Setting channel range to 1-13 [+] Selecting wfphshr-wlan0 interface for the deauthentication attack [+] Selecting wlan0 interface for creating the rogue Access Point [+] Changing wlan0 MAC addr (BSSID) to 00:00:00:5c:6d:0a [+] Changing wlan0 MAC addr (BSSID) to 00:00:00:f5:19:7d [*] Cleared leases, started DHCP, set up iptables [+] Selecting Network Manager Connect template [*] Starting the fake access point... [+] Show your support! [+] Follow us: https://twitter.com/wifiphisher [+] Like us: https://www.facebook.com/Wifiphisher [+] Captured credentials: [!] Closing

### ISSUE THREAD

**Issue by weamoo1996** [wifiphisher/wifiphisher#1034]
Before opening a new issue, please make sure that what you are about to report has not been reported already or is not included on the FAQ page. If not, use the following template for reporting.

Please keep in mind that our developers will prioritize your issue if you provide a detailed and extensive description.

**Version**: Use `git show | grep commit` command and paste here the output.

**Description**: Give a more analytical description here. Let us know how we can reproduce the reported issue. Detail the characteristics of your machine (e.g. Linux distribution and wireless card capabilities) and of the victim devices too (e.g. OS or web browser) if possible. The output of the `iw list` and `iwconfig` commands may also be helpful here.

**Script output**: Paste the output of the tool, including any stack traces.

**Comment by sophron** [comment]
Duplicate (#923).

**Comment by weamoo1996** [comment]
I don't understand you
