### ISSUE TITLE
Wont keep internet access

### ISSUE THREAD

**Issue by Mikewins1** [wifiphisher/wifiphisher#1042]
With no internet access the victims network mannager tells the victim there is no internet and requires them to click connect anyway.  Most people wont.  How to launch wifiphisher with internet access?

**Comment by Mikewins1** [comment]
With no internet access the victims network mannager tells the victim there is no internet and requires them to click connect anyway.  Most people wont.  How to launch wifiphisher with internet access?

**Comment by Mikewins1** [comment]
Yes. Because it ssys you have to use that argument with - eI or - aI. So I have tried. I haven't tried having it connected through ethernet so I will try that but usually you don't have access to ethernet

**Comment by sophron** [comment]
I have posted how you can do use a wireless interface for Internet connectivity here: https://github.com/wifiphisher/wifiphisher/pull/939#issuecomment-439046977

We will automate the process in the near future.
