### ISSUE TITLE
Ip tables message 

### ISSUE THREAD

**Issue by Dice2048** [wifiphisher/wifiphisher#1044]
**I have a Raspberry Pi 2 with a fresh install of Kali 2018.4
Updated and upgraded in total (no updates left)

Downloaded and installed WifiPhisher 1.4 from Git. (fresh)**
```bash
root@kali:~# lsusb
Bus 001 Device 005: ID 0cf3:9271 Atheros Communications, Inc. AR9271 802.11n
Bus 001 Device 006: ID 0bda:8812 Realtek Semiconductor Corp. RTL8812AU 802.11a/b/g/n/ac WLAN Adapter
Bus 001 Device 003: ID 0424:ec00 Standard Microsystems Corp. SMSC9512/9514 Fast Ethernet Adapter
Bus 001 Device 002: ID 0424:9514 Standard Microsystems Corp. SMC9514 Hub
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
```
Two wlan adapters capable of monitoring and packet injecting .

Starting the wifiphiser : 
```bash
root@kali:~# wifiphisher
[*] Starting Wifiphisher 1.4GIT ( https://wifiphisher.org ) at 2018-12-06 09:00
[+] Timezone detected. Setting channel range to 1-13
[+] Selecting wlan1 interface for the deauthentication attack
[+] Selecting wlan0 interface for creating the rogue Access Point
[+] Changing wlan0 MAC addr (BSSID) to 00:00:00:8e:3c:b1
[+] Changing wlan0 MAC addr (BSSID) to 00:00:00:ad:c4:72
No handlers could be found for logger "wifiphisher.common.utilities"
[*] Cleared leases, started DHCP, set up iptables
[+] Selecting Firmware Upgrade Page template
[*] Starting the fake access point...
[*] Starting HTTP/HTTPS server at ports 8080, 443
[+] Show your support!
[+] Follow us: https://twitter.com/wifiphisher
[+] Like us: https://www.facebook.com/Wifiphisher
[+] Captured credentials:
ERROR:wifiphisher.common.utilities:iptables -F has failed with the following error:
iptables: Operation not supported.

ERROR:wifiphisher.common.utilities:iptables -X has failed with the following error:
iptables: Operation not supported.

ERROR:wifiphisher.common.utilities:iptables -t nat -F has failed with the following error:
iptables: Operation not supported.

ERROR:wifiphisher.common.utilities:iptables -t nat -X has failed with the following error:
iptables: Operation not supported.

[!] Closing
```

I am attacking my own AP and am not presented with the firmware upgrade portal.

Spoke to one on Facebook who told me to open an issue here.

**Comment by Dice2048** [comment]
Version of Iptables

root@kali:~# iptables -V
iptables v1.8.2 (nf_tables)

I have not activated or added any iptable entries

**Comment by blackHatMonkey** [comment]
@Dice2048 Thanks for opening an issue.
Can you run the following command:
```bash
sudo iptables -F
```
and paste the output please.

**Comment by Dice2048** [comment]
> @Dice2048 Thanks for opening an issue.
> Can you run the following command:
> 
> ```shell
> sudo iptables -F
> ```
> 
> and paste the output please.

root@kali:~# iptables -F
iptables: Operation not supported.
root@kali:~# sudo iptables -F
iptables: Operation not supported.
root@kali:~#

**Comment by blackHatMonkey** [comment]
@sophron Have you seen anything like this before?

**Comment by Dice2048** [comment]
Reinstalling;

**Comment by Dice2048** [comment]
Unable to reproduce the iptables

In the mean time i have replaced the Rpi with a 3+ and reinstalled again.
That Kali distro installs iptables 1.6.2, not the 1.8.2 in the opening post.

Other problems occur but not this anymore

Thanks for the time

**Comment by mmomasters** [comment]
iptables 1.8.2 is now on latest Kali 2019.1

**Comment by N2Network** [comment]
I was able to fix this error in Kali by running the following command 

> sudo update-alternatives --config iptables

One that and select 

> /usr/sbin/iptables-legacy   10        manual mode

**Comment by strasharo** [comment]
Just do a dist upgrade, it wasn't present in the initial image and then they brought it back in the updates.

**Comment by N2Network** [comment]
> Just do a dist upgrade, it wasn't present in the initial image and then they brought it back in the updates.

I fully updated and I couldn't get it to work until I switched to legacy.

**Comment by jonkajmr** [comment]
> I was able to fix this error in Kali by running the following command
> 
> > sudo update-alternatives --config iptables
> 
> One that and select
> 
> > /usr/sbin/iptables-legacy   10        manual mode

Thank you. Thats work to me. Now I can use bettercap correctly on my rpi 3b+ but I want to know if had a solution for . rescue-ssh.target is a disabled or a static unit, not starting it.



root@kali-pi:~# uname -a

Linux kali-pi 4.14.93-Re4son-v7+ #1 SMP Thu Jan 24 12:44:19 AEDT 2019 armv7l GNU/Linux' I deleted all ssh_host_* (cd rm /etc/ssh/ssh_host_*) but always give me 'rescue-ssh.target is a disabled or a static unit, not starting it. ' how can I fix it? 
Pd: apologies for my bad english

**Comment by perlun** [comment]
The suggestion given by @N2Network helped for me as well, to get `iptables` working on Raspbian 10.3 (buster).
