### ISSUE TITLE
Could not install Tornado

### ISSUE THREAD

**Issue by daniel951127** [wifiphisher/wifiphisher#1047]
hello friends I have the following problem when inserting wifiphisher I would like you to help me solve.
![126](https://user-images.githubusercontent.com/45519695/49776653-7ca76400-fcc2-11e8-84bc-52b8aaac1e0e.jpg)

**Comment by blackHatMonkey** [comment]
@daniel951127 Is this issue different from #1038 ?

**Comment by daniel951127** [comment]
It is the same but what I did, the problem was that I was surfing by proxy and it seems that they did not let me download the wifiphisher nor stamped it either
