### ISSUE TITLE
How to install older versions

### ISSUE THREAD

**Issue by username836** [wifiphisher/wifiphisher#1051]
Can you make the older version available because the newest version of Wifi Phisher is not working the older version worked fine when I used it I'd rather use the old Version if it works instead of a new version that doesn't work. I GET SO MANY ERRORS WITH THE NEW VERSION

**Comment by blackHatMonkey** [comment]
@username836 Thanks for opening an issue. You can always install older version of `wifiphisher` like so:
```bash
sudo pip uninstall wifiphisher
sudo pip install wifiphisher==VERSION # like 1.3
```
You have to replace version with one of [these](https://pypi.org/project/wifiphisher/#history).

**Comment by username836** [comment]
I used this at school the older version it worked fine and I used a custom template and put a porn picture on it and the wifi the students use is a open and I closed the name and made a rouge AP so all devices that are close to me connect to me instead of the real WiFi cause that's how devices work so my classmates had no internet and it popped up a porn picture on their phone the school had Cisco routers so i couldn't deauth that wifi offline but it was funny as a prank to the school and I never got caught and did it everyday and then they searched students backbacks to see if they had a lapatop

**Comment by sophron** [comment]
Previous releases also lie here: https://github.com/wifiphisher/wifiphisher/releases
