### ISSUE TITLE
Wifiphisher not support kali linux version 2018.* up

### ISSUE THREAD

**Issue by christmex** [wifiphisher/wifiphisher#1056]
i think wifiphisher not support with kali linux 2018.* up , because i have to try to much use wifiphisher at update 2018.* but if i use kali linux 2017.* down 3-1 it work . why?

**Comment by sophron** [comment]
Hi,

What exact problem are you encountering on the later Kali versions?

**Comment by christmex** [comment]
if i install kali version 2017.3 wifiphisher is work. but if i upgrade to 2018.1/2/3/4 wifiphisher not work ...

**Comment by greg777** [comment]
> if i install kali version 2017.3 wifiphisher is work. but if i upgrade to 2018.1/2/3/4 wifiphisher not work ...

can you share please the link for kali 2017.3 which you use?

**Comment by christmex** [comment]
link iso?
i use the old iso of kali linux 2017.3 so i dont have link for kali linux 2017.3
i was download kali linux 2017.3 in 2017.
im sorry,my english bad

**Comment by kimocoder** [comment]
https://archive.kali.org

**Comment by sophron** [comment]
Hi guys,

What exact problem are you having with the latest Kali version? I will try to resolve soon.

**Comment by greg777** [comment]
> Hi guys,
> 
> What exact problem are you having with the latest Kali version? I will try to resolve soon.
Hi.
I tried to connect to the rogue AP but failed. I used 2 the same wifi adapters (Alfa Network AWUS036ACH) and used different scenarios to connect to fake AP and each time I could not do that.

* I increased txpower of wifi adapter to 30, 35, 40;
* reconnected wifi adapters to other USB ports;
* shut down AP via another program (aireplay-ng) and then run wifisher
* tried to use various combination of running wififisher like:
  ./wifiphisher -aI wlan2 -eI wlan1
  sudo wifiphisher -aI wlan1 -eI wlan2
  sudo python2 wifiphisher -aI wlan2 -eI wlan1 --essid "Open Wifi" -p facebook-login
  python /root/wifiphisher/bin/wifiphisher -aI wlan2 -eI wlan1 --essid "Open Wifi" --force-hostapd -p device-modal
  Nothing helped me

**Comment by greg777** [comment]
> https://archive.kali.org

thx for the link but there is no kali 2017 image unfortunately.

**Comment by greg777** [comment]
@sophron if you have any additional info about reproducing this issue, let me know.

**Comment by pendok99** [comment]
wifiphisher work for me on kali linux 2018.4 but you must to installing a libnl-dev package on it and edit the sources.list

**Comment by ludoES** [comment]
> Hi guys,
> 
> What exact problem are you having with the latest Kali version? I will try to resolve soon.
