### ISSUE TITLE
Could not install roguehostapd

### ISSUE THREAD

**Issue by djdisikd** [wifiphisher/wifiphisher#1060]
/tmp/tmp_netlink_ZifZ7k/test_netlink.c:2:10: fatal error: netlink/netlink.h: No such file or directory
 #include <netlink/netlink.h>
          ^~~~~~~~~~~~~~~~~~~
compilation terminated.
[!] The development package for netlink is missing. Please download it and restart the compilation.If you are on Debian-based system: 'apt-get install libnl-3-dev libnl-genl-3-dev'.

**Comment by djdisikd** [comment]
I will let you know soon

**Comment by W4RR3N7-3XP14Y** [comment]
having the same problem, no apt-get install libnl-3-dev libnl-genl-3-dev doesnt work

**Comment by W4RR3N7-3XP14Y** [comment]
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package libnl-3-dev
E: Unable to locate package libnl-genl-3-dev
