### ISSUE TITLE
Wifi using Mobile only

### ISSUE THREAD

**Issue by Samakin83** [wifiphisher/wifiphisher#1064]
Greetings, i am a new and in learning processe so apologies in advance, i noticed that when using Wifiphisher and choosing the firmware upgrade attack the victim have to connect to rogue AP but in the same time he will have to log into provided link manually, rather is there a way that this link could be changed to a login page that pop up automatically same as what happens when we connect to airport wifi.....the reason am asking this is some user dont own laptops and use wifi only on their mobiles... already tried Fluxion and it has the same issue for mobile devices...any suggestions??

**Comment by Samakin83** [comment]
Greetings, i am a new and in learning processe so apologies in advance, i noticed that when using Wifiphisher and choosing the firmware upgrade attack the victim have to connect to rogue AP but in the same time he will have to log into provided link manually, rather is there a way that this link could be changed to a login page that pop up automatically  same as what happens when we connect to airport wifi.....the reason am asking this is some user dont own laptops and use wifi only on their mobiles... already tried Fluxion and it has the same issue for mobile devices...any suggestions??

**Comment by sophron** [comment]
We have #1029 for this.
