### ISSUE TITLE
The phone showed no internet access and the wifi network automatically disconnected

### ISSUE THREAD

**Issue by djdisikd** [wifiphisher/wifiphisher#1069]
Hi anyone help?

**Comment by sophron** [comment]
Hi @djdisikd,

Are you describing #1029?

If not, please provide more information (see the issue template).

**Comment by djdisikd** [comment]
When I connect to the rogue network, it automatically disconnected because no internet access has been detected

But some devices won't automatically disconnected even when no internet access has been detected

**Comment by n3k1t** [comment]
Hello guys i have the same problem, i use this coomand "wifiphisher --essid "FREE WI-FI" -p oauth-login -kB",when i try to connect to AP FREE WIFI my iPhone automatically disconnected because no internet access ,please help

**Comment by sophron** [comment]
Let's stick to #1029.
