### ISSUE TITLE
Change url displayed in captive portal (firmware-upgrade)

### ISSUE THREAD

**Issue by Murima** [wifiphisher/wifiphisher#1071]
**Version: commit ba295f6410

The tool is working fine, thank you!, but i need to change the URL displayed on the firmware-upgrade captive portal. I have an android device but it somehow got detected as an IOS device so the url on the firmware-upgrade landing page is `captive.apple.com/generate_204`. 

I tried changing this file `wifiphiser-os-initial-requests` and re-installing wifiphisher with no luck, i have read throught this commit 964a3ce99c  which is trying to match URL to OS i cant seem to figure it out. Please help.

My system is Debian 9. Thanks

**Comment by sophron** [comment]
Hi @Murima,

Thanks for opening an issue. If your device is Android, why is it asking for `captive.apple.com/generate_204`? 

After you edit the file, you will have to run `python setup.py install` again for the changes to take effect.

**Comment by Murima** [comment]
Thanks for the response,
I have no idea why. I already ran `python setup.py install` after editing the file but it still seeking the same URL.

**Comment by sophron** [comment]
What if you run the tool by typing `python bin/wifiphisher` (from within the tool's directory) instead of simply `wifiphisher`?
