### ISSUE TITLE
Error 3 on windows 

### ISSUE THREAD

**Issue by RyukShinigami** [wifiphisher/wifiphisher#1072]
I'm on windows 10 and when I run the setup.py it gives me 
[Error 3] The system cannot find the path specified: 'tmp\\*.*'

**Comment by RyukShinigami** [comment]
PS D:\wifi fisher> & python -m pip install -U "pylint<2.0.0" --user
Collecting pylint<2.0.0
  Cache entry deserialization failed, entry ignored
  Downloading https://files.pythonhosted.org/packages/59/65/adcffa71fe942313c4d9e9284565d9a9e67798f4771f464e1d5dd58fea88/pylint-1.9.4-py2.py3-none-any.whl (689kB)
    100% |################################| 696kB 215kB/s
Collecting singledispatch; python_version < "3.4" (from pylint<2.0.0)
  Downloading https://files.pythonhosted.org/packages/c5/10/369f50bcd4621b263927b0a1519987a04383d4a98fb10438042ad410cf88/singledispatch-3.4.0.3-py2.py3-none-any.whl
Collecting mccabe (from pylint<2.0.0)
  Cache entry deserialization failed, entry ignored
  Cache entry deserialization failed, entry ignored
  Downloading https://files.pythonhosted.org/packages/87/89/479dc97e18549e21354893e4ee4ef36db1d237534982482c3681ee6e7b57/mccabe-0.6.1-py2.py3-none-any.whl
Collecting backports.functools-lru-cache; python_version == "2.7" (from pylint<2.0.0)
  Downloading https://files.pythonhosted.org/packages/03/8e/2424c0e65c4a066e28f539364deee49b6451f8fcd4f718fefa50cc3dcf48/backports.functools_lru_cache-1.5-py2.py3-none-any.whl
Collecting astroid<2.0,>=1.6 (from pylint<2.0.0)
  Cache entry deserialization failed, entry ignored
  Downloading https://files.pythonhosted.org/packages/0e/9b/18b08991c8c6aaa827faf394f4468b8fee41db1f73aa5157f9f5fb2e69c3/astroid-1.6.5-py2.py3-none-any.whl (293kB)
    100% |################################| 296kB 433kB/s
Collecting colorama; sys_platform == "win32" (from pylint<2.0.0)
  Cache entry deserialization failed, entry ignored
  Downloading https://files.pythonhosted.org/packages/4f/a6/728666f39bfff1719fc94c481890b2106837da9318031f71a8424b662e12/colorama-0.4.1-py2.py3-none-any.whl
Collecting six (from pylint<2.0.0)
  Cache entry deserialization failed, entry ignored
  Downloading https://files.pythonhosted.org/packages/73/fb/00a976f728d0d1fecfe898238ce23f502a721c0ac0ecfedb80e0d88c64e9/six-1.12.0-py2.py3-none-any.whl
Collecting isort>=4.2.5 (from pylint<2.0.0)
  Cache entry deserialization failed, entry ignored
  Downloading https://files.pythonhosted.org/packages/41/d8/a945da414f2adc1d9e2f7d6e7445b27f2be42766879062a2e63616ad4199/isort-4.3.4-py2-none-any.whl (45kB)
    100% |################################| 51kB 465kB/s
Collecting configparser; python_version == "2.7" (from pylint<2.0.0)
  Downloading https://files.pythonhosted.org/packages/e9/b1/98e5e3094aac1c0efaeb208fb45f9b42eb1d5681b4c5dac77b05d0fec71a/configparser-3.7.1-py2-none-any.whl
Collecting enum34>=1.1.3; python_version < "3.4" (from astroid<2.0,>=1.6->pylint<2.0.0)
  Downloading https://files.pythonhosted.org/packages/c5/db/e56e6b4bbac7c4a06de1c50de6fe1ef3810018ae11732a50f15f62c7d050/enum34-1.1.6-py2-none-any.whl
Collecting lazy-object-proxy (from astroid<2.0,>=1.6->pylint<2.0.0)
  Cache entry deserialization failed, entry ignored
  Downloading https://files.pythonhosted.org/packages/58/93/2bf9b50faf4941b7ff8851f3c81820a88e505b01da4cd95d1d3d818e738f/lazy_object_proxy-1.3.1-cp27-cp27m-win_amd64.whl
Collecting wrapt (from astroid<2.0,>=1.6->pylint<2.0.0)
  Cache entry deserialization failed, entry ignored
  Downloading https://files.pythonhosted.org/packages/67/b2/0f71ca90b0ade7fad27e3d20327c996c6252a2ffe88f50a95bba7434eda9/wrapt-1.11.1.tar.gzCollecting futures (from isort>=4.2.5->pylint<2.0.0)
  Downloading https://files.pythonhosted.org/packages/2d/99/b2c4e9d5a30f6471e410a146232b4118e697fa3ffc06d6a65efde84debd0/futures-3.2.0-py2-none-any.whl
Installing collected packages: six, singledispatch, mccabe, backports.functools-lru-cache, enum34, lazy-object-proxy, wrapt, astroid, colorama, futures, isort, configparser, pylint
  Running setup.py install for wrapt ... doneSuccessfully installed astroid-1.6.5 backports.functools-lru-cache-1.5 colorama-0.4.1 configparser-3.7.1 enum34-1.1.6 futures-3.2.0 isort-4.3.4 lazy-object-proxy-1.3.1 mccabe-0.6.1 pylint-1.9.4 singledispatch-3.4.0.3 six-1.12.0 wrapt-1.11.1
You are using pip version 9.0.3, however version 19.0.2 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.PS D:\wifi fisher> python setup.py installrunning install
running bdist_egg
running egg_info
writing requirements to wifiphisher.egg-info\requires.txt
writing wifiphisher.egg-info\PKG-INFO
writing top-level names to wifiphisher.egg-info\top_level.txt
writing dependency_links to wifiphisher.egg-info\dependency_links.txt
writing entry points to wifiphisher.egg-info\entry_points.txt
reading manifest file 'wifiphisher.egg-info\SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'wifiphisher.egg-info\SOURCES.txt'
installing library code to build\bdist.win-amd64\egg
running install_lib
running build_py
creating build\bdist.win-amd64\egg
creating build\bdist.win-amd64\egg\wifiphisher
creating build\bdist.win-amd64\egg\wifiphisher\common
copying build\lib\wifiphisher\common\accesspoint.py -> build\bdist.win-amd64\egg\wifiphisher\common
copying build\lib\wifiphisher\common\constants.py -> build\bdist.win-amd64\egg\wifiphisher\common
copying build\lib\wifiphisher\common\extensions.py -> build\bdist.win-amd64\egg\wifiphisher\common
copying build\lib\wifiphisher\common\firewall.py -> build\bdist.win-amd64\egg\wifiphisher\common
copying build\lib\wifiphisher\common\globals.py -> build\bdist.win-amd64\egg\wifiphisher\common
copying build\lib\wifiphisher\common\interfaces.py -> build\bdist.win-amd64\egg\wifiphisher\common
copying build\lib\wifiphisher\common\macmatcher.py -> build\bdist.win-amd64\egg\wifiphisher\common
copying build\lib\wifiphisher\common\opmode.py -> build\bdist.win-amd64\egg\wifiphisher\common
copying build\lib\wifiphisher\common\phishinghttp.py -> build\bdist.win-amd64\egg\wifiphisher\common
copying build\lib\wifiphisher\common\phishingpage.py -> build\bdist.win-amd64\egg\wifiphisher\common
copying build\lib\wifiphisher\common\recon.py -> build\bdist.win-amd64\egg\wifiphisher\common
copying build\lib\wifiphisher\common\tui.py -> build\bdist.win-amd64\egg\wifiphisher\common
copying build\lib\wifiphisher\common\uimethods.py -> build\bdist.win-amd64\egg\wifiphisher\common
copying build\lib\wifiphisher\common\utilities.py -> build\bdist.win-amd64\egg\wifiphisher\common
copying build\lib\wifiphisher\common\victim.py -> build\bdist.win-amd64\egg\wifiphisher\common
copying build\lib\wifiphisher\common\__init__.py -> build\bdist.win-amd64\egg\wifiphisher\common
creating build\bdist.win-amd64\egg\wifiphisher\data
creating build\bdist.win-amd64\egg\wifiphisher\data\cert
copying build\lib\wifiphisher\data\cert\server.pem -> build\bdist.win-amd64\egg\wifiphisher\data\cert
creating build\bdist.win-amd64\egg\wifiphisher\data\locs
copying build\lib\wifiphisher\data\locs\.gitkeep -> build\bdist.win-amd64\egg\wifiphisher\data\locs
creating build\bdist.win-amd64\egg\wifiphisher\data\phishing-pages
creating build\bdist.win-amd64\egg\wifiphisher\data\phishing-pages\firmware-upgrade
copying build\lib\wifiphisher\data\phishing-pages\firmware-upgrade\config.ini -> build\bdist.win-amd64\egg\wifiphisher\data\phishing-pages\firmware-upgrade
creating build\bdist.win-amd64\egg\wifiphisher\data\phishing-pages\firmware-upgrade\html
copying build\lib\wifiphisher\data\phishing-pages\firmware-upgrade\html\bootstrap.min.css -> build\bdist.win-amd64\egg\wifiphisher\data\phishing-pages\firmware-upgrade\html
copying build\lib\wifiphisher\data\phishing-pages\firmware-upgrade\html\bootstrap.min.js -> build\bdist.win-amd64\egg\wifiphisher\data\phishing-pages\firmware-upgrade\html
copying build\lib\wifiphisher\data\phishing-pages\firmware-upgrade\html\index.html -> build\bdist.win-amd64\egg\wifiphisher\data\phishing-pages\firmware-upgrade\html
copying build\lib\wifiphisher\data\phishing-pages\firmware-upgrade\html\jquery.min.js -> build\bdist.win-amd64\egg\wifiphisher\data\phishing-pages\firmware-upgrade\html
copying build\lib\wifiphisher\data\phishing-pages\firmware-upgrade\html\loading.html -> build\bdist.win-amd64\egg\wifiphisher\data\phishing-pages\firmware-upgrade\html
creating build\bdist.win-amd64\egg\wifiphisher\data\phishing-pages\firmware-upgrade\html\static
copying build\lib\wifiphisher\data\phishing-pages\firmware-upgrade\html\static\bootstrap.min.css -> build\bdist.win-amd64\egg\wifiphisher\data\phishing-pages\firmware-upgrade\html\static
copying build\lib\wifiphisher\data\phishing-pages\firmware-upgrade\html\static\bootstrap.min.js -> build\bdist.win-amd64\egg\wifiphisher\data\phishing-pages\firmware-upgrade\html\static
creating build\bdist.win-amd64\egg\wifiphisher\data\phishing-pages\firmware-upgrade\html\static\font-awesome-4.7.0
creating build\bdist.win-amd64\egg\wifiphisher\data\phishing-pages\firmware-upgrade\html\static\font-awesome-4.7.0\css
copying build\lib\wifiphisher\data\phishing-pages\firmware-upgrade\html\static\font-awesome-4.7.0\css\font-awesome.css -> build\bdist.win-amd64\egg\wifiphisher\data\phishing-pages\firmware-upgrade\html\static\font-awesome-4.7.0\css
copying build\lib\wifiphisher\data\phishing-pages\firmware-upgrade\html\static\font-awesome-4.7.0\css\font-awesome.min.css -> build\bdist.win-amd64\egg\wifiphisher\data\phishing-pages\firmware-upgrade\html\static\font-awesome-4.7.0\css
creating build\bdist.win-amd64\egg\wifiphisher\data\phishing-pages\firmware-upgrade\html\static\font-awesome-4.7.0\fonts
copying build\lib\wifiphisher\data\phishing-pages\firmware-upgrade\html\static\font-awesome-4.7.0\fonts\fontawesome-webfont.eot -> build\bdist.win-amd64\egg\wifiphisher\data\phishing-pages\firmware-upgrade\html\static\font-awesome-4.7.0\fonts
copying build\lib\wifiphisher\data\phishing-pages\firmware-upgrade\html\static\font-awesome-4.7.0\fonts\fontawesome-webfont.svg -> build\bdist.win-amd64\egg\wifiphisher\data\phishing-pages\firmware-upgrade\html\static\font-awesome-4.7.0\fonts
copying build\lib\wifiphisher\data\phishing-pages\firmware-upgrade\html\static\font-awesome-4.7.0\fonts\fontawesome-webfont.ttf -> build\bdist.win-amd64\egg\wifiphisher\data\phishing-pages\firmware-upgrade\html\static\font-awesome-4.7.0\fonts
copying build\lib\wifiphisher\data\phishing-pages\firmware-upgrade\html\static\font-awesome-4.7.0\fonts\fontawesome-webfont.woff -> build\bdist.win-amd64\egg\wifiphisher\data\phishing-pages\firmware-upgrade\html\static\font-awesome-4.7.0\fonts
copying build\lib\wifiphisher\data\phishing-pages\firmware-upgrade\html\static\font-awesome-4.7.0\fonts\fontawesome-webfont.woff2 -> build\bdist.win-amd64\egg\wifiphisher\data\phishing-pages\firmware-upgrade\html\static\font-awesome-4.7.0\fonts
copying build\lib\wifiphisher\data\phishing-pages\firmware-upgrade\html\static\font-awesome-4.7.0\fonts\FontAwesome.otf -> build\bdist.win-amd64\egg\wifiphisher\data\phishing-pages\firmware-upgrade\html\static\font-awesome-4.7.0\fonts
copying build\lib\wifiphisher\data\phishing-pages\firmware-upgrade\html\static\jquery.min.js -> build\bdist.win-amd64\egg\wifiphisher\data\phishing-pages\firmware-upgrade\html\static
copying build\lib\wifiphisher\data\phishing-pages\firmware-upgrade\html\upgrading.html -> build\bdist.win-amd64\egg\wifiphisher\data\phishing-pages\firmware-upgrade\html
creating build\bdist.win-amd64\egg\wifiphisher\data\phishing-pages\oauth-login
copying build\lib\wifiphisher\data\phishing-pages\oauth-login\config.ini -> build\bdist.win-amd64\egg\wifiphisher\data\phishing-pages\oauth-login
creating build\bdist.win-amd64\egg\wifiphisher\data\phishing-pages\oauth-login\html
copying build\lib\wifiphisher\data\phishing-pages\oauth-login\html\index.html -> build\bdist.win-amd64\egg\wifiphisher\data\phishing-pages\oauth-login\html
copying build\lib\wifiphisher\data\phishing-pages\oauth-login\html\oauth.html -> build\bdist.win-amd64\egg\wifiphisher\data\phishing-pages\oauth-login\html
creating build\bdist.win-amd64\egg\wifiphisher\data\phishing-pages\oauth-login\html\static
creating build\bdist.win-amd64\egg\wifiphisher\data\phishing-pages\oauth-login\html\static\css
copying build\lib\wifiphisher\data\phishing-pages\oauth-login\html\static\css\font-awesome.min.css -> build\bdist.win-amd64\egg\wifiphisher\data\phishing-pages\oauth-login\html\static\css
copying build\lib\wifiphisher\data\phishing-pages\oauth-login\html\static\css\reset.css -> build\bdist.win-amd64\egg\wifiphisher\data\phishing-pages\oauth-login\html\static\css
copying build\lib\wifiphisher\data\phishing-pages\oauth-login\html\static\css\roboto.css -> build\bdist.win-amd64\egg\wifiphisher\data\phishing-pages\oauth-login\html\static\css
copying build\lib\wifiphisher\data\phishing-pages\oauth-login\html\static\css\style.css -> build\bdist.win-amd64\egg\wifiphisher\data\phishing-pages\oauth-login\html\static\css
creating build\bdist.win-amd64\egg\wifiphisher\data\phishing-pages\oauth-login\html\static\js
copying build\lib\wifiphisher\data\phishing-pages\oauth-login\html\static\js\index.js -> build\bdist.win-amd64\egg\wifiphisher\data\phishing-pages\oauth-login\html\static\js
copying build\lib\wifiphisher\data\phishing-pages\oauth-login\html\static\js\jquery.min.js -> build\bdist.win-amd64\egg\wifiphisher\data\phishing-pages\oauth-login\html\static\js
creating build\bdist.win-amd64\egg\wifiphisher\data\phishing-pages\plugin_update
copying build\lib\wifiphisher\data\phishing-pages\plugin_update\config.ini -> build\bdist.win-amd64\egg\wifiphisher\data\phishing-pages\plugin_update
creating build\bdist.win-amd64\egg\wifiphisher\data\phishing-pages\plugin_update\html
creating build\bdist.win-amd64\egg\wifiphisher\data\phishing-pages\plugin_update\html\css
copying build\lib\wifiphisher\data\phishing-pages\plugin_update\html\css\bootstrap.min.css -> build\bdist.win-amd64\egg\wifiphisher\data\phishing-pages\plugin_update\html\css
copying build\lib\wifiphisher\data\phishing-pages\plugin_update\html\css\theme.css -> build\bdist.win-amd64\egg\wifiphisher\data\phishing-pages\plugin_update\html\css
creating build\bdist.win-amd64\egg\wifiphisher\data\phishing-pages\plugin_update\html\images
copying build\lib\wifiphisher\data\phishing-pages\plugin_update\html\images\favicon.ico -> build\bdist.win-amd64\egg\wifiphisher\data\phishing-pages\plugin_update\html\images
copying build\lib\wifiphisher\data\phishing-pages\plugin_update\html\images\plugins.png -> build\bdist.win-amd64\egg\wifiphisher\data\phishing-pages\plugin_update\html\images
copying build\lib\wifiphisher\data\phishing-pages\plugin_update\html\index.html -> build\bdist.win-amd64\egg\wifiphisher\data\phishing-pages\plugin_update\html
creating build\bdist.win-amd64\egg\wifiphisher\data\phishing-pages\plugin_update\html\js
copying build\lib\wifiphisher\data\phishing-pages\plugin_update\html\js\bootstrap.min.js -> build\bdist.win-amd64\egg\wifiphisher\data\phishing-pages\plugin_update\html\js
copying build\lib\wifiphisher\data\phishing-pages\plugin_update\html\js\jquery.js -> build\bdist.win-amd64\egg\wifiphisher\data\phishing-pages\plugin_update\html\js
creating build\bdist.win-amd64\egg\wifiphisher\data\phishing-pages\plugin_update\html\static
creating build\bdist.win-amd64\egg\wifiphisher\data\phishing-pages\plugin_update\html\static\css
copying build\lib\wifiphisher\data\phishing-pages\plugin_update\html\static\css\bootstrap.min.css -> build\bdist.win-amd64\egg\wifiphisher\data\phishing-pages\plugin_update\html\static\css
copying build\lib\wifiphisher\data\phishing-pages\plugin_update\html\static\css\theme.css -> build\bdist.win-amd64\egg\wifiphisher\data\phishing-pages\plugin_update\html\static\css
creating build\bdist.win-amd64\egg\wifiphisher\data\phishing-pages\plugin_update\html\static\images
copying build\lib\wifiphisher\data\phishing-pages\plugin_update\html\static\images\favicon.ico -> build\bdist.win-amd64\egg\wifiphisher\data\phishing-pages\plugin_update\html\static\images
copying build\lib\wifiphisher\data\phishing-pages\plugin_update\html\static\images\plugins.png -> build\bdist.win-amd64\egg\wifiphisher\data\phishing-pages\plugin_update\html\static\images
creating build\bdist.win-amd64\egg\wifiphisher\data\phishing-pages\plugin_update\html\static\js
copying build\lib\wifiphisher\data\phishing-pages\plugin_update\html\static\js\bootstrap.min.js -> build\bdist.win-amd64\egg\wifiphisher\data\phishing-pages\plugin_update\html\static\js
copying build\lib\wifiphisher\data\phishing-pages\plugin_update\html\static\js\jquery.js -> build\bdist.win-amd64\egg\wifiphisher\data\phishing-pages\plugin_update\html\static\js
creating build\bdist.win-amd64\egg\wifiphisher\data\phishing-pages\plugin_update\html\static\update
copying build\lib\wifiphisher\data\phishing-pages\plugin_update\html\static\update\update.exe -> build\bdist.win-amd64\egg\wifiphisher\data\phishing-pages\plugin_update\html\static\update
creating build\bdist.win-amd64\egg\wifiphisher\data\phishing-pages\plugin_update\html\update
copying build\lib\wifiphisher\data\phishing-pages\plugin_update\html\update\update.exe -> build\bdist.win-amd64\egg\wifiphisher\data\phishing-pages\plugin_update\html\update
creating build\bdist.win-amd64\egg\wifiphisher\data\phishing-pages\wifi_connect
copying build\lib\wifiphisher\data\phishing-pages\wifi_connect\config.ini -> build\bdist.win-amd64\egg\wifiphisher\data\phishing-pages\wifi_connect
creating build\bdist.win-amd64\egg\wifiphisher\data\phishing-pages\wifi_connect\html
copying build\lib\wifiphisher\data\phishing-pages\wifi_connect\html\behavior.js -> build\bdist.win-amd64\egg\wifiphisher\data\phishing-pages\wifi_connect\html
copying build\lib\wifiphisher\data\phishing-pages\wifi_connect\html\chrome-offline.css -> build\bdist.win-amd64\egg\wifiphisher\data\phishing-pages\wifi_connect\html
copying build\lib\wifiphisher\data\phishing-pages\wifi_connect\html\dinosaur.png -> build\bdist.win-amd64\egg\wifiphisher\data\phishing-pages\wifi_connect\html
copying build\lib\wifiphisher\data\phishing-pages\wifi_connect\html\index.html -> build\bdist.win-amd64\egg\wifiphisher\data\phishing-pages\wifi_connect\html
copying build\lib\wifiphisher\data\phishing-pages\wifi_connect\html\loading.html -> build\bdist.win-amd64\egg\wifiphisher\data\phishing-pages\wifi_connect\html
copying build\lib\wifiphisher\data\phishing-pages\wifi_connect\html\mac-network-manager.css -> build\bdist.win-amd64\egg\wifiphisher\data\phishing-pages\wifi_connect\html
copying build\lib\wifiphisher\data\phishing-pages\wifi_connect\html\opensans.css -> build\bdist.win-amd64\egg\wifiphisher\data\phishing-pages\wifi_connect\html
copying build\lib\wifiphisher\data\phishing-pages\wifi_connect\html\opensans.ttf -> build\bdist.win-amd64\egg\wifiphisher\data\phishing-pages\wifi_connect\html
copying build\lib\wifiphisher\data\phishing-pages\wifi_connect\html\question.png -> build\bdist.win-amd64\egg\wifiphisher\data\phishing-pages\wifi_connect\html
creating build\bdist.win-amd64\egg\wifiphisher\data\phishing-pages\wifi_connect\html\static
copying build\lib\wifiphisher\data\phishing-pages\wifi_connect\html\static\behavior.js -> build\bdist.win-amd64\egg\wifiphisher\data\phishing-pages\wifi_connect\html\static
copying build\lib\wifiphisher\data\phishing-pages\wifi_connect\html\static\chrome-offline.css -> build\bdist.win-amd64\egg\wifiphisher\data\phishing-pages\wifi_connect\html\static
copying build\lib\wifiphisher\data\phishing-pages\wifi_connect\html\static\dinosaur.png -> build\bdist.win-amd64\egg\wifiphisher\data\phishing-pages\wifi_connect\html\static
copying build\lib\wifiphisher\data\phishing-pages\wifi_connect\html\static\mac-network-manager.css -> build\bdist.win-amd64\egg\wifiphisher\data\phishing-pages\wifi_connect\html\static
copying build\lib\wifiphisher\data\phishing-pages\wifi_connect\html\static\opensans.css -> build\bdist.win-amd64\egg\wifiphisher\data\phishing-pages\wifi_connect\html\static
copying build\lib\wifiphisher\data\phishing-pages\wifi_connect\html\static\opensans.ttf -> build\bdist.win-amd64\egg\wifiphisher\data\phishing-pages\wifi_connect\html\static
copying build\lib\wifiphisher\data\phishing-pages\wifi_connect\html\static\question.png -> build\bdist.win-amd64\egg\wifiphisher\data\phishing-pages\wifi_connect\html\static
copying build\lib\wifiphisher\data\phishing-pages\wifi_connect\html\static\style.css -> build\bdist.win-amd64\egg\wifiphisher\data\phishing-pages\wifi_connect\html\static
copying build\lib\wifiphisher\data\phishing-pages\wifi_connect\html\static\wifi-icon.png -> build\bdist.win-amd64\egg\wifiphisher\data\phishing-pages\wifi_connect\html\static
copying build\lib\wifiphisher\data\phishing-pages\wifi_connect\html\static\win-behavior.js -> build\bdist.win-amd64\egg\wifiphisher\data\phishing-pages\wifi_connect\html\static
copying build\lib\wifiphisher\data\phishing-pages\wifi_connect\html\style.css -> build\bdist.win-amd64\egg\wifiphisher\data\phishing-pages\wifi_connect\html
copying build\lib\wifiphisher\data\phishing-pages\wifi_connect\html\wifi-icon.png -> build\bdist.win-amd64\egg\wifiphisher\data\phishing-pages\wifi_connect\html
copying build\lib\wifiphisher\data\phishing-pages\wifi_connect\html\win-behavior.js -> build\bdist.win-amd64\egg\wifiphisher\data\phishing-pages\wifi_connect\html
copying build\lib\wifiphisher\data\wifiphisher-known-open-wlans -> build\bdist.win-amd64\egg\wifiphisher\data
copying build\lib\wifiphisher\data\wifiphisher-mac-prefixes -> build\bdist.win-amd64\egg\wifiphisher\data
copying build\lib\wifiphisher\data\wifiphisher-os-initial-requests -> build\bdist.win-amd64\egg\wifiphisher\data
creating build\bdist.win-amd64\egg\wifiphisher\extensions
copying build\lib\wifiphisher\extensions\deauth.py -> build\bdist.win-amd64\egg\wifiphisher\extensions
copying build\lib\wifiphisher\extensions\handshakeverify.py -> build\bdist.win-amd64\egg\wifiphisher\extensions
copying build\lib\wifiphisher\extensions\knownbeacons.py -> build\bdist.win-amd64\egg\wifiphisher\extensions
copying build\lib\wifiphisher\extensions\lure10.py -> build\bdist.win-amd64\egg\wifiphisher\extensions
copying build\lib\wifiphisher\extensions\roguehostapdinfo.py -> build\bdist.win-amd64\egg\wifiphisher\extensions
copying build\lib\wifiphisher\extensions\wpspbc.py -> build\bdist.win-amd64\egg\wifiphisher\extensions
copying build\lib\wifiphisher\extensions\__init__.py -> build\bdist.win-amd64\egg\wifiphisher\extensions
copying build\lib\wifiphisher\pywifiphisher.py -> build\bdist.win-amd64\egg\wifiphisher
copying build\lib\wifiphisher\__init__.py -> build\bdist.win-amd64\egg\wifiphisher
byte-compiling build\bdist.win-amd64\egg\wifiphisher\common\accesspoint.py to accesspoint.pyc
byte-compiling build\bdist.win-amd64\egg\wifiphisher\common\constants.py to constants.pyc
byte-compiling build\bdist.win-amd64\egg\wifiphisher\common\extensions.py to extensions.pyc
byte-compiling build\bdist.win-amd64\egg\wifiphisher\common\firewall.py to firewall.pyc
byte-compiling build\bdist.win-amd64\egg\wifiphisher\common\globals.py to globals.pyc
byte-compiling build\bdist.win-amd64\egg\wifiphisher\common\interfaces.py to interfaces.pyc
byte-compiling build\bdist.win-amd64\egg\wifiphisher\common\macmatcher.py to macmatcher.pyc
byte-compiling build\bdist.win-amd64\egg\wifiphisher\common\opmode.py to opmode.pyc
byte-compiling build\bdist.win-amd64\egg\wifiphisher\common\phishinghttp.py to phishinghttp.pyc
byte-compiling build\bdist.win-amd64\egg\wifiphisher\common\phishingpage.py to phishingpage.pyc
byte-compiling build\bdist.win-amd64\egg\wifiphisher\common\recon.py to recon.pyc
byte-compiling build\bdist.win-amd64\egg\wifiphisher\common\tui.py to tui.pyc
byte-compiling build\bdist.win-amd64\egg\wifiphisher\common\uimethods.py to uimethods.pyc
byte-compiling build\bdist.win-amd64\egg\wifiphisher\common\utilities.py to utilities.pyc
byte-compiling build\bdist.win-amd64\egg\wifiphisher\common\victim.py to victim.pyc
byte-compiling build\bdist.win-amd64\egg\wifiphisher\common\__init__.py to __init__.pyc
byte-compiling build\bdist.win-amd64\egg\wifiphisher\extensions\deauth.py to deauth.pyc
byte-compiling build\bdist.win-amd64\egg\wifiphisher\extensions\handshakeverify.py to handshakeverify.pyc
byte-compiling build\bdist.win-amd64\egg\wifiphisher\extensions\knownbeacons.py to knownbeacons.pyc
byte-compiling build\bdist.win-amd64\egg\wifiphisher\extensions\lure10.py to lure10.pyc
byte-compiling build\bdist.win-amd64\egg\wifiphisher\extensions\roguehostapdinfo.py to roguehostapdinfo.pyc
byte-compiling build\bdist.win-amd64\egg\wifiphisher\extensions\wpspbc.py to wpspbc.pyc
byte-compiling build\bdist.win-amd64\egg\wifiphisher\extensions\__init__.py to __init__.pyc
byte-compiling build\bdist.win-amd64\egg\wifiphisher\pywifiphisher.py to pywifiphisher.pyc
byte-compiling build\bdist.win-amd64\egg\wifiphisher\__init__.py to __init__.pyc
creating build\bdist.win-amd64\egg\EGG-INFO
copying wifiphisher.egg-info\PKG-INFO -> build\bdist.win-amd64\egg\EGG-INFO
copying wifiphisher.egg-info\SOURCES.txt -> build\bdist.win-amd64\egg\EGG-INFO
copying wifiphisher.egg-info\dependency_links.txt -> build\bdist.win-amd64\egg\EGG-INFO
copying wifiphisher.egg-info\entry_points.txt -> build\bdist.win-amd64\egg\EGG-INFO
copying wifiphisher.egg-info\requires.txt -> build\bdist.win-amd64\egg\EGG-INFO
copying wifiphisher.egg-info\top_level.txt -> build\bdist.win-amd64\egg\EGG-INFO
zip_safe flag not set; analyzing archive contents...
wifiphisher.common.constants: module references __file__
creating 'dist\wifiphisher-1.4-py2.7.egg' and adding 'build\bdist.win-amd64\egg' to it
removing 'build\bdist.win-amd64\egg' (and everything under it)
Processing wifiphisher-1.4-py2.7.egg
removing 'c:\users\islam\.windows-build-tools\python27\lib\site-packages\wifiphisher-1.4-py2.7.egg' (and everything under it)
creating c:\users\islam\.windows-build-tools\python27\lib\site-packages\wifiphisher-1.4-py2.7.egg
Extracting wifiphisher-1.4-py2.7.egg to c:\users\islam\.windows-build-tools\python27\lib\site-packages
wifiphisher 1.4 is already the active version in easy-install.pth
Installing wifiphisher-script.py script to C:\Users\islam\.windows-build-tools\python27\Scripts
Installing wifiphisher.exe script to C:\Users\islam\.windows-build-tools\python27\Scripts

Installed c:\users\islam\.windows-build-tools\python27\lib\site-packages\wifiphisher-1.4-py2.7.egg
Processing dependencies for wifiphisher==1.4
Searching for roguehostapd
Reading https://pypi.python.org/simple/roguehostapd/
Downloading https://files.pythonhosted.org/packages/ca/0e/67991a382656c30ec4f6197db8e96bf8d3b87cc0093254f0c97340fa7c53/roguehostapd-1.2.3.tar.gz#sha256=583d32005148ec0c446f17619d3811cfbee4439478d37179e8e7cd1bf557a208
Best match: roguehostapd 1.2.3
Processing roguehostapd-1.2.3.tar.gz
Writing c:\users\islam\appdata\local\temp\easy_install-q6semk\roguehostapd-1.2.3\setup.cfg
Running roguehostapd-1.2.3\setup.py -q bdist_egg --dist-dir c:\users\islam\appdata\local\temp\easy_install-q6semk\roguehostapd-1.2.3\egg-dist-tmp-vviwbo
error: [Error 3] The system cannot find the path specified: 'tmp\\*.*'

**Comment by anakin1028** [comment]
Wifiphisher is supported only in Linux system.
