### ISSUE TITLE
Suggestion to Bypass HSTS!!

### ISSUE THREAD

**Issue by jeegarjani** [wifiphisher/wifiphisher#1080]
Can u automate ssl2strip, dns2proxy or evilginx in the update so it can bypass HSTS warning while trying connection request in fake dns. I am not a coder but I understand where the problem lies...See if u can work out...

**Comment by sophron** [comment]
This will significantly widen the scope of our project and I don't believe we have the resources to do it.

We can, however, create guides describing how Wifiphisher can work with these tools and add them to our docs.

**Comment by jeegarjani** [comment]
Hey brother , were u able to write the method using evilginx with
wifiphisher and add it to your docs..?

Kindly update thanks.
