### ISSUE TITLE
what about this chrome thing ?!

### ISSUE THREAD

**Issue by minanagehsalalma** [wifiphisher/wifiphisher#1081]
https://security.stackexchange.com/questions/87320/distinguish-between-wi-fi-captive-portal-and-mitm-attack/87324#87324

"In the event that Chrome detects SSL connection timeouts, certificate errors, or other network issues that might be caused by a captive portal (a hotel's WiFi network, for instance), Chrome will make a cookieless request to http://www.gstatic.com/generate_204 and check the response code. If that request is redirected, Chrome will open the redirect target in a new tab on the assumption that it's a login page. Requests to the captive portal detection page are not logged."

does our fake AP able of doing this too ?!

**Comment by sophron** [comment]
I don't think that you are describing a problem neither you are suggesting anything new.

We want our rogue AP to be detected as a captive portal by all modern devices. See #1029.

**Comment by minanagehsalalma** [comment]
@sophron  seems that you fixed it now :) thanks 
https://github.com/wifiphisher/wifiphisher/issues/1029#issuecomment-473951125
