### ISSUE TITLE
wifiphisher not work but all setup is okay ?

### ISSUE THREAD

**Issue by ramboUS** [wifiphisher/wifiphisher#1082]
Hello why my wifiphisher not work and show this error ?
![notwok](https://user-images.githubusercontent.com/48353575/54026892-74d06080-41da-11e9-9c96-26621ef862fa.png)
![notwork2](https://user-images.githubusercontent.com/48353575/54026893-74d06080-41da-11e9-984c-2a91f38bfc8b.png)

**Comment by sophron** [comment]
This is a known issue. It should not affect the execution of the program.

You can use our --logging option to have a clean output for now.

**Comment by sophron** [comment]
#439
