### ISSUE TITLE
you should add this esp project info to the wifiphisher wiki !!

### ISSUE THREAD

**Issue by minanagehsalalma** [wifiphisher/wifiphisher#1084]
as it will make -wP attack a lot easier and now you can make the page just asks the user to push the button 
... without the submit button in the page ...
[WiFi cracker ESP8266(PBC)
](https://hackaday.io/project/28924-wifi-cracker-esp8266pbc)

**Comment by sophron** [comment]
I'm not sure I understand why we should add this to our wiki.

**Comment by minanagehsalalma** [comment]
@sophron  case it will make  -wP attack a lot easier .... and nobody knows about it ?!

**Comment by djdisikd** [comment]
I knew if you connect already you can get the password

**Comment by minanagehsalalma** [comment]
@djdisikd  "I knew if you connect already you can get the password" 
what are you talking about ?

**Comment by djdisikd** [comment]
I mean if you are connected to the wifi network, you can get the wifi password directly from the router settings page

**Comment by minanagehsalalma** [comment]
@djdisikd  ....  we need to get connected first !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by djdisikd** [comment]
But how

**Comment by minanagehsalalma** [comment]
Are you stupid or what ?
