### ISSUE TITLE
Operation not possible due to RF-kill

### ISSUE THREAD

**Issue by jepunband** [wifiphisher/wifiphisher#1087]
Before opening a new issue, please make sure that what you are about to report has not been reported already or is not included on the FAQ page. If not, use the following template for reporting.

Please keep in mind that our developers will prioritize your issue if you provide a detailed and extensive description.

**Version**: Use `git show | grep commit` command and paste here the output.

6e22ba3db6ffe97dff9715760f43d4dfad4244bb

**Description**: Give a more analytical description here. Let us know how we can reproduce the reported issue. Detail the characteristics of your machine (e.g. Linux distribution and wireless card capabilities) and of the victim devices too (e.g. OS or web browser) if possible. The output of the `iw list` and `iwconfig` commands may also be helpful here.

**Script output**: Paste the output of the tool, including any stack traces.

[*] Starting Wifiphisher 1.4GIT ( https://wifiphisher.org ) at 2019-03-11 11:05
[+] Timezone detected. Setting channel range to 1-13
[+] Selecting wfphshr-wlan0 interface for the deauthentication attack
[+] Selecting wlan0 interface for creating the rogue Access Point
[+] Changing wlan0 MAC addr (BSSID) to 00:00:00:d5:92:f4
[+] Changing wlan0 MAC addr (BSSID) to 00:00:00:ce:a0:73
[+] Sending SIGKILL to wpa_supplicant
[+] Sending SIGKILL to NetworkManager
[*] Cleared leases, started DHCP, set up iptables
Traceback (most recent call last):
  File "/usr/local/bin/wifiphisher", line 11, in <module>
    load_entry_point('wifiphisher==1.4', 'console_scripts', 'wifiphisher')()
  File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.4-py2.7.egg/wifiphisher/pywifiphisher.py", line 693, in run
    engine.start()
  File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.4-py2.7.egg/wifiphisher/pywifiphisher.py", line 513, in start
    self.network_manager.up_interface(mon_iface)
  File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.4-py2.7.egg/wifiphisher/common/interfaces.py", line 459, in up_interface
    pyw.up(card)
  File "/usr/lib/python2.7/dist-packages/pyric/pyw.py", line 600, in up
    return _iostub_(up, card)
  File "/usr/lib/python2.7/dist-packages/pyric/pyw.py", line 2391, in _iostub_
    return fct(*argv)
  File "/usr/lib/python2.7/dist-packages/pyric/pyw.py", line 605, in up
    _flagsset_(card.dev, _setf_(flags, ifh.IFF_UP), iosock)
  File "/usr/lib/python2.7/dist-packages/pyric/pyw.py", line 2097, in _flagsset_
    raise pyric.error(e.errno, e.strerror)
pyric.error: [Errno 132] Operation not possible due to RF-kill

-------------------------

it kills my internet connection and it blocks all interface soft/hard block.

**Comment by sophron** [comment]
Have a look at previous issues: https://github.com/wifiphisher/wifiphisher/search?q=Operation+not+possible+due+to+RF-kill&type=Issues

**Comment by wissanu1987** [comment]
Duplicate of #> Before opening a new issue, please make sure that what you are about to report has not been reported already or is not included on the FAQ page. If not, use the following template for reporting.
> 
> Please keep in mind that our developers will prioritize your issue if you provide a detailed and extensive description.
> 
> **Version**: Use `git show | grep commit` command and paste here the output.
> 
> [6e22ba3](https://github.com/wifiphisher/wifiphisher/commit/6e22ba3db6ffe97dff9715760f43d4dfad4244bb)
> 
> **Description**: Give a more analytical description here. Let us know how we can reproduce the reported issue. Detail the characteristics of your machine (e.g. Linux distribution and wireless card capabilities) and of the victim devices too (e.g. OS or web browser) if possible. The output of the `iw list` and `iwconfig` commands may also be helpful here.
> 
> **Script output**: Paste the output of the tool, including any stack traces.
> 
> [_] Starting Wifiphisher 1.4GIT ( https://wifiphisher.org ) at 2019-03-11 11:05 [+] Timezone detected. Setting channel range to 1-13 [+] Selecting wfphshr-wlan0 interface for the deauthentication attack [+] Selecting wlan0 interface for creating the rogue Access Point [+] Changing wlan0 MAC addr (BSSID) to 00:00:00:d5:92:f4 [+] Changing wlan0 MAC addr (BSSID) to 00:00:00:ce:a0:73 [+] Sending SIGKILL to wpa_supplicant [+] Sending SIGKILL to NetworkManager [_] Cleared leases, started DHCP, set up iptables
> Traceback (most recent call last):
> File "/usr/local/bin/wifiphisher", line 11, in 
> load_entry_point('wifiphisher==1.4', 'console_scripts', 'wifiphisher')()
> File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.4-py2.7.egg/wifiphisher/pywifiphisher.py", line 693, in run
> engine.start()
> File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.4-py2.7.egg/wifiphisher/pywifiphisher.py", line 513, in start
> self.network_manager.up_interface(mon_iface)
> File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.4-py2.7.egg/wifiphisher/common/interfaces.py", line 459, in up_interface
> pyw.up(card)
> File "/usr/lib/python2.7/dist-packages/pyric/pyw.py", line 600, in up
> return _iostub_(up, card)
> File "/usr/lib/python2.7/dist-packages/pyric/pyw.py", line 2391, in _iostub_
> return fct(*argv)
> File "/usr/lib/python2.7/dist-packages/pyric/pyw.py", line 605, in up
> _flagsset_(card.dev, _setf_(flags, ifh.IFF_UP), iosock)
> File "/usr/lib/python2.7/dist-packages/pyric/pyw.py", line 2097, in _flagsset_
> raise pyric.error(e.errno, e.strerror)
> pyric.error: [Errno 132] Operation not possible due to RF-kill
> 
> it kills my internet connection and it blocks all interface soft/hard block.
