### ISSUE TITLE
Can't connect to known beacons 

### ISSUE THREAD

**Issue by N2Network** [wifiphisher/wifiphisher#1096]
I'm having an issue where I can connect from my devices to the SSID specified in -e "Rogue Network" However, when I try to connect to the known beacon SSID's none of my devices will connect. 

commit c27c2ab1ef9c5c3aad6f9643acb9170cf2c45a73

**Comment by conghtse05773** [comment]
(Please give more info of the issue) you should check if dnsmasq process is running while wifiphisher starting.Maybe due to already-opened port problem.

**Comment by N2Network** [comment]
![Screenshot_20190327-093641_Settings](https://user-images.githubusercontent.com/13750325/55094891-7de37d80-5074-11e9-906c-177c496cc62c.jpg)

**Comment by sophron** [comment]
You won't be connected to the Known Beacons networks if KARMA attack is disabled. Are you using "roguehostapd" or "hostapd"?

**Comment by sophron** [comment]
Based on #1099, I guess you haven't installed roguehostapd.

**Comment by N2Network** [comment]
> You won't be connected to the Known Beacons networks if KARMA attack is disabled. Are you using "roguehostapd" or "hostapd"?

I'm using -kB switch so I think I have Karma enabled. 
I'm also NOT using -fH so I think by default I'm using roguehostapd.
I did > git clone https://github.com/wifiphisher/roguehostapd.git && cd roguehostapd && sudo python setup.py install && cd ..

Here is my command:

> sudo wifiphisher -pPD /root/wifiphisher/wifiphisher/data/phishing-pages -e "Free Wifi" -kB -p google-login --logging -lP /root/wifiphisher/logging.txt -cP /root/wifiphisher/credentials.txt -kB -aI wlan0 -eI wlan1

**Comment by sophron** [comment]
I'm not sure what is wrong. In order to debug this further, you will have to provide us with a network capture. Feel free to use Wireshark to capture the traffic of your card in monitor mode when you are trying to connect to one of the open networks and post it here.
