### ISSUE TITLE
Verizon tool detects compromised network

### ISSUE THREAD

**Issue by N2Network** [wifiphisher/wifiphisher#1097]
![Screenshot_20190325-121119_Security   Privacy](https://user-images.githubusercontent.com/13750325/54960957-19150f80-4f1c-11e9-9b5e-d0449a373c7e.jpg)
On Android I have this Verizon pre-installed app, It's detecting a compromised network when connected to Wifiphisher. Does anyone know how it is detecting this?

**Comment by sophron** [comment]
Let's keep everything related to alerts and detections on #1100.
