### ISSUE TITLE
Wifiphisher.service possible?

### ISSUE THREAD

**Issue by N2Network** [wifiphisher/wifiphisher#1098]
I'm trying to configure Wifiphisher as a service but I think it needs an active console or something in order to run. I was hoping someone could point me in the right direction on how this can be accomplished. The main goal is to have it run on startup.

>
 [Unit]
Description=wifiphisher
After=multi-user.target

[Service]
Type=oneshot
ExecStart=airmon-ng check kill
ExecStart=ifconfig wlan0 down
ExecStart=iwconfig wlan0 mode monitor
ExecStart=ifconfig wlan0 up
##Enable if two wireless cards
#ExecStart=ifconfig wlan1 down
#ExecStart=iwconfig wlan1 mode monitor
#ExecStart=ifconfig wlan1 up
ExecStart=/usr/bin/python -u /root/wifiphisher/bin/wifiphisher -pPD /root/wifiphisher/wifiphisher/data/phishing-pages -e "Free Wifi" -kB -p google-login --logging -lP /root/w$
StandardOutput=syslog
StandardError=syslog

[Install]
WantedBy=multi-user.target
>

**Comment by sophron** [comment]
I'm not sure I understand what you are trying to achieve. You are executing other binaries (e.g. airmon-ng) when you probably don't have to. 

In any case, this is neither a bug nor a feature request. You will find more luck asking this somewhere else.
