### ISSUE TITLE
Wifiphisher works on version 1.3 but not 1.4 ?  On version 1.4 it says rogue host and not installed but on 1.3 it works fine can you use the code in 1.3 to fix problems 

### ISSUE THREAD

**Issue by username836** [wifiphisher/wifiphisher#1099]
Before opening a new issue, please make sure that what you are about to report has not been reported already or is not included on the FAQ page. If not, use the following template for reporting.

Please keep in mind that our developers will prioritize your issue if you provide a detailed and extensive description.

**Version**: Use `git show | grep commit` command and paste here the output.

**Description**: Give a more analytical description here. Let us know how we can reproduce the reported issue. Detail the characteristics of your machine (e.g. Linux distribution and wireless card capabilities) and of the victim devices too (e.g. OS or web browser) if possible. The output of the `iw list` and `iwconfig` commands may also be helpful here.

**Script output**: Paste the output of the tool, including any stack traces.

**Comment by sophron** [comment]
On Wifiphisher 1.4 we introduced roguehostapd (a fork of hostapd) as a requirement. You will have to install it if you want to run Wifiphisher.

**Comment by username836** [comment]
I did install it but it still says roguehostapd not installed but when I use the older version it works I don't know why ?

**Comment by sophron** [comment]
Look at my answer above.
