### ISSUE TITLE
How to install roguehostapd ?

### ISSUE THREAD

**Issue by username836** [wifiphisher/wifiphisher#1102]
I followed the steps on the git hub roguehostapd and still won't work

**Comment by sophron** [comment]
We won't be able to help you if you don't provide any information.

**Comment by username836** [comment]
I'll take a photo

**Comment by username836** [comment]
The issue is python: can't open file 'run.py when I type:python run.py -i

**Comment by username836** [comment]
And when I type root@kali:where is roguehostapd:

It finds nothing 

Or locate finds nothing 
Which is why wifiphisher will not detect it I think ?

**Comment by username836** [comment]
And my interface is wlan0 by the way

**Comment by IDETUSOFT** [comment]
still won't work
![image](https://user-images.githubusercontent.com/47303228/60561627-c9639280-9d19-11e9-9666-a87dd61b2b5f.png)
