### ISSUE TITLE
My rtl8187 Wireless card is working with other evil twin scripts but not with Wifiphisher

### ISSUE THREAD

**Issue by matdejfirst** [wifiphisher/wifiphisher#1106]
Hello,

I hope you all doing well, recently I discovered wifiphisher, it looks interesting, but unfortanantly can't get it to work, it says that either the selected interface doesn't exist or it doesn't support ap mode, meanwhile the same card is working fine with linset, it can create a fake ap and an mdk3 attack the same time, can someone explain what the issue here? if it's with the card can you please suggest some?

Thanks in advance.

**Comment by sophron** [comment]
What card are you using? Can you give us the output of `iw list` and `iwconfig`?

**Comment by djdisikd** [comment]
Yeah I have this problem too

**Comment by djdisikd** [comment]
It works with airbase-ng but wifiphisher doesn't seem to work at all
