### ISSUE TITLE
what about  a Sextortion  based phishing page ?

### ISSUE THREAD

**Issue by minanagehsalalma** [wifiphisher/wifiphisher#1107]
i am not talking about Threatening the user to send money or post the *** videos part  ..

but i am talking about the part where  they makes these threats more plausible .. 
that they use old/still in use   passwords  from data breaches .
so the idea is to tell the user to confirm the old password change ( here we type the old password ) please re-enter your new password . this only in case of knowing an old password of the target wifi .

or if we don't know the old password but we know that the password had been changed recently 
the page tells the user to confirm the password change please re-enter your new password .

![image](https://user-images.githubusercontent.com/20546638/55673580-fe428380-58a9-11e9-93da-7e34d8cce190.png)

tell me what do you think 

reference 
https://www.cisecurity.org/blog/sextortion-hoax-scams-updated-tactics/

**Comment by sophron** [comment]
Feel free to create your own phishing scenario: https://wifiphisher.readthedocs.io/en/latest/custom_phishing_scenario.html

**Comment by minanagehsalalma** [comment]
Thanks I will add it to my to do later :)
