### ISSUE TITLE
Startup failure

### ISSUE THREAD

**Issue by seyo-IV** [wifiphisher/wifiphisher#1109]
I'm getting the following error. What am I missing? I'm running it on a raspberry pi zero w with kali linux and nexmon installed. Monitor mode and injection should work.

root@kali:~# wifiphisher
[*] Starting Wifiphisher 1.4GIT ( https://wifiphisher.org ) at 2019-04-08 06:23
[+] Timezone detected. Setting channel range to 1-13
[+] Selecting wfphshr-wlan0 interface for the deauthentication attack
[+] Selecting wlan0 interface for creating the rogue Access Point
[+] Changing wlan0 MAC addr (BSSID) to 00:00:00:23:15:68
Traceback (most recent call last):
  File "/usr/local/bin/wifiphisher", line 11, in <module>
    load_entry_point('wifiphisher==1.4', 'console_scripts', 'wifiphisher')()
  File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.4-py2.7.egg/wifiphisher/pywifiphisher.py", line 693, in run
    engine.start()
  File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.4-py2.7.egg/wifiphisher/pywifiphisher.py", line 466, in start
    args.mac_extensions_interface)
  File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.4-py2.7.egg/wifiphisher/common/interfaces.py", line 496, in set_interface_mac
    self.set_interface_mode(interface_name, "managed")
  File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.4-py2.7.egg/wifiphisher/common/interfaces.py", line 541, in set_interface_mode
    pyw.modeset(card, mode)
  File "/usr/local/lib/python2.7/dist-packages/PyRIC-0.1.6.3-py2.7.egg/pyric/pyw.py", line 1323, in modeset
    if nlsock is None: return _nlstub_(modeset, card, mode, flags)
  File "/usr/local/lib/python2.7/dist-packages/PyRIC-0.1.6.3-py2.7.egg/pyric/pyw.py", line 2236, in _nlstub_
    return fct(*argv)
  File "/usr/local/lib/python2.7/dist-packages/PyRIC-0.1.6.3-py2.7.egg/pyric/pyw.py", line 1340, in modeset
    raise pyric.error(e.errno, e.strerror)
pyric.error: [Errno 16] Device or resource busy

**Comment by seyo-IV** [comment]
Now im getting the same error on my raspberry pi 3 b+
I have installed all needed dependencies, waht am i missing?

**Comment by sophron** [comment]
See #354.

**Comment by seyo-IV** [comment]
I actually tried that before but now it did work. Can be closed.

**Comment by Nekr0zJDM** [comment]
I've also just come across this problem. I have tried airmon-ng check kill but it still doesn't work for me. Please help.

**Comment by haroonalhadisk** [comment]
@Nekr0zJDM  I had the same issue. dont know why but these steps actully helped
create a file named startupap.sh add the following lines

service apache2 start
sleep 1
ifconfig wlan0 down
macchanger -A wlan0
ifconfig wlan0 up
sleep 1
hostapd -B /etc/hostapd/hostapd.conf
sleep 2
ifconfig br0 up
ifconfig br0 10.1.1.1 netmask 255.255.255.0
sysctl net.ipv4.ip_forward=1
iptables --flush
iptables -t nat --flush
iptables -t nat -A PREROUTING -i br0 -p udp -m udp --dport 53 -j DNAT --to-destination 10.1.1.1:53
iptables -t nat -A PREROUTING -i br0 -p tcp -m tcp --dport 80 -j DNAT --to-destination 10.1.1.1:80
iptables -t nat -A PREROUTING -i br0 -p tcp -m tcp --dport 443 -j DNAT --to-destination 10.1.1.1:80
iptables -t nat -A POSTROUTING -j MASQUERADE
service dnsmasq start
exit 0

#------------------------------------------------------------------------------------

move the file to root directory
type command crontab -e
add lines into the file "@reboot sudo sleep 15 && sudo sh /root/startap.sh &"
paste the same line 3-4 times and try rebooting. hope this helps

**Comment by Joerny** [comment]
I managed to start wifiphisher on a raspberry pi. It seems that it do not like the changing of the MAC address. If I start it with `wifiphisher -iNM`, it starts and shows the list of networks as expected.
