### ISSUE TITLE
what about a dns rebinding  attack ?

### ISSUE THREAD

**Issue by minanagehsalalma** [wifiphisher/wifiphisher#1114]
the advantage is that we get the password just by the user opening  the captive portal page !

how i think the Scenario should go 
evil twining a wifi using wifiphisher .... when the user opens the captive portal sign in network page (that has dns rebinding scripts in it )is detected we stop the ddos ... the user auto connects to his wifi then the page refreshes and execute the dns rebinding attack to get the wifi password from his router ....

an article that explains this more 
https://sinister.ly/Thread-DNS-Rebinding-Attack

**Comment by sophron** [comment]
After getting man-in-the-middle with Wifiphisher, there are many different attacks that the tester can mount (DNS rebinding too). We cannot support all of them for many reasons and we recommend users to use Wifiphisher in conjunction with other tools.

**Comment by minanagehsalalma** [comment]
@sophron  
I know .. 
I don't see any other tools that automate this .
I don't think that's the others are too useful compared to DNS rebinding .
So is it no for DNS rebinding ?

**Comment by minanagehsalalma** [comment]
@sophron 

>After getting man-in-the-middle with Wifiphisher, there are many different attacks that the tester can mount 

 not really non of them gets you the wifi password ( there is no other new  ways  as i think)without user intervention  
And non as fast as dns-rebinding  ! 
"We cannot support all of them for many reasons" 
I am not asking for all of them  ..  Only this one 
I can't  think of anyother one that's good as this !

**Comment by minanagehsalalma** [comment]
@sophron  but this isn't a question ... This is a feature request :( 😕

**Comment by sophron** [comment]
This is a question of whether we want to implement a feature request. And the answer is no.

**Comment by minanagehsalalma** [comment]
@sophron  lol ... That makes sense now :).
Alright as you like I may try to implement it  on my own ... Although I know that I will failed doing it :(
Thanks for your response
