### ISSUE TITLE
scripts crashes !!

### ISSUE THREAD

**Issue by excep** [wifiphisher/wifiphisher#1115]
everything was Okay !! I tried it myself just to make sur everything is good, but when I connect to the fake AP and it stars redirecting me to connect Manager on my phone ..... the script crashes and that upgrade framwork don,t pop up ....

**Comment by sophron** [comment]
Hi, use the issue template for reporting. Otherwise, we won't be able to help you.

**Comment by excep** [comment]
It creats to many random fake APs.
Sometimes it doesn't redirect the victime to the fake upgrade framework. And even if it does, the script crashes. And the fake upgrade framework don't pop up.
 

I can't even give you template error cuz it merely often times that it redirects the victime to the fake upgrade framework so the crash happens

**Comment by sophron** [comment]
> It creats to many random fake APs.

You probably have Known Beacons enabled.

> Sometimes it doesn't redirect the victime to the fake upgrade framework. And even if it does, the script crashes. And the fake upgrade framework don't pop up.

When exactly? And what is the output of the crash?

> I can't even give you template error cuz it merely often times that it redirects the victime to the fake upgrade framework so the crash happens

We cannot help you if you don't provide the required information.
