### ISSUE TITLE
Can't install wifiphisher

### ISSUE THREAD

**Issue by XTheBreakerX** [wifiphisher/wifiphisher#1119]
When i setup the install this error apears...
root@Bruno:~/wifiphisher# sudo python setup.py install
running install
running bdist_egg
running egg_info
writing requirements to wifiphisher.egg-info/requires.txt
writing wifiphisher.egg-info/PKG-INFO
writing top-level names to wifiphisher.egg-info/top_level.txt
writing dependency_links to wifiphisher.egg-info/dependency_links.txt
writing entry points to wifiphisher.egg-info/entry_points.txt
reading manifest file 'wifiphisher.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'wifiphisher.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/wifiphisher
creating build/bdist.linux-x86_64/egg/wifiphisher/extensions
copying build/lib.linux-x86_64-2.7/wifiphisher/extensions/__init__.py -> build/bdist.linux-x86_64/egg/wifiphisher/extensions
copying build/lib.linux-x86_64-2.7/wifiphisher/extensions/deauth.py -> build/bdist.linux-x86_64/egg/wifiphisher/extensions
copying build/lib.linux-x86_64-2.7/wifiphisher/extensions/knownbeacons.py -> build/bdist.linux-x86_64/egg/wifiphisher/extensions
copying build/lib.linux-x86_64-2.7/wifiphisher/extensions/lure10.py -> build/bdist.linux-x86_64/egg/wifiphisher/extensions
copying build/lib.linux-x86_64-2.7/wifiphisher/extensions/roguehostapdinfo.py -> build/bdist.linux-x86_64/egg/wifiphisher/extensions
copying build/lib.linux-x86_64-2.7/wifiphisher/extensions/wpspbc.py -> build/bdist.linux-x86_64/egg/wifiphisher/extensions
copying build/lib.linux-x86_64-2.7/wifiphisher/extensions/handshakeverify.py -> build/bdist.linux-x86_64/egg/wifiphisher/extensions
copying build/lib.linux-x86_64-2.7/wifiphisher/pywifiphisher.py -> build/bdist.linux-x86_64/egg/wifiphisher
copying build/lib.linux-x86_64-2.7/wifiphisher/__init__.py -> build/bdist.linux-x86_64/egg/wifiphisher
creating build/bdist.linux-x86_64/egg/wifiphisher/data
copying build/lib.linux-x86_64-2.7/wifiphisher/data/wifiphisher-os-initial-requests -> build/bdist.linux-x86_64/egg/wifiphisher/data
creating build/bdist.linux-x86_64/egg/wifiphisher/data/locs
copying build/lib.linux-x86_64-2.7/wifiphisher/data/locs/.gitkeep -> build/bdist.linux-x86_64/egg/wifiphisher/data/locs
creating build/bdist.linux-x86_64/egg/wifiphisher/data/cert
copying build/lib.linux-x86_64-2.7/wifiphisher/data/cert/server.pem -> build/bdist.linux-x86_64/egg/wifiphisher/data/cert
creating build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages
creating build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/firmware-upgrade
creating build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/firmware-upgrade/html
copying build/lib.linux-x86_64-2.7/wifiphisher/data/phishing-pages/firmware-upgrade/html/loading.html -> build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/firmware-upgrade/html
creating build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/firmware-upgrade/html/static
copying build/lib.linux-x86_64-2.7/wifiphisher/data/phishing-pages/firmware-upgrade/html/static/bootstrap.min.css -> build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/firmware-upgrade/html/static
copying build/lib.linux-x86_64-2.7/wifiphisher/data/phishing-pages/firmware-upgrade/html/static/jquery.min.js -> build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/firmware-upgrade/html/static
copying build/lib.linux-x86_64-2.7/wifiphisher/data/phishing-pages/firmware-upgrade/html/static/bootstrap.min.js -> build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/firmware-upgrade/html/static
creating build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/firmware-upgrade/html/static/font-awesome-4.7.0
creating build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/firmware-upgrade/html/static/font-awesome-4.7.0/css
copying build/lib.linux-x86_64-2.7/wifiphisher/data/phishing-pages/firmware-upgrade/html/static/font-awesome-4.7.0/css/font-awesome.css -> build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/firmware-upgrade/html/static/font-awesome-4.7.0/css
copying build/lib.linux-x86_64-2.7/wifiphisher/data/phishing-pages/firmware-upgrade/html/static/font-awesome-4.7.0/css/font-awesome.min.css -> build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/firmware-upgrade/html/static/font-awesome-4.7.0/css
creating build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/firmware-upgrade/html/static/font-awesome-4.7.0/fonts
copying build/lib.linux-x86_64-2.7/wifiphisher/data/phishing-pages/firmware-upgrade/html/static/font-awesome-4.7.0/fonts/fontawesome-webfont.ttf -> build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/firmware-upgrade/html/static/font-awesome-4.7.0/fonts
copying build/lib.linux-x86_64-2.7/wifiphisher/data/phishing-pages/firmware-upgrade/html/static/font-awesome-4.7.0/fonts/fontawesome-webfont.woff -> build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/firmware-upgrade/html/static/font-awesome-4.7.0/fonts
copying build/lib.linux-x86_64-2.7/wifiphisher/data/phishing-pages/firmware-upgrade/html/static/font-awesome-4.7.0/fonts/fontawesome-webfont.woff2 -> build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/firmware-upgrade/html/static/font-awesome-4.7.0/fonts
copying build/lib.linux-x86_64-2.7/wifiphisher/data/phishing-pages/firmware-upgrade/html/static/font-awesome-4.7.0/fonts/FontAwesome.otf -> build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/firmware-upgrade/html/static/font-awesome-4.7.0/fonts
copying build/lib.linux-x86_64-2.7/wifiphisher/data/phishing-pages/firmware-upgrade/html/static/font-awesome-4.7.0/fonts/fontawesome-webfont.eot -> build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/firmware-upgrade/html/static/font-awesome-4.7.0/fonts
copying build/lib.linux-x86_64-2.7/wifiphisher/data/phishing-pages/firmware-upgrade/html/static/font-awesome-4.7.0/fonts/fontawesome-webfont.svg -> build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/firmware-upgrade/html/static/font-awesome-4.7.0/fonts
copying build/lib.linux-x86_64-2.7/wifiphisher/data/phishing-pages/firmware-upgrade/html/bootstrap.min.css -> build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/firmware-upgrade/html
copying build/lib.linux-x86_64-2.7/wifiphisher/data/phishing-pages/firmware-upgrade/html/jquery.min.js -> build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/firmware-upgrade/html
copying build/lib.linux-x86_64-2.7/wifiphisher/data/phishing-pages/firmware-upgrade/html/upgrading.html -> build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/firmware-upgrade/html
copying build/lib.linux-x86_64-2.7/wifiphisher/data/phishing-pages/firmware-upgrade/html/bootstrap.min.js -> build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/firmware-upgrade/html
copying build/lib.linux-x86_64-2.7/wifiphisher/data/phishing-pages/firmware-upgrade/html/index.html -> build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/firmware-upgrade/html
copying build/lib.linux-x86_64-2.7/wifiphisher/data/phishing-pages/firmware-upgrade/config.ini -> build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/firmware-upgrade
creating build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/oauth-login
creating build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/oauth-login/html
creating build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/oauth-login/html/static
creating build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/oauth-login/html/static/js
copying build/lib.linux-x86_64-2.7/wifiphisher/data/phishing-pages/oauth-login/html/static/js/index.js -> build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/oauth-login/html/static/js
copying build/lib.linux-x86_64-2.7/wifiphisher/data/phishing-pages/oauth-login/html/static/js/jquery.min.js -> build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/oauth-login/html/static/js
creating build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/oauth-login/html/static/css
copying build/lib.linux-x86_64-2.7/wifiphisher/data/phishing-pages/oauth-login/html/static/css/reset.css -> build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/oauth-login/html/static/css
copying build/lib.linux-x86_64-2.7/wifiphisher/data/phishing-pages/oauth-login/html/static/css/roboto.css -> build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/oauth-login/html/static/css
copying build/lib.linux-x86_64-2.7/wifiphisher/data/phishing-pages/oauth-login/html/static/css/style.css -> build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/oauth-login/html/static/css
copying build/lib.linux-x86_64-2.7/wifiphisher/data/phishing-pages/oauth-login/html/static/css/font-awesome.min.css -> build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/oauth-login/html/static/css
copying build/lib.linux-x86_64-2.7/wifiphisher/data/phishing-pages/oauth-login/html/index.html -> build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/oauth-login/html
copying build/lib.linux-x86_64-2.7/wifiphisher/data/phishing-pages/oauth-login/html/oauth.html -> build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/oauth-login/html
copying build/lib.linux-x86_64-2.7/wifiphisher/data/phishing-pages/oauth-login/config.ini -> build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/oauth-login
creating build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/plugin_update
creating build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/plugin_update/html
creating build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/plugin_update/html/static
creating build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/plugin_update/html/static/images
copying build/lib.linux-x86_64-2.7/wifiphisher/data/phishing-pages/plugin_update/html/static/images/favicon.ico -> build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/plugin_update/html/static/images
copying build/lib.linux-x86_64-2.7/wifiphisher/data/phishing-pages/plugin_update/html/static/images/plugins.png -> build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/plugin_update/html/static/images
creating build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/plugin_update/html/static/js
copying build/lib.linux-x86_64-2.7/wifiphisher/data/phishing-pages/plugin_update/html/static/js/bootstrap.min.js -> build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/plugin_update/html/static/js
copying build/lib.linux-x86_64-2.7/wifiphisher/data/phishing-pages/plugin_update/html/static/js/jquery.js -> build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/plugin_update/html/static/js
creating build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/plugin_update/html/static/update
copying build/lib.linux-x86_64-2.7/wifiphisher/data/phishing-pages/plugin_update/html/static/update/update.exe -> build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/plugin_update/html/static/update
creating build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/plugin_update/html/static/css
copying build/lib.linux-x86_64-2.7/wifiphisher/data/phishing-pages/plugin_update/html/static/css/theme.css -> build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/plugin_update/html/static/css
copying build/lib.linux-x86_64-2.7/wifiphisher/data/phishing-pages/plugin_update/html/static/css/bootstrap.min.css -> build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/plugin_update/html/static/css
creating build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/plugin_update/html/images
copying build/lib.linux-x86_64-2.7/wifiphisher/data/phishing-pages/plugin_update/html/images/favicon.ico -> build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/plugin_update/html/images
copying build/lib.linux-x86_64-2.7/wifiphisher/data/phishing-pages/plugin_update/html/images/plugins.png -> build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/plugin_update/html/images
creating build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/plugin_update/html/js
copying build/lib.linux-x86_64-2.7/wifiphisher/data/phishing-pages/plugin_update/html/js/bootstrap.min.js -> build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/plugin_update/html/js
copying build/lib.linux-x86_64-2.7/wifiphisher/data/phishing-pages/plugin_update/html/js/jquery.js -> build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/plugin_update/html/js
creating build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/plugin_update/html/update
copying build/lib.linux-x86_64-2.7/wifiphisher/data/phishing-pages/plugin_update/html/update/update.exe -> build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/plugin_update/html/update
copying build/lib.linux-x86_64-2.7/wifiphisher/data/phishing-pages/plugin_update/html/index.html -> build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/plugin_update/html
creating build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/plugin_update/html/css
copying build/lib.linux-x86_64-2.7/wifiphisher/data/phishing-pages/plugin_update/html/css/theme.css -> build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/plugin_update/html/css
copying build/lib.linux-x86_64-2.7/wifiphisher/data/phishing-pages/plugin_update/html/css/bootstrap.min.css -> build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/plugin_update/html/css
copying build/lib.linux-x86_64-2.7/wifiphisher/data/phishing-pages/plugin_update/config.ini -> build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/plugin_update
creating build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/wifi_connect
creating build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/wifi_connect/html
copying build/lib.linux-x86_64-2.7/wifiphisher/data/phishing-pages/wifi_connect/html/loading.html -> build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/wifi_connect/html
creating build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/wifi_connect/html/static
copying build/lib.linux-x86_64-2.7/wifiphisher/data/phishing-pages/wifi_connect/html/static/wifi-icon.png -> build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/wifi_connect/html/static
copying build/lib.linux-x86_64-2.7/wifiphisher/data/phishing-pages/wifi_connect/html/static/chrome-offline.css -> build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/wifi_connect/html/static
copying build/lib.linux-x86_64-2.7/wifiphisher/data/phishing-pages/wifi_connect/html/static/win-behavior.js -> build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/wifi_connect/html/static
copying build/lib.linux-x86_64-2.7/wifiphisher/data/phishing-pages/wifi_connect/html/static/mac-network-manager.css -> build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/wifi_connect/html/static
copying build/lib.linux-x86_64-2.7/wifiphisher/data/phishing-pages/wifi_connect/html/static/behavior.js -> build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/wifi_connect/html/static
copying build/lib.linux-x86_64-2.7/wifiphisher/data/phishing-pages/wifi_connect/html/static/opensans.ttf -> build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/wifi_connect/html/static
copying build/lib.linux-x86_64-2.7/wifiphisher/data/phishing-pages/wifi_connect/html/static/dinosaur.png -> build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/wifi_connect/html/static
copying build/lib.linux-x86_64-2.7/wifiphisher/data/phishing-pages/wifi_connect/html/static/opensans.css -> build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/wifi_connect/html/static
copying build/lib.linux-x86_64-2.7/wifiphisher/data/phishing-pages/wifi_connect/html/static/style.css -> build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/wifi_connect/html/static
copying build/lib.linux-x86_64-2.7/wifiphisher/data/phishing-pages/wifi_connect/html/static/question.png -> build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/wifi_connect/html/static
copying build/lib.linux-x86_64-2.7/wifiphisher/data/phishing-pages/wifi_connect/html/wifi-icon.png -> build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/wifi_connect/html
copying build/lib.linux-x86_64-2.7/wifiphisher/data/phishing-pages/wifi_connect/html/chrome-offline.css -> build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/wifi_connect/html
copying build/lib.linux-x86_64-2.7/wifiphisher/data/phishing-pages/wifi_connect/html/win-behavior.js -> build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/wifi_connect/html
copying build/lib.linux-x86_64-2.7/wifiphisher/data/phishing-pages/wifi_connect/html/mac-network-manager.css -> build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/wifi_connect/html
copying build/lib.linux-x86_64-2.7/wifiphisher/data/phishing-pages/wifi_connect/html/behavior.js -> build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/wifi_connect/html
copying build/lib.linux-x86_64-2.7/wifiphisher/data/phishing-pages/wifi_connect/html/opensans.ttf -> build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/wifi_connect/html
copying build/lib.linux-x86_64-2.7/wifiphisher/data/phishing-pages/wifi_connect/html/index.html -> build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/wifi_connect/html
copying build/lib.linux-x86_64-2.7/wifiphisher/data/phishing-pages/wifi_connect/html/dinosaur.png -> build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/wifi_connect/html
copying build/lib.linux-x86_64-2.7/wifiphisher/data/phishing-pages/wifi_connect/html/opensans.css -> build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/wifi_connect/html
copying build/lib.linux-x86_64-2.7/wifiphisher/data/phishing-pages/wifi_connect/html/style.css -> build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/wifi_connect/html
copying build/lib.linux-x86_64-2.7/wifiphisher/data/phishing-pages/wifi_connect/html/question.png -> build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/wifi_connect/html
copying build/lib.linux-x86_64-2.7/wifiphisher/data/phishing-pages/wifi_connect/config.ini -> build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/wifi_connect
copying build/lib.linux-x86_64-2.7/wifiphisher/data/wifiphisher-known-open-wlans -> build/bdist.linux-x86_64/egg/wifiphisher/data
copying build/lib.linux-x86_64-2.7/wifiphisher/data/wifiphisher-mac-prefixes -> build/bdist.linux-x86_64/egg/wifiphisher/data
creating build/bdist.linux-x86_64/egg/wifiphisher/common
copying build/lib.linux-x86_64-2.7/wifiphisher/common/macmatcher.py -> build/bdist.linux-x86_64/egg/wifiphisher/common
copying build/lib.linux-x86_64-2.7/wifiphisher/common/firewall.py -> build/bdist.linux-x86_64/egg/wifiphisher/common
copying build/lib.linux-x86_64-2.7/wifiphisher/common/phishingpage.py -> build/bdist.linux-x86_64/egg/wifiphisher/common
copying build/lib.linux-x86_64-2.7/wifiphisher/common/utilities.py -> build/bdist.linux-x86_64/egg/wifiphisher/common
copying build/lib.linux-x86_64-2.7/wifiphisher/common/__init__.py -> build/bdist.linux-x86_64/egg/wifiphisher/common
copying build/lib.linux-x86_64-2.7/wifiphisher/common/interfaces.py -> build/bdist.linux-x86_64/egg/wifiphisher/common
copying build/lib.linux-x86_64-2.7/wifiphisher/common/victim.py -> build/bdist.linux-x86_64/egg/wifiphisher/common
copying build/lib.linux-x86_64-2.7/wifiphisher/common/uimethods.py -> build/bdist.linux-x86_64/egg/wifiphisher/common
copying build/lib.linux-x86_64-2.7/wifiphisher/common/globals.py -> build/bdist.linux-x86_64/egg/wifiphisher/common
copying build/lib.linux-x86_64-2.7/wifiphisher/common/opmode.py -> build/bdist.linux-x86_64/egg/wifiphisher/common
copying build/lib.linux-x86_64-2.7/wifiphisher/common/extensions.py -> build/bdist.linux-x86_64/egg/wifiphisher/common
copying build/lib.linux-x86_64-2.7/wifiphisher/common/constants.py -> build/bdist.linux-x86_64/egg/wifiphisher/common
copying build/lib.linux-x86_64-2.7/wifiphisher/common/tui.py -> build/bdist.linux-x86_64/egg/wifiphisher/common
copying build/lib.linux-x86_64-2.7/wifiphisher/common/recon.py -> build/bdist.linux-x86_64/egg/wifiphisher/common
copying build/lib.linux-x86_64-2.7/wifiphisher/common/accesspoint.py -> build/bdist.linux-x86_64/egg/wifiphisher/common
copying build/lib.linux-x86_64-2.7/wifiphisher/common/phishinghttp.py -> build/bdist.linux-x86_64/egg/wifiphisher/common
byte-compiling build/bdist.linux-x86_64/egg/wifiphisher/extensions/__init__.py to __init__.pyc
byte-compiling build/bdist.linux-x86_64/egg/wifiphisher/extensions/deauth.py to deauth.pyc
byte-compiling build/bdist.linux-x86_64/egg/wifiphisher/extensions/knownbeacons.py to knownbeacons.pyc
byte-compiling build/bdist.linux-x86_64/egg/wifiphisher/extensions/lure10.py to lure10.pyc
byte-compiling build/bdist.linux-x86_64/egg/wifiphisher/extensions/roguehostapdinfo.py to roguehostapdinfo.pyc
byte-compiling build/bdist.linux-x86_64/egg/wifiphisher/extensions/wpspbc.py to wpspbc.pyc
byte-compiling build/bdist.linux-x86_64/egg/wifiphisher/extensions/handshakeverify.py to handshakeverify.pyc
byte-compiling build/bdist.linux-x86_64/egg/wifiphisher/pywifiphisher.py to pywifiphisher.pyc
byte-compiling build/bdist.linux-x86_64/egg/wifiphisher/__init__.py to __init__.pyc
byte-compiling build/bdist.linux-x86_64/egg/wifiphisher/common/macmatcher.py to macmatcher.pyc
byte-compiling build/bdist.linux-x86_64/egg/wifiphisher/common/firewall.py to firewall.pyc
byte-compiling build/bdist.linux-x86_64/egg/wifiphisher/common/phishingpage.py to phishingpage.pyc
byte-compiling build/bdist.linux-x86_64/egg/wifiphisher/common/utilities.py to utilities.pyc
byte-compiling build/bdist.linux-x86_64/egg/wifiphisher/common/__init__.py to __init__.pyc
byte-compiling build/bdist.linux-x86_64/egg/wifiphisher/common/interfaces.py to interfaces.pyc
byte-compiling build/bdist.linux-x86_64/egg/wifiphisher/common/victim.py to victim.pyc
byte-compiling build/bdist.linux-x86_64/egg/wifiphisher/common/uimethods.py to uimethods.pyc
byte-compiling build/bdist.linux-x86_64/egg/wifiphisher/common/globals.py to globals.pyc
byte-compiling build/bdist.linux-x86_64/egg/wifiphisher/common/opmode.py to opmode.pyc
byte-compiling build/bdist.linux-x86_64/egg/wifiphisher/common/extensions.py to extensions.pyc
byte-compiling build/bdist.linux-x86_64/egg/wifiphisher/common/constants.py to constants.pyc
byte-compiling build/bdist.linux-x86_64/egg/wifiphisher/common/tui.py to tui.pyc
byte-compiling build/bdist.linux-x86_64/egg/wifiphisher/common/recon.py to recon.pyc
byte-compiling build/bdist.linux-x86_64/egg/wifiphisher/common/accesspoint.py to accesspoint.pyc
byte-compiling build/bdist.linux-x86_64/egg/wifiphisher/common/phishinghttp.py to phishinghttp.pyc
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying wifiphisher.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying wifiphisher.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying wifiphisher.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying wifiphisher.egg-info/entry_points.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying wifiphisher.egg-info/requires.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying wifiphisher.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
zip_safe flag not set; analyzing archive contents...
wifiphisher.common.constants: module references __file__
creating 'dist/wifiphisher-1.4-py2.7.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing wifiphisher-1.4-py2.7.egg
removing '/usr/local/lib/python2.7/dist-packages/wifiphisher-1.4-py2.7.egg' (and everything under it)
creating /usr/local/lib/python2.7/dist-packages/wifiphisher-1.4-py2.7.egg
Extracting wifiphisher-1.4-py2.7.egg to /usr/local/lib/python2.7/dist-packages
wifiphisher 1.4 is already the active version in easy-install.pth
Installing wifiphisher script to /usr/local/bin

Installed /usr/local/lib/python2.7/dist-packages/wifiphisher-1.4-py2.7.egg
Processing dependencies for wifiphisher==1.4
Searching for tornado==4.5.3
Reading https://pypi.org/simple/tornado/
Download error on https://pypi.org/simple/tornado/: [Errno 104] Connection reset by peer -- Some packages may not be found!
Couldn't retrieve index page for 'tornado'
Scanning index of all packages (this may take a while)
Reading https://pypi.org/simple/
Download error on https://pypi.org/simple/: [Errno 104] Connection reset by peer -- Some packages may not be found!
No local packages or working download links found for tornado==4.5.3
error: Could not find suitable distribution for Requirement.parse('tornado==4.5.3')
I can't fix it, please help

**Comment by sophron** [comment]
There is obviously a problem with your Internet connection. Nothing related to Wifiphisher here.
