### ISSUE TITLE
Fully working distro for wifiphisher?

### ISSUE THREAD

**Issue by Throwaway684736** [wifiphisher/wifiphisher#1123]
Can you suggest a fully working distro to try wifiphisher on?
I'm installing it to vbox anyway, so I don't want to mess with failed dependencies and missing libs that is often the case.

(Had a really hard time installing WIFI Pumpkin .. =)

Thanks!

**Comment by vs4vijay** [comment]
I think, "Kali Linux" will work.

**Comment by sophron** [comment]
Kali Linux is the officially supported distribution.
