### ISSUE TITLE
Wifiphisher not Working

### ISSUE THREAD

**Issue by visheshmishra9918** [wifiphisher/wifiphisher#1124]
Before opening a new issue, please make sure that what you are about to report has not been reported already or is not included on the FAQ page. If not, use the following template for reporting.

Please keep in mind that our developers will prioritize your issue if you provide a detailed and extensive description.

**Version**: Use `git show | grep commit` command and paste here the output.

**Description**: Give a more analytical description here. Let us know how we can reproduce the reported issue. Detail the characteristics of your machine (e.g. Linux distribution and wireless card capabilities) and of the victim devices too (e.g. OS or web browser) if possible. The output of the `iw list` and `iwconfig` commands may also be helpful here.

**Script output**: Paste the output of the tool, including any stack traces.

**Comment by visheshmishra9918** [comment]
![Screenshot at 2019-05-03 02-24-00](https://user-images.githubusercontent.com/50218329/57106322-ac770700-6d4a-11e9-9d23-a71fb54e5584.png)

**Comment by visheshmishra9918** [comment]
![Screenshot at 2019-05-03 02-26-20](https://user-images.githubusercontent.com/50218329/57106390-daf4e200-6d4a-11e9-8691-46e296ac3ebf.png)

**Comment by djdisikd** [comment]
Failed to find an interface with AP mode

**Comment by sophron** [comment]
You need a card that supports AP mode. Also, `--nojamming` is deprecated.
