### ISSUE TITLE
Modify login facebook

### ISSUE THREAD

**Issue by miswindev** [wifiphisher/wifiphisher#1132]
Modify Facebook page( OAuth Login Page)  to accept numbers and texts instead of email
![Facbook](https://user-images.githubusercontent.com/51040731/58377697-b32e1e00-7f86-11e9-835c-d6334874d2e5.jpg)

**Comment by sophron** [comment]
I'm not sure I understand your request. The email field should always accept an email, right?

**Comment by miswindev** [comment]
I want the field to accept everything numbers or texts

**Comment by miswindev** [comment]
I found some information on the subject but I did not find the instruction line
<form name="theform" class="theform" method="post" action="oauth.html" onsubmit="return validateForm();">
To this

<form name="theform" class="theform" method="post" action="oauth.html">

**Comment by miswindev** [comment]
![facbook](https://user-images.githubusercontent.com/51040731/58521284-62a00600-81bc-11e9-9de0-d01d2ebd6be3.png)

**Comment by sophron** [comment]
Learn HTML and create your own page: https://wifiphisher.readthedocs.io/en/latest/custom_phishing_scenario.html
