### ISSUE TITLE
Device does not support nl80211 TP link Wifi Dongle

### ISSUE THREAD

**Issue by MolinoDK** [wifiphisher/wifiphisher#1133]
I've got a laptop with Kali Linux, and i installed Wifiphiser. I tried with my build ind network card, and it works sometimes, then i invested in a TP Link USB wifi dongle TL-WN722N that should be that one that is connected to the internet, and then the build in card should capture. But when i plug the USB wifi dongle in, and choose the build in card (wlan1) and i try to run Wifiphisher, it says "Device not support nl80211" and i don't use that USB to wifiphisher. 

Is it possible to let WifiPhisher take the build in card, and ignore that USB wifi dongle?

**Comment by sophron** [comment]
Please read the manual. There are many options that you can use (e.g. --interface).
