### ISSUE TITLE
It just closes

### ISSUE THREAD

**Issue by PartyManCZ** [wifiphisher/wifiphisher#1134]
Hello guys, I have been trying to run wifiphisher for about 3 hours now but it still keeps writing Closing after I select any phishing type, I am using Ubuntu 18.10 and using a wifi adapter, pls help.

> [*] Starting Wifiphisher 1.4GIT ( https://wifiphisher.org ) at 2019-05-26 19:34 

> [+] Timezone detected. Setting channel range to 1-13 

> [+] Selecting wfphshr-wlan0 interface for the deauthentication attack 

> [+] Selecting wlan0mon interface for creating the rogue Access Point 

> [+] Sending SIGKILL to avahi-daemon 

> [+] Sending SIGKILL to avahi-daemon 

> [*] Cleared leases, started DHCP, set up iptables 

> [+] Selecting Firmware Upgrade Page template 

> [*] Using hostapd instead of roguehostapd. Many significant features will be turned off. 

> [*] Starting the fake access point... 

> [+] Show your support! 

> [+] Follow us: https://twitter.com/wifiphisher 

> [+] Like us: https://www.facebook.com/Wifiphisher 

> [+] Captured credentials: 

> [!] Closing

**Comment by sophron** [comment]
Are you encountering any error at all? Can we see a screenshot? What distro are you using?
