### ISSUE TITLE
wifiphisher stuck

### ISSUE THREAD

**Issue by israeljohn** [wifiphisher/wifiphisher#1141]
hi there, i'm stuck at this page. after i run the wifiphisher and select the access point to attack it comes to this page and nothing happens after this except the escape button to quit. thanks in advance to everyone who contributes to this thread.
![Screenshot from 2019-06-12 14-30-53](https://user-images.githubusercontent.com/51743103/59342344-368d9480-8d27-11e9-9bf9-02fca47e37c8.png)

**Comment by sophron** [comment]
Wifiphisher does not aim to be script-kiddie friendly. Make sure you do understand how the tool works before opening an issue.
