### ISSUE TITLE
No de-authorization

### ISSUE THREAD

**Issue by Mahdi321** [wifiphisher/wifiphisher#1145]
**Version**: aab4efe986c75a8d822f9b0dfa2b148801734837

Only fake AP will be created. No de-auth happens

My OS (Hacker): Ubuntu 18.04

**Comment by Mahdi321** [comment]
Using another wifi device solved this problem

**Comment by sophron** [comment]
There are various reasons that de-authentication may not work as expected. Read here: https://wifiphisher.readthedocs.io/en/latest/faq.html#why-does-deauthentication-is-not-always-working
