### ISSUE TITLE
Prevent use of specific wifi interface

### ISSUE THREAD

**Issue by Drumshtick** [wifiphisher/wifiphisher#1153]
Hey guys, i'm curious about how I could go about blacklisting a specific interface. I am running kali linux on macbook pro with bcm94360cs NIC.

**Comment by sophron** [comment]
Have a look at the README. You have many options to specify the interfaces you wish to use. You can use `-I or --interface` if you are planning to use one interface that supports AP and monitor mode. Alternatively, you can use two different interfaces using the `-eI or --extensionsinterface` and `-aI or --apinterface`.
