### ISSUE TITLE
GUI Issue? Interrupts network search 

### ISSUE THREAD

**Issue by kaySpaz** [wifiphisher/wifiphisher#1154]
Hey guys. Began having problems after fresh install with Kali Virtual Box. Below is a screenshot of the problem I'm having. I will start it up, it selects correct interfaces but when network search begins these lines of code pop up and it prevents more networks from showing. Sometimes 1 -5 or none. There should be 50+ networks in the area.
<img width="960" alt="Screen Shot 2019-07-24 at 9 14 02 PM" src="https://user-images.githubusercontent.com/45438350/61843311-6668a580-ae58-11e9-9edd-68eb0bfa446c.png">

**Comment by kaySpaz** [comment]
Rolled back to pre install with snapshot.

**Comment by Bsoft2007** [comment]
Got same problem,
