### ISSUE TITLE
Either it doesn't create the rogue AP or creates it WPA protected instead of open

### ISSUE THREAD

**Issue by gr4v1ty69** [wifiphisher/wifiphisher#1162]
**Version**: latest 

**Description**: I'm not sure how exactly it works, but i guess wifiphisher tries to imitate the network (including WPA password). This is how I understand it works. Correct me if I'm wrong. Let's say we want to attack SSID : WIFI1 (WPA). Wifiphisher will deauth users from WIFI1, make the network disappear and create a new WIFI1 (WPA). Whenever the user tries to connect to WIFI1, it doesn't work because they are entering the wrong password. Is that caused by the deauth or by the fact that we created a rogue AP without knowing what the password is? So how can we trick someone into giving us his password to the AP when he can't even connect to the AP itself. Isn't wifiphiser supposed to create a open WIFI1 instead of a WPA protected one?

**Comment by sophron** [comment]
https://wifiphisher.org/research.html
