### ISSUE TITLE
HTTPS redirect support without a certificate 

### ISSUE THREAD

**Issue by minanagehsalalma** [wifiphisher/wifiphisher#1165]
just like mikrotik hotspot as [they do on this setup](http://systemzone.net/mikrotik-hotspot-configuration-using-winbox/) 

i think 
> they’re suppressing the warnings by actually allowing some access to the internet

**Comment by sophron** [comment]
Hi @minanagehsalalma,

I'm not sure you understand how SSL certificates work. I appreciate your time on proposing ideas but you will have to study further and make sure that these ideas actually make sense.

**Comment by minanagehsalalma** [comment]
> Hi @minanagehsalalma,
> 
> I'm not sure you understand how SSL certificates work. I appreciate your time on proposing ideas but you will have to study further and make sure that these ideas actually make sense.

Yeah I have noticed  .. That's why I said 

> Seems 
it wasn't correct..

So what about the FAQ  ?
