### ISSUE TITLE
How to display fake page on windows?

### ISSUE THREAD

**Issue by MateoOO7** [wifiphisher/wifiphisher#1171]
I would like modify only visual and text elements on existing website "firmware upgrade" but i cant open this website correctly using Windows. When i open index file i got this: https://i.imgur.com/MdYVPQ0.png  . How can i open this website correctly?

**Comment by pavonis9** [comment]
@MateoOO7 You will put all the files in your parent directory which is your drive.
Copy them directly to any drive.

**Comment by MateoOO7** [comment]
The point is that page works very well when i run wifiphisher and connect to the fake access point. Problem is when i try open page in internet browser without starting wifiphisher. It hard change this page when i have preview only after runing wifiphisher, because i have to do lot of things like reinstall wifiphisher, run wfifiphisher, connect to the fake AP...

**Comment by sophron** [comment]
Obviously your CSS file is not loading. Make sure you can point to the CSS file from the index file.

**Comment by MateoOO7** [comment]
Ok i got it, i changed path in index file and it works. However, it strange that default path of every fake pages works only after running wifiphisher.
