### ISSUE TITLE
[Feature] Add INTERNET connection - For legitimacy 

### ISSUE THREAD

**Issue by teratzu** [wifiphisher/wifiphisher#1180]
A feature request, to add an actual internet connection that works either from a lan cable. 

The idea is that when a user connects, it displays the 'Internet connection not available' - message or on the PC/Laptop variant 'No connection'.

It could add legitimacy if we could provide the users we phish with an internet connection so it looks more legitimate and thereby improving the % of users that get tricked into giving up the password.

**Comment by pavonis9** [comment]
Take a look at :
https://github.com/wifiphisher/wifiphisher/issues/1139#issue-453326733

**Comment by teratzu** [comment]
> Take a look at :
> [#1139 (comment)](https://github.com/wifiphisher/wifiphisher/issues/1139#issue-453326733)

OK my questions is already answered. Happy to move on, thanks!
