### ISSUE TITLE
I lost my wireless card after turn off wifiphisher

### ISSUE THREAD

**Issue by SHK2018** [wifiphisher/wifiphisher#1185]
Hi everyone, I came across some problem on my ubuntu system while using wifiphisher. When I accidently close the terminal of wifiphisher, I lost my wireless card. Even I reboot my laptop I still cannot use wifi on my laptop now. I am new comer to Linux, may need some help to enable my wireless card. And wifi is still workable in my WIN10 system. Thanks.

**Comment by giupardeb** [comment]
Do you have ubuntu 18.04?

**Comment by SHK2018** [comment]
yes，I am using 18.04

**Comment by giupardeb** [comment]
Can you tried `sudo systemctl start NetworkManager` ?

**Comment by giupardeb** [comment]
I believe that the script enable monitor mode automatically. Furthermore, I don't  know if is necessary to have two wireless card, I always use this script with VM with external wireless usb

**Comment by SHK2018** [comment]
> I believe that the script enable monitor mode automatically. Furthermore, I don't know if is necessary to have two wireless card, I always use this script with VM with external wireless usb

Thanks very much. I thought it just coz my build in card doesnt support injection, I may need a USB card instead!
