### ISSUE TITLE
Uninstall wifiphisher

### ISSUE THREAD

**Issue by popadrop** [wifiphisher/wifiphisher#1199]
How to uninstall  wifiphisher and roguehostapd from linux So i can make a clean install.
is there a python setup uninstall can you use pip??
Thanks for the help.

**Comment by fabaff** [comment]
Try:

```bash
$ pip uninstall wifiphisher
```

This may not work as it depends on your installation method. Or remove `wifiphisher` from the `site-packages` directory manually.

**Comment by sophron** [comment]
> pip uninstall wifiphisher
> pip uninstall roguehostapd

should be sufficient.
