### ISSUE TITLE
not connected, stuck obtaining IP address

### ISSUE THREAD

**Issue by mugi789** [wifiphisher/wifiphisher#1201]
**Version** : Wifiphisher 1.4GIT
################################
![Screenshot_2019-11-07-23-03-47](https://user-images.githubusercontent.com/32443765/68405951-904d9a00-01b3-11ea-93c6-4c30bab9bb1b.png)
![Screenshot_2019-11-07_23-03-39](https://user-images.githubusercontent.com/32443765/68405977-9ba0c580-01b3-11ea-9d3d-6f580c12cc3d.png)

**Comment by bessalahAmar** [comment]
I have exactly the same problem , did you find any solution for that ?
