### ISSUE TITLE
not connected, stuck obtaining IP address :(

### ISSUE THREAD

**Issue by mugi789** [wifiphisher/wifiphisher#1211]
All my life, I could not use it :(
All my life, I could not use it :(
All my life, I could not use it :(
All my life, I could not use it :(
All my life, I could not use it :(
All my life, I could not use it :(
All my life, I could not use it :(
All my life, I could not use it :(
All my life, I could not use it :(
All my life, I could not use it :(
All my life, I could not use it :(
All my life, I could not use it :(
All my life, I could not use it :(
All my life, I could not use it :(
All my life, I could not use it :(
All my life, I could not use it :(
All my life, I could not use it :(
All my life, I could not use it :(
All my life, I could not use it :(
All my life, I could not use it :(
All my life, I could not use it :(
All my life, I could not use it :(
All my life, I could not use it :(
All my life, I could not use it :(
All my life, I could not use it :(
All my life, I could not use it :(
All my life, I could not use it :(
All my life, I could not use it :(
All my life, I could not use it :(
All my life, I could not use it :(
All my life, I could not use it :(
All my life, I could not use it :(
All my life, I could not use it :(
All my life, I could not use it :(
All my life, I could not use it :(
All my life, I could not use it :(
All my life, I could not use it :(
All my life, I could not use it :(
All my life, I could not use it :(
All my life, I could not use it :(
All my life, I could not use it :(
All my life, I could not use it :(
All my life, I could not use it :(
All my life, I could not use it :(
All my life, I could not use it :(
All my life, I could not use it :(
All my life, I could not use it :(
All my life, I could not use it :(
All my life, I could not use it :(
All my life, I could not use it :(
All my life, I could not use it :(
All my life, I could not use it :(
All my life, I could not use it :(
All my life, I could not use it :(
All my life, I could not use it :(
All my life, I could not use it :(
All my life, I could not use it :(
All my life, I could not use it :(
All my life, I could not use it :(
All my life, I could not use it :(
All my life, I could not use it :(
All my life, I could not use it :(
All my life, I could not use it :(
All my life, I could not use it :(
All my life, I could not use it :(
All my life, I could not use it :(
All my life, I could not use it :(
All my life, I could not use it :(
All my life, I could not use it :(
All my life, I could not use it :(
All my life, I could not use it :(
All my life, I could not use it :(
All my life, I could not use it :(
All my life, I could not use it :(
All my life, I could not use it :(
All my life, I could not use it :(
All my life, I could not use it :(
All my life, I could not use it :(
All my life, I could not use it :(
All my life, I could not use it :(
All my life, I could not use it :(
All my life, I could not use it :(
All my life, I could not use it :(
All my life, I could not use it :(
All my life, I could not use it :(
All my life, I could not use it :(
All my life, I could not use it :(
All my life, I could not use it :(
All my life, I could not use it :(
All my life, I could not use it :(
All my life, I could not use it :(
All my life, I could not use it :(
All my life, I could not use it :(
All my life, I could not use it :(
All my life, I could not use it :(
All my life, I could not use it :(
All my life, I could not use it :(
All my life, I could not use it :(
All my life, I could not use it :(
All my life, I could not use it :(
All my life, I could not use it :(
All my life, I could not use it :(
All my life, I could not use it :(
All my life, I could not use it :(
All my life, I could not use it :(
All my life, I could not use it :(
All my life, I could not use it :(
All my life, I could not use it :(
All my life, I could not use it :(
All my life, I could not use it :(
All my life, I could not use it :(
All my life, I could not use it :(
All my life, I could not use it :(
All my life, I could not use it :(
All my life, I could not use it :(
All my life, I could not use it :(
All my life, I could not use it :(
All my life, I could not use it :(
All my life, I could not use it :(
All my life, I could not use it :(
All my life, I could not use it :(
All my life, I could not use it :(
All my life, I could not use it :(
All my life, I could not use it :(
All my life, I could not use it :(
All my life, I could not use it :(
All my life, I could not use it :(
All my life, I could not use it :(
All my life, I could not use it :(
All my life, I could not use it :(
All my life, I could not use it :(
All my life, I could not use it :(
All my life, I could not use it :(
All my life, I could not use it :(
All my life, I could not use it :(

**Comment by sophron** [comment]
That's sad.
