### ISSUE TITLE
Provide Internet Post Submission

### ISSUE THREAD

**Issue by DustyArmstrong** [wifiphisher/wifiphisher#1217]
I have seen some posts previously, back in 2017. The question was raised surrounding Wifiphisher acting as a "true" captive portal, i.e. once a user has made their credentials submission they are then provided access to the internet. Of course the flag -iI allows internet from the start, though that doesn't trigger the portal - as is expected. 

The topic was originally brought up on issue #617, and further touched upon in issue #922. Here it was mentioned by sophron: 

>This should be done within the next few months.

Was this work completed? I believe the original thought was around the manual modification of IP tables to include the MAC address of the connected target. It goes beyond my skill level to implement an automatic trigger for this, so I just wondered if it had indeed been added to the source. My use case would very much benefit from this, but I understand if it's not something that was done or didn't warrant as much attention, as it is slightly out of scope for the general intent of the project.

**Comment by sophron** [comment]
Hi @DustyArmstrong,

This is definitely something that we have on our list and we want to have it ready for our v2.0 release. @manosf will start working on this soon enough. He can provide updates if needed.

**Comment by DustyArmstrong** [comment]
Hi @sophron thanks for the update, much appreciated. 

I will close this request off and keep an eye out for future releases.
