### ISSUE TITLE
Macmatcher not founed

### ISSUE THREAD

**Issue by wolfighter-pixel** [wifiphisher/wifiphisher#1218]
I did all the things after finishing the installation and runing wifiphisher i got:
from macmatcher import MACMatcher a macmatcher
ModuleNotFoundError: No module named 'macmatcher'

**Comment by putinpe** [comment]
![2019-12-03_15-41-21](https://user-images.githubusercontent.com/58068256/70052010-5e2d2d80-15e3-11ea-993e-22071b7bd9d4.png)

**Comment by wolfighter-pixel** [comment]
Well i'm in ubuntu

**Comment by sophron** [comment]
Use Python2.7 for now. We will support Python3 soon enough.

**Comment by sophron** [comment]
We now support Python3. Please update to the latest revision and try again.
