### ISSUE TITLE
Using wifi sticks that do not support nl80211

### ISSUE THREAD

**Issue by Dekuish** [wifiphisher/wifiphisher#1220]
Hello developers and readers,

On the readme it asked everyone to provide feedback. This is why the following will not be a specific bug in the software that I encountered. I'm currently studying computer science and have a project assignment for my os lecture. Don't worry, I'm just giving background to where I'm coming from.

I'm currently learning about networking and kali and bought 2 wifi sticks: TP-Link WN722N V2 (or V3 | the packaging says V3, the system shows it as V2).
These sticks use a realtek chipset, which is why I'm encountering the following problem. When trying to launch wifiphisher (using the sticks / specified directly or by wifiphisher):

pyric.error: [Erno 93] Device does not support nl80211

I've read through the issues and saw answers regarding this topic. I've read that pyric specifically requires the nl80211 driver.

My question:
**Is there a possibility that I can install that driver to use with the wifi sticks or would I need to buy new sticks  with another chipset regarding this issue?**

As a user asked for feedback. I would recommend putting the answer to this question on the readme/FAQ. I'm sorry that I'm not bringing much to the table regarding this topic, but I'm really interested in wifi networking and protecting myself from these kind of attacks.

**Comment by sophron** [comment]
You will need a different chipset which its drivers support netlink. Have a look at #558 before buying.
