### ISSUE TITLE
Wifiphisher closing with 2 wireless card

### ISSUE THREAD

**Issue by BaptisteCorp** [wifiphisher/wifiphisher#1223]
Hello there
I downloaded wifiphisher and bought another wifi wireless card 
But when i try to use the script it closes automatically 
 sudo wifiphisher
[*] Starting Wifiphisher 1.4GIT ( https://wifiphisher.org ) at 2019-12-07 16:13
[+] Timezone detected. Setting channel range to 1-13
[+] Selecting wlp2s0 interface for the deauthentication attack
[+] Selecting wlx1cbfce9e79b7 interface for creating the rogue Access Point
[+] Changing wlx1cbfce9e79b7 MAC addr (BSSID) to 00:00:00:4c:5d:52
[+] Changing wlx1cbfce9e79b7 MAC addr (BSSID) to 00:00:00:e0:d1:cb
[+] Sending SIGKILL to wpa_supplicant
[+] Sending SIGKILL to avahi-daemon
[+] Sending SIGKILL to avahi-daemon
[*] Cleared leases, started DHCP, set up iptables
[+] Selecting Network Manager Connect template
[*] Starting the fake access point...
[+] Show your support!
[+] Follow us: https://twitter.com/wifiphisher
[+] Like us: https://www.facebook.com/Wifiphisher
[+] Captured credentials:
[!] Closing

MY IWCONFIG : 
 iwconfig
wlp2s0    IEEE 802.11  ESSID:off/any  
          Mode:Managed  Access Point: Not-Associated   Tx-Power=20 dBm   
          Retry short limit:7   RTS thr=2347 B   Fragment thr:off
          Power Management:on
          
wlx1cbfce9e79b7  unassociated  Nickname:"<WIFI@REALTEK>"
          Mode:Managed  Frequency=2.437 GHz  Access Point: Not-Associated   
          Sensitivity:0/0  
          Retry:off   RTS thr:off   Fragment thr:off
          Power Management:off
          Link Quality=0/100  Signal level=0 dBm  Noise level=0 dBm
          Rx invalid nwid:0  Rx invalid crypt:0  Rx invalid frag:0
          Tx excessive retries:0  Invalid misc:0   Missed beacon:0

lo        no wireless extensions.

enp1s0    no wireless extensions.

if someone can help me, thank you

**Comment by sophron** [comment]
Hi, I pushed a commit recently. It should either work properly now or post a relative error message.
