### ISSUE TITLE
how to grant Victim to access an Internet after Oauth-Login ?

### ISSUE THREAD

**Issue by dogzamak** [wifiphisher/wifiphisher#1224]
i use wifiphisher on Kali linux with all lastest version
I use 'wifiphisher --essid "FREE WI-FI" -p oauth-login -kB'
to create AP but how to grant user access an Internet after Fill oauth-login

can wifiphisher can access to Internet ? please guild me 

or after oauth-login can connect other my wifi hospot to access Internet ?

Thank you

**Comment by sophron** [comment]
This feature is not ready yet. See #1217.
