### ISSUE TITLE
Please use Python 3 to run wifiphisher

### ISSUE THREAD

**Issue by djdisikd** [wifiphisher/wifiphisher#1227]
How to fix this issue?

Thanks

**Comment by sophron** [comment]
Fix it by using Python 3.

**Comment by djdisikd** [comment]
Where to download python 3 ?

**Comment by sophron** [comment]
If you cannot answer this question, you shouldn't be using Wifiphisher.

**Comment by kozel747** [comment]
sudo apt install wifiphisher hostapd dnsmasq python-pyric python-jinja2

**Comment by kozel747** [comment]
> Where to download python 3 ?

sudo apt install wifiphisher hostapd dnsmasq python-pyric python-jinja2
