### ISSUE TITLE
known-open-wlans now update

### ISSUE THREAD

**Issue by Neokey-star** [wifiphisher/wifiphisher#1228]
Hello I tried to fill the list with known-open-wlans (https://github.com/wifiphisher/wifiphisher/blob/master/wifiphisher/data/wifiphisher-known-open-wlans) with public wlans from my area. Unfortunately, no success. When I run -KB my registered wlans are not processed. How can I update it?

**Comment by sophron** [comment]
Hi, have you will have to run `python setup.py install` again after editing the `known-open-wlans` file.

**Comment by Neokey-star** [comment]
OK thank you
