### ISSUE TITLE
Problem installing 

### ISSUE THREAD

**Issue by demodemi** [wifiphisher/wifiphisher#1229]
i tried installing setup.py using python and python3 but the same error as mention in attached pic. 
in addition, i cant find requirements.txt file inside directory to run order ' python3 -m pip install -r requirements.txt' . 
so any help please ???

Thanks in advance 
![WIFIPHISHER PROB](https://user-images.githubusercontent.com/58898476/70863936-fa492400-1f55-11ea-9f74-726455c6bc1e.jpg)

**Comment by sophron** [comment]
Please don't create more accounts to open issues like this. Wifiphisher does not aim to be script-kiddie friendly.

**Comment by demodemi** [comment]
Is your email helped me???  Of course no because you think I'm kiddin of you but i really needs your help to understand the problem 
--
Sent from myMail for Android Monday, 16 December 2019, 07:43AM +02:00 from George Chatzisofroniou  notifications@github.com :
