### ISSUE TITLE
wifiphisher cannot install

### ISSUE THREAD

**Issue by yqman** [wifiphisher/wifiphisher#1230]
Before opening a new issue, please make sure that what you are about to report has not been reported already or is not included on the FAQ page. If not, use the following template for reporting.

Please keep in mind that our developers will prioritize your issue if you provide a detailed and extensive description.

**Version**: Use `git show | grep commit` command and paste here the output.

**Description**: Give a more analytical description here. Let us know how we can reproduce the reported issue. Detail the characteristics of your machine (e.g. Linux distribution and wireless card capabilities) and of the victim devices too (e.g. OS or web browser) if possible. The output of the `iw list` and `iwconfig` commands may also be helpful here.

**Script output**: Paste the output of the tool, including any stack traces.

Installed /usr/local/lib/python3.5/dist-packages/wifiphisher-1.4-py3.5.egg
Processing dependencies for wifiphisher==1.4
Searching for pyric
Downloading http://github.com/sophron/pyric/tarball/master#egg=pyric-0.5.0
error: Download error for http://github.com/sophron/pyric/tarball/master#egg=pyric-0.5.0: [Errno 104] Connection reset by peer

**Comment by sophron** [comment]
I'm sure you can figure it out on your own.

**Comment by azam1225** [comment]
sir this problem not solving
