### ISSUE TITLE
Please use Python3 to install Wifiphisher

### ISSUE THREAD

**Issue by X1FIN** [wifiphisher/wifiphisher#1236]
I used the command: sudo python setup.py install
Writes: "Please use python 3 to install wifiphisher"
I used the command: sudo python3 setup.py install
Writes: " ModuleNotFoundError: No module named 'setuptools' "

**Comment by X1FIN** [comment]
> I used the command: sudo python setup.py install
> Writes: "Please use python 3 to install wifiphisher"
> I used the command: sudo python3 setup.py install
> Writes: " ModuleNotFoundError: No module named 'setuptools' "

how to fix it?

**Comment by mane** [comment]
Same issue here.

**Comment by mane** [comment]
@X1FIN  After a bit of googling I've solved the issue installing the following additional packages on my kali OS:
apt-get install -y python3-setuptools libnl-3-dev libnl-genl-3-dev libssl-dev

**Comment by cisnemsis** [comment]
Thanks, that worked!

**Comment by drakona14** [comment]
Please help me to solve this problem "Please use python 3 to install wifiphisher"

**Comment by sophron** [comment]
To everyone struggling with this:

Download and install Python3. If you don't know how, you shouldn't be running Wifiphisher on the first place.

**Comment by drakona14** [comment]
> To everyone struggling with this:
> 
> Download and install Python3. If you don't know how, you shouldn't be running Wifiphisher on the first place.

I have downloaded and installed the python 3 but don't install wifiphisher please to help me my telegram user is @Abbosbek_raxmonov

**Comment by kozel747** [comment]
> Please help me to solve this problem "Please use python 3 to install wifiphisher"

sudo apt install wifiphisher hostapd dnsmasq python-pyric python-jinja2

**Comment by victorhfsilva** [comment]
...
sudo apt-get install -y python3-setuptools libnl-3-dev libnl-genl-3-dev libssl-dev
sudo apt-get update
git clone https://github.com/wifiphisher/wifiphisher.git
cd wifiphisher
sudo python3 setup.py install
```

**Comment by LS255** [comment]
> @X1FIN After a bit of googling I've solved the issue installing the following additional packages on my kali OS:
> apt-get install -y python3-setuptools libnl-3-dev libnl-genl-3-dev libssl-dev

Is it work? When i am using windows 10 Store's kali linux..
Please reply..

**Comment by LS255** [comment]
apt-get install -y python3-setuptools libnl-3-dev libnl-genl-3-dev libssl-dev   
Is it works? When I am using windows 10 store's kali linux..
Please reply

**Comment by P4l4ko** [comment]
> sudo apt-get install -y python3-setuptools libnl-3-dev libnl-genl-3-dev libssl-dev
> sudo apt-get update

Before this, it still giving me problems with pure-ftpd-common module every time.

i try the following:

`sudo apt-mark hold pure-ftpd
sudo apt-mark hold pure-ftpd-common
sudo dpkg --configure -a
sudo apt-get install -f pure-ftpd
sudo apt-get install -f pure-ftpd-common
sudo apt-mark unhold pure-ftpd
sudo apt-mark unhold pure-ftpd-common
sudo dpkg --configure -a
apt-get upgrade`

And still the same, every time something has sometjhing to do with pure -ftpd or pure-ftpd common it gives an error, and im on a loop now... im tired.

**Comment by Divyanshguptx** [comment]
> ```
> 
> sudo apt-get install -y python3-setuptools libnl-3-dev libnl-genl-3-dev libssl-dev
> sudo apt-get update
> git clone https://github.com/wifiphisher/wifiphisher.git
> cd wifiphisher
> sudo python3 setup.py install
> ```

still the same error

**Comment by LS255** [comment]
It not  works in windows 10 official kali subOS .
What I need to do for installation in windows 10 official kali linux.

**Comment by sptpower** [comment]
Hello. I encountered such a problem. 
![1](https://user-images.githubusercontent.com/62520520/83040468-f3b3f200-a047-11ea-9f6a-6a7c31c59030.png)
![2](https://user-images.githubusercontent.com/62520520/83040475-f57db580-a047-11ea-921a-e2d8c89ef850.png)

**Comment by Usman7200** [comment]
> ```
> 
> sudo apt-get install -y python3-setuptools libnl-3-dev libnl-genl-3-dev libssl-dev
> sudo apt-get update
> git clone https://github.com/wifiphisher/wifiphisher.git
> cd wifiphisher
> sudo python3 setup.py install
> ```

its still giving error:
dnsmasq not found in. Please install dnsmasq and return the script

**Comment by ashkan5050** [comment]
1-you should type : sudo python3 setup.py install
2-and probebly you will see this eror : dnsmasq not found in /usr/sbin/dnsmasq. Please install dnsmasq and rerun the script (e.g. on Debian-based systems: apt-get install dnsmasq)
3-therfor you should type this:sudo apt-get install dnsmasq   
4- and of handel this eror you should type sudo python3 setup.py install
