### ISSUE TITLE
setuptools and python3 on newest Kali Linux

### ISSUE THREAD

**Issue by SirCthulhu** [wifiphisher/wifiphisher#1240]
Hello everyone ! to get started I just wanna mention that, if i sound like noobish it's coplety normal ! cause I am !
Im going to try my best to explain my issues with you..

So, I install the very lastest version of Kali Linux, fresh install new start.
I have tried to install wifi-phisher and there is what i get into my terminal :

**root@MacPro-kali:~#** cd wifiphisher/
**root@MacPro-kali:~/wifiphisher#** sudo python setup.py
Please use Python 3 to install Wifiphisher.
**root@MacPro-kali:~/wifiphisher#** sudo python3 setup.py
Traceback (most recent call last):
  File "setup.py", line 23, in <module>
    from setuptools import Command, find_packages, setup
ModuleNotFoundError: No module named 'setuptools'

If someone have an idea on how to solve this issues..
Thanks for reading me !

**Comment by AseresNV** [comment]
try to install pip, download from here https://bootstrap.pypa.io/get-pip.py and type "python get-pip.py",
setuptools install automatically.

**Comment by SirCthulhu** [comment]
Hi !  sorry for late respond.
I did what you say ! It installed successfully.
but I got the exact same error, and I can't install wifiphisher.

**Comment by gunjan-solanki** [comment]
Try installing via pip:
```
python3 -m pip install setuptools
```

**Comment by sophron** [comment]
See #1236.
