### ISSUE TITLE
Wifiphisher doesn't catch the entered password from this custom phishing page! 

### ISSUE THREAD

**Issue by minanagehsalalma** [wifiphisher/wifiphisher#1251]
I have always preferred fluxion's pages over wifiphisher as they were simple and direct ....but i prefer your tool more so i tried to use the genric page on it ... but it didn't work correctly... Although i took a look on the wiki but couldn't figure out the fix ....  any ideas how to fix it?

Then maybe add it to the main project as it supports a lot of languages.... and it feels less serious so it wouldn't scare the victims a little bit !

[The page.zip](https://github.com/wifiphisher/wifiphisher/files/4083908/captive_portalen.zip)

**Comment by sophron** [comment]
I'm not willing to extract a random zip from the Internet. You can post snippets of your code and be more descriptive if you need help. What do you mean "it didn't work properly"? What is the error?

**Comment by minanagehsalalma** [comment]
> I'm not willing to extract a random zip from the Internet. You can post snippets of your code and be more descriptive if you need help. What do you mean "it didn't work properly"? What is the error?

it loads in a buggy way ... 
here are the files not in a "zip"
https://ufile.io/f/kjig6

**Comment by sophron** [comment]
I'm not willing to download any random files from the Internet. 

Please understand that we are volunteers with very limited time. We really don't have the time to debug your page. You will have to be 10 times more descriptive if you want a serious response.

**Comment by minanagehsalalma** [comment]
> I'm not willing to download any random files from the Internet.
> 
> Please understand that we are volunteers with very limited time. We really don't have the time to debug your page. You will have to be 10 times more descriptive if you want a serious response.

alright at least answer https://github.com/wifiphisher/wifiphisher/issues/1252 with more explanation the wiki is made for only the script devs to understand it ! not normal users !!

**Comment by sophron** [comment]
@minanagehsalalma Wifiphisher is a software that aims to be used by professionals, not script-kiddies. Please use another tool if you are having trouble with the basics.

**Comment by minanagehsalalma** [comment]
> Wifiphisher is a software that aims to be used by professionals, not script-kiddies.

What are you talking about I been using your tool since 2016 check the issues tab(https://github.com/wifiphisher/wifiphisher/issues/494 https://github.com/wifiphisher/wifiphisher/issues/495)  I been here since the script was just basic .... 

> Please use another tool if you are having trouble with the basics.

Do you call customization basic !?
![IMG_20200123_192222](https://user-images.githubusercontent.com/20546638/73007743-bdeeca80-3e15-11ea-8767-647e88881c5f.png)
What does a one understand from this ? Atleast give a clear example fr the real code !
