### ISSUE TITLE
--handshake-capture doesn't support custom pages 

### ISSUE THREAD

**Issue by minanagehsalalma** [wifiphisher/wifiphisher#1252]
let's say wifiphisher catches the passwords and verifies  it against the handshake  and finds that it's correct how will the custom page know that the password was right to show the user "please wait few seconds for the connection to work" 

or if the password was wrong how will the custom page know that to show the user error wrong password please try again !

**Comment by sophron** [comment]
You need to leverage a backend handler. See here: https://wifiphisher.readthedocs.io/en/latest/custom_phishing_scenario.html 

An idea is to look at the source code of `firmware-upgrade` and see how it is done there.

**Comment by minanagehsalalma** [comment]
> An idea is to look at the source code of firmware-upgrade and see how it is done there.

does it show a error message if the entered password was wrong ? 
and is there a more faster/friendly way to do it 
like some lines of code to past in the html file ?

**Comment by minanagehsalalma** [comment]
> You need to leverage a backend handler. See here: https://wifiphisher.readthedocs.io/en/latest/custom_phishing_scenario.html
> 
> An idea is to look at the source code of `firmware-upgrade` and see how it is done there.

which part of the code to look at ?  why the wiki isn't more specific and clear !
can you at least explain the steps to do this a little bit ? 
https://github.com/wifiphisher/wifiphisher/blob/master/wifiphisher/data/phishing-pages/firmware-upgrade/html/index.html
