### ISSUE TITLE
No handlers could be found for logger "wifiphisher.pywifiphisher"

### ISSUE THREAD

**Issue by peijs** [wifiphisher/wifiphisher#1259]
wlan0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.0.136  netmask 255.255.255.0  broadcast 192.168.0.255
        inet6 fe80::f919:6c5f:6e30:xxxx  prefixlen 64  scopeid 0x20<link>
        ether 00:c0:ca:aa:54:21  txqueuelen 1000  (Ethernet)
        RX packets 878  bytes 110850 (108.2 KiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 25  bytes 2946 (2.8 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

root@kali:~# lsusb 
Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 001 Device 006: ID 0bda:8812 Realtek Semiconductor Corp. RTL8812AU 802.11a/b/g/n/ac 2T2R DB WLAN Adapter
Bus 001 Device 005: ID 0e0f:0002 VMware, Inc. Virtual USB Hub
Bus 001 Device 004: ID 0e0f:0002 VMware, Inc. Virtual USB Hub
Bus 001 Device 003: ID 0e0f:0008 VMware, Inc. Virtual Bluetooth Adapter
Bus 001 Device 002: ID 0e0f:0003 VMware, Inc. Virtual Mouse
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 003 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 004 Device 002: ID 0e0f:0002 VMware, Inc. Virtual USB Hub
Bus 004 Device 001: ID 1d6b:0001 Linux Foundation 1.1 root hub
root@kali:~# wifiphisher 
[*] Starting Wifiphisher 1.4GIT ( https://wifiphisher.org ) at 2020-01-31 06:01
No handlers could be found for logger "wifiphisher.pywifiphisher"
[!] Failed to find an interface with monitor mode
[+] Show your support!
[+] Follow us: https://twitter.com/wifiphisher
[+] Like us: https://www.facebook.com/Wifiphisher
[+] Captured credentials:
[!] Closing
root@kali:~#

**Comment by sophron** [comment]
The real error you are receiving is "Failed to find an interface with monitor mode". And that's because Wifiphisher failed to find an interface with monitor mode (duh).

Check the requirements of the project, you need a card that supports monitor mode.

**Comment by peijs** [comment]
At present, it seems to support the latest rlt8812au chip


peijs@qmhd.com.cn
 
From: George Chatzisofroniou
Date: 2020-01-31 23:02
To: wifiphisher/wifiphisher
CC: peijs; Author
Subject: Re: [wifiphisher/wifiphisher] No handlers could be found for logger "wifiphisher.pywifiphisher" (#1259)
The real error you are receiving is "Failed to find an interface with monitor mode". And that's because Wifiphisher failed to find an interface with monitor mode (duh).
Check the requirements of the project, you need a card that supports monitor mode.
