### ISSUE TITLE
Help 

### ISSUE THREAD

**Issue by JorgesJ** [wifiphisher/wifiphisher#1265]
Hi, I'm new and I'm trying to use wifiphisher with a raspberry 4 with raspbian OS.
But this error throws me and I don't know how to fix it.

See if you can help.

I am completely new with linux and script themes but it has taken me a lot to get to the point seen in the image.
![error](https://user-images.githubusercontent.com/60850895/74105831-9a3fba00-4b61-11ea-88cb-ea1f8c0a279b.jpg)

**Comment by sophron** [comment]
pip install six?

**Comment by JorgesJ** [comment]
Hi, I think I solved the module installation with pip install. Now I run the script and throw this message from the photo.
In the raspberry I have an alpha connected that I suppose serves to execute the script.
Do you know what the reason for the error may be?

Thank.

Attached console images.
![error](https://user-images.githubusercontent.com/60850895/75294568-10fad980-5829-11ea-9c36-4ebf0ab47c72.jpeg)

**Comment by sophron** [comment]
Your Alfa card does not support AP mode.

**Comment by JorgesJ** [comment]
And which card do you recommend for me to use?
I believed that the Alfa chipset supports AP mode.

**Comment by sophron** [comment]
See #558.

**Comment by JorgesJ** [comment]
The TP-link TL-WN722N v3 that does not have an Atheros chip, does not serve to put it in AP mode? It is that I have bought it to be able to use it and if it does not work I return it.
Thank you.
