### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by jigsaw678** [wifiphisher/wifiphisher#1269]
wifiphisher
[*] Starting Wifiphisher 1.4GIT ( https://wifiphisher.org ) at 2020-02-17 16:58
[+] Timezone detected. Setting channel range to 1-13
[+] Selecting wlan1 interface for the deauthentication attack
[+] Selecting wlan0 interface for creating the rogue Access Point
[+] Changing wlan0 MAC addr (BSSID) to 00:00:00:04:13:b6
[+] Changing wlan0 MAC addr (BSSID) to 00:00:00:f5:7e:6a
[+] Sending SIGKILL to wpa_supplicant
[+] Sending SIGKILL to NetworkManager
[*] Cleared leases, started DHCP, set up iptables
[+] Selecting OAuth Login Page template
[*] Starting the fake access point...
Segmentation fault

**Comment by sophron** [comment]
#942.
