### ISSUE TITLE
Setup.py can't find dnsmasq

### ISSUE THREAD

**Issue by Valter4578** [wifiphisher/wifiphisher#1282]
**Version**: commit 46bdf134d838bb33e1272c598a67c8cf085c5d8d

**Description**: setup.py can't find dnsmasq, but it already installed on my Mac  

**Script output**: dnsmasq not found in /usr/sbin/dnsmasq. Please install dnsmasq and rerun the script (e.g. on Debian-based systems: apt-get install dnsmasq)

**Comment by sophron** [comment]
Hi @Valter4578,

We don't support Wifiphisher for MacOS.
