### ISSUE TITLE
how does exactly the karma attack work in wifiphisher ? 

### ISSUE THREAD

**Issue by minanagehsalalma** [wifiphisher/wifiphisher#1283]
the normal karma attack works by creating an open network that's saved on the target devices which can be gathered by listing to the devices network prob requests ...... but in case of evil twin we have Multi devices on the target network with different saved networks so how will wifiphisher act to this ? would it make Multi ssids for each target in addition to the original one ? 
is this even possible ?

**Comment by sophron** [comment]
Wifiphisher supports both KARMA and Evil Twin and executes both attacks at the same time.

Keep in mind that modern devices are no longer probing for open networks they have associated with in the past. They may do it in a few specific cases (e.g. a stored hidden network of Open-type will enforce the device to perform active scanning).

**Comment by minanagehsalalma** [comment]
@sophron okay thanks.
