### ISSUE TITLE
FileNotFoundError: [Errno 2] PyRIC

### ISSUE THREAD

**Issue by caseykey** [wifiphisher/wifiphisher#1284]
**Version**:  commit 46bdf134d838bb33e1272c598a67c8cf085c5d8d

**Description**: 
I am on Kali Rolling Release 2020.1. I add my wireless card to the machine via VirtualBox USB menu (Ralink Alfa AWUS036NH). I install WiFiPhisher via `sudo python3 setup.py install`. Then, when I run `sudo wifiphisher` I get an error. I've tried installing PyRIC but the dependency is already met. Additionally, I have navigated to `/usr/local/lib/python3.7/dist-packages/PyRIC-0.1.6.4-py3.7.egg/pyric/lib/` and the file `libio.py` exists.

**Script output**: 
```
kali@kali:~/wifiphisher$ sudo wifiphisher
[*] Starting Wifiphisher 1.4GIT ( https://wifiphisher.org ) at 2020-03-22 23:36
[+] Timezone detected. Setting channel range to 1-13
[+] Selecting wfphshr-wlan0 interface for the deauthentication attack
[+] Selecting wlan0 interface for creating the rogue Access Point
[+] Changing wlan0 MAC addr (BSSID) to 00:00:00:c6:fd:b8
[!] The MAC address could not be set. (Tried 00:00:00:9d:39:ba)
[*] Cleared leases, started DHCP, set up iptables
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/PyRIC-0.1.6.4-py3.7.egg/pyric/lib/libio.py", line 64, in io_transfer
    return ioctl(iosock.fileno(),flag,ifreq)
FileNotFoundError: [Errno 2] No such file or directory
```

**Comment by caseykey** [comment]
Waiting for a response in this issue: https://github.com/netlify/netlify-cms/issues/1353

**Comment by sophron** [comment]
Hi,

Something appears to be wrong with your environment. Are you using a `virtualenv`?

Can you try running Wifiphisher from within the project's directory (e.g. `python3 bin/wifiphisher`)?

Please note that the PyRIC version that we are currently using lies here: https://github.com/sophron/PyRIC You may want to purge your version and install this one.

**Comment by caseykey** [comment]
I ran it from that directory but got the same error. I tried an install on Manjaro and it worked. I believe it's an issue with VirtualBox/virtualization.
