### ISSUE TITLE
Wifiphisher not Deauthing network it is attacking

### ISSUE THREAD

**Issue by THEpWn3R-o** [wifiphisher/wifiphisher#1287]
**Version**: The most up to date Version

**Description**: After selecting network to attack, (i use --force-hostap) it creates the AP and password capture page good, but it doesn't deauth the original AP.

**Comment by DarkGuy10** [comment]
@THEpWn3R-o can you please give the result of ifconfig

**Comment by DarkGuy10** [comment]
Either you are using a single adapter or using `--force-hostap` while it is actually `--force-hostapd`

**Comment by sophron** [comment]
Check here: https://wifiphisher.readthedocs.io/en/latest/faq.html#why-does-deauthentication-is-not-always-working
