### ISSUE TITLE
Error when Lauching

### ISSUE THREAD

**Issue by AlienWolfX** [wifiphisher/wifiphisher#1298]
**Version**: git version 2.25.1 | ommit 2481ba8a197ea507d64c0a5335582be3972f4719 (HEAD -> master, origin/master, origin/HEAD)
Merge: 306ae51 f3f5c97
Author: George Chatzisofroniou <sophron@latthi.com>
Date:   Sun Apr 12 21:01:31 2020 -0500

    Merge pull request #1234 from p91/master
    
    Added hotfix for 3.8 due to changed Thread Creation Policy

**Description**: I am sing the Latest Kali Linux with a adapter that supports monitor mode and packet injection, i just need help it is my first time installing and encountered this problem.

**Script output**: 
![Screenshot 2020-04-14 15:12:32](https://user-images.githubusercontent.com/60495687/79196629-69e4f800-7dfe-11ea-9b55-4cb9aa1d22f9.png)
Traceback (most recent call last):
  File "bin/wifiphisher", line 15, in <module>
    from wifiphisher.pywifiphisher import run
  File "/usr/local/lib/python3.8/site-packages/wifiphisher-1.4-py3.8.egg/wifiphisher/pywifiphisher.py", line 31, in <module>
    import wifiphisher.common.phishinghttp as phishinghttp
  File "/usr/local/lib/python3.8/site-packages/wifiphisher-1.4-py3.8.egg/wifiphisher/common/phishinghttp.py", line 18, in <module>
    asyncio.set_event_loop_policy(tornado.platform.asyncio.AnyThreadEventLoopPolicy())
AttributeError: module 'tornado.platform.asyncio' has no attribute 'AnyThreadEventLoopPolicy'

**Comment by sotiris155** [comment]
Hello AlienWolfX,

You can edit the 153 line of setup.py file, that says somewhere withing the line "tornado 4.5.3" to "tornado". The specific version of tornado creates this issue. Though I'll have to warn you that Wifiphisher WILL work, but with some other basic issues, especially on oauth-login.

Best of luck with it
PS. I fought quite some hours with many errors on it. But still is a great tool. Feel free to ask further questions :3

**Comment by Ri-tik** [comment]
I was getting the same error but after changing Tornado Version 4.5.3 to 5.1.1 it was working, To change:
**cd wifiphisher
leafpad setup.py**
(Press CTRL + J, Search for Line Number 154)
Change this line
`INSTALL_REQUIRES = ["pbkdf2", "scapy", "tornado==4.5.3", "roguehostapd", "pyric"]`
To
`INSTALL_REQUIRES = ["pbkdf2", "scapy", "tornado==5.1.1", "roguehostapd", "pyric"]`
(Save the file)
and run Setup once again

**Comment by AlienWolfX** [comment]
Do i have to change the tornado version to the version that is install on my kali.?

**Comment by Alpha-1729** [comment]
> I was getting the same error but after changing Tornado Version 4.5.3 to 5.1.1 it was working, To change:
> **cd wifiphisher leafpad setup.py**
> (Press CTRL + J, Search for Line Number 154)
> Change this line
> `INSTALL_REQUIRES = ["pbkdf2", "scapy", "tornado==4.5.3", "roguehostapd", "pyric"]`
> To
> `INSTALL_REQUIRES = ["pbkdf2", "scapy", "tornado==5.1.1", "roguehostapd", "pyric"]`
> (Save the file)
> and run Setup once again

worked

**Comment by ErAle001** [comment]
> I was getting the same error but after changing Tornado Version 4.5.3 to 5.1.1 it was working, To change:
> **cd wifiphisher leafpad setup.py**
> (Press CTRL + J, Search for Line Number 154)
> Change this line
> `INSTALL_REQUIRES = ["pbkdf2", "scapy", "tornado==4.5.3", "roguehostapd", "pyric"]`
> To
> `INSTALL_REQUIRES = ["pbkdf2", "scapy", "tornado==5.1.1", "roguehostapd", "pyric"]`
> (Save the file)
> and run Setup once again

As @Alpha-1729 said, this solution worked. I had almost the same problem described in this issue and gave this solution a go. Totally worth it. Thanks.

Note: `sudo python setup.py install` gave me a couple errors and could not install for any reason. But using python3 worked fine.

**Comment by AlienWolfX** [comment]
Thank you all for the Help Got it Working. :)
