### ISSUE TITLE
Why i can't run wifiphisher?

### ISSUE THREAD

**Issue by snux123** [wifiphisher/wifiphisher#1308]
root@GL-:~# wifiphisher
[*] Starting Wifiphisher 1.4GIT ( https://wifiphisher.org ) at 2020-04-23 13:57
[+] Timezone detected. Setting channel range to 1-13
ERROR:root:The following error has occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/wifiphisher-1.4-py3.8.egg/wifiphisher/pywifiphisher.py", line 439, in start
    mon_iface, ap_iface = self.network_manager.get_interface_automatically(
  File "/usr/local/lib/python3.8/dist-packages/wifiphisher-1.4-py3.8.egg/wifiphisher/common/interfaces.py", line 608, in get_interface_automatically
    monitor_interface = self.get_interface(has_monitor_mode=True)
  File "/usr/local/lib/python3.8/dist-packages/wifiphisher-1.4-py3.8.egg/wifiphisher/common/interfaces.py", line 597, in get_interface
    raise InterfaceCantBeFoundError((has_monitor_mode, has_ap_mode))
wifiphisher.common.interfaces.InterfaceCantBeFoundError: Failed to find an interface with monitor mode
[!] Failed to find an interface with monitor mode
[+] Show your support!
[+] Follow us: https://twitter.com/wifiphisher
[+] Like us: https://www.facebook.com/Wifiphisher
[+] Captured credentials:
ERROR:wifiphisher.common.utilities:iptables -F has failed with the following error:
b'iptables/1.8.3 Failed to initialize nft: Protocol not supported\n'
ERROR:wifiphisher.common.utilities:iptables -X has failed with the following error:
b'iptables/1.8.3 Failed to initialize nft: Protocol not supported\n'
ERROR:wifiphisher.common.utilities:iptables -t nat -F has failed with the following error:
b'iptables/1.8.3 Failed to initialize nft: Protocol not supported\n'
ERROR:wifiphisher.common.utilities:iptables -t nat -X has failed with the following error:
b'iptables/1.8.3 Failed to initialize nft: Protocol not supported\n'
[!] Closing

**Comment by lonewolfss** [comment]
you need to set your monitor mode

sudo airmon-ng start "Wirlesscardname"

[!] Failed to find an interface with monitor mode

**Comment by snux123** [comment]
E: Unable to locate package airmon-ng

**Comment by lonewolfss** [comment]
when you try to add the command it will tell you what you need to install if it cannot be found :D but here is the code to install it 

sudo apt-get install aircrack-ng

**Comment by sophron** [comment]
You don't seem to have a wireless interface that supports monitor mode in your system. Please check the requirements of the project before running the tool.

**Comment by DanLay** [comment]
I have the same problem.

kali@kali:~/wifiphisher/bin$ sudo wifiphisher
[*] Starting Wifiphisher 1.4GIT ( https://wifiphisher.org ) at 2020-05-18 10:49
[+] Timezone detected. Setting channel range to 1-13
ERROR:root:The following error has occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/wifiphisher-1.4-py3.8.egg/wifiphisher/pywifiphisher.py", line 446, in start
    mon_iface, ap_iface = self.network_manager.get_interface_automatically(
  File "/usr/local/lib/python3.8/dist-packages/wifiphisher-1.4-py3.8.egg/wifiphisher/common/interfaces.py", line 627, in get_interface_automatically
    ap_interface = self.get_interface(has_ap_mode=True)
  File "/usr/local/lib/python3.8/dist-packages/wifiphisher-1.4-py3.8.egg/wifiphisher/common/interfaces.py", line 615, in get_interface
    raise InterfaceCantBeFoundError((has_monitor_mode, has_ap_mode))
wifiphisher.common.interfaces.InterfaceCantBeFoundError: Failed to find an interface with AP mode
[!] Failed to find an interface with AP mode
[+] Show your support!
[+] Follow us: https://twitter.com/wifiphisher
[+] Like us: https://www.facebook.com/Wifiphisher
[+] Captured credentials:
[!] Closing

What can it be?

**Comment by sophron** [comment]
You need a card that supports AP mode.

**Comment by mahmuod88m** [comment]
──(root㉿kali)-[~]
└─#  wifiphisher
[*] Starting Wifiphisher 1.4GIT ( https://wifiphisher.org ) at 2023-03-09 14:51
[+] Timezone detected. Setting channel range to 1-13
ERROR:root:The following error has occurred:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/wifiphisher/pywifiphisher.py", line 489, in start
    mon_iface, ap_iface = self.network_manager.get_interface_automatically(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/wifiphisher/common/interfaces.py", line 627, in get_interface_automatically
    ap_interface = self.get_interface(has_ap_mode=True)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/wifiphisher/common/interfaces.py", line 615, in get_interface
    raise InterfaceCantBeFoundError((has_monitor_mode, has_ap_mode))
wifiphisher.common.interfaces.InterfaceCantBeFoundError: Failed to find an interface with AP mode
[!] Failed to find an interface with AP mode
[+] Show your support!
[+] Follow us: https://twitter.com/wifiphisher
[+] Like us: https://www.facebook.com/Wifiphisher
[+] Captured credentials:
[!] Closing
