### ISSUE TITLE
Option `-jI` does not exist anymore?

### ISSUE THREAD

**Issue by fntkg** [wifiphisher/wifiphisher#1311]
**Version**: commit 809174109b1f728346dcc2f3c3bb4ff549617f7a

**Description**:  When i try to do the example you give in README.md about "Firmware Upgrade" scenario, the script returns `wifiphisher: error: unrecognized arguments: -jI wlp0s20f0u6`.
Also, i have tested it with  `--jamminginterface` but ends with the same result

Linux distribution:  `Arch Linux x86_64`
Kernel: `5.6.6-arch1-1`

**Script output**: `wifiphisher: error: unrecognized arguments: -jI wlp0s20f0u6`

**Comment by sophron** [comment]
Yes, use `-nD` instead.

**Comment by fntkg** [comment]
Okey thanks, and what's the meaning of `nD`? Just curiosity

**Comment by Muhammadjihas** [comment]
> Okey thanks, and what's the meaning of `nD`? Just curiosity

Skip the deauthentication phase.
