### ISSUE TITLE
iftable or ip table ?

### ISSUE THREAD

**Issue by Flourdeau** [wifiphisher/wifiphisher#1314]
Hi, since 3 days i try to connect to the fake pages but it doesnt work.
I know it's because the dhcp and the http can't start, so i dont understand why. I have iptables and nftables packets installed yet.
It return me "iptables v1.8.4 (nf_tables): could not fetch rule set genera tion id: invalid argument" \n\n'

**Comment by Flourdeau** [comment]
I run on kali 2020.2 with raspberry pi 3b (arm64)

**Comment by sophron** [comment]
#1305
