### ISSUE TITLE
a question need be solve，see img

### ISSUE THREAD

**Issue by TonyK-T** [wifiphisher/wifiphisher#1315]
![image](https://user-images.githubusercontent.com/11296126/80590056-d9d5be00-8a4d-11ea-9dac-43d862b1555a.png)

**Comment by sophron** [comment]
Hi @TonyK-T,

We pass the interface as "managed" to hostapd and hostapd will do the rest.

**Comment by TonyK-T** [comment]
one perfect_card support AP and monitor

**Comment by TonyK-T** [comment]
1.mon_iface(Monitor) to find_all_access_points 
2. choose a target_access_point
3. ap_iface(managed) with target_ap information to  hostapd , and hostapd Start a softAP,?  (others people connect to the rogue softAP? )
4. mon_iface to attack target_ap
5. start a web service

Is the above procedure correct?
I don't understand how the third step works，Can you explain？
Tk U very much

**Comment by sophron** [comment]
Yes, hostapd will leverage the "AP" capabilities of your card to spawn a soft AP. You will get better answers if you ask the hostapd developers directly.

**Comment by TonyK-T** [comment]
> Yes, hostapd will leverage the "AP" capabilities of your card to spawn a soft AP. You will get better answers if you ask the hostapd developers directly.

Thank you very much
