### ISSUE TITLE
Problem on wifiPhisher please Fr/Us

### ISSUE THREAD

**Issue by MadMax6z** [wifiphisher/wifiphisher#1320]
Bonjour j'ai un problème avec wifiphisher lors de l'installation sur ubuntu cela m'affiche un code d'erreur je ne sais pas d'ou vient la source j'ai passer 10 heures sur le problème je serais très reconnaisant si quelqu'un trouve la solution je suis pret a faire un don de 10 euro !

Hello I have a problem with wifiphisher during the installation on ubuntu this shows me an error code I do not know where the source comes from I spend 10 hours on the problem I would be very grateful if someone one finds the solution I am ready to make a donation of 10 euro!

I'm on ubuntu 20.04-Desktop.iso 

 'madmax@madmax-X300-X340-X400-series:~/Bureau/wifiphisher$ sudo python setup.py install
[sudo] Mot de passe de madmax : 
Désolé, essayez de nouveau.
[sudo] Mot de passe de madmax : 
Please use Python 3 to install Wifiphisher.
madmax@madmax-X300-X340-X400-series:~/Bureau/wifiphisher$ sudo python3 setup.py install
unable to execute 'x86_64-linux-gnu-gcc': No such file or directory
The development package for netlink is required for the compilation of roguehostapd. Please install it and rerun the script (e.g. on Debian-based systems run: apt-get install libnl-3-dev libnl-genl-3-dev
madmax@madmax-X300-X340-X400-series:~/Bureau/wifiphisher$ cd
madmax@madmax-X300-X340-X400-series:~$ apt-get install libnl-3-dev libnl-genl-3-dev
E: Impossible d'ouvrir le fichier verrou /var/lib/dpkg/lock-frontend - open (13: Permission non accordée)
E: Impossible d'obtenir le verrou de dpkg (/var/lib/dpkg/lock-frontend). Avez-vous les droits du superutilisateur ?
madmax@madmax-X300-X340-X400-series:~$ sudo apt-get install libnl-3-dev libnl-genl-3-dev
Lecture des listes de paquets... Fait
Construction de l'arbre des dépendances       
Lecture des informations d'état... Fait
libnl-3-dev est déjà la version la plus récente (3.4.0-1).
libnl-genl-3-dev est déjà la version la plus récente (3.4.0-1).
0 mis à jour, 0 nouvellement installés, 0 à enlever et 0 non mis à jour.
madmax@madmax-X300-X340-X400-series:~$ cd /Bureau/
bash: cd: /Bureau/: Aucun fichier ou dossier de ce type
madmax@madmax-X300-X340-X400-series:~$ cd Bureau
madmax@madmax-X300-X340-X400-series:~/Bureau$ cd wifiphisher
madmax@madmax-X300-X340-X400-series:~/Bureau/wifiphisher$ sudo python3 setup.py install
unable to execute 'x86_64-linux-gnu-gcc': No such file or directory
The development package for netlink is required for the compilation of roguehostapd. Please install it and rerun the script (e.g. on Debian-based systems run: apt-get install libnl-3-dev libnl-genl-3-dev
madmax@madmax-X300-X340-X400-series:~/Bureau/wifiphisher$`

**Comment by MadMax6z** [comment]
`madmax@madmax-X300-X340-X400-series:~/Bureau/wifiphisher$ sudo apt-get install wifiphisher
[sudo] Mot de passe de madmax : 
Lecture des listes de paquets... Fait
Construction de l'arbre des dépendances       
Lecture des informations d'état... Fait
E: Impossible de trouver le paquet wifiphisher
madmax@madmax-X300-X340-X400-series:~/Bureau/wifiphisher$ sudo python3 setup.py install
unable to execute 'x86_64-linux-gnu-gcc': No such file or directory
The development package for netlink is required for the compilation of roguehostapd. Please install it and rerun the script (e.g. on Debian-based systems run: apt-get install libnl-3-dev libnl-genl-3-dev
madmax@madmax-X300-X340-X400-series:~/Bureau/wifiphisher$`

**Comment by MadMax6z** [comment]
`madmax@madmax-X300-X340-X400-series:~/Bureau/wifiphisher$ sudo apt-get install wifiphisher
[sudo] Mot de passe de madmax : 
Lecture des listes de paquets... Fait
Construction de l'arbre des dépendances       
Lecture des informations d'état... Fait
E: Impossible de trouver le paquet wifiphisher
madmax@madmax-X300-X340-X400-series:~/Bureau/wifiphisher$ sudo python3 setup.py install
unable to execute 'x86_64-linux-gnu-gcc': No such file or directory
The development package for netlink is required for the compilation of roguehostapd. Please install it and rerun the script (e.g. on Debian-based systems run: apt-get install libnl-3-dev libnl-genl-3-dev
madmax@madmax-X300-X340-X400-series:~/Bureau/wifiphisher$`

**Comment by MadMax6z** [comment]
Please bro..

**Comment by MadMax6z** [comment]
and i install roguehostapd 

`admax@madmax-X300-X340-X400-series:~/Bureau/wifiphisher/roguehostapd$ python setup.py install
unable to execute 'x86_64-linux-gnu-gcc': No such file or directory
[!] The development package for netlink is missing. Please download it and restart the compilation.If you are on Debian-based system: 'apt-get install libnl-3-dev libnl-genl-3-dev'.`

**Comment by lonewolfss** [comment]
its telling you there is No such file or directory    and   The development package for netlink is required for the compilation of roguehostapd. Please install it and rerun the script so start from the start and do 


sudo apt update 
sudo git clone https://github.com/wifiphisher/wifiphisher.git
cd wifiphisher
sudo python setup.py install

if anything needs to be installed it will tell you when you try to install this from the code you added it already needs  

sudo apt-get install libnl-3-dev libnl-genl-3-dev

**Comment by MadMax6z** [comment]
Thanks a lot for your reply i found the solution on similar thread the solution is on this link
http://www.hacklove.net/discussion/97/unable-to-execute-x86-64-linux-gnu-gcc-no-such-file-or-directory

Thanks bro
