### ISSUE TITLE
Power is at 0% when I run Wifiphisher!!!

### ISSUE THREAD

**Issue by shekhar097** [wifiphisher/wifiphisher#1333]
After running wifiphisher, the power column is always at 0%. And it is happening every time. Also running wifiphisher, "network manager needs to be running" error is diplayed in GUI setting. When hitting iwconfig after closing wifiphisher, this is what I get as below: 
lo        no wireless extensions.

eth0      no wireless extensions.

wlan0mon  IEEE 802.11  Mode:Monitor  Frequency:2.432 GHz  Tx-Power=20 dBm   
          Retry short limit:7   RTS thr=2347 B   Fragment thr:off
          Power Management:on
          
usb0      no wireless extensions.

wfphshr-wlan0  IEEE 802.11  ESSID:off/any  
          Mode:Managed  Access Point: Not-Associated   Tx-Power=20 dBm   
          Retry short limit:7   RTS thr=2347 B   Fragment thr:off
          Encryption key:off
          Power Management:on
!!!pls help!!!

**Comment by sophron** [comment]
#1328.
