### ISSUE TITLE
SyntaxError: Missing parentheses in call to 'print'

### ISSUE THREAD

**Issue by rochdi3** [wifiphisher/wifiphisher#1335]
raceback (most recent call last):
  File "/home/rosh/.local/bin/wifiphisher", line 5, in <module>
    from wifiphisher.pywifiphisher import run
  File "/home/rosh/.local/lib/python3.8/site-packages/wifiphisher/pywifiphisher.py", line 203
    print "\nAvailable Phishing Scenarios:\n"
          ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("\nAvailable Phishing Scenarios:\n")?

**Comment by JetseVerschuren** [comment]
Try installing the latest version from git
