### ISSUE TITLE
Hello. I encountered such a problem.

### ISSUE THREAD

**Issue by sptpower** [wifiphisher/wifiphisher#1336]
Hello. I encountered such a problem. 
![1](https://user-images.githubusercontent.com/62520520/83040468-f3b3f200-a047-11ea-9f6a-6a7c31c59030.png)
![2](https://user-images.githubusercontent.com/62520520/83040475-f57db580-a047-11ea-921a-e2d8c89ef850.png)

_Originally posted by @sptpower in https://github.com/wifiphisher/wifiphisher/issues/1236#issuecomment-634741502_

**Comment by sptpower** [comment]
Hm. Does anyone understand? 🙃

**Comment by JetseVerschuren** [comment]
Try running `apt-get install python3-setuptools` and then running `python3 setup.py install`.

**Comment by sptpower** [comment]
> apt-get install python3-setuptools

![scr](https://user-images.githubusercontent.com/62520520/83331463-489d7580-a29f-11ea-9506-81fc4d869134.png)

**Comment by JetseVerschuren** [comment]
Try the command the error is already suggesting: `apt --fix-broken install`.

**Comment by sptpower** [comment]
Delete libobasis6.4-ru-help? 

![92](https://user-images.githubusercontent.com/62520520/83360407-d0f84500-a389-11ea-8050-05065865d4a5.png)

**Comment by sptpower** [comment]
> apt --fix-broken install

Everything is fine, I figured it out. Thank you very much, you had to reinstall the package `` apt --fix-broken instal ''
