### ISSUE TITLE
Power is 0% and shows!!!

### ISSUE THREAD

**Issue by shekhar097** [wifiphisher/wifiphisher#1338]
While using wifiphisher, it shows power 0%. Also it shows the network WEP encrypted although the wifi network is WPA encrypted. Adding to this, after using wifiphisher, network manager goes down displaying a message in settings 'network manager needs to be running'.
I'm using kali linux 2020.2

Plz Help!!!

**Comment by benek15** [comment]
I have this same problem

**Comment by sophron** [comment]
#1328.
