### ISSUE TITLE
how to fix ModuleNotFoundError: No module named 'six' in wifiphisher kali

### ISSUE THREAD

**Issue by 3liq822** [wifiphisher/wifiphisher#1340]
So I tried installing wifiphisher using the git clone it asked me to install python 3 so I installed python3 and it worked the logo appears but when I write wifiphisher to run it it doesnt run it says ModuleNotFoundError: No module named 'six' I tired every thing deleting it and clone it again I tried running it using python /bin/wifiphisher I also tried python3 /bin/wifiphisher. please help....

**Comment by JetseVerschuren** [comment]
Try `pip3 install six`.
