### ISSUE TITLE
ModuleNotFoundError: No module named 'ConfigParser'

### ISSUE THREAD

**Issue by hwac121** [wifiphisher/wifiphisher#1342]
**Version**:
wifiphisher-1.4

**Description**: 
Newest version of Kali 2020 - Lenovo laptop

**Script output**:
ModuleNotFoundError: No module named 'ConfigParser'

**Comment by sophron** [comment]
We are no longer using `ConfigParser`. Use the latest version from git (e.g. `git clone https://github.com/wifiphisher`).
