### ISSUE TITLE
path to a payload, Syntax error

### ISSUE THREAD

**Issue by https-sam** [wifiphisher/wifiphisher#1349]
I am trying to put a payload, but every time I choose that option and put a path to my payload, it says "syntax error". Could someone help me out with this? 

wifiphisher
[*] Starting Wifiphisher 1.4GIT ( https://wifiphisher.org ) at 2020-06-20 13:27
[+] Timezone detected. Setting channel range to 1-13
[+] Selecting wfphshr-wlan0 interface for the deauthentication attack
[+] Selecting wlan1 interface for creating the rogue Access Point
[+] Changing wlan1 MAC addr (BSSID) to 00:00:00:c8:b6:e8
[+] Changing wlan1 MAC addr (BSSID) to 00:00:00:7c:06:5b
[*] Cleared leases, started DHCP, set up iptables
[+] Selecting Browser Plugin Update template
[+] Enter the [full path] to the payload you wish to serve: /root/Desktop/istockphoto-93174442.exe          
Traceback (most recent call last):
  File "/usr/bin/wifiphisher", line 11, in <module>
    load_entry_point('wifiphisher==1.4', 'console_scripts', 'wifiphisher')()
  File "/usr/local/lib/python3.8/dist-packages/wifiphisher-1.4-py3.8.egg/wifiphisher/pywifiphisher.py", line 728, in run
    engine.start()
  File "/usr/local/lib/python3.8/dist-packages/wifiphisher-1.4-py3.8.egg/wifiphisher/pywifiphisher.py", line 575, in start
    payload_path = eval(input(
  File "<string>", line 1
    /root/Desktop/isto.exe
    ^
SyntaxError: invalid syntax

**Comment by five2seven** [comment]
Same issue, can't figure out what syntax to use. The path is already in the Config.ini file but it's still asking for it during launch.
