### ISSUE TITLE
apt-get install libnl-3-dev libnl-genl-3-dev error

### ISSUE THREAD

**Issue by azam1225** [wifiphisher/wifiphisher#1355]
root@kali:~/wifiphisher# python3 setup.py install
In file included from /tmp/tmp_netlink_4yo1b3hq/test_netlink.c:2:
/usr/include/libnl3/netlink/netlink.h:15:10: fatal error: stdio.h: No such file or directory
   15 | #include <stdio.h>
      |          ^~~~~~~~~
compilation terminated.
The development package for netlink is required for the compilation of roguehostapd. Please install it and rerun the script (e.g. on Debian-based systems run: apt-get install libnl-3-dev libnl-genl-3-dev
root@kali:~/wifiphisher# 
![Screenshot 2020-06-29 05:36:41](https://user-images.githubusercontent.com/64639907/85956121-38151380-b9a1-11ea-8b59-02fde44609f4.png)

**Comment by u-ahmedofficial** [comment]
Getting Same issue, any solution?

**Comment by satana666luciferka** [comment]
was there a solution for this problem ???

**Comment by lerileri444** [comment]
em pleno ano de copa e o problema não foi resolvido :(

**Comment by upz999** [comment]
There is a simple fix. Sudo apt update 
Update your repository and it should be able to find the packages you need.

**Comment by upz999** [comment]
Try the sudo apt get command after sudo apt update
