### ISSUE TITLE
Question about how clients are deauthenticated from their network and not the evil twin

### ISSUE THREAD

**Issue by Drumshtick** [wifiphisher/wifiphisher#1369]
Hi all, love the work you guys have put in on wifiphisher. I am curious about how clients can connect to the evil twin network while they are being disconnected from their actual network. Since the evil twin has the same mac, ESSID and channel, how are the clients able to connect to the evil twin without being immediately disconnected due to the deuathentication attack. wont the deauth packets target the Evil Twin network clients as well?

**Comment by JetseVerschuren** [comment]
If the fake AP had the same MAC address there would indeed be quite some interference, that's why the MAC address is different. The MAC is randomized on startup, not cloned.

**Comment by Drumshtick** [comment]
excellent. Thanks for the reply. I realize now that I could have figured that out myself.

**Comment by JetseVerschuren** [comment]
Glad I could help.
