### ISSUE TITLE
Is this an issue with hardware or a mistake on my end?

### ISSUE THREAD

**Issue by ai-mir** [wifiphisher/wifiphisher#1385]
[+] Captured credentials:
^[[A^[[A[!] Closing
root@kali:~# wifiphisher --force-hostapd
[*] Starting Wifiphisher 1.4GIT ( https://wifiphisher.org ) at 2020-10-10 12:15
[+] Timezone detected. Setting channel range to 1-13
[+] Selecting wlan0 interface for the deauthentication attack
[+] Selecting wfphshr-wlan0 interface for creating the rogue Access Point
[+] Changing wfphshr-wlan0 MAC addr (BSSID) to 00:00:00:61:4a:e6
[!] The MAC address could not be set. (Tried 00:00:00:ea:af:89)  <-----
[*] Cleared leases, started DHCP, set up iptables
[+] Selecting Firmware Upgrade Page template
[*] Using hostapd instead of roguehostapd. Many significant features will be turned off.
[*] Starting the fake access point...  <-----
[!] hostapd failed to lunch!  <-----

[+] Show your support!
[+] Follow us: https://twitter.com/wifiphisher
[+] Like us: https://www.facebook.com/Wifiphisher
[+] Captured credentials:
[!] The MAC address could not be set. (Tried 00:00:00:77:e3:c0)
[!] Closing
root@kali:~# wif

I'm using a TP-link WN722n V3 and I have monitor mode on. I am doing this on Kali Linux on Virtual Box and my laptop has an internal Wifi card. I'm sorry if this isn't where I should be asking about this but I'm genuinely tired and don't know who to ask anymore. Can my card not manage AP and Monitoring at the same? What is the issue? I read that internal wireless card can't interact with VBox and if that's the case, should I just stop trying?
Thank you and sorry if this is out of place.

**Comment by CKlymko** [comment]
Try using a card with an atheros chipset.
