### ISSUE TITLE
ImportError: No module named setuptools

### ISSUE THREAD

**Issue by secuhiro** [wifiphisher/wifiphisher#1388]
According to https://github.com/wifiphisher/wifiphisher/#installation
i did sudo python setup.py install
But it gives me this error:
Traceback (most recent call last):
File "setup.py", line 23, in
from setuptools import Command, find_packages, setup
ImportError: No module named setuptools

SoI found the solution from https://github.com/wifiphisher/wifiphisher/issues/1346
Then I tried
1.I downloaded the latest Kali 2020.3 and installed it on the hard disk: https://www.kali.org/downloads/
2.After long and succesfull installation I did: sudo apt update && apt full-upgrade -y
3.Then: sudo apt-get install libnl-3-dev libnl-genl-3-dev
4.Then: sudo apt-get install libssl-dev
5.Then: sudo apt-get install libpcap-dev (reaver needs this lib)
6.I downloaded the latest version of Wifiphisher and installed as it is here: https://github.com/wifiphisher/wifiphisher/#installation

But still it gives me same error:
ImportError: No module named setuptools

Would you please help me.

**Comment by niwo77** [comment]
i have the same issue, do you found a solution?

**Comment by secuhiro** [comment]
> i have the same issue, did you found a solution?
Still waiting for the advice
If you get some solutions, please share it here.

**Comment by toufikben** [comment]
i dont know if this will help you , but i did install it using   sudo python3 setup.py install on wifislax not kali , hope its help

**Comment by secuhiro** [comment]
Thank you guys!!
"sudo python3 setup.py install" works fine.
So install and setting is OK
But still have problem about running.
Then we are discuss about this on https://github.com/wifiphisher/wifiphisher/issues/1389
