### ISSUE TITLE
Successful deauth but client can't auto connect to rogue ap

### ISSUE THREAD

**Issue by GIGAM25** [wifiphisher/wifiphisher#1395]
Using kali linux and wifiphisher 1.4. Everything is working fine. Can deauthenticate client from the target ap. Page automatically popup when i manually connect to rogue ap. My issue is, when it successfully deauth my device, that device will not automatically connect to the rogue ap. it is continuously connecting to the original ap and continues deauth it. is this something to do with wpa2?

**Comment by vido89** [comment]
I have same issue

**Comment by mu-majid** [comment]
If you are running `Evil Twin` attack it might not work, I think you should try KARMA or Known Beacons attacks for auto-association with rogue AP.

**Comment by JetseVerschuren** [comment]
If your target network has a password, and you want your targets to auto connect to WifiPhisher, you need to give WifiPhisher the password of the network using `-pK`. That's just how WPA2 works. You could try naming the WifiPhisher network something the devices would connect to automatically that doesn't have a password. Somethink like starbuck, mcdonalds or train wifi.
