### ISSUE TITLE
Known Beacons

### ISSUE THREAD

**Issue by GIGAM25** [wifiphisher/wifiphisher#1396]
hello masters,

how can i change the list of beacons to send?
and
since beacons are all open network, is there a way that i can add password in 1 beacon?

TIA

**Comment by sophron** [comment]
You can edit `wifiphisher/data/wifiphisher-known-open-wlans`. As of now, we don't support WPA/WPA2 know beacons.

**Comment by GIGAM25** [comment]
Hello master sophron,
Actuallyvi already did that. I made a backup file of that file, replace the content there. Placed only 5 beacons (open wlan). Some suggested that i have to the install again after changing. But old record still showing up
