### ISSUE TITLE
--protectinterface not work

### ISSUE THREAD

**Issue by sagaardu** [wifiphisher/wifiphisher#1409]
Before opening a new issue, please make sure that what you are about to report has not been reported already or is not included on the FAQ page. If not, use the following template for reporting.

Please keep in mind that our developers will prioritize your issue if you provide a detailed and extensive description.

**Version**: Raspberry pi4 with dietpi installed (Linux DietPi 5.4.51-v7l+ #1333 SMP Mon Aug 10 16:51:40 BST 2020 armv7l GNU/Linux)

**Description**: I have the raspberry connected to my network via wifi with its native wireless card (wlan0) and two more adapters to use wifiphisher (wlan2 and wlan3).

root@DietPi:~# iwconfig
eth0      no wireless extensions.

wlan2     IEEE 802.11  ESSID:off/any
          Mode:Managed  Access Point: Not-Associated   Tx-Power=20 dBm
          Retry short  long limit:2   RTS thr:off   Fragment thr:off
          Encryption key:off
          Power Management:off

wlan0     IEEE 802.11  ESSID:"WIRELESS_XXXX"
          Mode:Managed  Frequency:2.437 GHz  Access Point: XX:XX:XX:XX:XX:XX
          Bit Rate=65 Mb/s   Tx-Power=31 dBm
          Retry short limit:7   RTS thr:off   Fragment thr:off
          Encryption key:off
          Power Management:off
          Link Quality=46/70  Signal level=-64 dBm
          Rx invalid nwid:0  Rx invalid crypt:0  Rx invalid frag:0
          Tx excessive retries:1  Invalid misc:0   Missed beacon:0

wlan3     IEEE 802.11  ESSID:off/any
          Mode:Managed  Access Point: Not-Associated   Tx-Power=20 dBm
          Retry short limit:7   RTS thr:off   Fragment thr:off
          Encryption key:off
          Power Management:off

lo        no wireless extensions.

When I launch wifiphisher everything seems to be going well, but the problem is that it also disconnects the wlan0 card despite indicating the protection mode for this interface.

This is the command I launch:

wifiphisher -aI wlan2 -eI wlan3 -pI wlan0 -dC 6 -qS --phishing-pages-directory ~ / wifiphisher / wifiphisher / data / phishing-pages /

And this from that moment I lose the management:

Response from 192.168.200.60: bytes = 32 time = 5ms TTL = 64
Response from 192.168.200.60: bytes = 32 time = 4ms TTL = 64
Response from 192.168.200.60: bytes = 32 time = 2ms TTL = 64
Timeout for this request.
Reply from 192.168.200.100: Destination host unreachable.
Reply from 192.168.200.100: Destination host unreachable.
Reply from 192.168.200.100: Destination host unreachable.
Reply from 192.168.200.100: Destination host unreachable.
Reply from 192.168.200.100: Destination host unreachable.

**Script output**: 

root@DietPi:~# wifiphisher -aI wlan2 -eI wlan3 -pI wlan0 -dC 6 -qS --phishing-pages-directory ~/wifiphisher/wifiphisher/data/phishing-pages/
[*] Starting Wifiphisher 1.4GIT ( https://wifiphisher.org ) at 2020-12-25 11:45
[+] Timezone detected. Setting channel range to 1-13
[+] Selecting wlan3 interface for the deauthentication attack
[+] Selecting wlan2 interface for creating the rogue Access Point
[+] Changing wlan2 MAC addr (BSSID) to 00:00:00:a5:b1:52
[+] Changing wlan2 MAC addr (BSSID) to 00:00:00:c9:32:6b
[+] Sending SIGKILL to wpa_supplicant
[+] Sending SIGKILL to wpa_supplicant
[+] Sending SIGKILL to dhclient
[*] Cleared leases, started DHCP, set up iptables

**Comment by sophron** [comment]
Try using `--keepnetworkmanager` too.
