### ISSUE TITLE
none of the 4 default phishing pages load on victim's browser while testing

### ISSUE THREAD

**Issue by ren3g4de** [wifiphisher/wifiphisher#1421]
**Version**:
commit f0be7838b5c39855aa7a1f6b70566e69ad2f4334

**Description**: 
So i have managed to get wifiphisher to launch and create a rogue ap and deauth clients, on all 4 different phishing techniques. Yet none of them actually give any kind of phishing page to load on the victims web browser after connecting. i feel like this is related to what is being served via /var/www/html, but i could be wrong (i base this off a loose knowledge of how this attack works outside of this automation scripting.)

i have looked through the FAQ and browsed through various Issues request, but not all of the (currently 204) posted and open. 

i have tried both the version included in the repos of kali rolling and installing from the git clone.

my test victims have included a VM of win10, a physical win7 machine, and multiple android devices running android 9/10. none of these victims browsers have recieved the desired pages after connecting to rogue ap. 

i feel like i may be missing something very obvious, and i hope that is the case, and pre-appologize if this is the case. 

**Script output**: 
output of tool seems to be non diagnostic (so i did not post it here), it does show a few get and post, but like i stated above, the browser on victim does not receive any of the desired phishing pages.

**Comment by sophron** [comment]
Hi @ren3g4de,

Are you connecting over HTTPS? What happens when you try connecting to `neverssl.com` from a victim's browser? 

Also, what options are you using?

**Comment by ren3g4de** [comment]
options being used are just -aI wlan# -eI wlan#

i have tried all 4 default methods of phishing scenarios all with the same result. 

going back to my attack machine and will try neverssl.com on my test victims, will update shortly

**Comment by ren3g4de** [comment]
while attempting to access neverssl.com there is nothing loading on either victims browser, test both on win10 and android10

**Comment by xpz3** [comment]
From any client device, try pinging the attacker machine ip. Also try pointing clients3.google.com from the client. What do you get?

**Comment by sophron** [comment]
I just pushed a commit that fixes this. Update to the latest revision and try again.
