### ISSUE TITLE
wifiphisher using wrong interface for Deauth attack

### ISSUE THREAD

**Issue by hdawg12** [wifiphisher/wifiphisher#1423]
Before opening a new issue, please make sure that what you are about to report has not been reported already or is not included on the FAQ page. If not, use the following template for reporting.

Please keep in mind that our developers will prioritize your issue if you provide a detailed and extensive description.

**Version**: Use `git show | grep commit` command and paste here the output.

Here is the information.  I'm using Kali 2020.2
my hardware info: 
processors 8 x intel core i5-8250U CPU @ 1.60GHz
Memory: 8 gigs
Graphics Processor: Mesa Intel UHD Graphics 620
I have NVIDIA Geforce MX150 with 2GB VRAM installed in my laptop
My laptop is an Aspire E15
I have a Panda wireless PAU05 and Alfa ath9k_htc Qualcomm Atheros Communications AR9271 802.11n

**Description**: 
When I use wifiphisher I make sure to shutdown my internal NIC so that I have my PAU05 and my Atheros working. I put my Atheros into monitor mode before I open wifiphisher(not sure if that is what I should do) and I choose "Firmware Upgrade" as my attack.  The problem I have is that wifiphisher uses my wlan0(internal NIC)for the death attack and my wlan2(PAU05) as the rogue access point.  So I'm not sure if my firmware upgrade attack will work correctly, because my wlan0 doesn't perform deauth attacks.  Thats why I have my Atheros.   Is there a way for wifiphisher to recognize my wlan1mon(atheros) as the interface for the deauth attack? 

Thank you

**Script output**:
root@KaliLinux:~/wifiphisher# wifiphisher
[*] Starting Wifiphisher 1.4GIT ( https://wifiphisher.org ) at 2021-02-24 22:48
[+] Timezone detected. Setting channel range to 1-13
[+] Selecting wlan0 interface for the deauthentication attack
[+] Selecting wlan2 interface for creating the rogue Access Point
[+] Changing wlan2 MAC addr (BSSID) to 00:00:00:b9:e9:d5
[+] Changing wlan2 MAC addr (BSSID) to 00:00:00:d8:96:a9
[*] Cleared leases, started DHCP, set up iptables
[+] Selecting Firmware Upgrade Page template
[*] Starting the fake access point...
[*] Starting HTTP/HTTPS server at ports 8080, 443
[+] Show your support!
[+] Follow us: https://twitter.com/wifiphisher
[+] Like us: https://www.facebook.com/Wifiphisher
[+] Captured credentials:
[!] Closing

**Comment by tylerw500** [comment]
Check your syntax string, specify your external card along with your internal card.

**Comment by sophron** [comment]
`wifiphisher -h`
