### ISSUE TITLE
Automatic rename ESSID

### ISSUE THREAD

**Issue by antyneutron** [wifiphisher/wifiphisher#1459]
Hello everyone :)
Im new here, and in kali linux wolrd - thats my 3rd day ...

i have a kali linux installed 3 days ago , newest version of wifipfisher, so my problem is : 
use command `sudo wifiphisher -i wlan1`  , choose a target ( ESSID: SKY7FBEE )  and scenario : firmware update 

and then i see `Victim 7c:b2:64:2b:66:a7 probed for WLAN with ESSID: 'iPhone (Mark)' (KARMA) `

i dont understand why ESSID is iPhone (Mark) .
when i try other target , same situation .

I found a few answers and try somethink like this `sudo wifiphisher -i wlan1 --essid SKY7FBEE -pE SKY7FBEE -p firmware-upgade `

then i see  `[*] Starting Wifiphisher 1.4GIT ( https://wifiphisher.org ) at 2021-09-05 22:15
[+] Timezone detected. Setting channel range to 1-13
[+] Selecting wfphshr-wlan0 interface for the deauthentication attack
[+] Selecting wlan0 interface for creating the rogue Access Point
[+] Changing wlan0 MAC addr (BSSID) to 00:00:00:e7:99:a6
[+] Changing wlan0 MAC addr (BSSID) to 00:00:00:6c:d5:68
[*] Cleared leases, started DHCP, set up iptables
Traceback (most recent call last):
  File "/usr/bin/wifiphisher", line 33, in <module>
    sys.exit(load_entry_point('wifiphisher==1.4', 'console_scripts', 'wifiphisher')())
  File "/usr/lib/python3/dist-packages/wifiphisher/pywifiphisher.py", line 728, in run
    engine.start()
  File "/usr/lib/python3/dist-packages/wifiphisher/pywifiphisher.py", line 562, in start
    template = tui_template_obj.gather_info(args.phishingscenario,
  File "/usr/lib/python3/dist-packages/wifiphisher/common/tui.py", line 131, in gather_info
    raise phishingpage.InvalidTemplate
wifiphisher.common.phishingpage.InvalidTemplate: The given template is either invalid or not available locally!
`

PS i know my english and my knowledge is horrible , but give me a time :)

:

**Comment by antyneutron** [comment]
aynone?

**Comment by oon2** [comment]
Yes

Pada tanggal Rab, 8 Sep 2021 08.20, antyneutron ***@***.***>
menulis:
