### ISSUE TITLE
kali latest wifiphisher hangs after channel selection

### ISSUE THREAD

**Issue by sbreaksalot** [wifiphisher/wifiphisher#1472]
![image](https://user-images.githubusercontent.com/80778203/139321426-309fbf3e-4d40-4198-9599-39c4fa12342e.png)

I installed using apt install wifiphisher.
I have kali running in the latest vmware station 16 pro. lastest version on both
I have an  tplink wifiadapter that supports monitor mode connected to the vm.
After i start wifiphisher with sudo in qterminal the whole vm becomes unresponsive.
When i open a second terminal and type top i dont see that the vm is using to much rescources and so on.
when i start with the -nE switch it works

also when i give this command: wifiphisher --essid "FREE WI-FI" -p oauth-login -kB  i get an error
Noting works for me without the -nE switch.
Is that how it suppose to work?

![image](https://user-images.githubusercontent.com/80778203/139490410-38f4bb8b-8d29-4017-a1ee-4fd9e72d9240.png)

**Comment by bplegacy** [comment]
I have the same issue, hanging up on "Setting channel range from 1-13" I dont get any further than that on my machine. Just updated my machine yesterday.

**Comment by hlgf** [comment]
Encountered the same problem, the problem solved

**Comment by hlgf** [comment]
Encountered the same problem,

**Comment by flathill** [comment]
I encountered the same problem on kali linux 2022.1

**Comment by solidsids77** [comment]
Wifiphishing use 2 Wi-Fi card with monitor mode but for your screen you have only one card with monitor mode
