### ISSUE TITLE
Phishing scenario but with username and password for Firmware Upgrade Page

### ISSUE THREAD

**Issue by Mystic-Crystal** [wifiphisher/wifiphisher#1487]
I was wondering how to edit/make a Phishing scenario where there is a username and password instead of just a password for the Firmware Upgrade Page. Any advice, help would be accepted as I have no clue what to do.

**Comment by sophron** [comment]
https://wifiphisher.readthedocs.io/en/stable/phishing_scenarios.html#creating-a-custom-phishing-scenario
