### ISSUE TITLE
when i run wifiphisher in kali linux 2021.4a shows this error Traceback (most recent call last):   File "/home/wifiphisher/bin/wifiphisher", line 24, in <module>     run()   File "/usr/local/lib/python3.9/dist-packages/wifiphisher-1.4-py3.9.egg/wifiphisher/pywifiphisher.py", line 729, in run     engine.start()   File "/usr/local/lib/python3.9/dist-packages/wifiphisher-1.4-py3.9.egg/wifiphisher/pywifiphisher.py", line 503, in start     self.network_manager.unblock_interface(ap_iface)   File "/usr/local/lib/python3.9/dist-packages/wifiphisher-1.4-py3.9.egg/wifiphisher/common/interfaces.py", line 647, in unblock_interface     if pyw.isblocked(card):   File "/usr/lib/python3/dist-packages/pyric/pyw.py", line 624, in isblocked     idx = rfkill.getidx(card.phy)   File "/usr/lib/python3/dist-packages/pyric/utils/rfkill.py", line 200, in getidx     rfks = rfkill_list()   File "/usr/lib/python3/dist-packages/pyric/utils/rfkill.py", line 86, in rfkill_list     'soft':RFKILL_STATE[s], IndexError: list index out of range

### ISSUE THREAD

**Issue by anvinbiju** [wifiphisher/wifiphisher#1495]
Before opening a new issue, please make sure that what you are about to report has not been reported already or is not included on the FAQ page. If not, use the following template for reporting.

Please keep in mind that our developers will prioritize your issue if you provide a detailed and extensive description.

**Version**: Use `git show | grep commit` command and paste here the output.

**Description**: Give a more analytical description here. Let us know how we can reproduce the reported issue. Detail the characteristics of your machine (e.g. Linux distribution and wireless card capabilities) and of the victim devices too (e.g. OS or web browser) if possible. The output of the `iw list` and `iwconfig` commands may also be helpful here.

**Script output**: Paste the output of the tool, including any stack traces.

**Comment by kkk-petrov** [comment]
i have the same problem
