### ISSUE TITLE
  syntaxerror missing parentheses in call to 'print'. did you mean print("")  

### ISSUE THREAD

**Issue by nyameba** [wifiphisher/wifiphisher#1517]
Hello Guys I tried installing KatanaFramework  and  I keep getting the Error below. 
 
syntaxerror missing parentheses in call to 'print'. did you mean print("") 

Can Anyone help me fix this it's been 2 days now and still can't find a solution

**Comment by EngineerNV** [comment]
Hi! So what version of Python do you have installed? And how did you get this error? 

Python is very sensitive to having parenthesis () in the 3.x and higher versions compared to the way you would code 2.x. 

If you are running 3.x and this has Python 2 like prints then you have to manually convert them.

**Comment by EngineerNV** [comment]
Just reread your comment, if it is just installing that means what you were installing might be dependent on an older Python package 2.x. You could try downgrading or finding a newer package for that framework

**Comment by nyameba** [comment]
> Just reread your comment, if it is just installing that means what you were installing might be dependent on an older Python package 2.x. You could try downgrading or finding a newer package for that framework

Yes I discovered the framework was designed for python2 and I was using python3. I had to switch to python2 and it worked. Thanks
