### ISSUE TITLE
Hack

### ISSUE THREAD

**Issue by shiyasshiyas786** [wifiphisher/wifiphisher#1524]

**Comment by digitalirony** [comment]
This should be closed. No description provided

**Comment by sophron** [comment]
Thank you, @digitalirony. I can give you the permissions to manage Wifiphisher issues on your own if you are interested. My time is too limited to manage all of them. Some help would be appreciated.

**Comment by digitalirony** [comment]
Sure, ill help you out with some spare time.

**Comment by sophron** [comment]
Thank you. I sent you an invite.
