### ISSUE TITLE
setup.py is not working 

### ISSUE THREAD

**Issue by kishwordulal** [wifiphisher/wifiphisher#1526]
/home/unknonehart/Desktop/New Folder/wifiphisher/setup.py:19: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
  import distutils.sysconfig
/home/unknonehart/Desktop/New Folder/wifiphisher/setup.py:19: DeprecationWarning: The distutils.sysconfig module is deprecated, use sysconfig instead
  import distutils.sysconfig
/tmp/tmp_netlink_nnm33aj7/test_netlink.c:2:10: fatal error: netlink/netlink.h: No such file or directory
    2 | #include <netlink/netlink.h>
      |          ^~~~~~~~~~~~~~~~~~~
compilation terminated.
The development package for netlink is required for the compilation of roguehostapd. Please install it and rerun the script (e.g. on Debian-based systems run: apt-get install libnl-3-dev libnl-genl-3-dev

**Comment by kishwordulal** [comment]
![Screenshot from 2022-07-03 06-54-57](https://user-images.githubusercontent.com/85834871/177020845-3721f40a-8388-4c3d-b129-c45f133825f8.png)

**Comment by Xp0nent** [comment]
run this "apt-get install libnl-3-dev libnl-genl-3-dev"
