### ISSUE TITLE
Wifiphisher not starting - Traceback (most recent call last):

### ISSUE THREAD

**Issue by Do-odle** [wifiphisher/wifiphisher#1559]
Hello, I have been trying to get wifiphisher to work on my kali linux. I have been trying for over 1 week. It still keeps popping this error. I have seen a lot of other issues, I have tried all sorts of things but still can't make it to work. I tried to clone it following the instructions on the GitHub page, it didn't work. Tried apt-get, it didn't work. I tried to use the wifi adapter in monitor and managed mode, to be sure I am not having any problems with that but nope still same result.
Changed the lines of code inside different folders but no success. I am really tired of it.

![Screenshot_2](https://user-images.githubusercontent.com/96703695/202926001-097cfd50-f7ad-4639-8cf4-c266ce7c7853.png)
Here is the error.

![Screenshot_1](https://user-images.githubusercontent.com/96703695/202926258-e5b28352-e3c4-46c1-b854-539d596150f0.png)
Here are the kali version and python version.

Any ideas or suggestions are appreciated a lot. Thank you in advance

**Comment by thaynes91** [comment]
I am getting this same error, I believe it is a bug that needs to be fixed to be honest, a user made a commit change but even in that commit change it is still not working.

**Comment by Louis-Microsoft** [comment]
First, open rfkill.py

Second, find line 134

Step 3: Modify as follows


Modify into：open(dpath, 'wb+')

**Comment by Do-odle** [comment]
Thank you very much, it worked!
