### ISSUE TITLE
Using in Hidden Networks

### ISSUE THREAD

**Issue by c0d3xpl0it** [wifiphisher/wifiphisher#156]
Dear George,

May I know how to use this tool incase the target is using hidden network. ?

**Comment by sophron** [comment]
Hi @c0d3xpl0it,

There's currently no way for using wifiphisher against hidden networks. That's a feature that we need to add by asking the user to provide ESSID and BSSID of the network he targets.

**Comment by MHCHesham** [comment]
Ok... we need feature to add essid for hidden network by ourself

**Comment by blackHatMonkey** [comment]
@c0d3xpl0it A new patch has been released which includes the feature you requested, please update.

**Comment by minanagehsalalma** [comment]
you can view the essid by sending aireplay-ng 0 0

**Comment by blackHatMonkey** [comment]
Since there are no problems after the patch release, I'm closing this issue. Feel free to open again if needed.
