### ISSUE TITLE
I need solve

### ISSUE THREAD

**Issue by x150ll** [wifiphisher/wifiphisher#1631]
How do I solve this problem even though I have installed it?

The development package for netlink is required for the compilation of roguehostapd. Please install it and rerun the script (e.g. on Debian-based systems run: apt-get install libnl-3-dev libnl-genl-3-dev

This in wifiphisher

**Comment by sophron** [comment]
Hi. The tool is not supposed to be script-kiddie-friendly or easy to use. It's strictly for penetration testing activities. Thank you.
