### ISSUE TITLE
Not found module configparser that not done

### ISSUE THREAD

**Issue by Art4Islami** [wifiphisher/wifiphisher#1670]
I try to install wifiphisher on a kali live usb but theres a problem not a found module configparser line 12 and i looked at closed issues and someone of your team said that the module configparser its not in use and said install from here and there was a page adn said the leatst wifiphisher i installed and run command cd wifiphisher after i installed the git clone and then sudo python3 setup.py install,but the same issue happend
![Screenshot_2024-11-02_09_38_34](https://github.com/user-attachments/assets/32843681-d120-4638-8678-9df29d2f57fc)
![Screenshot_2024-11-02_09_38_40](https://github.com/user-attachments/assets/eb65f4aa-3953-4c46-9506-a8f5e6e9943e)

**Comment by dr1408** [comment]
pip3 install ConfigParser

**Comment by Art4Islami** [comment]
> pip3 install ConfigParser

Mate its not working i dont know why.Says something about a virtual somemthing dont know much of linux i do have a wn722n usb adapter if its needed
![Uploading Screenshot_2024-11-09_19_13_27.png…]()

**Comment by michael2to3** [comment]
Fixed a bug in my fork, a small problem with the new version of the library. I will open a new pr with a correction. In the meantime, you can use my fork: https://github.com/michael2to3/wifiphisher

**Comment by Art4Islami** [comment]
> Fixed a bug in my fork, a small problem with the new version of the library. I will open a new pr with a correction. In the meantime, you can use my fork: https://github.com/michael2to3/wifiphisher

I will now try thanks very much mate

**Comment by Art4Islami** [comment]
> Fixed a bug in my fork, a small problem with the new version of the library. I will open a new pr with a correction. In the meantime, you can use my fork: https://github.com/michael2to3/wifiphisher

Still no something else while figuring out with chatgpt 
![Uploading Screenshot_2024-11-12_17_14_35.png…]()
