### ISSUE TITLE
LastPass phishing

### ISSUE THREAD

**Issue by sophron** [wifiphisher/wifiphisher#198]
An interesting case that we could possibly add to our set of phishing scenarios: https://www.seancassidy.me/lostpass.html

The page seems ready and lies <a href="https://github.com/cxxr/lostpass">here</a>. One simply needs to integrate this to our software.

Proposed by @dionyziz.

**Comment by blackHatMonkey** [comment]
It's very interesting idea but it seems to rely on the user having internet access to show the banner.

**Comment by sophron** [comment]
@blackHatMonkey Routing Internet traffic from the rogue AP is in our TODO. :)

**Comment by blackHatMonkey** [comment]
@sophron 
I suggest creating a road map in the wiki.

**Comment by Labseb** [comment]
could you add this :
https://github.com/anttiviljami/browser-autofill-phishing

It could work with LastPass with the OAuth Login Page ;)

**Comment by sophron** [comment]
Scenario requests now go to our dedicated repo: https://github.com/wifiphisher/extra-phishing-pages
