### ISSUE TITLE
Use of aireplay-ng for deauthentication

### ISSUE THREAD

**Issue by sophron** [wifiphisher/wifiphisher#218]
We are currently using <a href="https://github.com/DanMcInerney/wifijammer">wifijammer</a> for kicking out the victims.

We should consider using `aireplay-ng --deauth` for doing the same thing (if installed on user's machine).

**Comment by kn0wledge** [comment]
That would be great. Because the jammer is currently not working at all for me

**Comment by blackHatMonkey** [comment]
I'm almost done with the re-design of the jamming and it should be pushed out within the next week or so after @sophron reviews it.
