### ISSUE TITLE
Provide Internet access to the victims

### ISSUE THREAD

**Issue by sophron** [wifiphisher/wifiphisher#270]
We should give the option to provide Internet access to the victims. Then, we can either:

1) Grab cleartext credentials (e.g. by leveraging <a href="https://github.com/DanMcInerney/net-creds">net-creds</a>).

2) Throw the phishing page at an unsuspecting time. (#263, #198).

**Comment by laozi999** [comment]
This would open the gates to crazy MITM attacks.

We should add `-nI` (net interface) to assign an interface that has internet access and set up iptables for that interface. I'm still trying to figure out the easiest way to only enable internet access after the wifi password has been entered, as it would be nice to get both the victim's WPA key **and** sniff the traffic.

Once the user is allowed internet access, it's simply a matter of running bettercap + DNS forwarding the more 'secure' websites.

**Comment by sophron** [comment]
Hi @laozi999,

We don't really need to set a third (net) interface. What we should do is create a virtual monitor interface out of one available interface and use that for jamming. The first interface can maintain the Internet connection.

In other words, with two physical wireless cards, our three interfaces would be:

wlan0 - Internet Connected
wlan1 - hostapd
wlan0mon - jamming (created out of wlan0)

I'm wondering if this is our best choice though. Can we spawn two virtual interfaces out of wlan0 for example? That way, the script will only need one physical card. @wraith-wireless can you let us know your opinion on this?

Now, regarding the phishing part, I would like users to be able to edit the `config.ini` file and adjust *where* and *when* the phishing page should come out. For example, a user should be able to set the script to show the phishing page after 300 HTTP requests or after 15 minutes of normal Internet browsing or only when the victim is requesting specific pages. I believe this will be the cover many different use cases.

**Comment by sophron** [comment]
I pushed a commit yesterday that introduces `--internetinterface` option. By using that option you specify an Internet connected interface that will provide Internet access to the connected victims. 

For the time being, this interface cannot be wireless.  I'm still trying to figure out the best way to isolate `NetworkManager`.

**Comment by sophron** [comment]
I'm closing this. For providing Internet from a wireless interface see #511.
