### ISSUE TITLE
Not Deauthenticating the target network

### ISSUE THREAD

**Issue by Marcelo-Manzano** [wifiphisher/wifiphisher#332]
**Version**: Wifiphisher 1.1GIT

**Distribution**: Kali linux 
Release: kali-rolling
Comand to see ther version: #lsb_release -a

**Summary**: I run the command: #wifiphisher 
and its not deauthenticating the target network (Notebooks, tablets, mobiles, Iphones and Androids accessing the internet withou problem).

If I run # aireplay-ng -0 0 ...... it works perfect fine, (deauthenticate everybody)

I got the external wireless card Realtek TP-LINK TP-WN722N
I got the onboard wireless card on my Dell inspiron mini10: RTL8101E/RTL8102E (#lspci | grep Ether)

When I first run #wifiphisher it was working perfect fine (it was a week ago) and I used wifiphisher a LOT on my 3 networks to learn more about your software.
and now it is not working anymore.

I realised that when you run the command: #wifiphisher 
it is not cleaning the infos (lease) about the last time you have runned the command

I know that this tool works perfect fine (it did). It might be just a stupid ajust and certainlly everything will be OK and I will keep this tool on on my pocket for the future.

I have seen a post/issue number #188 but it is not exactly the same problem I am soffering here!

Thanks guys!

**Comment by sophron** [comment]
There are a few optimizations that need to be done regarding jamming. I'll try to work on them soon.

**Comment by mdshehabaz** [comment]
Same issue I m also facing, I got the external wireless card Realtek TP-LINK TP-WN722N
I got the onboard wireless card on my Dell inspiron .

**Comment by chikehenderson** [comment]
Jamming issues ...

**Comment by dumper93** [comment]
You have to start airmon-ng on the non-ap-device. Than jamming works.
