### ISSUE TITLE
duplicate of #341

### ISSUE THREAD

**Issue by mcy260** [wifiphisher/wifiphisher#351]
Any idea how to make this work?

I'm using a nexus 5  with TL WN722N   running  AOPP (Android Open Pwn Project)
http://i.imgur.com/AcEioYf.jpg

**Comment by mcy260** [comment]
<img src="http://i.imgur.com/AcEioYf.jpg">

**Comment by PJF16** [comment]
Should be the same as here. No solution found by now.

https://github.com/sophron/wifiphisher/issues/341

**Comment by mcy260** [comment]
who is the developer?

**Comment by mcy260** [comment]
@sophron is there a way to run this on the nexus 5?  Could you suggest what kind of changes do i have to do in order to make this work on the phone?

**Comment by sophron** [comment]
@mcy260 I have never tried it myself and I doubt it will work due to peculiarities of the kernel.

@wraith-wireless may be able to give a more clear answer.

**Comment by mcy260** [comment]
@sophron  what about raspberry pi? its about the hardware or just the kernel? 
Is not working with AOPP (Android Open Pwn Project) but i  tried with kali nethunter and i got the same issue.... is a hardware thing?

**Comment by PJF16** [comment]
I think it's because of the different architectures of the processors (x86/x64 vs ARM)

**Comment by sophron** [comment]
I am not sure how these kernels handle netlink operations.

People have made it run under Raspberry PI. Check for example, <a href="https://github.com/secgroundzero/warberry">Warberry</a>.

**Comment by whithecasper** [comment]
This work fine in raspberry pi. I'm using with a kali linux arm distro and have no problems.

**Comment by djdisikd** [comment]
How did it work in android smartphones if they have only one wireless network adapter?

**Comment by PJF16** [comment]
With external wireless adapters. ;-)

**Comment by djdisikd** [comment]
Where to buy the most affordable external wireless adapters for smartphones?

**Comment by PJF16** [comment]
I bought this one twice for 8€

https://www.amazon.de/TP-Link-TL-WN722N-High-Gain-Antenne-WLAN-Empfang-unterstützt/dp/B002SZEOLG/ref=sr_1_fkmr0_1?ie=UTF8&qid=1476896860&sr=8-1-fkmr0&keywords=tp+link+wn+722

**Comment by mcy260** [comment]
is there a way to make it work? any suggestion or alternative? I had the same external wireless adapter TP-Link TL-WN722N

**Comment by djdisikd** [comment]
Unfortunately, this wireless adapter is for windows only.

**Comment by PJF16** [comment]
@djdisikd That's not true. It works like charm on my Kali Linux Notebook and on my Nexus 7 with Nethunter. It has the Atheros chipset and this driver and firmware is included in the Linux Kernel.

**Comment by mcy260** [comment]
@PJF16 it works on Nexus 7???? Wow, but how??

**Comment by PJF16** [comment]
@mcy260 Yep without any issues. Just plug it in and then type ifconfig wlan1 up in the Kali Terminal.

**Comment by mcy260** [comment]
I'm using Android Open Pwn Project (Pwnie Express) not Kali, but is based on Kali, for some reason i got those errors on my Nexus 5.  
 BUT if  its working on your nexus 7, it means that is not a kernel problem

**Comment by djdisikd** [comment]
I need additional cable to plug it in the smartphone?

**Comment by strasharo** [comment]
You'll need an OTG adapter.

**Comment by djdisikd** [comment]
Just plug it in and done?

**Comment by mcy260** [comment]
@djdisikd  

http://i.ebayimg.com/images/i/201536977655-0-1/s-l1000.jpg

![](http://i.ebayimg.com/images/i/201536977655-0-1/s-l1000.jpg)

**Comment by djdisikd** [comment]
Ok.

**Comment by laozi999** [comment]
I am having issues installing `firmware-atheros`, or any package on nethunter. I think it has to do with the process id of apt. Nethunter isn't that compatible with Nexus 5 yet.

**Comment by blackHatMonkey** [comment]
If you would like to continue this discussion please use #341.
