### ISSUE TITLE
HTTPS problem with redirecting victim

### ISSUE THREAD

**Issue by cicina** [wifiphisher/wifiphisher#392]
Hello im using latest version of wifiphisher. 
Using Kali Linux

There is a problem redirecting victim from HTTPS websites. 

Redirecting victims from HTTPS websites not working. Redirecting from HTTP is working perfectly but with HTTPS every browser show a warning to the victim, that website is trying to use fake HTTPS certificate and this happened mostly because of attackers who try to steal credit cards or other credentials. Not really a message we want them to see. (cmooon we just want wifi right? we r not that bad) 
anyway.. I have been using wifiphisher about 9 months ago and it was alright. Do you guys have same issue? I have seen similar topics but it was closed and issue still here :/ 

Question 2: is possible use airmon-ng for deactivating users within same PC? I know wifiphisher uses different script for the job but I would like to use something more aggressive like 100% disconnecting exact same mac address, not all of them in a loop. I know its possible to skip mac address but I think 9 months ago it was easier to attact exact same person. 

Question 3: Which network card is better for deactivating and which one for creating fake AP? I use strong alfa external and intel internal one. 

Consider question 2 and 3 less important :) 

Now I also want to thank you for your hard work Sophron and all of you who helped. Its an excelent piece of software with great idea. I just love wifiphisher. I am a big fan. I even copied Virgin Media router page to use with wifiphisher (9 months ago) and I can make it public. Of course it needs to be updated but it works. 

Now problem is https and I want to get it work again please :P :P 

**Script output**: Paste the output of the tool, including any stack traces.

**Comment by laozi999** [comment]
**Question 1**
Have you changed browsers in those 9 months?

This is exactly the point of HTTPS, to warn the user when they are forced to see a captive portal page. When a user tries to access an insecure site (HTTP), wifiphisher will detect this and instead redirect the user to your captive portal.

Some browsers show the user a warning, other browsers simply show an error.

**Question 2**
I'm not sure what you mean. If you want to run wifiphisher and kick everyone off their wifi (deauthenticate) at the same time, you will need 2 interfaces. TP-Link has [a very cheap USB adapter](https://www.amazon.com/TP-Link-N150-Wireless-Adapter-TL-WN722N/dp/B002SZEOLG/ref=sr_1_3?srs=2530652011&ie=UTF8&qid=1483693083&sr=8-3&keywords=usb+adapter) that works out of the box on Kali.

You can deauthenticate with the built in jamming function in wifiphisher, or you can use `aireplay-ng`, although personally, I prefer to use mdk3.

`mdk3 wlan2 d -w /root/whitelist.txt`

Explained:

`mdk3 [interface] [deauth] [whitelist] [/path/to/whitelist.txt]`

This will kick all users off every wifi network, except for the MAC addresses listed in `whitelist.txt`, you can also target one or more BSSID by using the blacklist option instead (`-b /root/blacklist.txt`)

**Question 3**
This depends on what you're trying to achieve, but usually the better your wireless card, the more effective your attack will be. You want a strong signal for both the access point and deauthentication. Try researching which wireless adapters allow you to increase `tx-power`, which is basically the setting for how 'loud' your wifi signal will broadcast.

**Comment by cicina** [comment]
Thank you for answers, especially for question 2 and 3. 

Now im running old version of wifiphisher which is available in kali repositories v1.1 and https redirect is working just fine. No matter what victim types, it will redirect to our phishing scenario. In new version of wifiphisher, it will work only with http :( I have no idea why it was working and now its not. Btw warning shows most popular browsers, tested on safari ipad, firefox android and google chrome android different device. G chrome will tell you even before you open new tab!

**Comment by cicina** [comment]
No I haven't changed browser, I still use firefox. Mobile, pc, doesnt matter its still firefox. Ofc just newer version.

**Comment by laozi999** [comment]
Hmm, strange. Are you running wifiphisher v1.1?

**Comment by laozi999** [comment]
try accessing 'https://www.paypal.com' (including the https://) using your current version of wifiphisher and let me know if it shows an error.

**Comment by cicina** [comment]
Well, my bad. You are right, https://paypal.com not working. I dont know what I was thinking. 
Still v1.1 is working better with deauthenticating clients and/or AP. 
is there any hope for future to work with https? Or is it clearly impossible?

**Comment by laozi999** [comment]
No worries, most browsers tend to remember which sites use HTTPS and will automatically send you to the secure page. When you clear your history, and type 'youtube.com' without the 'https://', chances are that you are first taken to the non-secure (HTTP) page.

Your browser knows that when it sends a request and gets redirected to a captive portal, the connection is insecure, and will show the user a warning most of the time (depending on the browser).

Your best chance (for now) is to wait until the user tries to access a HTTP link. Which is more likely to occur after their browser history is cleared.

A way to bypass HTTPS would be to perform a karma attack and enabling internet access on your access point (requires a strong antenna signal). From there you basically have full control over traffic. This could still trigger a warning on Macs (and maybe other OS) which alerts the user that their network no longer has a WPA key.

**Comment by laozi999** [comment]
It'd be a nice addition to wifiphisher to enable internet access and runnig bettercap. This could act as a traffic vacuum when performed with a karma attack.

**Comment by cicina** [comment]
Thank you for excelent explaination. 
Yes that is what made me think its working with https. I tried to access youtube or other site which resulted with accessing non https variant of website first which was redirected successfully. 
Also spoofing dns is awesome but implement such thing in wifiphisher would be hardcore. Looking forward xD thank you for your time i got that all for now.

**Comment by cicina** [comment]
However, if web browser shows warning, its impossible to continue and thats mean less change to trick victim :(

**Comment by cicina** [comment]
BUT! Most modern os such as IOS will show our scenario right after connecting to wifi which is good.

**Comment by laozi999** [comment]
You can definitely use the captive portal pop-up screens on Macintosh and iOS to your advantage.

I have used the iOS captive portal pop-up to trick the user into thinking that it's the password page:
(I will release this phishing scenario shortly!)

[https://github.com/sophron/wifiphisher/issues/238](url)

![2](https://cloud.githubusercontent.com/assets/24898383/21720264/389ec17a-d476-11e6-96ef-ce9c3b3c2ee0.png)

Macs tend to show a large, centered pop-up window which you could basically turn into whatever you like (updates, warnings, apps, etc..) :)

And of course.. You can disable these pop-ups by [adding `captive.apple.com` to your hosts file](https://community.ubnt.com/t5/UniFi-Wireless/captive-portal-amp-apple-popup-window/td-p/494153).

**Comment by cicina** [comment]
laozi999 IOS pop up scenario is briliant, I can't wait to try it . :+1:

**Comment by cicina** [comment]
I ve been thinking.. is there a way to implement sslstrip to force victim open non https website even if they have https variant cached? Since our AP is without internet connection, im not sure if thats possible. What do you think?

**Comment by niicee** [comment]
Testing lastest great tool wifiphisher on Kali 2016.1/2016.2 on USB persistence with laptop/desktop PC. 
Wifi Interface :  Ath9, Ath5, RTL8187 USB and RT2870 USB

I have most similar issues as what Cicina indicated above. Most of problem is fake page NOT pops up at all. I recall it is about 10% of time it works. Windows 10 is worse, nothing works once.

Sometime not is it because those wifi card/usb that I use but they are suppose to compatible with Linux. Such as RTL8187, it is capable of injection 100% using aireplay then sometime wifiphisher reported not capable -jI , so is the RT2870, I am sure sure it is okay for AP mode (because its windows driver even offers AP mode under windows), but it failed under -aI switch. Windows based browser fails most of time however, it works nice in cell browser a couple times.

Fake AP does created most of time and after connected to fake AP, I see it obtained IP (10...). It just no page pops up for victim input. What possibly be the problem. There are lot of victim AP might still have PC hooks with these days.

**Comment by sophron** [comment]
@niicee This is how SSL works. Read @laozi999 answer. You would get the same behavior in a hotel with a captive portal. 

To check if your cards are compatible, type `iw list` and look for "Supported modes" section.

**Comment by niicee** [comment]
Thanks for the suggestion. After many tries, I finally know the RT2780 works for AP master mode and RLT8187 for injection (some router were not injectable). Have tried 20~30 times, each every time when I have jamming the target AP, its client(s) NEVER willing to connect to the fake AP (see no IP giving away and I assumed this is what phiphing means !!!).
When I intentionally connect to the fake AP, I have encounted...
1) if I was surfing on a HTTPS site, then the fake router firmware update page never pops up AND worse is it actually warning the user it is NOT safe, sure the fake router firmware update is in HTTP rather the than HTTPS
2) if I was at a HTTP site, then refresh screen will works as expected...good !
3) the -qS switch is working good
4) the display (right upper conner) shows incorrect AP. It is different than I specified in -aI and -jI (sometimes very confuse)
5) wish there are more phishing pages available such as simply a Connection Reset and requires WPA/WPA2 input. It is logical and effective as client's AP is jammed.

Very interesting idear and tool. Please keep up the good works....cheers.

**Comment by niicee** [comment]
Ops...one more thing...does wifiphisher capable of providing/indicates if there is any client(s) currently connecting to its AP when pull out the AP list ? We actually NEEDs client to be present for phiphing a particular AP, if there is no client connecting to a AP then there is no point of testing that AP for the moment.

**Comment by Cris90sb** [comment]
it's useless if we're not connected to the victim's router. If you are not connected as I told you, make the attack on yourself: D
