### ISSUE TITLE
Nothing jamming

### ISSUE THREAD

**Issue by mcocigra** [wifiphisher/wifiphisher#423]
The program start you can choose the network but then there isn't anything jamming or leasing
![img_20170124_171316_2](https://cloud.githubusercontent.com/assets/25259626/22256303/a0083dd6-e25a-11e6-9824-e2d140571a7f.jpg)

**Comment by mcocigra** [comment]
I know for leasing there needs for someone to connect but for jamming it should at least jam the router of the selected network

**Comment by djdisikd** [comment]
Yeah, this happens to me too, I don't know why.

**Comment by mcocigra** [comment]
Is there a solution I think it's something with wlan1 interface because you can connect to the fake network it just isn't jamming anything

**Comment by sophron** [comment]
I'm currently working on providing the victims with Internet access. I'll push fixes to jamming right after. Expect them within the next two-three weeks.

**Comment by mcocigra** [comment]
Nice. But I don't think really necessary for the internet access and how will it work would we need 3 cards because one for jamming and one for fake. I personally use it for getting the wpa or wpa2 password. If you could please fix the jamming issue and if you can make the first scenario mobile friendly. Because the second scenario is less believable people don't usually upgrade things they don't understand

**Comment by sophron** [comment]
Update to the latest revision and let me know if you are still having any issues.
