### ISSUE TITLE
Additional AP List Info

### ISSUE THREAD

**Issue by zero77** [wifiphisher/wifiphisher#431]
Can you add more information on the each APs in the list.
For instance, the signal strength of each AP and number of devices connected to each AP (if known).
Thanks,

**Comment by mcocigra** [comment]
That would actually be helpful. And making the first scenario mobile friendly.

**Comment by kn0wledge** [comment]
very helpful in identifying if you are within range for the rogue access point to be effective ;)

**Comment by sophron** [comment]
There's a PR in progress introducing signal strength. 

We could probably estimate the number of active devices in a network. I'm putting the "Enhancement" label. However, this is not something that we will work on in the near future.

**Comment by alternatexp** [comment]
You can see which networks are most active by using `airodump-ng <interface>` and looking at the `#Data,` column.

**Comment by blackHatMonkey** [comment]
@alternatexp This has been implemented in #470 which shows the number of connected clients.

**Comment by alternatexp** [comment]
@blackHatMonkey oh nice! I thougth this issue was still open :)

**Comment by blackHatMonkey** [comment]
However the PR is still has to be tested and approved by @sophron.

**Comment by blackHatMonkey** [comment]
@zero77 A new patch has been released that includes this feature requested by you, please update.

**Comment by zero77** [comment]
Thank you.

**Comment by blackHatMonkey** [comment]
Since there are no problems with issue, I'm closing it. If you have any issues or comments feel free to open it again.
