### ISSUE TITLE
MAC Changes Support

### ISSUE THREAD

**Issue by zero77** [wifiphisher/wifiphisher#432]
Can you add inbuilt support for Mac changer so that the MAC address of each wireless card is spoofed before the deal authentication process and fake APs are started.
MAC address changer is installed by default in Kali LINUX.
Thanks,

**Comment by laozi999** [comment]
You can use **airodump-ng** to monitor networks for activity, and then target them.

**Comment by sophron** [comment]
PyRIC provides methods for changing the mac of a vif. We should leverage that.

**Comment by anakin1028** [comment]
@zero77 we have this future now. You can clone with the latest version of `wifiphisher` and default we will randomize mac address. You can also specify the mac address you want by the option `-iAM` and `-iDM`
