### ISSUE TITLE
Output bug

### ISSUE THREAD

**Issue by mcocigra** [wifiphisher/wifiphisher#441]
![img_20170208_171358_1](https://cloud.githubusercontent.com/assets/25259626/22746638/c54c1f38-ee24-11e6-8ac0-4150b0e8858b.jpg)
I was using the solution we had for jamming with aireplay and I think it actually works just on the output this is what I get

**Comment by cicina** [comment]
I can see you have created AP with wlan0. Aren't you using wlan0 for aireplay already?

**Comment by cicina** [comment]
really strange output though o.O

**Comment by mcocigra** [comment]
No I tried it creating with wlan0 and with wlan1 and opposite for jamming

**Comment by cicina** [comment]
Well, i would not really bother with outputs.. look at mine (same activity, jamming with aireplay and wifiphisher with -nJ option) so.. there is something wrong with that idk what. But jamming is alright and also fake ap is working right?

http://imgpost.me/img/p/jpg/2inIRLRdEKXyBRebTVq1JT8ge8Vx8WeY.jpg

**Comment by blackHatMonkey** [comment]
@cicina @mcocigra You could get better screen shots using the `Prt Scrn` button right next to `F12` key or using `screenshot` application in Kali. This will help us diagnose the problem faster.

@cicina Also it would be easier to upload the images directly to Github by just drag and dropping it in the comment section.

**Comment by cicina** [comment]
Sorry mate, i have uploaded in my threat, this was taken by phone as I dont have internet connection on my PC while jamming. Also, I do use NoScript everywhere so this drag and drop functionality is not available for me sorry about that.

**Comment by blackHatMonkey** [comment]
Another example that I ran today while testing is this:

![test](https://cloud.githubusercontent.com/assets/25112506/22865586/5c39b8f2-f135-11e6-8e44-ed4d3a8c3297.gif)

**Comment by mcocigra** [comment]
Yes something similar happen to me the screen was flickering you just can capture it with a picture

**Comment by blackHatMonkey** [comment]
After some testing the flickering happens due to the size of the terminal. This happens because currently the row numbers are hard coded and therefore if height of the window is less that a specific number it causes this bug.

**Comment by blackHatMonkey** [comment]
A new patch has been merged. It does not fix the entire problem however it requires the minimum number of rows to work. If you experience [this](https://github.com/wifiphisher/wifiphisher/issues/441#issuecomment-279244680) behavior all you need to do is increase your terminal size.
