### ISSUE TITLE
Why does the tool not stop working if it gets a password ?

### ISSUE THREAD

**Issue by dumper93** [wifiphisher/wifiphisher#446]
Hello,

why does the tool not stop for a specific client mac if it gets a password ?

It's very suspect and weird, when the firmware upgrade is successful and the upgrade page comes up again.

Best regards

**Comment by sophron** [comment]
This is not the default behavior. Most users want to keep the attack going even after receiving a password.

Use `-qS` or `--quitonsuccess` to stop the script after getting a password.

**Comment by dumper93** [comment]
Is the command mac specified ?

**Comment by sophron** [comment]
I'm not sure I understand what is the "command mac".

**Comment by dumper93** [comment]
If a user joins the wifi network with a specific mac and inputs a password it stopped the service and he gets disconnected ?

**Comment by sophron** [comment]
The script terminates; the AP goes down and the attack completely stops.

**Comment by dumper93** [comment]
But its fail, if it works so, because if someone joins the open ap who are not the owner of the original ap and input an incorrect password. You have to start it again and again.

**Comment by cicina** [comment]
well, that is just a bad luck, i would say :P

**Comment by blackHatMonkey** [comment]
@dumper93 I believe the question has been answered, if not, feel free to re-open :smile:.
