### ISSUE TITLE
Deauthenticaton to broadcast fails if no client is found

### ISSUE THREAD

**Issue by andeees** [wifiphisher/wifiphisher#449]
I am using the Latest version in Kali Linux. The problem is the following: The fake access point created doesn't appear to have internet connection, and for example in android it says that it doesn't connect automatically. Is there any way to have connection? And it doesn't kick really people out of the network, and I am using the latest version, anyone else having the same problem? I heard this update improved that matter, thanks.

**Comment by blackHatMonkey** [comment]
Hi @andeees Can you show us what command are you running from the terminal?

**Comment by andeees** [comment]
@blackHatMonkey hey, I am running just wifiphisher. The problem is that jamming doesn't really de-auth the broadcast (I have also tried "-d" direct) and also didn't work. The second problem is that when I run wifiphisher -iI (ethernet adapter) it doesn't give me any error and, but still no internet connection. My main inquiry is how to fix the de-auth problem, (btw: I am ussing 1 template, but shouldn't matter right?)

**Comment by andeees** [comment]
And also, I don't know if this helps but, whenever I first start wifiphisher (after restarting the PC) it gets stuck at wlan1
```
wlan0
lo
tun0
eth0
[+] Selecting wlan1 interface for the deauthentication attack
[+] Selecting wlan0 interface for creating the rogue Access Point
[*] Cleared leases, started DHCP, set up iptables
```
I have to Ctrl + c to close it and after that it doesn't happen. Maybe is a problem with initializing the antennas.

**Comment by alternatexp** [comment]
Try using `mdk3` in the meantime to deauthenticate clients.

**Comment by blackHatMonkey** [comment]
@andeees I was able to reproduce the bug where deauthentication to broadcast was not being performed when no clients where found. A new patch will be pushed soon to solve this issue. As for it get stuck after `Cleared leases` issue #470 will solve it after it's approved.

**Comment by blackHatMonkey** [comment]
@andeees  A new patch has been released please update and see if the problem persists.

**Comment by blackHatMonkey** [comment]
This bug has been solved and there are no problems after the patch release. I'm closing this now but if you encounter the bug again feel free to open the issue.
