### ISSUE TITLE
could not find scenario

### ISSUE THREAD

**Issue by cicina** [wifiphisher/wifiphisher#456]
Hello, I am having a problem with wifiphisher.. If I run just wifiphisher without any arguments, it runs with errors (but it runs) described here https://github.com/sophron/wifiphisher/issues/439

But if I add arguments like -qS or -p 5 or any other, script stops before i am able to pick up scenario and it says scenario could not be found and there is name of the scenario too (even I didn't pick up one yet)
So.. basically I can't use any arguments.. I can only run tool as it is. Please do you have any idea what is going on? I have reinstalled wifiphisher recently because of merged files which btw works great now. 

I had this problem (arguments with wifiphisher) also before, but it occurred only with -qS or -p option. Now it happens with any.

**Comment by blackHatMonkey** [comment]
Well if you use the `-p` option, you are telling `Wifiphisher` to skip the interactive scenario selection. Another suggestion is to just download the files via web browser and run it locally like so:
```bash
python bin/wifiphisher
```
instead of installing it and see if the problem still remains.

**Comment by cicina** [comment]
Well, yeah I know what -p stands for.. anyway, I always run tool from directory. I have installed v1.1 for testing purposes and new version I only run from /bin folder. Damn why my copy is always that broke one

**Comment by sophron** [comment]
Hi @cicina,

I'm not sure I understand the problem. Are you using the latest revision? Do you have problems with `-qS`?

**Comment by cicina** [comment]
Well, i will explain step by step what is going on.. when i start wifiphisher (latest, updated cloned from git) it will run but no AP's are shown. I have to stop script ctrl+c and run again which brings AP list correctly now. However if I use any arguments for example -p or -qS or any other, including -nJ or -e or whatever.. it will crash 6 times out of 10. I have to stop and re-run script each time. Error is usually that scenario not found or similar.. dont remember, its a quite mess. Even if I use -p option, it will never allow me to use preffered scenario, it will always crash so I dont use it since I can choose scenario on my own in script menu. Also, my alfa adapter is blinking when hostapd is working and wifi is spawned. So I know exactly when it is working or not. And I have to say wifi rogue AP sometimes stops but wifiphisher show no error and keep going like nothing happened. Thats it hopefully u got picture. 
Need to say: it works fine.. i have to restart script but afterwards it works. So its not an "urgent" thing to do but still important enough to not ignore. Cheers

**Comment by cicina** [comment]
Well, i will explain step by step what is going on.. when i start wifiphisher (latest, updated cloned from git) it will run but no AP's are shown. I have to stop script ctrl+c and run again which brings AP list correctly now. However if I use any arguments for example -p or -qS or any other, including -nJ or -e or whatever.. it will crash 6 times out of 10. I have to stop and re-run script each time. Error is usually that scenario not found or similar.. dont remember, its a quite mess. Even if I use -p option, it will never allow me to use preffered scenario, it will always crash so I dont use it since I can choose scenario on my own in script menu. Also, my alfa adapter is blinking when hostapd is working and wifi is spawned. So I know exactly when it is working or not. And I have to say wifi rogue AP sometimes stops but wifiphisher show no error and keep going like nothing happened. Thats it hopefully u got picture. 
Need to say: it works fine.. i have to restart script but afterwards it works. So its not an "urgent" thing to do but still important enough to not ignore. Cheers

**Comment by cicina** [comment]
Sorry i didnt want to close topic if you could remove one of my previous comment would be great sorry for that my phone is odd

**Comment by cicina** [comment]
@blackHatMonkey thanks for assist :))

**Comment by blackHatMonkey** [comment]
Hi @cicina I have experienced this bug so I know how frustrating it is to keep restarting the program :cry: . Check back in a week or so as I'm working on a major re-design for the access point selection.

**Comment by cicina** [comment]
@blackHatMonkey glad to hear that. at least I dont feel like from different planet :D thanks for quick replies guys appreciate you are taking care of such things.

**Comment by blackHatMonkey** [comment]
@cicina You can reach me at `blackHatMonkey` in `freenode` IRC.

**Comment by kn0wledge** [comment]
guys i started having the same issue. I didnt have that issue before when I just cloned it from git. however when I ran the install command and it "installed" then whenever I reach the scenario selection (after AP selection) I get this error:

> [+] Choose the [num] of the AP you wish to copy: 2
Traceback (most recent call last):
  File "/usr/local/bin/wifiphisher", line 11, in <module>
    load_entry_point('wifiphisher==1.2', 'console_scripts', 'wifiphisher')()
  File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.2-py2.7.egg/wifiphisher/pywifiphisher.py", line 779, in run
    template = select_template(args.phishingscenario)
  File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.2-py2.7.egg/wifiphisher/pywifiphisher.py", line 382, in select_template
    template_manager = phishingpage.TemplateManager()
  File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.2-py2.7.egg/wifiphisher/phishingpage.py", line 241, in __init__
    self.add_user_templates()
  File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.2-py2.7.egg/wifiphisher/phishingpage.py", line 295, in add_user_templates
    local_template = PhishingTemplate(template)
  File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.2-py2.7.egg/wifiphisher/phishingpage.py", line 63, in __init__
    self._display_name = info['name']
KeyError: 'name'
> 

I removed it with the rm command and then re-cloned from git, and I still get the error now... what is the error cause ?

**Comment by cicina** [comment]
Hi there, I have installed wifiphisher on different user account and it is working without any errors. Even arguments are working. Everything is okay. I still dont know tho why my 1st install get so wrong. and it is still unusable for me. At least its working under another user but anyway.. i am afraid it will happen again

**Comment by blackHatMonkey** [comment]
@kn0wledge the bug you posted [here](https://github.com/wifiphisher/wifiphisher/issues/456#issuecomment-283306597) is not related this thread. If you experience the same problem please feel free to open a new issue.

**Comment by blackHatMonkey** [comment]
@cicina A new patch has been released please update and see if the problem persists.

**Comment by blackHatMonkey** [comment]
I'm closing this issue since the bug has been fixed and there are no issues afterward.
