### ISSUE TITLE
Upgrade wifiphisher

### ISSUE THREAD

**Issue by serpunja** [wifiphisher/wifiphisher#457]
Hello!
My smartphone - Nexus 6 
Nethunter - nethunter-shamu-lollipop-3.0.zip
Tried different Interfaces: awus051NH v.2, awus036H, WN722N and WN821N.
I do not know what to do with the error "pyric.error: [Errno 1] Operation not permitted" !

Hopefully wifiphisher v1.2 on Nethunter will work correctly
**Please tell me how to update wifipnisher?**

**That's right?  # _apt-get_ _upgrade_ _wifiphisher_**

**Comment by blackHatMonkey** [comment]
@serpunja `Wifiphisher` is currently **not** compatible with `Nethunter`. The project's target os is `Kali` and therefore we are unable to help you.

**Comment by serpunja** [comment]
Damn!
A lot of time spent to correctly working wifiphisher.
There was hope.
Here is an example: 
![1](https://cloud.githubusercontent.com/assets/24878620/23103444/6be0cf60-f6cc-11e6-8f03-fd071b898381.jpg)
![2](https://cloud.githubusercontent.com/assets/24878620/23103446/7076fab8-f6cc-11e6-987e-b1bef8f882d2.jpg)
![3](https://cloud.githubusercontent.com/assets/24878620/23103449/88181f6c-f6cc-11e6-8912-b4ac85927baf.jpg)
What is the point - wifiphisher, if you can not put in your pocket !?
Sorry.
Shanks, **blackHatMonkey**

**Comment by kn0wledge** [comment]
How did you do it ? @serpunja

**Comment by serpunja** [comment]
@kn0wledge How did you do it ? :
+1: 
1) # git clone https://github.com/sophron/wifiphisher.git
2) # cd wifiphisher/
3) # python setup.py install
4) # wifiphisher
**Wifiphisher is currently not compatible with Nethunter.** ((
Wifiphisher WORKS on NetHunter, but the curve.
fucking error!

**Comment by blackHatMonkey** [comment]
If you would like to discuss anything regarding `Nethunter` please use #341.
