### ISSUE TITLE
Run a fake page on MANA-toolkit

### ISSUE THREAD

**Issue by serpunja** [wifiphisher/wifiphisher#458]
Hello!
My smartphone - Nexus 6
Nethunter - nethunter-shamu-lollipop-3.0.zip
I want to do the following: What would connect to the fake point, client in a moment got my written html page (localhost).
For example: To connect to the WiFi please log in through your email or social network ...... :).

Please.
Tell me **where** (on a line), and **how** to edit the script **start-nat-simple-lollipop.sh** ?

**Comment by sophron** [comment]
Hi @serpunja,

I believe you'll have more luck posting on <a href="https://github.com/sensepost/mana">this page</a>.

**Comment by serpunja** [comment]
O.k.
