### ISSUE TITLE
Clients not automatically connecting to fake AP.

### ISSUE THREAD

**Issue by andeees** [wifiphisher/wifiphisher#461]
Using version 1.2 in kali linux, the clients that are de-auth don't reconnect automatically to fake AP. In android it says ("No internet connection, and won't reconnect automatically") This should be solved by providing internet? I tried -iI eth0 and no error showed but no internet. Is there anyway to solve this?

**Comment by mcocigra** [comment]
What scenario are you using maybe it isn't mobile compatible. Try the second one it should show up the upgrade page

**Comment by blackHatMonkey** [comment]
@andeees The clients will not automatically connect to our access point and the user has to connect to it manually. Regarding the internet I just tried it and it acts like if you are connected to the real access point(doesn't show any scenario pages).

**Comment by andeees** [comment]
@blackHatMonkey But many times the fake AP is flagged not to have inter connection, maybe if it did have would automatically re-connect? I tried to solve this problem by connecting an ethernet cable and using the -iI option but it simply appeared the same message (Won't automatically re-connect (No Internet access detected)) Maybe it is an issue? 
Wireless connection to the internet won't work since wifiphisher disables the service `network-manager`.

**Comment by blackHatMonkey** [comment]
Thats not how it works. For a device to connect automatically it has to have been connected to it previously. Although the `fake AP` has the same name as the original, it has a different encryption type and therefore the see it as a different access point. @sophron might be able to provide more information regarding this situation.

**Comment by kn0wledge** [comment]
Yeah I have the same issue. Successfully Jamming , but not autoconnecting to the Fake AP. Have to connect to it manually which defeats the purpose. Not sure why this is the case

**Comment by kn0wledge** [comment]
@blackHatMonkey actually the more I test around, the more I find this feature (Auto-join fake AP) a must have. with this feature, you will not even notice you got disconnected, hence all scenarios have a much higher chance of success. I recommend opening a new thread with this as an enhancement. It is feasible, I would recommend you look at the code of the Pineapple AP from the wifi pineapple. what it is does is basically beacon a response to mimics the original router hence getting auto association with its fake ap. hope that helps.

**Comment by blackHatMonkey** [comment]
@kn0wledge We already have thread for this and it's #76.

**Comment by andeees** [comment]
@kn0wledge Do you have WiFi pinapple? Did it work its karma attack? I read that this attack is very unlikely to happen in new computers and smartphones ... but I can't find much information on the topic.
