### ISSUE TITLE
Add a full website with multiple static pages as a phishing scenario

### ISSUE THREAD

**Issue by alternatexp** [wifiphisher/wifiphisher#463]
Why is there a static folder and why do users only get to see index.html?

Why doesn't it just send users to `http://10.0.0.1:8080/` and let the attacker decide how the site functions?

Right now, if the URL path contains "/" (which it always does) it gets forced to the index.html page... Why? 

I don't see how this is useful, it seems rather limiting to me.

**Comment by alternatexp** [comment]
most public networks have a captive portal.

How much better would wifiphisher be if we could simply copy those captive portal sites and paste them right into wifiphisher? (using curl or httrack for example)

**Comment by alternatexp** [comment]
or heck, just press CTRL+S on a page

**Comment by alternatexp** [comment]
and if you don't think so, could you please tell me how i can achieve this without creating silly redirection rules based on self.request.path?

**Comment by alternatexp** [comment]
`self.render(self.request.path, ...` doesn't work

**Comment by blackHatMonkey** [comment]
@alternatexp If I understand your question correctly you are asking on how to use a scenario where you have a custom captive portal. There is **NO** need to modify the internal code. All you have to do is save your desired page and all the required files in a folder and place it in the `/wifiphisher/data/phishing-pages` directory. Install the tool again or run `bin/wifiphisher` and select your custom scenario in the selection part. Also your main page has to be named `index.html` and the name of the password input must be `wfphshr-wpa-password`. An example of this would be:
```html
<input id='password' type='password' name='wfphshr-wpa-password' />
```

**Comment by alternatexp** [comment]
are you serious?

No, you're entirely misinterpreting my question...

Wifiphisher is set up so that it ONLY works the way the current pages are structured, which are not that good to begin with...

There are MANY captive portal pages all around the world from different ISPs, hotels, apartments, etc...

Wifiphisher could set the standard of WPA & credential phishing frameworks if it were not so limited. Programmers ourselves can combine things like httrack and use it just like the SET (Social Engineering Toolkit) does.

There is absolutely no need to tie yourself to a /static folder as is done inside the python code of wifiphisher. It is very bad practice and simply limits the capabilities of this powerful tool.

https://github.com/wifiphisher/wifiphisher/issues/464
Referencing my other post here as it is on a similar topic.

**Comment by alternatexp** [comment]
@blackHatMonkey said:

> All you have to do is save your desired page

I am not talking about a single page, but an entire site. Wifiphisher is literally limited to one index page only...

**Comment by sophron** [comment]
Hi @alternatexp,

We haven't found any users requesting this and our current scenarios are not requiring it. I can surely imagine many use cases for this though, that's why I added the "enchancement" tag.

Please, be more friendly in your messages. Expressions like "Are you serious?" do not fit with our <a href="https://github.com/wifiphisher/wifiphisher/blob/master/CODE_OF_CONDUCT.md">Code of Conduct</a>.

**Comment by alternatexp** [comment]
You haven't found any users because most of then are trying to get their neighbours WPA passwords by hoping that they will fall for some random router page or OATH login.. If the victim is not stupid, he/she will notice something's up. (good hacking is done unnoticed)

Hotels, airports and most public networks on the other hand, are already using a captive portal. Simply replicating the original captive portal page would yield such a high success rate because people within your range won't have a clue of which is the real captive portal and which one is the fake.

Please don't take offense with what I say, I might sound a little confused and frustrated because I don't understand this type of reasoning/lack thereof. Simply redirecting to http://10.0.0.1:8080/ and letting the attacker operate the sites would solve all problems and on top of that, allow many, many, MANY more scenarios.

You will never hear me say "So what.. It's good-ish already..."

I want to see this tool as powerful as it can be.

I am happy to contribute and all I'm saying is that I see a world of potential for wifiphisher.

(long story short, redirecting to the scenario directory instead of the index page and listening to all POST requests would unlock the gates)

**Comment by alexsalvetti** [comment]
HI @alternatexp, I think that what you are looking for is a sort of what Bettercap ( https://github.com/evilsocket/bettercap ) does.
So I think you are talking about doing a MITM when a victim connects to the evil twin and then give him internet connection while sniffing the username and password that he writes.
Am I right?

**Comment by alternatexp** [comment]
Hi @alexsalvetti 

No, that is not what I'm saying, please read what I said.

> (long story short, redirecting to the scenario directory instead of the index page and listening to all POST requests would unlock the gates)

As of right now, Wifiphisher can only show the victim 1 index page (which has to be structured with a static folder), and only listens to POST requests sent to a `/post` folder. I am saying that this is limiting, and I strongly advice removing these conditions as much more could be achieved with Wifiphisher.

@alexsalvetti this would allow attackers to phish much more info, but `bettercap` is no comparison.

**Comment by Splinter0** [comment]
@alternatexp hi, your is a pretty good idea, but since you don't know how many or the name of urls you will nees to clone the website, it's kind of useless to add new urls right in the source code. You could add them in your local machine based on what AP your attacking...

Hope i helped out

**Comment by Splinter0** [comment]
What could be done is add a dictionary right into the code with custom urls, to make everything easier

**Comment by alternatexp** [comment]
@sophron why did you change the title of the post? I implied to steer away from static pages and allow any html page the user gets redirected to. (see below)

@Splinter0 it can be simpler than that.

If [request path] is "/"
    if scenario/index.html
        send to http://10.0.0.1:8080/index.html
    else if scenario/index.htm
        send to http://10.0.0.1:8080/index.htm
else
    send to http://10.0.0.1:8080/[request path]
    

If Wifiphisher logs all POST requests, and listens for specific POST requests sent to (for example) a `/captive_portal_login` directory, the IP of the client can be logged in a file within the Wifiphisher directory. The script can then listen to requests made from those client's IPs and send them to an interface that is connected to the internet.

**Comment by alternatexp** [comment]
But enabling internet access is not entirely necessary once you gain access to the target AP through Wifiphisher and then use a tool such as Bettercap.

**Comment by alternatexp** [comment]
But would be a very nice feature to create an uninterrupted experience for the target, silent hacking is good hacking.

**Comment by kn0wledge** [comment]
@alternatexp aren't you describing exactly what the Harvester module does in Setoolkit ? Clones any site and listens for all POST s and writes them in a file . The difference is that you want to setup this clones page automatically as a captive portal so that it's the first thing that pops out . If that's the case .. then hell yeah , if it can be done as automates as SET is with auto listening to all POST and no headaches editing each index.html to fit the current code , then that would be awesome .

**Comment by alternatexp** [comment]
@kn0wledge exactly

I mentioned the Social Engineering Toolkit and how Wifiphisher could implement httrack in a similar way. But it can be as easy as just pressing CTRL+S on the necessary web pages and moving them inside a new scenario folder.

See the concept of the code I typed above, this should make Wifiphisher much more compatible with all sorts of captive portals.

**Comment by kn0wledge** [comment]
@blackhatmonkey I tried saving a website in the folder you mentioned with index.html as a page , however when I run wifiphisher again I don't see that page as an option .. i didn't install wifiphisher to start with , just cloned it from git and works fine .

**Comment by blackHatMonkey** [comment]
@kn0wledge Is your new folder in `wifiphisher/data/phishing-pages/`?

**Comment by alternatexp** [comment]
@kn0wledge make sure your new scenario has a `config.ini` file like the other scenario folders do.

**Comment by kn0wledge** [comment]
Yup it is

**Comment by kn0wledge** [comment]
Ok will test that in the morning and will keep you posted

**Comment by alternatexp** [comment]
Initial issue remains

**Comment by kn0wledge** [comment]
@alternatexp ok so I tried it again, no luck .. still doesnt show up.. copied it in the right folder, index.html and config.ini , is it working with anyone else?

**Comment by kn0wledge** [comment]
Actually i found the reason it doesnt appear. I was adding it in the wifiphisher folder that I got from the clone on my root directory. I located the directory it was actually running from: 

> /usr/local/lib/python2.7/dist-packages/wifiphisher-1.2-py2.7.egg/wifiphisher/data/phishing-pages/

> 

So great, now I see the option in the selection but when I select it I get this error. 

> Traceback (most recent call last):
  File "/usr/local/bin/wifiphisher", line 11, in <module>
    load_entry_point('wifiphisher==1.2', 'console_scripts', 'wifiphisher')()
  File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.2-py2.7.egg/wifiphisher/pywifiphisher.py", line 810, in run
    ap_logo_path = template.use_file(mac_matcher.get_vendor_logo_path(ap_mac))
  File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.2-py2.7.egg/wifiphisher/phishingpage.py", line 185, in use_file
    copyfile(path, self.get_path_static() + filename)
  File "/usr/lib/python2.7/shutil.py", line 83, in copyfile
    with open(dst, 'wb') as fdst:
IOError: [Errno 2] No such file or directory: '/usr/local/lib/python2.7/dist-packages/wifiphisher-1.2-py2.7.egg/wifiphisher/data/phishing-pages/nestle/static/asus.png'

>

any fix? 

This is all in the effort of finding out how easy it would be to achieve what OP is asking for. Once the steps are clear, maybe we could add a script to httrack so auto download in the right folder and add potential edit html to read posts to the wifiphisher interface (pretty much the same way SETOOLKIT does it with the harvester option).

**Comment by blackHatMonkey** [comment]
@kn0wledge once you put your new folder in `wifiphisher/data/phishing-pages/` just run the `sudo python setup.py install` again and it should appear in the list of templates.

**Comment by alternatexp** [comment]
@kn0wledge please open a new issue if you have a different one.

The original issue still remains and I would like an answer to my questions.

**Comment by blackHatMonkey** [comment]
@alternatexp There are two sides to this argument. One is pointing the software to a directory and let the user handle everything and give them the freedom of setting things up. On the other hand what `torando` allow us to do is automatically configure a page without the need for human intervention. The first case is really useful for advanced users while the second case for novice users without any programming knowledge. Therefore @sophron and myself have to come up with a decision on how to handle this situation.

**Comment by alternatexp** [comment]
Thanks @blackHatMonkey 

So are you talking about the {{ commands }} from the tornado module?

Does the tornado module have to be abandoned? I feel like it can function the same way if only the redirection rules get rewritten, like so:

```
if [request path] is "/"
    if scenario/index.html
        send to http://10.0.0.1:8080/index.html
    else if scenario/index.htm
        send to http://10.0.0.1:8080/index.htm
else
    if scenario/[request path] // If path/file exists in scenario folder
        send to http://10.0.0.1:8080/[request path]
    else // Path/file doesn't exist in scenario folder
        (...send back to index page)
```

Surely the tornado module can listen to all POST requests?

I can't imagine this changing much at all, other than allowing more flexibility for scenarios.

**Comment by sophron** [comment]
>@sophron why did you change the title of the post? I implied to steer away from static pages and allow any html page the user gets redirected to. (see below)

HTML are static pages. If you are thinking of dynamic languages (e.g. PHP), that's a different story.

**Comment by alternatexp** [comment]
@sophron ah I see, I thought you were still referring to the `/static` folder

@blackHatMonkey said:

> The first case is really useful for advanced users while the second case for novice users without any programming knowledge.

For various reasons I advise against making Wifiphisher so beginner friendly. If you don't know how/never hosted a web server, I don't think you will/should jump right into pen testing (but it's possible).

Wifiphisher obviously won't be used for testing purposes only, we have to be realistic and recognise that an overly confident newbie might make a mistake and get himself/herself in trouble. This is best avoided to begin with.

**Comment by laozi999** [comment]
> There is absolutely no need to tie yourself to a /static or /post directory as is done inside the python code of wifiphisher. It is very bad practice and simply limits the capabilities of this powerful tool.

My opinion

**Comment by vay3t** [comment]
I think that they could add the option of using a custom captive portal and place the path of that portal, example: 
```
wifiphisher -c /root/customcaptiveportal
```

**Comment by alternatexp** [comment]
@vay3t that wouldn't change much, the python code needs to be changed so users are allowed to navigate inside the scenario folder, the redirection rules currently always redirect the user to index.html, which is annoying if you want multiple pages.

**Comment by alternatexp** [comment]
Can anyone answer my question?

> could you please tell me how to get Wifiphisher to behave like this without writing silly redirection rules for every path/file the user gets redirected to?

This is exactly how I want Wifiphisher to work:

```
if [request path] is "/":
    if scenario/index.html: // If scenario folder contains index.html
        send to http://10.0.0.1:8080/index.html
    elif scenario/index.htm: // If scenario folder contains index.htm
        send to http://10.0.0.1:8080/index.htm
elif ".html" in self.request.path or ".htm" in self.request.path:
    if scenario/[request path]: // If path/file exists in scenario folder
        send to http://10.0.0.1:8080/[request path]
    else: // Path/file doesn't exist in scenario folder
        (...send back to index page)
else: // if user requests a different file type
    (...ignore weird requests)
```

The part that doesn't work is:
```
    self.render(self.request.path, **template.get_context())
```

**Comment by blackHatMonkey** [comment]
@alternatexp What you are asking is all good but unfortunately both @sophron and myself are busy and therefore implementing this wouldn't be on top of our list. That being said this should be implemented some time in the future.

**Comment by alternatexp** [comment]
Ok.

Can anyone answer my question?

**Comment by alternatexp** [comment]
Also, @blackHatMonkey, I basically laid it all out in front of you, the only part that doesn't work is

`self.render(self.request.path, **template.get_context())`

I'd say someone with adequate python knowledge can answer this within 10 seconds.

**Comment by vay3t** [comment]
u can add ur contribution with pull requests

**Comment by alternatexp** [comment]
@vay3t I will do this **for sure**, still fiddling with it

**Comment by laozi999** [comment]
Any luck on this @alternatexp ?

**Comment by Splinter0** [comment]
@alternatexp I think you should focus on something that clones that original captive portal, then save it and modify all the present forms with the javascript we need for the post request

**Comment by laozi999** [comment]
I went ahead and integrated @alternatexp's idea:

The following code allows victims to navigate to other files within the scenario folder:
(ultimately making it easier to add new scenarios)

`import os.path`

...

```
    def get(self, url):
        client_request = self.request.path[1:]
        try:
            if self.request.path == "/": # If user requests root:
                if os.path.exists(template.get_path() + "index.html"): # If index.html exists:
                    self.render("index.html", **template.get_context()) # Show index.html
                elif os.path.exists(template.get_path() + "index.htm"): # Else if index.htm exists:
                    self.render("index.htm", **template.get_context()) # Show index.htm
            else: # Else if user requests custom path/file:
                if os.path.exists(template.get_path() + client_request): # If path/file exists in scenario:
                    self.render(client_request, **template.get_context()) # Show path/file
                else: # If requested path/file does not exist in scenario:
                    if os.path.exists(template.get_path() + "index.html"): # If index.html exists:
                        self.render("index.html", **template.get_context()) # Show index.html
                    elif os.path.exists(template.get_path() + "index.htm"): # Else if index.htm exists:
                        self.render("index.htm", **template.get_context()) # Show index.htm

```

I think this needs to be reviewed, so I won't submit a PR before it has. @sophron @blackHatMonkey 

I feel like:

1. ...the user should only be able to navigate to HTML/HTM files.
2. ...arbitrary code might be able to be injected this way (might need escaping)
3. ...a lot of code can become redundant with these changes, not sure exactly what
4. ...all post request could be logged, including the input's name, this would save us from having to edit the scenarios (also in response to @Splinter0)

**Comment by laozi999** [comment]
@sophron feel free to close this issue so we can continue the discussion in [the PR](https://github.com/wifiphisher/wifiphisher/pull/523)
