### ISSUE TITLE
Why limit concat lines?

### ISSUE THREAD

**Issue by alternatexp** [wifiphisher/wifiphisher#464]
There are lots of reasons why you would want to save the MAC of a victim, or why their HTTP requests might be valuable, why limit these to 5 lines??????? And why clear the logs????????????????? Shouldn't that be up to us?

I don't think any of us are gonna be too lazy to scroll through some logs, and I know how frustrating it is to lose everything with an accidental keyboard interrupt...

**Comment by sophron** [comment]
There's #427 already for this.
