### ISSUE TITLE
please check my wifi card details // it's not create fake AP

### ISSUE THREAD

**Issue by haxtivitiez** [wifiphisher/wifiphisher#465]
http://pastebin.com/raw/nLd5nWT1

**Comment by blackHatMonkey** [comment]
Hi @haxtivitiez Can you show us the output that `wifiphisher` shows?
Also can you try running the following:
```bash
wifiphisher -aI wlan0 -jI wlan1
```
and see if it fixes the problem.

**Comment by haxtivitiez** [comment]
thank guy hehe... now it's work :)
