### ISSUE TITLE
"Sign in to network" notification | Android devices

### ISSUE THREAD

**Issue by nikraupp** [wifiphisher/wifiphisher#466]
I'm Brazilian, I do not speak English.

Request login to a portal on android devices without having to enter your browser! It would greatly improve the capture of passwords from sites like facebook, google ... using the portal.

**Comment by blackHatMonkey** [comment]
Hi @nikraupp I'm not sure I fully understand what you are asking for. Could you be more specific or provide any examples.

**Comment by alternatexp** [comment]
I think @nikraupp is talking about the captive portal login notification that usually pops up when connecting to a public network with a captive portal. A window pops up on both Android and Apple devices when a captive portal is found.

Upon connecting to an AP, the devices send a request to a server (`gstatic.com/generate_204` on Android and `captive.apple.com` on iOS) to check whether there is access to the WWW or just the captive portal.

**Comment by sophron** [comment]
Hi guys,

On my Android device, Wifiphisher does trigger this notification. Isn't that the case for you?

**Comment by alternatexp** [comment]
Not for me.

I'm pretty sure iPhones send a request to captive.apple.com and expect a file containing 'Success' as a response.

**Comment by alternatexp** [comment]
Not for me.

I'm pretty sure iPhones send a request to captive.apple.com and expect a file containing 'Success' as a response.

**Comment by blackHatMonkey** [comment]
>iPhone/iPad specifically requires access to apple.com/library/test/success.html to "test" if the device is behind a captive portal or not, if it can't reach that page, with the expected content, then it must be behind the captive portal and therefore show the webpage right after associating to the wireless. Other devices use their own URL, Windows Phones/laptops will use msftncsi.com for example.

The above is from SO. Since it is not able to reach that file and it should automatically label it as captive portal.

**Comment by blackHatMonkey** [comment]
Please continue the discussion over at #524.

**Comment by mfyuce** [comment]
As long as I see, on the background (from network/pf sniffing), my android is using `captive.apple.com` to check if OS has connected to a captive portal. But popup is `gstatic.com/generate_204`
