### ISSUE TITLE
credit card phish

### ISSUE THREAD

**Issue by cicina** [wifiphisher/wifiphisher#469]
Hello there, I have seen this pull https://github.com/wifiphisher/wifiphisher/pull/467 which reminds me of more use of wifiphisher.. I figured out how to build ISP scenario now.

Do you know about mobile internet providers, who won't let you browse porn sites and they want you to use your credit card to verify your age.. We could do this, we could even ask for credit card info pretending to be ISP who won't allow  access to 18+ websites or just any websites, "based on customer preferences" (security preferences) or something like that. I can't really code but I can basic html and I will take a look at gopro scenario mentioned earlier and I will try to modify to look like I want it to looks like. I can't promise anything and even now I know I will have difficult time to get it capture cc details instead of password. It would be excelent if some1 could help include script which will check if numbers are valid. 

lol what am I saying?! ... We could even use oauth-login scenario to do this!! Simply let users pay funny amount for internet access and we will capture their cc info lol xD briliant idea huh?
This way, it would have to redirect user to "payment gateway" tho. it could not be the same page.
BT internet do this all over the country. people are used to it.

**Comment by andeees** [comment]
That is not good to card, if you want to do it just hire someone, I don't believe @sophron is okay with this.

**Comment by cicina** [comment]
Hire some1 is the last thing I would do.. I dont need it its just for fun. It is an option, thats what I said. Anyway It would be awesome. I hope its not 100% declined already.

**Comment by sophron** [comment]
For very specific scenarios, we now have a <a href="https://github.com/wifiphisher/extra-phishing-pages">dedicated repository</a>. This repository is mostly community-based, meaning that we won't be strict reviewing the PRs there. Anyone will be able to upload and share its own scenario there.

Having said that, your idea fits in that repo. If you implement it, feel free to make a PR there.

**Comment by Splinter0** [comment]
@cicina I'll help you if needed to create the actual scenario 
Email : <a href="mailto:splint@protonmail.com.com" target="_blank">splint@protonmail.com</a>

**Comment by cicina** [comment]
awesome guys, that repo is very good idea indeed. Thanks blackhatMonkey for label I knew you would like it xD @Splinter0 great, I will try to find old scripts of mine and try to use them for this. I will let you know if there is any progress and will ask you for advices.  Feel free to remove your mail address, I copied it :)

**Comment by alternatexp** [comment]
I hope you all realise that every type of issue like this could have been avoided if Wifiphisher functions as discussed [here](https://github.com/wifiphisher/wifiphisher/issues/463)...

**Comment by alternatexp** [comment]
@sophron I really like the idea of a dedicated phishing scenario page, but only if they aren't tied to the current way of structuring the HTML pages (only allowing `/static`, `/post`, `/loading` folders).

Once these conditions are lifted I will be glad to share numerous captive portals collected from coffee shops, hotels and airports from all over the world!

**Comment by alternatexp** [comment]
And, @cicina, be careful.

> I dont need it its just for fun.

won't excuse you in court.

**Comment by cicina** [comment]
I can't imagine how would anyone trace my AP from outsite if my AP appears randomly and for short period of time. Even if they would go for it, with increased txpower I dont think they could know where is the AP. dangerous part comes after this. But I dont see reason to talk about it here or just talk about it at all. Even angry neighbor could kill you with a knife if they find out you are running on his wifi..... and MITM him or whatever

**Comment by alternatexp** [comment]
@cicina said:
> I can't imagine how would anyone trace my AP from outsite if my AP appears randomly and for short period of time. Even if they would go for it, with increased txpower I dont think they could know where is the AP.

If I had wireless at home and it would send me to a captive portal I'll be using my phone to scan the air and trace down the MITM.

> I like your idea and without it, Its almost impossible to make what I have written above anyway.

yeah, a lot would be possible

**Comment by sophron** [comment]
@cicina @alternatexp Using Wifiphisher in public areas or against WLANS that you have no permission to do so, is illegal and not advisable. 

How not to be traced (outside of a penetration testing) implies illegal activities that we do not encourage. Please do not discuss anything like this on this forum again.

**Comment by alternatexp** [comment]
@sophron that was exactly my point.

**Comment by alternatexp** [comment]
And this issue basically comes down to getting Wifiphisher to use the scenario folder like Apache uses a `/public_html` folder.

**Comment by sophron** [comment]
@alternatexp No, it's not. This issue is about someone writing the actual HTML code for the phishing. #463 is what you propose.

**Comment by alternatexp** [comment]
@sophron 

@cicina said:

> btw I like your idea and without it, Its almost impossible to make what I have written above anyway.

It basically comes down to the same thing.

**Comment by cicina** [comment]
@sophron  sorry, I understand. I meant it like in public places WITH permissions ofc.

**Comment by Splinter0** [comment]
@cicina i know it isn't actually the same but how about a Swish transaction scenario

**Comment by laozi999** [comment]
Before anyone should waste their time on adapting any type of scenario to fit in with Wifiphisher, I strongly believe Wifiphisher should be more scenario friendly, as in, it should behave like a `public_html` folder (without the strict redirection rules)

**Comment by sophron** [comment]
For any specific scenario requests, please use the dedicated repo:

https://github.com/wifiphisher/extra-phishing-pages

**Comment by Faithmanex** [comment]
> Hello there, I have seen this pull #467 which reminds me of more use of wifiphisher.. I figured out how to build ISP scenario now.
> 
> Do you know about mobile internet providers, who won't let you browse porn sites and they want you to use your credit card to verify your age.. We could do this, we could even ask for credit card info pretending to be ISP who won't allow access to 18+ websites or just any websites, "based on customer preferences" (security preferences) or something like that. I can't really code but I can basic html and I will take a look at gopro scenario mentioned earlier and I will try to modify to look like I want it to looks like. I can't promise anything and even now I know I will have difficult time to get it capture cc details instead of password. It would be excelent if some1 could help include script which will check if numbers are valid.
> 
> lol what am I saying?! ... We could even use oauth-login scenario to do this!! Simply let users pay funny amount for internet access and we will capture their cc info lol xD briliant idea huh? This way, it would have to redirect user to "payment gateway" tho. it could not be the same page. BT internet do this all over the country. people are used to it.

I have made a phishing site for Credit Card, I can share if you're interested.
