### ISSUE TITLE
Use gitter for community chat

### ISSUE THREAD

**Issue by blackHatMonkey** [wifiphisher/wifiphisher#473]
I think using [gitter](https://gitter.im/) for community chat is a really good idea.

**Comment by ssMarie** [comment]
Hello, 
i have an issue when usuing wifiphisher,, 
it's about the deauth mode, the client are not automatically reconnect to my twin ap, and i saw always the original AP on the list of wifi . 
Thanks to give me more details about that .

**Comment by sophron** [comment]
I would prefer IRC over Gitter and most (if not all) of the open-source communities I have contributed lie there. Is there a reason we should use Gitter instead?

**Comment by blackHatMonkey** [comment]
@sophron I'm not saying that we should abandon `IRC` but use `gitter` a companion. Couple advantages of using `gitter` are:
* Closely integrated with `github` and therefore users can easily login using their `github` accounts 
* Unlike `IRC` you don't have to be online to get the messages
* You can reference issues and post `gist` code in the messges
* It is publicly available to everyone even if you joined after the conversation has ended

**Comment by blackHatMonkey** [comment]
Since `IRC` does the job for now I'm closing this issue. However this issue could be revisited in the future.

**Comment by laozi999** [comment]
I vote for gitter cause I'm sitting here waiting for a response in another timezone :smile:

**Comment by Splinter0** [comment]
Me too i vote for gitter! :+1:

**Comment by Splinter0** [comment]
@blackHatMonkey I find gitter way better than the IRC chat, also you can use gitter also on your phone ( there's the app )

**Comment by blackHatMonkey** [comment]
@Splinter0 The final decision is with @sophron.

**Comment by Splinter0** [comment]
@sophron @blackHatMonkey I know we have more important stuff to do :smile: but can we decide cause i love gitter and I would be very happy to use it as community chat :laughing:

**Comment by sophron** [comment]
I don't see what how `gitter` is useful.

For instant communication, we use IRC. For long-term, one may fill an issue. How does `gitter` adds to this?

**Comment by blackHatMonkey** [comment]
As it stands issue will suffice and therefore I'm closing this thread.
