### ISSUE TITLE
Duplicate of #461

### ISSUE THREAD

**Issue by ssMarie** [wifiphisher/wifiphisher#474]
Hello,
i have an issue when usuing wifiphisher,,
it's about the deauth mode, the client are not automatically reconnect to my twin ap, and i saw always the original AP on the list of wifi .
Thanks to give me more details about that .

**Comment by blackHatMonkey** [comment]
Hi @ssMarie What you are describing seems to be a duplicate of #461. Please refrain from posting in multiple places as you would not get answered any faster. Let me know if you have any more questions.
