### ISSUE TITLE
Add --update flag to update Wifiphisher

### ISSUE THREAD

**Issue by Asux3** [wifiphisher/wifiphisher#477]
Is it possible to add update from the terminal
![screenshot from 2017-03-01 19-21-11](https://cloud.githubusercontent.com/assets/25803756/23477049/fa57bb50-fe79-11e6-8d94-c9330068f74a.png)

**Comment by blackHatMonkey** [comment]
Hi @Asux3 what is the purpose of the `--update` flag?

**Comment by Asux3** [comment]
For the update

**Comment by blackHatMonkey** [comment]
what does it exactly update?

**Comment by sophron** [comment]
I believe he means an option that will automatically update the tool.

Myself wouldn't trust software updates that are unsigned. And if we want to provide secure signed updates, we will need the right infrastructure (that we don't have). 

The best thing that we can offer is an alias of `wifiphisher --update` to `git pull`. It will be exactly the same though and I find no reason for it. Is `git pull` a problem for you?

**Comment by blackHatMonkey** [comment]
Once the tool has been pushed to `PyPi` I think the problem would not exist anymore.

**Comment by sophron** [comment]
I'm closing this. Please use `git pull` for updating.
