### ISSUE TITLE
-iI option skips Phishing Pages.

### ISSUE THREAD

**Issue by andeees** [wifiphisher/wifiphisher#487]
I am using the current version of this repository. By passing the argument `wifiphisher -iI eth0` it creates the fake AP, however there is no Phishing scenario when I connect to it, it just let me browse the internet without any login page.

**Comment by sophron** [comment]
Hi @andeees,

That's the idea. Instead of returning a phishing page, we provide the victim with Internet access. Then, we may use a sniffer (e.g. Wireshark) to capture any clear-text data.

**Comment by alternatexp** [comment]
I suggest using **bettercap** as it's literally better than having to use Wireshark + SSLstrip + other modules manually. **bettercap** does it all for you, and there are many custom modules built for it.

I also suggest enabling the captive portal even when the `-iI` option is issued. Then Wifiphisher can listen to POST requests to (for example) `/captive_portal_login`, log the client's lease in a new log file, and then send their requests to the interface with internet.
