### ISSUE TITLE
still mess :(

### ISSUE THREAD

**Issue by cicina** [wifiphisher/wifiphisher#491]
![Uploading Screenshot from 2017-03-04 10-47-12.png…]()

cant run the tool. on screenshot you can see what command I used and I reached scenario selection but then error.

**Comment by cicina** [comment]
https://s3.postimg.org/svb5mi4wj/Screenshot_from_2017_03_04_10_47_12.png

**Comment by blackHatMonkey** [comment]
This is a duplicate of #489 .
