### ISSUE TITLE
Supported Adapters

### ISSUE THREAD

**Issue by miuiu** [wifiphisher/wifiphisher#499]
Hello. I would like to know the full list of supported adapters

Many of my not working

**Comment by alternatexp** [comment]
https://www.raymond.cc/blog/best-compatible-usb-wireless-adapter-for-backtrack-5-and-aircrack-ng/

**Comment by alternatexp** [comment]
A lot of info can be found on wireless adapters here: 

https://wikidevi.com

**Comment by miuiu** [comment]
What are the proven 2 adapter you need?

1) TP-Link wn722n
2) TP-Link wn822n

Does not work

I need to know the proven model

**Comment by alternatexp** [comment]
@miuiu They should both work!

What OS are you running?

If you are using Linux, try `sudo apt-get install firmware-atheros`

**Comment by miuiu** [comment]
Updated wifiphisher through git it works
