### ISSUE TITLE
the password has been  sent encoded with html ? 

### ISSUE THREAD

**Issue by minanagehsalalma** [wifiphisher/wifiphisher#504]
when the password includes a special characters like @!? ... it sent me an html encoded password

**Comment by blackHatMonkey** [comment]
Hi @minanagehsalalma Would you be able to provide the output or a screenshot of it?

**Comment by alternatexp** [comment]
that's pretty normal, you can decode it here:
http://meyerweb.com/eric/tools/dencoder/

**Comment by minanagehsalalma** [comment]
i know i can decode but why not to fix this

**Comment by blackHatMonkey** [comment]
@minanagehsalalma In order to solve this bug can you provide the following:
1. Which scenario are you using?
2. What is output?

**Comment by alternatexp** [comment]
How is this a bug?

**Comment by minanagehsalalma** [comment]
so @alternatexp  it's not a problem!!!!

**Comment by minanagehsalalma** [comment]
@blackHatMonkey  i use the firmware-upgrade scenario...  the output is as i told you  in the first  ...

**Comment by alternatexp** [comment]
It isn't a problem if you can take 2 seconds to decode it..

No need for a screenshot, really, @minanagehsalalma means that characters like

`@!?`

are displayed like:

`%40!%3F`

Probably a good thing!

**Comment by minanagehsalalma** [comment]
@alternatexp yes

**Comment by minanagehsalalma** [comment]
will  it be hard if you added a decoder to decode the password if it is was encoded ?? it's not an important thing like what you said

**Comment by alternatexp** [comment]
@minanagehsalalma however, what if the WPA key actually is %20? 

This could be confusing if think it's a space.. Might be a bug after all!

**Comment by minanagehsalalma** [comment]
@alternatexp  yeah cause  when will i know if the password is encoded or not... !

**Comment by alternatexp** [comment]
@minanagehsalalma Trial and error for now ;)

**Comment by minanagehsalalma** [comment]
ok @alternatexp ...  but when you fix this please let me now....  i think fluxion script will be help

**Comment by minanagehsalalma** [comment]
ok @alternatexp ...  but when you fix this please let me now....  i think fluxion script will be help

**Comment by minanagehsalalma** [comment]
ok @alternatexp ...  but when you fix this please let me now....  i think fluxion script will be help

**Comment by alternatexp** [comment]
@minanagehsalalma yeah I remember fluxion! Thanks for reminding me of that tool :)

**Comment by minanagehsalalma** [comment]
@alternatexp you're welcome 😀😀😀

**Comment by blackHatMonkey** [comment]
@minanagehsalalma A new commit has been pushed to repository. Please update to the latest version and let me know if you still are experiencing the issue.

**Comment by blackHatMonkey** [comment]
I'm assuming that this has been fixed. If not feel free to re-open :smile:.
