### ISSUE TITLE
Include dependencies for installation without internet

### ISSUE THREAD

**Issue by minanagehsalalma** [wifiphisher/wifiphisher#508]
because of using live Linux

**Comment by blackHatMonkey** [comment]
@minanagehsalalma  Can you explain in more detail?

**Comment by vay3t** [comment]
Sometimes one does not have internet available. It could be possible to create a paqiete where all the dependencies of python to be able to have wifiphisher always with one

**Comment by minanagehsalalma** [comment]
@blackHatMonkey  as @vay3t  said..

**Comment by minanagehsalalma** [comment]
@blackHatMonkey  could you do it  ???  it will be so helpful ....

**Comment by alternatexp** [comment]
Sounds fair. A reason not to do it is outdated copies of the software floating around, but I can see how this could help.

**Comment by minanagehsalalma** [comment]
@blackHatMonkey @alternatexp you can put the new dependencies every  3 months  or years

**Comment by alternatexp** [comment]
@minanagehsalalma if you can download wifiphisher, you can take the extra minute to install it and the dependencies

**Comment by minanagehsalalma** [comment]
@alternatexp i have the wifiphisher.zip stored on laptop..  so i won't download every time i open...  cause Sometimes i don't  have internet available.

**Comment by alternatexp** [comment]
Right. I already shared my opinion on this.

**Comment by minanagehsalalma** [comment]
@blackHatMonkey @sophron  what is your opinions  too     ????

**Comment by blackHatMonkey** [comment]
@minanagehsalalma I personally think that doing this would create extra and unnecessary work as well as leave outdated software.  Installing with `pip` would be the most elegant as it would keep track of the version and get new version with a single command.

**Comment by minanagehsalalma** [comment]
@blackHatMonkey ok i understood  your idea...  and  i will close this issue cause it's useless now...
