### ISSUE TITLE
Enhancement for 1.3: Auto-connect to rogue AP

### ISSUE THREAD

**Issue by kn0wledge** [wifiphisher/wifiphisher#509]
Hi @sophron , As a new feature that would really enhance the functionality of wifiphishing, is auto-connecting to rogue AP. Not sure what needs to be done to achieve that however I know it is possible (Karma). 

This will significantly increase the success rate of wifiphisher.

**Comment by blackHatMonkey** [comment]
Hi @kn0wledge We have #76 for that. Please continue the discussion over there.
