### ISSUE TITLE
Failed to start the fake access point! (hostapd error)

### ISSUE THREAD

**Issue by d0geda** [wifiphisher/wifiphisher#512]
**Version**: Use `git show | grep commit` command and paste here the output.

**Distribution**: Kali

Hello, I have the lastest Kali and I am still getting "Failed to start the fake access point! (hostapd error)"
I've tried to turn the wlan0 to monitoring mode -> wlan0mon and it didn't work either.

**Comment by alternatexp** [comment]
Have you installed wifiphisher and all its dependencies?

**Comment by blackHatMonkey** [comment]
Hi @d0geda Can you provide us with the exact output?

**Comment by d0geda** [comment]
Well the output is:

[+] Selecting Firmware Upgrade Page Template...
[*] Starting the fake access point...
[+] Failed to start the fake access point! (hostapd error)
[+] Try different wireless interface using -aI option.
[+] Capturing credentials
[!] Closing

**Comment by blackHatMonkey** [comment]
@d0geda Can you do me a favor and save this as `hostapd.conf`(make sure to change the **interface**):
```text
interface=THE INTERFACE WIFIPHISHER USES FOR AP CREATION
driver=nl80211
ssid=SOMETHING
hw_mode=g
channel=2
macaddr_acl=0
ignore_broadcast_ssid=0
````
 And then run this from the same directory:
```bash
sudo hostapd hostapd.conf
```
Let me know if you get any errors or not.

**Comment by d0geda** [comment]
It says

`Configuration file ´: hotsapd.conf
Line 2: invalid/unknown driver 'n180211'
1 errors found in configuration file 'hostapd.conf'
Failed to set up interface with hostapd.conf
Failed to initialize interface`

**Comment by blackHatMonkey** [comment]
It seems that the problem lies with your system rather than `wifiphisher`. The answer provided [here](http://askubuntu.com/questions/288437/how-fix-hostapd-invalid-unknown-driver-nl80211-error/289723) might help you.

**Comment by blackHatMonkey** [comment]
@d0geda If you have found a way to solve this issue it might be useful to others as well. Therefore it would be a good idea to post your results here. I'm closing this now but feel free to open it if needed.
