### ISSUE TITLE
Unable to get the latest version

### ISSUE THREAD

**Issue by mbingl** [wifiphisher/wifiphisher#513]
I'm using the latest Wifiphisher on Kali Linux 2016-2 VBox AMD 64.  With a rtl8187  for monitoring and ath9k_htc for AP. 

I can see a lot of activity on both the existing and the newly created AP in Airodump-ng. But there is no Jamming devices, nor DHCP Leases, no HTTP requests. Nothing happens. And it is impossible to connect to the new AP from a different computer.  

I see others have described the same or similar issue in 2016 but I have yet to see a solution. Any suggestions?

```bash
root@kali:~# wifiphisher -aI wlan0 -jI wlan1mon -p firmware-upgrade
[*] Starting Wifiphisher 1.1GIT at 2017-03-11 12:09
[+] Selecting wlan1mon interface for the deauthentication attack
[+] Selecting wlan0 interface for creating the rogue Access Point
[*] Cleared leases, started DHCP, set up iptables


[+] Ctrl-C at any time to copy an access point from below
num  ch   ESSID                             BSSID             vendor 

 1 - 1   - NETGEAR53                            - dc:4a:3e:a1:82:9f Hewlett Packard
 2 - 1   - Eddie                                      - a0:a3:e2:ba:c0:75 Actiontec Electronics
 3 - 1   - LinksysExtender07339           - b4:75:0e:87:f2:12 Belkin International
 4 - 1   - CenturyLink9670                - a2:e4:cb:5b:85:40 None

[+] Choose the [num] of the AP you wish to copy: 1

Available Phishing Scenarios:

1 - Firmware Upgrade Page
	A router configuration page without logos or brands asking for WPA/WPA2 password due to a firmware upgrade. Mobile-friendly.

2 - Browser Connection Reset
	A browser error message asking for router credentials. Customized accordingly based on victim's browser.

3 - Browser Plugin Update
	A generic browser plugin update page that can be used to serve payloads to the victims.

[+] Choose the [num] of the scenario you wish to use: 1
[+] Selecting Firmware Upgrade Page template
[*] Starting the fake access point...

[*] NETGEAR53 set up on channel 1 via wlan1mon on wlan0
[*] Starting HTTP server at port 8080
[*] Starting HTTPS server at port 443
[*] Monitor mode: wlan1mon - 00:c0:ca:4f:27:53




Jamming devices:



DHCP Leases:



HTTP requests:
```
Edited by @blackhatmonkey for formating

**Comment by alternatexp** [comment]
Remember to not use one interface for airodump-ng and wifiphisher at the same time, if that's what you were doing.

**Comment by mbingl** [comment]
Good suggestion, but no.

**Comment by minanagehsalalma** [comment]
@mbingl  make   sure  that you installed it with this   git clone https://github.com/wifiphisher/wifiphisher.git    

2- cd wifiphisher 
3-  sudo python setup.py install 
4- wifiphisher

(internet connection required for the installation )

**Comment by mbingl** [comment]
Yup I did.... 

-----Original Message-----

**Comment by minanagehsalalma** [comment]
@mbingl  try any other Linux distro  like wifislax ....  worked perfect with me

**Comment by mbingl** [comment]
Will do! Thanks for your input!

On Sat, Mar 11, 2017 at 10:43 PM, minanagehsalalma <notifications@github.com

**Comment by minanagehsalalma** [comment]
@mbingl you are welcome

**Comment by blackHatMonkey** [comment]
Hi @mbingl It seems that based on the output you provided you are using a older version of `wifiphisher`. Please update the latest version and let me know if you have any issues.

**Comment by mbingl** [comment]
Hi @blackHatMonkey ! I think you are on to something! Turns out I am on 1.1 which I cloned just a few days ago from https://github.com/wifiphisher/wifiphisher.git . I uninstalled & deleted it and cloned it again, then ran all the apt-get updates and upgrades....  but I still get 1.1 when I clone - and it tells me it is the latest revision.... 

However I see there is actually a 1.2 revision, which I downloaded manually and unpacked.  However since I am a noob I have no idea how to install it from my shared external folder in Kali&VlBox... I have tried a bunch of commandos but no luck. Driving me nuts!

**Comment by blackHatMonkey** [comment]
@mbingl the simplest way to install is via `pip`:
```bash
sudo -H pip install wifiphisher
```
or if you clone from `github` just run the following in `wifiphisher` directory:
```bash
sudo python setup.py install
```

**Comment by mbingl** [comment]
Thanks! But why is it that cloning from Github only gives me 1.1?

**Comment by blackHatMonkey** [comment]
What command are you using to start `wifiphisher`?

**Comment by mbingl** [comment]
cd wifiphisher
sudo python setup.py install
(install looks successful, ends with `Finished processing dependencies for wifiphisher==1.2
`

wifiphisher

wifiphisher -aI wlan0 -jI wlan1mon -p firmware-upgrade
[*] Starting Wifiphisher 1.2GIT at 2017-03-12 14:17

So it looks like 1,2 installs fine, but 1,1 is the version that the command `wifiphisher` brings up, regardless.

**Comment by blackHatMonkey** [comment]
I'm not really sure why it does that. Another way to start `wifiphisher` is to go to `wifiphisher` directory and run
```bash
sudo python bin/wifiphisher
```

**Comment by mbingl** [comment]
@blackHatMonkey   SUCCESS!!!! 

I tried `sudo python bin/wifiphisher` and....   Now it started 1.2 like clockwork!!!! :)  

Many thanks!!!
