### ISSUE TITLE
Ransom scenario

### ISSUE THREAD

**Issue by Splinter0** [wifiphisher/wifiphisher#519]
A really interesting idea popped in my mind, 
since we take down the victim AP with  deauth packets the attack turns obviously into a Denial of Service so what if we do a scenario where the victim has to pay certain money to get his AP back running?
I know it's really really unethical but it would be cool ( of course we won't fool a lot of victim but still ).

@blackHatMonkey

**Comment by sophron** [comment]
I can't imagine how this would work during a penetration testing or under a security-awareness training.

> I know it's really really unethical but it would be cool 

In this community we don't like unethical and we don't advocate illegal activity.

**Comment by Splinter0** [comment]
@sophron you're right sorry i shouldn't have proposed this. It won't happen again
