### ISSUE TITLE
Require one wireless card instead of two

### ISSUE THREAD

**Issue by ady133t** [wifiphisher/wifiphisher#525]
As the title above, I want to know whether 1 adapter that support ap/mon can be used for both attack (fake ap/deauth)

**Comment by JetseVerschuren** [comment]
No, 1 network card is not enough. Your network card is either in access point mode or in monitor mode (monitor mode is used for deauthentication). But if you are using a laptop you could use the internal wifi adapter in combination with a usb one to add up to two network cards.

**Comment by minanagehsalalma** [comment]
@JetseVerschuren  but how does (fluxion -  linset)  could do that ???

**Comment by JetseVerschuren** [comment]
> but how does (fluxion - linset) could do that ???

Apparently i was wrong. I thought you only could do one mode at a time but a quick google user search has proven me wrong.
https://superuser.com/questions/825706/can-a-wireless-interface-act-in-two-modes-at-the-same-time
But it it is not supported by all network cards so i thing @sophron chose to use two wireless cards (or he didn't know about this to ;)

**Comment by minanagehsalalma** [comment]
it's OK @JetseVerschuren

**Comment by minanagehsalalma** [comment]
@JetseVerschuren 👍👍👍👍

**Comment by ady133t** [comment]
apparently my wifi adapter (signalking) can do both AP and monitor mode at same time bcause I often use it in windows 10 to create hotspot for my devices, while at the same time the adapter connected to another long range home wifi. can i still use it in wifiphisher to do both job?

**Comment by minanagehsalalma** [comment]
there  no option in wifiphisher yet but you can run wifiphisher with no jamming option..  and start mdk3 with specified channel...  or use fluxion

**Comment by ady133t** [comment]
I see. tq :)

**Comment by sophron** [comment]
If your card (+ the driver) supports it, it is possible to spawn two different virtual interfaces in different modes.

However, what is not possible is to have these two virtual interfaces in different channels. If we want to do de-authentication (with channel hopping) in one virtual interface it's not possible to spawn a different interface for the Access Point. For example, there's no way to implement #510 with only one card.

Another reason is performance. We want a card dedicated for the Access Point and another for de-authentication that sends DEAUTH frames as fast as possible.

However, if we see that this is something that people want, we'll see if we can implement it for `v1.4`.

**Comment by JetseVerschuren** [comment]
Thank you @sophron for clarifying this.

**Comment by ady133t** [comment]
actually I managed to get wpa2 pass from my neighbour AP in less than 20 min by using fluxion in 1 adapter.  And I tested it using my own AP,  the device client dc instantly and and it cannot cnnect to real AP as long deauth program is running. There are no prformance issue. I guess it depend on which adapter we using.

**Comment by sophron** [comment]
> actually I managed to get wpa2 pass from my neighbour AP in less than 20 min

@ady133t  Please go somewhere else and post your "achievements" . Activities that may be considered illegal are not welcome in our forums.

**Comment by blackHatMonkey** [comment]
The conversation should be moved to #652.
