### ISSUE TITLE
Use semantic-release to automate releses

### ISSUE THREAD

**Issue by blackHatMonkey** [wifiphisher/wifiphisher#532]
Using [semantic-release](https://github.com/relekang/python-semantic-release) has a lot of advantages such as:
- users will always can get the latest version using `pip`
- reduces the maintenance time as you no longer need to individually create tags for each release
- automates releases
- can be run in `ci` so no human interaction is needed 
- creates change log
- uploads to `PyPI`

However using it requires the software version to follow [semantic versioning](http://semver.org/) as well as follow strict commit conventions. A popular commit convention is [AngularJs](https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md). Following formats can be hard but with tools such as [commitizen](http://commitizen.github.io/cz-cli/) this process can be eased.

Let me know what you think @sophron

**Comment by sophron** [comment]
I'm a little worried on how exactly it operates. For example, I'm not sure how does it generate a changelog.

I'm wondering how popular is this among open-source?

It doesn't look like it will save us a lot of time, but I can have a closer look if you like.

**Comment by sophron** [comment]
Semantic-release will currently bring overhead in our development process.
