### ISSUE TITLE
Logging file format

### ISSUE THREAD

**Issue by laozi999** [wifiphisher/wifiphisher#537]
The current logging is very problematic due to hard coded rows and columns (and 3 log files are being tailed in one terminal window, limited to 5 lines only).

Also, I don't think there is a logging feature, which is quite important for me.
The logs get cleared on termination, and valuable info can get lost (HTTP requests, hostnames, MAC addresses, etc).

This is an idea I'm proposing, it's inspired by bettercap. A single log file with the option to save the log each session, it won't clear anything on termination, and much more detail can be logged:

**(updated)**

![wifiphisher_tail](https://cloud.githubusercontent.com/assets/24898383/24318238/0f7520e2-1156-11e7-8333-1b4fd4940985.png)

**Comment by laozi999** [comment]
Added some more ideas

**Comment by laozi999** [comment]
And some more..

![screenshot from 2017-03-25 21-05-47](https://cloud.githubusercontent.com/assets/24898383/24327246/fc485634-1217-11e7-8ed4-67c57460f62f.png)

![Uploading Screenshot from 2017-03-25 21-05-51.png…]()

**Comment by sophron** [comment]
The good thing with our current output is that we see the state of our attack in real-time without having to scroll or anything.

What you propose is good as a logging feature (#427) where someone may want to how the attack involved in detail.

**Comment by laozi999** [comment]
@sophron that is not true, once you have more than 5 requests, clients, or deauthentications, the previous ones are lost forever...

**Comment by blackHatMonkey** [comment]
@laozi999 I think what you are talking about is the actual design of this section rather than logging. The goal is to rewrite the whole program in curses like the ap selection phase. I would love to hear you thoughts on the design.

**Comment by laozi999** [comment]
I think we should focus on getting the most functionality out of Wifiphisher first, then worry about how pretty it looks.

I have always been a fan of bettercap's log streamer, it's always given me that feeling of "so this is what internet traffic looks like", it's easy to read, detailed, and safe (nothing gets cleared).

@blackHatMonkey the log stream is basically the same thing, but right now it is divided into 3 separate logs and tailed up to 5 lines only, if we use a single log file, this can serve as the activity logs as well as a history logs.

**Comment by gabrig** [comment]
This is great.
Maybe one alternative solution could be to open 3 different terminal windows, each one for a different process (jamming, DHCP,HTTP), so that everything is in real time and also you can scroll up to see previous entries.

**Comment by laozi999** [comment]
@gabrig  the only downside with 3 terminal windows would be that we lose the order in which things happen, unless we add a timestamp to each log.

**Comment by gabrig** [comment]
@laozi999 mm I didn't thought about this and is not functional. Thanks for pointing out.
What about this: while the program try to phish, it opens a .txt file (like a log file), in which infos are stored just for the time the pgrogram is running: in this way, on the terminal you see the current session and if you need to search in the history, you can scroll up the .txt file. Once you stop the program, the .txt datas are showed into the terminal as a sum of the work just done (maybe with the option to save the .txt file too). Do you guys think it can work or is not functional?

**Comment by blackHatMonkey** [comment]
I opposed to using log files to display current operations. It adds a unnecessary IO overhead and it should all be done natively in the code. The log files are a necessity which should be used when debugging or running headless and should be persistent.

**Comment by laozi999** [comment]
@gabrig basically that's what a log stream is, but in this case we don't want to store the info just for the time Wifiphisher is running, but we want to save that same log file as a history log (unless the user chooses not to save the logs of course)

**Comment by laozi999** [comment]
@blackHatMonkey I'm not sure what you're trying to say. How could the logging not be done in native code? Or are you saying, don't use a log file and a tailing window, but instead **print** logs to the active terminal window?

**Comment by blackHatMonkey** [comment]
@laozi999 What I meant was that we should save the data internally and then print it on the screen rather than saving it to a file and reading it back again.

**Comment by sophron** [comment]
Let's separate the functionalities. We need two different outputs:

1) What is shown on the screen during the attack. Here we want to show the latest (more important) information from the modules that are directly involved with the attack (e.g. web server, deauth module, dhcp server).  This information is intended for a user that watches the attack during the run-time.

2) What is logged in a log file. This time we want to show the events one after another exactly at the time that they occur. This is useful for someone that runs Wifiphisher for hours and wants to have a look on how it performed at the end of the run.

What is described here is a good influence for (2).

**Comment by gabrig** [comment]
@sophron This is what I wanted to point out, with the only difference of the realtime log file, because if you have multiple accesses in a short time (actually I don't know if this can manage multiple logins, at least for the FB attack) you have to stop the program in order to see the log file.

I can understand that maybe people don't want logs and for this reason I added that the log file can be optional: when you end wifiphisher, you'll be asked if you want a log file (y/n). 
Or, this can be asked _before_ the program is started, if you are worried about memory (like you're running a RaspPI for hours).

**Comment by blackHatMonkey** [comment]
As for the UI design I would suggest doing something like this:

![screenshot_20170415_153253](https://cloud.githubusercontent.com/assets/25112506/25066332/ef1f7774-21f0-11e7-8a6d-5ebfc065841d.png)

This way nothing gets lost and its viewable.
The boxes are all scrollable and as for navigation:

← →: to switch between boxes
↑↓: to move up and down in a box

**Comment by laozi999** [comment]
Separating the logs will only cause confusion. You might like things to be organised in their own category, so that's what you can use colours for.

As far as any type of logging (1. or 2.) is concerned, you want these to be and stay in the exact same order as they happen, or you'll get confused down the track.

**Comment by blackHatMonkey** [comment]
#747 Has implemented this feature. Now you can use the `--log-file` option to log information to file.

**Comment by squalldna** [comment]
what does the --logging command do?
every time i include the command i get a wifiphisher.log file on my wifiphisher. is there a limit to how many .log files are created? some of my log file had been overwritten by latest log file.

thank you.

ps. i have 0 programming knowledge.

**Comment by anakin1028** [comment]
When you supply this option, wifiphisher will dump some useful information for you and store them in the .log file

For example the phishing paraphrase will be stored in that file too, in case the output is gone on the stdout of the terminal, you can look up this file.

**Comment by squalldna** [comment]
i see it. thanks.. however, i once encountered a situation where a .log file was overwritten by a new session instead of renaming the previous log file to log2 log3 etc. is that normal?
