### ISSUE TITLE
Support for raspberry pi 3

### ISSUE THREAD

**Issue by vay3t** [wifiphisher/wifiphisher#539]
You may have support for raspberry pi? (Kali or raspbian)

**Comment by JetseVerschuren** [comment]
I think it supports a raspberry pi 3 it because you can run kali on a raspberry pi.
The only thing could be that the build in wifi doesn't support monitor or host mode.
https://www.reddit.com/r/raspberry_pi/comments/4ah4oi/psa_the_raspberry_pi_3s_embedded_wifi_card_does/

**Comment by JetseVerschuren** [comment]
Apparently the built in wifi does support host mode.
https://www.raspberrypi.org/forums/viewtopic.php?f=36&t=138550

**Comment by vay3t** [comment]
Support exists in monitor mode: https://github.com/nethunteros/bcm-rpi3
Plus the raspberry pi wifi supports AP mode

**Comment by JetseVerschuren** [comment]
Nice didn't know that.

**Comment by JetseVerschuren** [comment]
But it may void your warranty.
> Our software may damage your hardware and may void your hardware’s warranty! You use our tools at your own risk and responsibility! If you don't like these terms, don't use nexmon!

So watch out.

**Comment by vay3t** [comment]
Could be used as rogue AP and an external antenna as hammer

**Comment by JetseVerschuren** [comment]
Yeah it think that is smarter then possibly voiding your warranty.
You could use a esp8266 to jam or as you said:

> as hammer

**Comment by vay3t** [comment]
i think tlwn722n

**Comment by Splinter0** [comment]
@vay3t i'm using a rpi 3 with a 

>  tlwn722n

And it works, the problems is that as the tool grows and more functions are added the raspberry pi struggle handling all that stuff. In fact few months ago the tool was working perfectly on my pi, but now it struggle and for this i takes about 10 mins to take down an AP and also when i can finally connect to the fake AP, everything it's really slow ( POST request, reload pages and stuff ).
it isn't a problem in the tool, its just that is too much for the pi. I guess maybe we could make a lighter version of the tool for boards like the pi.

**Comment by laozi999** [comment]
I like the idea of a light version, without certain features and menus

**Comment by laozi999** [comment]
@Splinter0 @sophron @blackHatMonkey  we could use Passenger Phusion as web server.

https://www.phusionpassenger.com/technical_advantages#speed

It's much more efficient in terms of CPU, and seems ideal for the raspberry pi.

**Comment by laozi999** [comment]
It also has support for Ruby, Python, NodeJS & Meteor applications.

**Comment by blackHatMonkey** [comment]
@laozi999 I could not find any information on whether it supports templating or not. Templating is really important in our operations right now and the advantage of `tornado` is that is a webserver as well as a templating engine.

**Comment by laozi999** [comment]
@blackHatMonkey do you mean support for things like adding custom variables in a config.ini file and using things like {{ these }} escape methods?

The tornado web module is built in python, so we could build a simple config.ini parser for our Passenger server, but I'm sure someone has already written an extension for that.

Is that what you meant with templating?

**Comment by blackHatMonkey** [comment]
@laozi999 we can continue the discussion in #556.

**Comment by salemalkhabuli** [comment]
error:[errno95] operation not supported

**Comment by stefjoe12** [comment]
Just set your Wireless USB to monitor mode with :
sudo airmon-ng start wlan1

run wifiphisher with the monitor interface :
sudo wifiphisher --nojamming --essid "FREE WI-FI" -p oauth-login -aI wlan1mon

and its working on your Raspberry Pi.
I got this working on my Raspberry Pi Zero W.
You can view the program running with VNC viewer if u connect to your fake AP

**Comment by yassinios** [comment]
Please i need Support <3
can u Subscribe My Youtube Channel please
https://www.youtube.com/watch?v=NNV3tfCIr_w
