### ISSUE TITLE
Permission to use snippet

### ISSUE THREAD

**Issue by kbeflo** [wifiphisher/wifiphisher#540]
Asking permission to use snippet from oauth-login template, the modal element, terms, and modal script.

**Comment by laozi999** [comment]
Welcome to open-source :)

**Comment by kbeflo** [comment]
Is it required to include license or credit to use snippet

**Comment by laozi999** [comment]
The friendly corner of the internet..

> The licenses for most software and other practical works are designed
to take away your freedom to share and change the works.  By contrast,
the GNU General Public License is intended to guarantee your freedom to
share and change all versions of a program--to make sure it remains free
software for all its users.  We, the Free Software Foundation, use the
GNU General Public License for most of our software; it applies also to
any other work released this way by its authors.  You can apply it to
your programs, too.

> When we speak of free software, we are referring to freedom, not
price.  Our General Public Licenses are designed to make sure that you
have the freedom to distribute copies of free software (and charge for
them if you wish), that you receive source code or can get it if you
want it, that you can change the software or use pieces of it in new
free programs, and that you know you can do these things.

**Comment by laozi999** [comment]
Credit would be appreciated, but no one's gonna chase you up for it

**Comment by laozi999** [comment]
Keep the license as it is if/when you distribute it, however, that's the only condition.

This software is free and has to stay free

**Comment by kbeflo** [comment]
Used the snippet [here](https://github.com/kbeflo/evilportals/tree/master/portals/sbux-login)

**Comment by laozi999** [comment]
Nice one :) the starbucks portal looks different in Australia.

Feel free to add your captive portals to Wifiphisher's [extra-phishing-pages](https://github.com/wifiphisher/extra-phishing-pages) repo.

**Comment by blackHatMonkey** [comment]
I'm closing this since I believe your question was answered. Feel free to reopen if needed.

**Comment by sophron** [comment]
Hi @kbeflo,

You are free to use the template but keep in mind that your application must also be licensed under the GPL.

**Comment by kbeflo** [comment]
I have included the copyright notice [here](https://github.com/kbeflo/evilportals/blob/master/portals/sbux-login/index.php), tell me if it needs correction. Recently updated my repository license from GPL v2 to GPL v3.
