### ISSUE TITLE
whenever i start wifiphishe this shows up 

### ISSUE THREAD

**Issue by malashhab** [wifiphisher/wifiphisher#544]
hello guys whenever i start wifiphisher whis shows up and it doesn't search for access points WARNING: Failed to execute tcpdump. Check it is installed and in the PATH please help me i have a rpi3 and raspbian on it

**Comment by blackHatMonkey** [comment]
Hi @malashhab thanks for filling a issue. In order to help us solve the problem can you show us the full stack trace(full error message).

**Comment by malashhab** [comment]
I installed tcpdump and it worked perfectly but like it just kick me out of the network I want to hack and it make the fake ap without turning off the wifi signal of the ap I want to hack how can I fix this i'm using raspberry pi 3 and using alpha network as a second wifi adapter @blackHatMonkey @mscherer @d33tah @tgalyean

**Comment by blackHatMonkey** [comment]
@malashhab Please read the [How it works](https://github.com/wifiphisher/wifiphisher#how-it-works) so you can understand what the tool works.

**Comment by sophron** [comment]
Tcpdump and Wifiphisher are two different tools, not depending to each other.
