### ISSUE TITLE
how to add a new phishing page ?? 

### ISSUE THREAD

**Issue by ali151yek** [wifiphisher/wifiphisher#548]
NB - I hava the index.html file 
how i can add it ??

**Comment by laozi999** [comment]
It's a bit of a pain to customise a web page/site to support Wifiphisher.

I have submitted a PR which makes it much easier to add new scenarios, but it's still being reviewed.

For now, you're better off copying one of the existing scenarios and changing it.

- Make sure all your images, css files, js files, fonts, etc. are placed within a folder called `static`
- Make sure forms are sent to `http://10.0.0.1:8080/post`
- Make sure you have configured config.ini with the details of your new scenario

**Comment by sophron** [comment]
Have a look at <a href="http://wifiphisher.org/docs.html">Create custom phishing scenario</a> section.

**Comment by laozi999** [comment]
@sophron downloads are interceptable on wifiphisher.org due to improper SSL redirection.

**Comment by sophron** [comment]
@laozi999 I understand the risk that is involved with the lack of HSTS and the lack of redirect to HTTPS.

However an attacker will have to compromise both Github (to provide the malicious executable) and achieve a man-in-the-middle position to alter the checksum and return a fake one. (Note that all the executables are downloaded via Github.)

That doesn't mean that the risk is accepted. It simply means that I will fix it as soon as I have free time available.

**Comment by laozi999** [comment]
@sophron you simply can't know how urgent it is until it's too late...

It surprises me that in this day in age, with free HSTS through services like Cloudflare, people are still lazy enough to keep their site's traffic decrypted.

Must anyone be using a public wifi, or unlucky enough to be MITM'd, your site could be the cause of SSLstripped referrals, and a simple tool like [this one](https://github.com/evilsocket/bettercap-proxy-modules/blob/master/http/download_hijack.rb) could easily hijack the downloads on your site and install malware without the victim noticing.

**Comment by sophron** [comment]
>It surprises me that in this day n age, with free HSTS through services like Cloudflare, people are still lazy enough to leave their site's traffic decrypted.

I would advice you not to characterize people as "lazy" in an open-source community. Have a look at our <a href="https://github.com/wifiphisher/wifiphisher/blob/master/CODE_OF_CONDUCT.md">Code of Conduct</a>. I believe this is the second time I point you there.



>Must anyone be using a public wifi, or unlucky enough to be MITM'd, your site could be the cause of SSLstripped referrals, and a simple tool like this one could easily hijack the downloads on your site and install malware without the victim noticing.

Nope. As I already explained to you the scenario you are describing is not valid. All downloads lie on Github (over SSL). The checksums on the other hand are PGP signed. 

This is also completely out of topic. Either open a new issue or contact me on IRC.

**Comment by laozi999** [comment]
@sophron Yes, lazy, that is the correct terminology, without offense. And with all due respect, I would expect HTTPS to be standardized within an open-source **(hacking)** community.

> Nope. As I already explained to you the scenario you are describing is not valid. All downloads lie on Github (over SSL). The checksums on the other hand are PGP signed.

Nope, through a tool called bettercap, your site would be SSLstripped, and any request sent to a file would be intercepted by the attacker's host. If you had a look at the code in the link I sent you, you'd know what I'm talking about.

> This is also completely out of topic. Either open a new issue or contact me on IRC.

I have already mention that wifiphisher.org is insecure on IRC... So I opened an issue here [here](https://github.com/wifiphisher/wifiphisher/issues/550).

**Comment by sophron** [comment]
> Nope, through a tool called bettercap, your site would be SSLstripped, and any request sent to a file would be intercepted by the attacker's host. If you had a look at the code in the link I sent you, you'd know what I'm talking about.

And then the user would verify the checksum and either it wouldn't match or it wouldn't be signed by me.

**Comment by laozi999** [comment]
Do you think every user has verified the checksum? Is that the basis of you assuming that wifiphisher.org is safe "enough"?

I wouldn't refer anyone to wifiphisher.org to download Wifiphisher, I would link them to the github page so they can click download on a site that has encryption, for their safety.

**Comment by laozi999** [comment]
Furthermore @sophron, I feel like in an open-source community we should be allowed to word exactly how we feel, especially when it concerns people's privacy.
