### ISSUE TITLE
wifiphisher.org is vulnerable to MITM attacks due to insecure HTTPS redirection

### ISSUE THREAD

**Issue by laozi999** [wifiphisher/wifiphisher#550]
This issue should be resolved.

**Comment by laozi999** [comment]
Proof

![screenshot from 2017-04-01 12-10-39](https://cloud.githubusercontent.com/assets/24898383/24574388/67b4f354-16dd-11e7-9f2d-26ebc4372bcd.png)

**Comment by Splinter0** [comment]
@laozi999 Only @sophron can do something about it. And i guess he has more important thing to do.
Anyway can you propose a solution?

**Comment by JetseVerschuren** [comment]
The site doesn't even redirect users to https automatically. I would start there and also enable hsts.

**Comment by Splinter0** [comment]
Again i think that for deeper investigation ( scanning for flaws ) you guys should ask @sophron

**Comment by laozi999** [comment]
bettercap would be unable to SSLstrip the site's code if it was encrypted over SSL and therefore unable to intercept the downloads.

**Comment by sophron** [comment]
wifiphisher.org now redirects to HTTPS. 

HSTS is sent as always.

@laozi999 In your "proof", you are hijacking the signatures not the actual software. You couldn't hijack the software as it resides on Github (under HTTPS).

The only risk existed here was an attacker modifying the contents of the /download page and tricking the victim to download a malicious executable that way.

**Comment by laozi999** [comment]
Good to know the transport is encrypted now.

> The only risk existed here was an attacker modifying the contents of the /download page and tricking the victim to download a malicious executable that way.

False, as I said before, the page would be SSLstripped meaning the github URL would turn into **http**://github.com/... 

Once the request is sent, a MITM on the same network intercepts this request and will reply with a 302 response to redirect the request to the attacker's local server where malicious files are hosted.

I used the signatures as an example, but any of the SSLstripped links could have been answered with a redirect response by an attacker.
