### ISSUE TITLE
Adapter in monitor mode when --essid argument is given

### ISSUE THREAD

**Issue by schniggie** [wifiphisher/wifiphisher#551]
Hey,

looks like wifiphisher tries to enable monitor mode even when --nojamming is set. I think my card doesn't support monitor mode.

```bash
root@pwner:/opt/wifiphisher# wifiphisher --nojamming --essid "FREE WI-FI" -p oauth-login
[*] Starting Wifiphisher 1.2GIT at 2017-03-31 12:34
[+] Selecting wlan0 interface for creating the rogue Access Point
Traceback (most recent call last):
  File "/usr/local/bin/wifiphisher", line 9, in <module>
    load_entry_point('wifiphisher==1.2', 'console_scripts', 'wifiphisher')()
  File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.2-py2.7.egg/wifiphisher/pywifiphisher.py", line 763, in run
    engine.start()
  File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.2-py2.7.egg/wifiphisher/pywifiphisher.py", line 587, in start
    self.network_manager.set_interface_mode(mon_iface, "monitor")
  File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.2-py2.7.egg/wifiphisher/common/interfaces.py", line 271, in set_interface_mode
    pyw.modeset(card, mode)
  File "/usr/local/lib/python2.7/dist-packages/PyRIC-0.1.6.3-py2.7.egg/pyric/pyw.py", line 1323, in modeset
    if nlsock is None: return _nlstub_(modeset, card, mode, flags)
  File "/usr/local/lib/python2.7/dist-packages/PyRIC-0.1.6.3-py2.7.egg/pyric/pyw.py", line 2236, in _nlstub_
    return fct(*argv)
  File "/usr/local/lib/python2.7/dist-packages/PyRIC-0.1.6.3-py2.7.egg/pyric/pyw.py", line 1340, in modeset
    raise pyric.error(e.errno, e.strerror)
pyric.error: [Errno 95] Operation not supported
root@pwner:/opt/wifiphisher#
```

```
root@pwner:/opt/wifiphisher# iw list
Wiphy phy0
        max # scan SSIDs: 10 
        max scan IEs length: 2048 bytes
        Retry short limit: 7 
        Retry long limit: 4  
        Coverage class: 0 (up to 0m)
        Device supports T-DLS.
        Supported Ciphers:   
                * WEP40 (00-0f-ac:1)
                * WEP104 (00-0f-ac:5)
                * TKIP (00-0f-ac:2)
                * CCMP (00-0f-ac:4)
                * CMAC (00-0f-ac:6)
        Available Antennas: TX 0 RX 0
        Supported interface modes:
                 * IBSS
                 * managed   
                 * AP
                 * P2P-client
                 * P2P-GO
                 * P2P-device
```

**Comment by laozi999** [comment]
What wireless card do you have?

When you type `ifconfig wlan0 down && iwconfig wlan0 mode master` do see any errors?

**Comment by blackHatMonkey** [comment]
Hi @schniggie for access point detection `monitor mode` is required therefore if you are using just one adapter it must have `AP` as well as `monitor` mode support.

**Comment by blackHatMonkey** [comment]
@schniggie Correction this should not be the case when using the `-essid` argument.

**Comment by laozi999** [comment]
@schniggie I notice you didn't execute the python file in the bin folder.

Try executing wifiphisher with the direct path:
`sudo python wifiphisher/bin/wifiphisher --nJ -e "FREE WI-FI" -p oath-login`

**Comment by schniggie** [comment]
@laozi999 here is the output what you wanted:

```
root@pwner:~# ifconfig wlan0 down && iwconfig wlan0 mode monitor
Error for wireless request "Set Mode" (8B06) :
    SET failed on device wlan0 ; Operation not supported.
```

So yes looks like monitor mode is not supported. Btw. using a raspberry pi zero w.

**Comment by schniggie** [comment]
@laozi999 and here is the result by using the direct path, same error:

```
root@pwner:/opt# python wifiphisher/bin/wifiphisher -nJ -e "FREE WI-FI" -p oath-login
[*] Starting Wifiphisher 1.2GIT at 2017-04-01 10:52
[+] Selecting wlan0 interface for creating the rogue Access Point
Traceback (most recent call last):
  File "wifiphisher/bin/wifiphisher", line 12, in <module>
    
  File "/opt/wifiphisher/wifiphisher/pywifiphisher.py", line 763, in run
    engine.start()
  File "/opt/wifiphisher/wifiphisher/pywifiphisher.py", line 587, in start
    self.network_manager.set_interface_mode(mon_iface, "monitor")
  File "/opt/wifiphisher/wifiphisher/common/interfaces.py", line 271, in set_interface_mode
    pyw.modeset(card, mode)
  File "/usr/local/lib/python2.7/dist-packages/PyRIC-0.1.6.3-py2.7.egg/pyric/pyw.py", line 1323, in modeset
    if nlsock is None: return _nlstub_(modeset, card, mode, flags)
  File "/usr/local/lib/python2.7/dist-packages/PyRIC-0.1.6.3-py2.7.egg/pyric/pyw.py", line 2236, in _nlstub_
    return fct(*argv)
  File "/usr/local/lib/python2.7/dist-packages/PyRIC-0.1.6.3-py2.7.egg/pyric/pyw.py", line 1340, in modeset
    raise pyric.error(e.errno, e.strerror)
pyric.error: [Errno 95] Operation not supported
```

**Comment by Splinter0** [comment]
@schniggie Rpi isn't supported yet ( any models ) check #539 for more info and updates.
@blackHatMonkey

**Comment by laozi999** [comment]
The access point interface normally goes into master mode. 

I don't seem to be able to manually force my card into master mode, but it happens when I run Wifiphisher.

I don't think adding support for raspbian will require that much work, we need someone with some spare time to do testing on the pi :+1:

**Comment by Splinter0** [comment]
@laozi999 I can work on it sometimes, it won't take much. Anyway what do you have in mind? A lighter version as is suggested?

**Comment by laozi999** [comment]
@Splinter0 have a look at the other related issue https://github.com/wifiphisher/wifiphisher/issues/539

I proposed a different web server, which is much, much faster than other web servers.

**Comment by st3p1** [comment]
I've found a quick and dirty solution. I've got an RPi3 with Kali, wifiphisher and a TP-Link TL-WN722N. I use the internal wifi  module in AP mode in order to connect in SSH via smartphone. 
If I try directly `wifiphisher --nojamming --essid "FREE WI-FI" -p oauth-login` it crashes everytime.
So I put in manually put monitor mode the tp-link (airmon) then I add the -aI command like this: `wifiphisher -nJ -aI wlan1mon --essid "FREE WI-FI" -p oauth-login`...and it works. 

Hope it helps

**Comment by blackHatMonkey** [comment]
We will be doing a update to this section of the code. So check back in a couple of weeks to see if the problem is still present 😄 .

**Comment by blackHatMonkey** [comment]
@schniggie Can you try the latest git version and let us know if the bug is still present?

**Comment by sophron** [comment]
Isn't this fixed?

https://github.com/wifiphisher/wifiphisher/blob/master/wifiphisher/pywifiphisher.py#L393

**Comment by anakin1028** [comment]
Yes this is fixed.
