### ISSUE TITLE
no access point has been discovered yet

### ISSUE THREAD

**Issue by almenyawe** [wifiphisher/wifiphisher#552]
Hi dears
I'm new in this forum 
Wifi adapters are working fine 
what is wrong ?
need help please
![new picture 1](https://cloud.githubusercontent.com/assets/26799019/24561681/57441640-1650-11e7-8b03-ec3817da915a.jpg)
![new picture 2](https://cloud.githubusercontent.com/assets/26799019/24561682/57464ff0-1650-11e7-8d8e-aae9cd32c2f5.jpg)

**Comment by Splinter0** [comment]
@almenyawe As i can see from your screenshots you're using a raspberry pi, the rpi isn't supported yet.
I suggest you to look at this #539 for updates and infos.
@blackHatMonkey You should probably close this issue cause we already have one like this

Thanks for reporting :+1:
