### ISSUE TITLE
PHP support

### ISSUE THREAD

**Issue by Splinter0** [wifiphisher/wifiphisher#553]
Hi guys, i researched around and i found that is actually possible to integrate PHP into our ```tornado``` webserver using the command  ```php /template-folder/*.php```, using subprocess to ```PIPE``` all the informations. This could allow us to have all the ```POST``` requests, field checking and informations like user agent, in PHP. This will provide more security because now we have all that stuff in JS and victim can access it, instead PHP can't be seen by the victim.
If you think is a good idea i can work on it :+1: 
@sophron @blackHatMonkey

**Comment by laozi999** [comment]
User agents can always be spoofed, as well as the other headers, but the beauty of PHP is that it's hidden from the client, which could serve as an extra security layer.

**Comment by sophron** [comment]
Hello @Splinter0,

> Hi guys, i researched around and i found that is actually possible to integrate PHP into our tornado webserver using the command php /template-folder/*.php, using subprocess to PIPE all the informations. 

Tornado doesn't seem to support PHP. Running PHP though subprocess is a different thing. You may be able to execute some PHP code through Python but you can't have the HTTP processing of a PHP web app that way.

>This will provide more security because now we have all that stuff in JS and victim can access it, instead PHP can't be seen by the victim.

If what worries you is the victim viewing the client source code, obfuscating the JS code is probably the way to go. 

> If you think is a good idea i can work on it 👍

I don't find a reason for supporting a server-side language. We still can do server-side processing with Tornado if needed. 

Tornado

**Comment by Splinter0** [comment]
@sophron If not using PHP how can we obfuscate the js code that now handles ```POST``` requests and user agent etc..? I mean we could use only tornado sintax ( the ```{{ target_ap }}``` or ```{% if 1==1 %}``` sintax ) but is it possible to execute things like ```POST``` requests?

**Comment by JetseVerschuren** [comment]
You could use [jsfuck](http://www.jsfuck.com).

**Comment by sophron** [comment]
As @JetseVerschuren noted, there are many online tools to obfuscate your Javascript code.

Supporting PHP would be overhead.
