### ISSUE TITLE
Server choice

### ISSUE THREAD

**Issue by blackHatMonkey** [wifiphisher/wifiphisher#556]
This thread is dedicated to finding alternatives to our current server(`tornado`) in order to improve performance if possible.

A possible alternative could be [cherrypy](http://cherrypy.org/) which could be used in combination with [jinja2](http://jinja.pocoo.org/).

**Comment by sophron** [comment]
What exactly is the problem with Tornado? Performance is not crucial for what we do. Even though, Tornado is <a href="https://en.wikipedia.org/wiki/Tornado_(web_server)#Performance">known for its speed</a>.

**Comment by laozi999** [comment]
More on this discussion at https://github.com/wifiphisher/wifiphisher/issues/539

@sophron I think this was inspired by @Splinter0's findings when testing wifiphisher on the raspberry pi 3

Wifiphisher used to run with ease before the latest major upgrades (I'm assuming the tornado upgrade).

Now the rpi3 struggles to handle simple requests as the tool requires too much CPU.

This means it's either time to upgrade hardware or finding a lighter server.

I've been using a very lightweight Ruby server lately called Sinatra, it's extremely simple, but probably not as light as the Phusion Passenger server.

I don't think there's a lighter server than Passenger out there yet, it's very focussed on performance and supports Python applications.

**Comment by sophron** [comment]
@laozi999 We don't want to include a web server. We want to include a Python web framework that we can customize to act as a web server.

As I said previously, Tornado is noted for its high performance. It offers support for rpi3 as well. If @Splinter0 encountered any issues, we need to focus on solving these instead. Maybe there's a bug in our logic or  maybe @Splinter0 setup is missing something.

**Comment by blackHatMonkey** [comment]
Here is a [benchmark](https://klen.github.io/py-frameworks-bench/) that I found online. Another good alternative could be [bottle](http://bottlepy.org) as it is easy to setup and supports python 3 as well.

**Comment by sophron** [comment]
@blackHatMonkey Performance is not really top on our requirements list. Maturity of the project is more important.

We need to have a concrete reason for moving from Tornado.
