### ISSUE TITLE
Facebook Phishing Scenario doesn't accept usernames and phone number as login

### ISSUE THREAD

**Issue by NourEddineX** [wifiphisher/wifiphisher#557]
when I type a username in the Email text box and write anything into password I get strange error and I don't get credentials on my linux shell

Distro: Manjaro 17.0
Wifiphisher version: latest (I installed it yestetday)

**Comment by blackHatMonkey** [comment]
Hi @NourEddineX thanks for opening an issue.
- What error are you getting?
- What scenario are you using?

**Comment by NourEddineX** [comment]
I didn't get any error
I'm using OAuth Scenario

**Comment by laozi999** [comment]
@NourEddineX 

> when I type a username in the Email text box and write anything into password I get strange error

What is the error you speak of?

**Comment by NourEddineX** [comment]
yes

**Comment by laozi999** [comment]
That's a JS alert, not a real response.

Maybe it asks for the password twice.
Did you try logging in twice?

**Comment by hellvetica42** [comment]
The python code checks if there's an "@" sign in the email and checks if the password is at least 8 characters long. 
If it's not it thows an alert.

**Comment by hellvetica42** [comment]
You can disable it by editing the code

**Comment by hellvetica42** [comment]
(actually it might not be the python code I haven't looked at it for a while I'm not sure)

**Comment by blackHatMonkey** [comment]
@NourEddineX As others have said you just need to edit the `Javascript` code inside the `HTML` file in order to change it's behavior. I'm closing this but if you have any more questions feel free to reopen the issue :smile:.
