### ISSUE TITLE
Changing name of fakeAp

### ISSUE THREAD

**Issue by gabrig** [wifiphisher/wifiphisher#561]
Hi!
Great program, but I was thinking to use it with another AP name. Is there a chance do to this?
What I would like to achieve is to make a fakeAP with a different name from the one that I've cloned (ie. I make a fakeAP from "wifihome" and change the name to "wifiwork").

I have not found a way to do this and I would like to know if this can be done.

Thanks guys!

**Comment by sophron** [comment]
You can use the `--essid` option.

**Comment by gabrig** [comment]
Thanks for replying.

Yes, I saw this in the readme, but I don't actually know how to do this. 
When I run "wifiphisher" from the terminal, it automatically assign the 2 wifi cards and show me the list of possible AP.
What I want to do is just a rogueAP with a different name from the original one, which doesn't deauth the real AP, but just stay there like an open AP. If someone connect, the "option 4" (facebook login phish) shows up and once he/she enter datas (both correct or incorrect) connect to the internet, making it less fake.

Do I need to start wifiphisher in a different way, specifying the --essid in the beginning?

Thanks again

**Comment by sophron** [comment]
Yes,

You need to type `wifiphisher --essid wifiwork --nojamming`. The `--nojamming` option will not jam any target AP.

**Comment by gabrig** [comment]
Thank you very much, actually after reading again (and better!) the readme, I found it was pointed out there. 
My bad, sorry.

Last question is: if the password (or login) contain symbols (like @ # _ - !), the terminal gives the urlencode value, like %40 for @.  Is there a way to show the right symbol? 
Also, when I run the program, my terminal continue to flicker (I think that the GET/POST continue to print results), but if many people connect, I lose some entry, because they go up and I can't scroll up the window. Is it normal? And is there a way to print out all the results, when I decide to stop the program?

Thanks for your help!

**Comment by laozi999** [comment]
> Also, when I run the program, my terminal continue to flicker (I think that the GET/POST continue to print the same result), but if many people connect, I lose some entry, because they go up and I can't scroll up the window

https://github.com/wifiphisher/wifiphisher/issues/537

**Comment by gabrig** [comment]
@laozi999 Thanks for the link, I've posted there!
