### ISSUE TITLE
error:[errno95] operation not supported

### ISSUE THREAD

**Issue by salemalkhabuli** [wifiphisher/wifiphisher#563]
error:[errno95] operation not supported

**Comment by blackHatMonkey** [comment]
Hi @salemalkhabuli Can you provide us with more information such as:
- what distribution are you using?
- can you post the full error?
- what arguments are you using if any(eg. `--nojamming`)?

**Comment by blackHatMonkey** [comment]
@salemalkhabuli I have deleted your other posts in different threads please don't spam other threads as it will not going to get you help any faster.

**Comment by salemalkhabuli** [comment]
raspberry pi 3 and mobile and mobilessh.apk and router tp-link model: TL-wn822n wireless usb adapter

**Comment by blackHatMonkey** [comment]
Can you provide the full error message?

**Comment by salemalkhabuli** [comment]
file"/user/local/lib/python2.7/dist-packages/PYRIC-0.16.3-py2.7.egg/pyric/pyw.py",line1287,in freqset 
  raise pyric.error(e.errno,e.strerror)
error:[errnp 95] operation not supported 
lqqqqq
lqqqqq
lqqqqq
lqqqqq
lqqqqq
lqqqqq
lqqqqq

**Comment by blackHatMonkey** [comment]
As stated in #539 you need to have two wireless adapters since the one built in to `rpi` is not compatible out of the box. You may want to follow this [advice](https://github.com/wifiphisher/wifiphisher/issues/539#issuecomment-289018327).

**Comment by salemalkhabuli** [comment]
need  ALFA

**Comment by blackHatMonkey** [comment]
Since there has been no response I'm closing this. Feel free to re-open if needed.
