### ISSUE TITLE
Use router as one of the wireless interfaces

### ISSUE THREAD

**Issue by BetaStacks** [wifiphisher/wifiphisher#567]
Is it possible to plug in a router to my eth0 port to use as the AP? 

The internal chip being used is not strong enough for it to reach through out my house.

**Comment by blackHatMonkey** [comment]
@BetaStacks Unless you modify internal firmware of the router it's not possible. That being said if you are going that route it would be better to just run a open access point on your router and use `MITM` attacks from there.
