### ISSUE TITLE
Latest wifiphisher 1.3 blocked by chrome. 

### ISSUE THREAD

**Issue by norasyraf** [wifiphisher/wifiphisher#568]
**Version**: 1.3

**Distribution**: 

**Summary**: 

**Description**: 

**Steps to Reproduce**:

**Expected VS actual behavior**: 

**Script output**:

Edited by @blackhatmonkey for clarity.

**Comment by norasyraf** [comment]
Latest v 1.3 was blocked by chrome. The login page did not pop up. Works fine on firefox.

**Comment by JetseVerschuren** [comment]
Can you post screenshots of the developer console?

**Comment by laozi999** [comment]
You didn't fill out any of the info in your first message. Please let us know exactly what goes wrong so we can help out

**Comment by ryuk321** [comment]
The connectivity check is running. It says its not safe to browse hackers are trying to steal your information. The frimware page that wifiphisher should execute it doesnt show up.
