### ISSUE TITLE
Custom hostapd

### ISSUE THREAD

**Issue by sophron** [wifiphisher/wifiphisher#569]
I believe it's time to host our own version of hostapd. We can get influence from projects such as <a href="https://github.com/sensepost/hostapd-mana/">hostapd-mana</a> and <a href="https://github.com/OpenSecurityResearch/hostapd-wpe">hostapd-wpe</a>.

Attacks like, KARMA, Evil Twin against Enterprise WLANs or Evil Twin with WPS-PBC technique can then be implemented. 

Our version of `hostapd` should come with Python bindings that will let us customize our Access Point in a more fluent way.

**Comment by blackHatMonkey** [comment]
I would rather implement [this](https://github.com/rpp0/scapy-fakeap.git) which you suggested in #128 over creating a custom version of `hostapd`.

**Comment by sophron** [comment]
As you can see in the discussion <a href="https://github.com/rpp0/scapy-fakeap/issues/6">here</a> scapy doesn't appear to be really efficient for our needs. You can probably give it a try if you want to.

Apart from KARMA though, we may want to do more tricks (e.g. WPS PBC technique). Implementing WPS Push in Python (if possible) will be a pain. Hostapd (and C) will give us the flexibility to implement time-critical operations.
