### ISSUE TITLE
"Advanced" mode

### ISSUE THREAD

**Issue by sophron** [wifiphisher/wifiphisher#570]
Instead of "jamming" (default) and "--nojamming" mode, we should have "normal" and "advanced" mode.

In "normal" mode, the user may run Wifiphisher with one wireless card and take full advantage of all the features provided through our custom `hostapd` (#569). Obviously, these would be the features related with the rogue Access Point.

In "advanced" mode, the user will need a second card. The second card will take advantage of our "attack" modules. These could be deauth, wps, lure10 and new ones. 

The modular architecture that switch between attacks will look like that:

```python
modules = ["deauth", "wps", "lure10"] 
while True:
    for module in modules: 
        sniff = getattr(module, 'sniff')
        sniff()

    for module in modules: 
        sniff = getattr(module, 'action')
        action()
```

**Comment by blackHatMonkey** [comment]
I would suggest coming up with a API for the `engine` and it could be:
* require `start` method: to start the objects services
* require `exit` method: to clean up

**Comment by sophron** [comment]
This is done already.
