### ISSUE TITLE
Allow wireless interfaces to be used as internet interface

### ISSUE THREAD

**Issue by SkiddieTech** [wifiphisher/wifiphisher#571]
Running latest Kali 32 bit, fully updated and upgraded.
Everything else working fine. 
This is using the latest fresh 1.3 release. 

COMMAND: 
wifiphisher -aI wlan1 --internetinterface wlan0 --nojamming  --essid CONFERENCE_WIFI -p plugin_update

(wlan0 is connected to Internet using the built in Kali network manager)
Wlan1 is up)

OUTPUT:
```bash
[*] Starting Wifiphisher 1.3 at 2017-04-17 13:40
Traceback (most recent call last):
  File "/usr/local/bin/wifiphisher", line 9, in <module>
    load_entry_point('wifiphisher==1.3', 'console_scripts', 'wifiphisher')()
  File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.3-py2.7.egg/wifiphisher/pywifiphisher.py", line 776, in run
    engine.start()
  File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.3-py2.7.egg/wifiphisher/pywifiphisher.py", line 572, in start
    internet_interface = self.network_manager.set_internet_iface(args.internetinterface)
  File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.3-py2.7.egg/wifiphisher/common/interfaces.py", line 367, in set_internet_iface
    raise Exception
Exception
```
If i you need me to fully commit to the error "form" i will do so.

**Comment by sophron** [comment]
Hi @SkiddieTech,

As of now the `--internetinterface` does not work with wireless interfaces. It should work with any wired interface though.

**Comment by SkiddieTech** [comment]
Thankyou! Hopefully, there will be support for both mobile/GSM and wireless interfaces in the future :)

**Comment by sophron** [comment]
Yes, it's in our plans. :)

**Comment by blackHatMonkey** [comment]
@sophron Since you did some research what exactly is the problem of not using other types of interfaces.

**Comment by SkiddieTech** [comment]
@blackHatMonkey it seems to be the network manager installed with KALI.

**Comment by SkiddieTech** [comment]
Still getting an error when trying to use this with a wired interface.
http://vvcap.com/7Lm4IQL9Csx

**Comment by blackHatMonkey** [comment]
@SkiddieTech I have pushed a fix for this. Please let me know if you have any more problems :smile:.

**Comment by laozi999** [comment]
NetworkManager should be killed on startup, and the wireless connection should be resumed using dhclient.

**Comment by laozi999** [comment]
Correction: NetworkManager should be ditched all together.

Im joking but I'm also serious.

**Comment by blackHatMonkey** [comment]
This has been implemented. If you wish you use this feature you must update to the latest version from the `Github`.
