### ISSUE TITLE
On the way to v2.0

### ISSUE THREAD

**Issue by sophron** [wifiphisher/wifiphisher#572]
Hi guys,

Version 1.3 has been released and we are now on our way to v1.4. I've already <a href="https://github.com/wifiphisher/wifiphisher/milestone/5">marked the issues</a> that I believe we should focus on. Known bugs and stability issues should be tackled as well.

I'm glad that more people are getting aboard and participate to discussions. Of'course as the project is getting bigger and bigger, these contributions are very important. 

If there are any features that you want to see on v1.4 write them here or up-vote accordingly. 

Let's have fun making v1.4. :)

**Comment by blackHatMonkey** [comment]
@SkiddieTech 
> Add a --noerros tag to hide possible error / stack exception messages (So it does not fill the screen while you are working/pentesting)

There shouldn't be any errors on the screen in the first place. Warnings should be logged though.

>Add a --savecreds tag to automatically store possible gather creds on disk.

We have #427 and #537.

**Comment by SkiddieTech** [comment]
@blackHatMonkey 427 and #537 looks amazing. 
that IO interface looks awesome.

**Comment by sophron** [comment]
> Consider adding option for live-auto-translation of phishing scenarios ( I'm sure this can be done but would most lightly require the --internetinterface option aswell)

I'm afraid this would turn out bad. Machine translations are getting more effective each day but especially for technical terms the result is often inaccurate. For our attacks to be realistic it is important to not show any spelling mistakes. 

> Maybe adding an option to use a custom phishing scenario? (requesting path of the files and storing every post request as credentials)?

Have you checked the <a href="https://wifiphisher.org/docs.html">docs</a>? There's a section "Create a custom phishing scenario" that you may find interesting :)

**Comment by laozi999** [comment]
I have some mods in the work, but first I'll give v1.3 a try and see what new :)

**Comment by sophron** [comment]
We have already included many cool new features since our v1.3 release and there are more to come. I believe our new release is gonna be pretty huge and we should tag it as v2.0 instead of v1.4.

**Comment by mdeverdelhan** [comment]
The milestone  for the 1.4 release is marked as "Past due by 10 days". Any idea of when the new version will be available?

**Comment by sophron** [comment]
Hi @mdeverdelhan, 

Thanks for pointing this out. We agreed to focus on a big 2.0 release instead. It should be out around Christmas.
