### ISSUE TITLE
Install portal templates

### ISSUE THREAD

**Issue by stefjoe12** [wifiphisher/wifiphisher#577]
Hi lads, 

I created a responsive McDonald's portal template but i am unable to install it. Can someone explain me how to install it?

I will post the template if i tested it. 

Greetings, 
stefjoe12

**Comment by sophron** [comment]
Hi @stefjoe12,

Have a look at the <a href="https://wifiphisher.org/docs.html">docs</a>. There's a section called "Creating a custom phishing  scenario" that you should follow.

**Comment by stefjoe12** [comment]
Thanks, didnt saw that document. I will post the McDonald's portal asp!

**Comment by blackHatMonkey** [comment]
@stefjoe12 You should make a PR in [this](https://github.com/wifiphisher/extra-phishing-pages) repository when you are ready :smile: .

**Comment by stefjoe12** [comment]
Oké man! It looks very original haha @blackHatMonkey

**Comment by stefjoe12** [comment]
@blackHatMonkey can you help me with testing out ? I can send u template.

**Comment by blackHatMonkey** [comment]
@stefjoe12 
Here is what you should do:
- make a fork of [this](https://github.com/wifiphisher/extra-phishing-pages) repository
- create a new branch
- add your files
- commit
- make a PR

I can then test it and let you know :smile:.

**Comment by JavaRockstar** [comment]
I'm having a very similar problem I add all the required Post data however I can not get an output when pressing a button I have added to the page also I'd love to see a some for various fast food restaurants good luck I hope to see your Mcdonalds template :).
