### ISSUE TITLE
Any idea why this is happening in Kali Linux when I use wifiphisher?

### ISSUE THREAD

**Issue by djdisikd** [wifiphisher/wifiphisher#578]
![img_20170421_171857](https://cloud.githubusercontent.com/assets/17978000/25271596/3aaf3916-26b7-11e7-8356-8d5c1771821f.jpg)

**Comment by JetseVerschuren** [comment]
Does it happen every time?

**Comment by djdisikd** [comment]
Yeah every time

**Comment by blackHatMonkey** [comment]
@djdisikd Are you running `kali` in a virtual environment or natively?

**Comment by djdisikd** [comment]
I am running Kali Linux with a CD

**Comment by blackHatMonkey** [comment]
@djdisikd This problem is definitely not normal response when launching `wifiphisher`. You have check the logs to see what went wrong.

**Comment by djdisikd** [comment]
I checked but I still don't know what went wrong

**Comment by JetseVerschuren** [comment]
Can you post your logs?

**Comment by JavaRockstar** [comment]
Are you using USB 3 for any of your cards by any change what is it like when you revert to USB 2 if so.

**Comment by djdisikd** [comment]
I have two adapters

**Comment by djdisikd** [comment]
I am using the two adapters (USB) at the same time

**Comment by djdisikd** [comment]
I check the logs but still I don't understand what is going wrong

**Comment by JetseVerschuren** [comment]
Again, can you post your logs?

**Comment by djdisikd** [comment]
ok

**Comment by blackHatMonkey** [comment]
I'm closing this as you have not provided any new information. If you want to add new information feel free to open it again.
