### ISSUE TITLE
No access point has been discovered yet.

### ISSUE THREAD

**Issue by J4FPredator** [wifiphisher/wifiphisher#580]
Hello.
Excuse me for any grammatical errors.
I just installed wifiphisher on kali linux but I'm having a problem:
When I run wifiphisher by the terminal this is what I see:
![e2oshhy](https://cloud.githubusercontent.com/assets/25112506/25289937/bda360b8-2699-11e7-9fe2-ee598c85b4db.jpg)

My wireless network adapter: D-Link DWL-G122 (I don't know if it supports the AP mode or the Monitor mode)

Edited by @blackhatmonkey: Fixed the screenshot
Can someone help me?

FIXED
I bought a new wireless network adapter (TP-LINK TL-WN722N)

**Comment by JetseVerschuren** [comment]
Your hyperlink doesn't work i needed to copy it manually into the addresss bar.6

**Comment by J4FPredator** [comment]
@JetseVerschuren  Excuse me, I fixed it!

**Comment by blackHatMonkey** [comment]
@J4FPredator are you using two wireless interfaces or the `--nojamming` `-nJ` flag?

**Comment by J4FPredator** [comment]
@blackHatMonkey I'm not using the `--nojamming` `-nJ` flag, what you intend for "are you using two wireless interfaces?"

**Comment by blackHatMonkey** [comment]
@J4FPredator If you look at the [requirements](https://github.com/wifiphisher/wifiphisher#requirements) you need two interfaces to run the tool since one is needed to create the fake access point and the other to deauthenticate. That is unless you run the `--nojamming` flag which allows you to only use one interface but in exchange for losing deauthentication.

**Comment by J4FPredator** [comment]
@blackHatMonkey Ah ok, yes I have 2 wireless interfaces, I just edited my last comment!

**Comment by blackHatMonkey** [comment]
@J4FPredator Have you tried using the `-aI` or `-jI` to see if a specific card is a problem?

**Comment by J4FPredator** [comment]
If I type wifiphisher -aI, I receive this error: wifiphisher: error: argument -aI/--apinterface: expected one argument

**Comment by blackHatMonkey** [comment]
Run

```bash 
iwconfig
```
Assuming you have the following interfaces `wlan0` and `wlan1` you could run:


```bash
wifiphisher -aI wlan0 -jI wlan1 
```
or

```bash 
wifiphisher -aI wlan1 -jI wlan0
```

**Comment by J4FPredator** [comment]
@blackHatMonkey I done it, but the problem isn't solved

**Comment by J4FPredator** [comment]
@blackHatMonkey  I tried to disconnect my usb wireless adapter and I run wifiphisher with the --nojamming flag, and it works (obviusly it doesn't DeAuth the devices), so, maybe, is the wireless adapter to be broken or unsupported, right?
Can you suggest me which wireless adapter I should buy?

**Comment by blackHatMonkey** [comment]
@J4FPredator checkout #558. People have posted their cards there and the `TP-Link TL-wn722N` is a good card and I use it myself for testing.

**Comment by falconsy** [comment]
dear hi i face same this issue u have to stop scan and u have to re start again ...

**Comment by sophron** [comment]
My guess is that the card probably becomes invalid (e.g. because the USB falls out). Pyric has `pyw.validcard(w0)` that we should call regularly and exit with an appropriate message if needed.

**Comment by vay3t** [comment]
i can confirm this error.

**Comment by Eishfaq** [comment]
i have the same problem .... help me to solve it ....

**Comment by siro99** [comment]
try  wifiphisher -aI wlan0 -eI wlan1  (make sure which one supports monitor mode)

**Comment by amitgiri723** [comment]
i have also the same problem , but i have dual boot kali linux and windows

please help!

**Comment by jonkajmr** [comment]
I have the same problem. I am using a Raspberry Pi 3b+ Kali Linux nexmon patch(WiFi internal support monitor mode). USB WiFi pau06, how can fix it?

**Comment by thunderbuns** [comment]
Did anyone manage to fix this problem?

**Comment by MaritoBorges** [comment]
hi, i have a tl-wn722n v3 card, but it doesnt work with wifiphisher and fluxion, what is the problem?
