### ISSUE TITLE
Test new interface detection

### ISSUE THREAD

**Issue by blackHatMonkey** [wifiphisher/wifiphisher#582]
I have re-designed the interface detection for `wifiphisher`. I need some help testing it to make sure everything is working fine. The files are in the `interface-refactor` branch. You can post any bugs to this thread. All the help for testing is appreciated :smile:.

**Comment by laozi999** [comment]
```
root@Fs4C:~# sudo python /root/Desktop/wifiphisher-interface-refactor/bin/wifiphisher
Traceback (most recent call last):
  File "/root/Desktop/wifiphisher-interface-refactor/bin/wifiphisher", line 11, in <module>
    from wifiphisher.pywifiphisher import run
  File "/root/Desktop/wifiphisher-interface-refactor/wifiphisher/pywifiphisher.py", line 735
    deauthentication = None
                   ^
SyntaxError: invalid syntax

```

`python setup.py build` doesn't work either

**Comment by JetseVerschuren** [comment]
I get the same error.

**Comment by JetseVerschuren** [comment]
You made a type error on line 733 you forgot to close.
`mon_MAC = mon_mac(mon_iface
deauthentication = None`

**Comment by anakin1028** [comment]
@blackHatMonkey 
I have made a pull-request for fixing the above mentioned problem and some other TypeErrors in refactoring process.

**Comment by blackHatMonkey** [comment]
Thanks to @anakin1028 the problems stated are fixed. Please update and let me know if you find any more errors :smile: :beer: .

**Comment by anakin1028** [comment]
@blackHatMonkey, thanks, it's ok for me now :+1:
