### ISSUE TITLE
Cant get custom template to work

### ISSUE THREAD

**Issue by stefjoe12** [wifiphisher/wifiphisher#584]
I just made a McDonald's Portal. But if i want to run it i get this error message : 

```bash
wifiphisher --nojamming --essid "McDonald's free Wifi" -p mcdonalds
[*] Starting Wifiphisher 1.3GIT at 2017-04-22 13:02
[+] Selecting wlan1 interface for creating the rogue Access Point
[*] Cleared leases, started DHCP, set up iptables
Traceback (most recent call last):
  File "/usr/local/bin/wifiphisher", line 9, in <module>
    load_entry_point('wifiphisher==1.3', 'console_scripts', 'wifiphisher')()
  File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.3-py2.7.egg/wifiphisher/pywifiphisher.py", line 776, in run
    engine.start()
  File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.3-py2.7.egg/wifiphisher/pywifiphisher.py", line 643, in start
    template = select_template(args.phishingscenario, self.template_manager)
  File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.3-py2.7.egg/wifiphisher/pywifiphisher.py", line 193, in select_template
    raise phishingpage.InvalidTemplate
wifiphisher.common.phishingpage.InvalidTemplate: The given template is either invalid or not available locally!
```

you can test the McDonalds portal from here : 
https://github.com/stefjoe12/extra-phishing-pages/tree/mcdonalds-login/McDonalds-login

please help me out and make this one for real :+1:

**Comment by blackHatMonkey** [comment]
@stefjoe12 The name is case sensitive so the correct way to call it would be
```bash
wifiphisher --nojamming --essid "McDonald's free Wifi" -p McDonalds-login
```

**Comment by JetseVerschuren** [comment]
I just wanted to comment

**Comment by JetseVerschuren** [comment]
30 seconds to late

**Comment by thackery** [comment]
Hi everybody, how can use extra-phishing-pages ? 
i copied folder i get from git with all others in .../data/phishing-pages it is the good way ?

thanks for help

**Comment by blackHatMonkey** [comment]
@thackery You either have to install `wifiphisher` again with
```bash
sudo python setup.py install
```
or just run it from the directory
```bash
sudo python bin/bash
```

And it should show up in the list.

**Comment by thackery** [comment]
wifiphisher is installed and run correctly so when i would run with custom page like device_modal for example. (command wifiphisher -nJ -p device_modal ) i got message error : the given template is either invalid or not locally!

**Comment by blackHatMonkey** [comment]
@thackery if `wifiphisher` is installed using:
- `pip`: You have to grab a copy off git and place all the new templates in the `data/phishing-pages` directory and install it
- `git`: Place all the new templates in the `data/phishing-pages` directory and install it

**Comment by thackery** [comment]
Thank you it s work !! good job guy !!!

**Comment by iobj** [comment]
Hello, 

Sorry if I sound like a noob. I copied the extra phishing folder and reinstalled it and still no luck. Do I need to place each scenario individually or can they stay in the extra phishing folder?

**Comment by sophron** [comment]
You don't want to copy the `extra-phishing-pages` directory. You want to copy the contents of the directory (the directories inside) in the `phishing-pages` directory of Wifiphisher.

**Comment by roufato** [comment]
that works for me /usr/local/lib/python2.7/dist-packages/wifiphisher-1.3-py2.7.egg/wifiphisher/data/phishing-pages/

**Comment by iobj** [comment]
Thank you! I forgot to reply I moved the wrong contents over. It is now working successfully for me :+1: 

Thanks!
