### ISSUE TITLE
Address 3 of deauth frame not correct when use --essid field

### ISSUE THREAD

**Issue by anakin1028** [wifiphisher/wifiphisher#593]
Hi, 
I just tried the following commands:
           `wifiphisher --essid wawa -pK 12345678 -p plugin_update`
and from sniffer capature I found that the address 3 is not correct as the following capture:
From the figure one can see that the BSSID field is equal to 0:0:0:0:0:0 which is not correct.

![deauh_frame_not_correct](https://cloud.githubusercontent.com/assets/6182530/25529645/994c9696-2c55-11e7-89fb-b227176c3d92.png)

And from the code, I found that it's because that when --essid is being used, the variable `ap_mac` is not correctly set, so the value is None.

To solve the problem, I think durring ap selection, we need to sniff say 2 seconds[if beacon interval is 100ms, then we can hear about 20 beacons] to hear the beacon and extract the ssid fields which equal to the essid, and forge all those BSSIDs.

If we send the invalid address 3 deauth, the client will not be disassociated, so this must be fixed.
How do you guys think?
**[UPDATE]**
Another minor problem is that when -essid option is used the channel is fixed to the constant value which is equal to 6 as defined in constant module. This is also problematic, if the APs are deployed other than channel 6, then we can do nothing.

**Comment by sophron** [comment]
Nice catch once again @anakin1028!

The thing with `--essid` is that users may run it when an AP that broadcasts the same ESSID is not even in range. For example, one may want to spawn an AP with ESSID "Free WiFi" to lure victims in a public area (e.g. in a mall) even when there are no other APs broadcasting the same ESSID around. I believe in that case, the script should deauthenticate all wifi clients and access points within range.

Now, if the user wants to target a password-protected AP that is within range and create a rogue AP that is also password-protected, he shouldn't use `--essid` option. He should manually select an Access Point during AP selection phase. I understand that this may be misleading as users may believe that `--essid` replaces the AP selection phase when in reality, `--essid` should be used whenever we don't want to target an AP in range. Maybe a new option `--target-ap` (that should be forbidden to be used along with `--essid`) can be introduced. Whenever the user runs `--target-ap` can be an alternative for AP selection phase.

**Comment by anakin1028** [comment]
@sophron thanks for your detail explanation! But the thing is the deauth frames' addresses are still not correct. So the jamming process will have no use. 

Consider the code in the following: since `_ap_bssid` is not defined, the code will never add the clients into the deauth list.

    ```
     if receiver == self._ap_bssid:
         self._observed_client.append(sender)
         self._craft_and_add_packet(sender, self._ap_bssid)
         self._craft_and_add_packet(self._ap_bssid, sender)
    ```
So here either we just modify to deauth all the clients or we have to classify which scenario is. Either manually select AP case or --essid case.

Another things need to consider is even use --essid case, you only deauth the clients on the same channel '6', and other clients will not get affect.

**Comment by sophron** [comment]
Correct, the bug exists. I believe we should fix by entering a "frenzy" mode where we deauth all clients and APs that are within range whenever `--essid` is used.

>Another things need to consider is even use --essid case, you only deauth the clients on the same channel '6', and other clients will not get affect.

Yes, we need to include a channel hopping mechanism and deauth all clients in every channel. The channel hopping should be part of the #570. If you are planning to make a patch for this, you can leave this aside for now until we have #570 ready (probably within the upcoming week).

**Comment by anakin1028** [comment]
@sophron, OK I think I can fixed the first part: the deauth address 3 and fixed the second part later.

**Comment by anakin1028** [comment]
If the command option `--essid` is used in #497, it it possible the same issue with this thread.

**Comment by anakin1028** [comment]
close #593 via #664
