### ISSUE TITLE
raspberry pi 3 kali version

### ISSUE THREAD

**Issue by grendle** [wifiphisher/wifiphisher#595]
A working version for Kali linux on the raspberry pi 3, arm platform.

**Comment by stefjoe12** [comment]
Just set your Wireless USB to monitor mode with :
**sudo airmon-ng start wlan1**

run wifiphisher with the monitor interface :
**sudo wifiphisher --nojamming --essid "FREE WI-FI" -p oauth-login -aI wlan1mon**

and its working on your Raspberry Pi. 
I got this working on my Raspberry Pi Zero W. 
You can view the program running with VNC viewer if u connect to your fake AP

**Comment by grendle** [comment]
ok ty, but curse you, wife making me mow lawn and I see this, hmm, how can i get out of mowing lawn to start up the pi and try this!!!! Seriously tho, thanks, Ill try this today.

**Comment by stefjoe12** [comment]
Opposite here today. I was figuring it out in the garden while my girlfriend was mowing the lawn. Haha! Let me know if it worked for you.

**Comment by yassinios** [comment]
Please i need Support <3
can u Subscribe My Youtube Channel please
https://www.youtube.com/watch?v=NNV3tfCIr_w

**Comment by grendle** [comment]
well got farther that time.
after it says  [*] Captured Credentials:   
the next line says   [!] Closing
and nothing. it looked good up to that point. 
it starts, selects the interface, changes MAC, clears leases starts DHCP and sets up iptables, selects 0Auth login page template, starts fake access point, then captured credentials and close. like i said, it got farther than b4, had to install tcpdump also. however, now she wants to play neverwinter, so ill be back to this when she goes for a nap i think . lol.

**Comment by stefjoe12** [comment]
Damn, i installed a lot of FakeAP. Maybe u miss some dependencies. I tought i had the solution. Sorry bro

**Comment by grendle** [comment]
no reason to be sorry, you've helped 100%, awesome job ty. you got me pointed in the right direction and got me farther than i was!!! thank you peace man!!!

**Comment by grendle** [comment]
also, just fyi, it seems to be a hostapd problem. got it running then when you select attack method it tries to set up and says hostapd problem.

**Comment by stefjoe12** [comment]
Maybe you should install and try the Sticky Fingers Kali image from re4son. Thats what i have installed atm.

**Comment by grendle** [comment]
downloading it now, ty, but after working on this for a few hours last night, on my laptop as well, i suspect i need to get better adapters. my laptops built in wifi adapter, believe it or not works great with aircrack, and has ehem "visited" other routers successfully.
