### ISSUE TITLE
Killing VNC when AP launches

### ISSUE THREAD

**Issue by SkiddieTech** [wifiphisher/wifiphisher#596]
So currently VNC'ing into my pie over eth0 with an static ip , however when wifiphisher launches the fake AP, the connection is killed.

VNC is running fine with and without network-manager running, so what is it killing clearing?
Anyway i can exclude eth0 from that list? possible reffer me to the point in the code?

**Comment by anakin1028** [comment]
@SkiddieTech 
While I don't have the pie, I have used the tight vnc server for my linux-laptop, and wifiphisher works fine for me.
From the code, I don't think wifiphisher will kill this connection. Can you post the `ifconfig` output and maybe check `ps aux|grep vnc` to confirm the process is being killed?

**Comment by SkiddieTech** [comment]
i will double check that it is not the process being killed, it must have something to do with it resetting some internet interface settings. 
On my VNC startup service script i have a simple "ifconfig eth0 10.0.0.1" that sets an static IP, so i can simply turn an interface card on my windows laptop into a little "private" network for VNC to operate in. 

I guess i can set this more "statically" inside some network config files on the Pie?

**Comment by anakin1028** [comment]
yeah, can you change the static IP address to another one? maybe `192.168.1.1` since our fakeap also use `10.0.0.x` so this will interfere your vpn connection.

**Comment by SkiddieTech** [comment]
@anakin1028 will try and report back! might explain it

**Comment by SkiddieTech** [comment]
@anakin1028 tried the 192.168.1.XXX netmask , same results. The last thing i see is "Starting the rouge access point" before VNC drops.

**Comment by anakin1028** [comment]
@SkiddieTech Thanks for your report.
What the exact command do you use? And if you are comfortable with `pdb`, can you try to trace at which statement cause the VNC connection drop?

From your observation, the statement may be in the file `pywifiphisher.py`  and around at the following code piece:
```python
    try:
        self.access_point.start()
        self.access_point.start_dhcp_dns()
```

**Comment by blackHatMonkey** [comment]
@SkiddieTech It would be also helpful to know:
- Which `VLC` are you running?
- Are you using the `--internetinterface` option?
- Did this happen to previous version of `wifiphisher` or is it new?
- If it is new can you try with previous versions and report back?

**Comment by SkiddieTech** [comment]
@blackHatMonkey 
01. TightVNC
02.Nope
03. Unknown
04. Will do

**Comment by blackHatMonkey** [comment]
@SkiddieTech Can you possibly try the latest version and see if there is a difference?
