### ISSUE TITLE
Does this software work for all modems?

### ISSUE THREAD

**Issue by J4FPredator** [wifiphisher/wifiphisher#597]
Hello.
Excuse me for any grammatical errors.

I was testing my home connection using this software:
I connected my phone to the access point and I tried to use this software for disconnect my phone and to force it to connect to my (fake) AP, but this simply doesn't work.

When I start the (attack) my phone disconnects by the original AP and after about 1 second it reconnect itself on the same AP.

Am I doing something wrong or is possible that this software does not work for all the cases?
Thank you!

**Comment by anakin1028** [comment]
@J4FPredator if possible can you post the sniffer log for this. You can use wireshark or tcpdump and use the deauth interface [i.e. the one you choose for jamming process] to sniff the frames on the air .


After reconnecting to the original AP, does your phone disconnect again, or it connects to the original AP forever?  And also what command options do you use?

For auto-connecting, you can check the thread #560, Sophron gives a explanation in that thread.

**Comment by blackHatMonkey** [comment]
@anakin1028 I think he is referring to the fact that it is not connecting automatically to the fake AP. 

@J4FPredator Currently the device doesn't connect to the fake AP automatically and it has to be done manually.

**Comment by J4FPredator** [comment]
Excuse me for the late!

@blackHatMonkey I didn't understand! I'm not English, so probably I have lost something while I was reading the info.

Thank you!
