### ISSUE TITLE
Create a twitter handle for wifiphisher

### ISSUE THREAD

**Issue by blackHatMonkey** [wifiphisher/wifiphisher#601]
@sophron  I think it would be great if we have a twitter handle for `wifiphisher` to promote as well as give periodic updates on there.

**Comment by hackertron** [comment]
I can manage the twitter page if you want . what say ?? 👍  

Handle  @WifiPhisher

**Comment by blackHatMonkey** [comment]
@sophron Can you add the twitter page to the `readme`.

**Comment by sophron** [comment]
Twitter account is here: https://twitter.com/wifiphisher
README has been updated.
