### ISSUE TITLE
Wifiphisher don't work on Qualcomm Atheros QCA9565 / AR9565 Wireless Network Adapter

### ISSUE THREAD

**Issue by kerncoola** [wifiphisher/wifiphisher#602]
Hello,
Excuse me for any grammatical errors.
I got a trouble, if anyone will help me, I will appreciate it.

**Following is terminal logs,**

Network controller: Qualcomm Atheros QCA9565 / AR9565 Wireless Network Adapter (rev 01)

root@evil-god:~# wifiphisher --nojamming
[*] Starting Wifiphisher 1.3GIT at 2017-05-06 09:03
[+] Selecting wlan0 interface for creating the rogue Access Point
[+] wlan0 mac address becomes 00:00:00:9d:98:fa
[*] Cleared leases, started DHCP, set up iptables

Available Phishing Scenarios:

1 - Firmware Upgrade Page
	A router configuration page without logos or brands asking for WPA/WPA2 password due to a firmware upgrade. Mobile-friendly.

2 - Network Manager Connect
	Imitates the behavior of the network manager. This template shows Chrome's "Connection Failed" page and displays a network manager window through the page asking for the pre-shared key. Currently, the network managers of Windows and MAC OS are supported.

3 - Browser Plugin Update
	A generic browser plugin update page that can be used to serve payloads to the victims.

4 - OAuth Login Page
	A free Wi-Fi Service asking for Facebook credentials to authenticate using OAuth

[+] Choose the [num] of the scenario you wish to use: 4
[+] Selecting OAuth Login Page template
[*] Starting the fake access point...
[+] **_Captured credentials:_**
[!] Closing
root@evil-god:~# 

I choose the num of the scenario, then directly closing, what happended?

**Comment by anakin1028** [comment]
@kerncoola I guess it is because that hostapd is launched fail. Can you manually try whether your adapter can lunch the hostapd correctly?

**Comment by kerncoola** [comment]
@anakin1028 It works, thanks😊😊

**Comment by anakin1028** [comment]
Ok nice :)

**Comment by davidfrh** [comment]
hello i'm french i have the same problem but i didn't understand the reply of anakin1028 could you explain more please, thanks ;)

**Comment by anakin1028** [comment]
@davidfrh 
Have you done `python setup.py install` for wifiphisher?
also do you have `hostapd` install in your system? you can use the command `which hostapd` to check that.

**Comment by davidfrh** [comment]
Yes and yes i have hostapd in my computer :/
