### ISSUE TITLE
Captive WiFi not working on Android

### ISSUE THREAD

**Issue by ghost** [wifiphisher/wifiphisher#604]
**Version**: Wifiphisher 1.3 

**Distribution**: Kali Linux 32bit Mate

**Summary**: Android devices not doing the captive WiFi thing that happens on most public WiFi

**Description**: When i create the fake WiFi and devices connect to it android does not show "Sign in to network" (Pictures of what should happen normally: [Android](http://4.bp.blogspot.com/-dw9MiaM5GmE/VaFd4t_QmZI/AAAAAAAAFuM/OTMfLTcdUeA/s320/starbucks.png))  You have to manually open a web browser app on the device and go to any link for the phishing page to show up. Everything else in WiFi phisher works, this is the only problem I'm having. I tried 2 different WiFi adapters and different Android devices and i still had the problem.

**Steps to Reproduce**: Create fake WiFi and connect an android device to it

EDIT: I tested it again and it works on iOS, but not on android.

**Comment by anakin1028** [comment]
@crystalg21  
I think currently we haven't implement it. While I am not so familiar with Captive Portal, after doing some research, it seems that for android devices we have to respond the following http GET request: `clients3.google.com`

The following links are for references:

[This explains how to response with the particular http requests for different OS](https://serverfault.com/questions/679393/captive-portal-popups-the-definitive-guide)

[And this link gives how the Android devices judge whether the service behind the site is Captive Portal:](https://android.stackexchange.com/questions/123129/how-does-wifi-in-android-detect-if-the-device-has-to-sign-in-or-not) 

Maybe @blackHatMonkey can give more onions.

**Comment by sophron** [comment]
@anakin1028 is correct. Have a look at #524.

**Comment by blackHatMonkey** [comment]
@sophron @anakin1028 Are you guys not getting any portals on android?

@crystalg21 Do you receive any `GET` messages from `google` or `apple` in the `HTTP requests` section?

**Comment by crystalg21** [comment]
@blackHatMonkey  I tested it again and captive does work on iOS, but it doesn't work on android

Android 4.4.2 Phone (Captive did not work)
GET  request from 10.0.0.2 for http://clients3.google.com/generate_204
GET  request from 10.0.0.2 for http://10.0.0.1/generate_204
GET  request from 10.0.0.2 for http://portal.fb.com/mobile/status.php 

Android marshmallow phone (Captive did not work)
GET  request from 10.0.0.66 for http://10.0.0.1

**Comment by JavaRockstar** [comment]
In android I find it uses the devices internet if it has 3g rather then the connected wifi as it has no internet disable mobile internet and have a go.

**Comment by JetseVerschuren** [comment]
My chromebook with chromeos version 57 requested 
`GET http://www.gstatic.com/generate_204`

**Comment by blackHatMonkey** [comment]
@JetseVerschuren Does `chrome os` display any notification either about no internet connection or portal?

**Comment by JetseVerschuren** [comment]
Yes here's a screenshot (it is in Dutch)
![captive_portal](https://user-images.githubusercontent.com/22445469/27069498-4fed275c-5015-11e7-81ff-37ba0323dd49.png)

**Comment by JetseVerschuren** [comment]
Here's one in english
![screenshot 2017-06-13 at 8 53 12 am](https://user-images.githubusercontent.com/22445469/27069622-f00e3f28-5015-11e7-94d8-b923cfc328fd.png)

**Comment by anakin1028** [comment]
@blackHatMonkey I have test with my two android phones, and they will pop out the wifi icons for the fake ap network. I can touch it and direct to our phishing page. I think the Captive Portal works on my phones 

The following is the snapshot http REQ and RESP for `GET /generate_204` 
![http](https://user-images.githubusercontent.com/6182530/27089389-ca081b1a-508c-11e7-9d38-7e68db59bd5e.png)

From the link I read before if we return a response with the status code other than 204, it will direct the device to Captive Portal.

Maybe we should see what response code we have sent for the not working cases.

**Comment by blackHatMonkey** [comment]
@crystalg21 Can you possibly use `wireshark` and show us what happens when you connect your `iphone` to the `fake-ap`?

**Comment by anakin1028** [comment]
The capture for your `android` devices is also helpful. Since we can see what response code we reply to your Android device and dig out why your device not pop out the Captive Portal.

**Comment by hal9kk** [comment]
I can confirm it is not working for me too with Android, asap I will try to report it by wireshark

**Comment by mmomasters** [comment]
I can confirm it is working on iOS but not on Android, any way to help you fix this issue?
