### ISSUE TITLE
randomize_interface_mac() fails when the interface is in monitor mode

### ISSUE THREAD

**Issue by sophron** [wifiphisher/wifiphisher#606]
When my `deauth` interface is in monitor mode, the script will fail to randomize its MAC address. Problem lies in <a href="https://github.com/sophron/wifiphisher/blob/master/wifiphisher/common/interfaces.py#L226">randomize_interface_mac</a>. It should first bring the interface to managed mode before changing the MAC.

@anakin1028 may want to fix this.

**Comment by anakin1028** [comment]
@sophron yeah, I know this issue. I have discussed with @blackHatMonkey. At that we think maybe we can use `randomize_interface_mac` initially that is when the adapter mode is in the managed mode. I can also fix this issue by changing the adapter to managed mode and reset back it to the original mode. How do you think?

**Comment by sophron** [comment]
Yes, I think we should switch back to managed, change the MAC and then restore to the previous state.

**Comment by anakin1028** [comment]
OK issue like this should I create PR or I should push to master directly?

**Comment by sophron** [comment]
Feel free to push directly to master for this one :)

**Comment by anakin1028** [comment]
@sophron the issue should be solved now :)

**Comment by blackHatMonkey** [comment]
@sophron Can you confirm if this issue is fixed?

**Comment by sophron** [comment]
It looks good.
