### ISSUE TITLE
Duplicate of #562

### ISSUE THREAD

**Issue by kerncoola** [wifiphisher/wifiphisher#607]
Hi,
![error6](https://cloud.githubusercontent.com/assets/13283995/25854251/eab23b80-3501-11e7-9af4-e86ec5a4be54.jpg)

![error7](https://cloud.githubusercontent.com/assets/13283995/25854292/1801ef04-3502-11e7-86b0-906d4877d014.jpg)
 What's wrong?

**Comment by anakin1028** [comment]
This is a known issue, have a look on #562
