### ISSUE TITLE
Removing Automatic Shutdown 

### ISSUE THREAD

**Issue by JavaRockstar** [wifiphisher/wifiphisher#612]
I installed wifiphisher using apt-get install wifiphisher in Kali Linux 2017 I don't have the file structure all in one folder but i quickly found data files in /usr/local/bin/python2.7. I notice that the console shuts down after 1 successful harvest i read a blog that told me I must edit the request handler you could point me in the right direction of disabling automatic shutdown from what i gather I need to edit the wifiphisher.py script thanks in advance great work by the work all.

**Comment by blackHatMonkey** [comment]
Installing through `apt-get` is not recommended as it is always multiple version older. You can get the latest by either using `pip`
```bash
[sudo] pip install wifiphisher --upgrade
```
or downloading from [Github](https://github.com/wifiphisher/wifiphisher/archive/master.zip) and running this command in the unzipped folder
```bash
[sudo] python setup.py install
```
As of some time ago `wifiphisher` no longer shutdown by default on the first credential it gets. If you want to shutdown on the first credential you could use the `-qS` option.

**Comment by pierrehts** [comment]
Still autoclosing for me after first credential.
