### ISSUE TITLE
ImportError: No module named wifiphisher.pywifiphisher

### ISSUE THREAD

**Issue by JavaRockstar** [wifiphisher/wifiphisher#614]
I've been running Wifiphisher from apt-get install wifiphisher in one of my last questions I was told to use the script instead so I've purged and removed all files that belong to wifiphisher including from python2.7/dist-packages I then download the latest version of the script.

When running wifiphisher I get this error message I thought it could be a chmod problem so I used chmod +x to make script executable but that was not the issue thanks has anyone has this error I'm using wifiphisher on a 32 bit version of Kali 2017.1 I also run wifiphisher on my Kubuntu 64 bit seems this issue only happens on 32 bit systems for me I seen a question by somebody else on this topic but they never got back about it so I thought I'd open my own thanks could this be caused by uninstalling wifiphisher at some point.
```bash
Traceback (most recent call last):
  File "/usr/local/bin/wifiphisher", line 11, in <module>
    load_entry_point('wifiphisher==1.3', 'console_scripts', 'wifiphisher')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 561, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2631, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2291, in load
    return self.resolve()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2297, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
ImportError: No module named wifiphisher.pywifiphisher
```

**Comment by blackHatMonkey** [comment]
@JavaRockstar How did you install and are running `wifiphisher`?

**Comment by JavaRockstar** [comment]
I installed first using apt-get install wifiphisher then removed that and downloaded the script to my desktop ran python setup.py build && python setup.py install then I call it from the command line as wifiphisher thanks.

**Comment by blackHatMonkey** [comment]
@JavaRockstar So is it working properly now?

**Comment by JavaRockstar** [comment]
Not yet just the same

**Comment by blackHatMonkey** [comment]
Have you tried installing using `pip` or running `wifiphisher` directly like so:
```bash
[sudo] python bin/wifiphisher
```

**Comment by JavaRockstar** [comment]
I've been running it directly I've tried from Pip and with script the error is the same I will try to call it from python bin/wifiphisher see if that works.
