### ISSUE TITLE
Duplicate of #439

### ISSUE THREAD

**Issue by vincentcox-ordina** [wifiphisher/wifiphisher#616]
If my client connects to the AP, the portal show correctly. However, if the client tries to access a HTTPS page, my screen is flooded with SSL errors in the console. The client also receives SSL errors.
Therefore, it would be great to disable SSL intercept with a --tag.

**Comment by blackHatMonkey** [comment]
@vincentcox-ordina Are you getting #439 ?

**Comment by vincentcox-ordina** [comment]
yes unfortunately. Is it fixed because I don't fully understand the thread.

**Comment by blackHatMonkey** [comment]
Not yet :cry: .

**Comment by anakin1028** [comment]
@blackHatMonkey @sophron do you have any idea about this problem? It seems that many users report this problem, but I cannot reproduce it ...
