### ISSUE TITLE
questions about redirect

### ISSUE THREAD

**Issue by vay3t** [wifiphisher/wifiphisher#618]
It is a question. I would like to know how the wifiphisher redirect works. Because in a phone it looks different than from the computer the captive portal, and how it generates the 204? What are the libraries?

So that the tool occupies tornado (I do not know very well how it works yet, so I understand it's a web server)

I do not know if in windows 10 the captive portal automatically opens it (I think that is done cuabdo is trying to redirect microsoft.com to another dns)

I would like to add: I do not know if it exists in the tool, but a good improvement is to add a dns to the captive portal. For example http://captive.portal.local/ and make all the sections go to that dns to be able to do the scam better

**Comment by sophron** [comment]
We handle all DNS requests by resolving everything to localhost using dnsmasq. This will redirect all HTTP/HTTPS requests to us and even trigger the captive portal mechanism in some devices. There are a few ways to trigger the captive portal in all devices that we are planning to implement (#524).

**Comment by vay3t** [comment]
and respect a http://captive.portal.local/ (cuatom dns in captive portal)?

**Comment by sophron** [comment]
I'm not aware of how "captive.portal.local" works.

**Comment by vay3t** [comment]
To add a custom dns to 10.0.0.1. For example redirect all to custom dns. when custom dms is a capt.portal.local (example dns). It is very common that the captive portals have a dns perzonalized

**Comment by sophron** [comment]
We do employ a custom DNS. 

Let's continue this discussion on #524.
