### ISSUE TITLE
Network is down on first run

### ISSUE THREAD

**Issue by squashen** [wifiphisher/wifiphisher#619]
Hello
First of all, sorry for my bad english and thanks for a awesome tool.

I have used ver 1.3 on kali 2016 without any troubles. (Exept for that i have to start the tool 2 times, first time it stop the service network-manager and hangs after that) second time it works smoth.

But when my kali 2016 totaly crasched i decide to make a fresch install of kali 2017 but now when i start wifiphisher first time i got some strange errors. 
![skarmbild fran 2017-05-20 11-21-02](https://cloud.githubusercontent.com/assets/28822593/26274656/9b9aec9a-3d4e-11e7-9a49-52a7e2fec3f0.png)

Now he close the network-manager as it did in kali 2016, but now even my 2 usb cards got downed 2 so i have to "ifconfig wlan1 up" both card to get them showed when i type "ifconfig"
But now when im starting the second time all went smoth until after i have choose target and attacktype
And wifiphisher only show this.
![skarmbild fran 2017-05-20 11-28-17](https://cloud.githubusercontent.com/assets/28822593/26274680/7f3499f6-3d4f-11e7-836c-84ff42d1376b.png)
and then quite.

Any ideas, all advice is welcomed.

Btw ...its only the 2 usb cards thats went down, not my integrated card in the laptop. 
The 2 usb cards is 1 alfa awus 036nh and 1 tp-link tl-wn722n
And my kali is fully apt-get dist-upgraded today.

**Comment by blackHatMonkey** [comment]
Hi @squashen Can you see if the recent updates changed that or not 😄 .

**Comment by squashen** [comment]
Hello again.
I have updated my kali to latest and cloned wifiphisher again and run the setup.
This tim it installed hostapd that was missed:P
I run the ./wifiphisher and it complained about that network-manager handle all the device so i had to make a configfile. But i only type "service network-manager stop" and next time it worked. now he start the tool and i can se som clients conected that is being jammed. I havent checked the rest yet if it is working.

ps: now when i stop the networkmanager only 1 of my 2 usb device went down, so still have to do ifconfig wlan2 up, but only on 1 of them.

**Comment by blackHatMonkey** [comment]
@squashen What happens when you don't bring the card up? Does it cause an error?

**Comment by squashen** [comment]
i pulled out and in the usb dongle so it doesent showed up when i type "ifconfig" only wlan0 and wlan1. then i type ./wifiphisher -aI wlan1 -jI wlan2 and it worked well.

But now i have tryed to clone my own network with choise 2 firmware upgrade. It cloned it and started up. my 2 device is showing under deauth list, but when i try to surf i can do the both on the win10 combuter and my galaxy s6, sometimes with some issues about connection shows up, but if i was nonknowing about whats going on i havent try to search for the other network and connect to that so.
But then if i anyway connecting to my fake network it say "connected no internet" in the right down corner in windows, but cant show any page, it complain about internet connections only and ask me for check cables, dns  etc etc.

Sorry for my bad english anyway, hope u understand.

**Comment by squashen** [comment]
hmm, seems to work fine whit showing upgradepage when i use my integrated card in the laptop as ap, wounder why it doesent work with my usb donles.
those worked in kali 2016.

**Comment by blackHatMonkey** [comment]
@squashen A new update has been merged. Let us know if the same bug is present in the latest git version.
