### ISSUE TITLE
Add a GUI using pywebview

### ISSUE THREAD

**Issue by blackHatMonkey** [wifiphisher/wifiphisher#625]
It is possible to setup a GUI using [pywebview](https://github.com/r0x0r/pywebview) library which runs `html` code. An example of that would be:

![screenshot_20170601_090711](https://cloud.githubusercontent.com/assets/25112506/26682960/39746558-46b0-11e7-8f24-7a7aef0feaa7.png)

If you want to try a simpler version you can run this:
```python
import webview
import threading

"""
This example demonstrates how to create a pywebview windows using QT (normally GTK is preferred)
"""

if __name__ == '__main__':
    #webview.config.use_qt = True

    # Create a resizable webview window
    webview.create_window("Simple browser", "http://flowrl.com")

```

I believe we can use the `tornado` framework to send data back and forth as well.
What do you think @sophron ?

**Comment by sophron** [comment]
I don't find a reason to mess with QT or GTK. 

We can use Tornado if we want a web GUI. A TUI (#611) has priority though.
