### ISSUE TITLE
Documentation module section not working

### ISSUE THREAD

**Issue by blackHatMonkey** [wifiphisher/wifiphisher#627]
@sophron ~~Did you setup the web hooks for the `readthedocs`?
I'm asking because I just pushed some documentation updates and it's not updating on `readthedocs`.~~

**Comment by blackHatMonkey** [comment]
It is working except the module sections where it is not showing anything.

**Comment by sophron** [comment]
We also need to be consistent with the information in readthedocs and wifiphisher.org.

**Comment by sophron** [comment]
What is the difference of this issue and #623?

**Comment by blackHatMonkey** [comment]
@sophron I'm stating the fact that part of the documentation specifically the module section is not getting displayed in the documentation.

**Comment by blackHatMonkey** [comment]
@sophron Also regarding the information being consistent after we add all the information from `wifiphisher.org` we should delete the documentation part of it and rather you can use it as a blog for updating what is being worked on or show your research etc.

**Comment by sophron** [comment]
The module section is this one: http://wifiphisher.readthedocs.io/en/latest/modules.html

And is rendered based on the file here: https://github.com/wifiphisher/wifiphisher/blob/master/docs/modules.rst

What is wrong with that?

**Comment by blackHatMonkey** [comment]
This is how it should look like and is on my system:
![screenshot_20170607_070638](https://user-images.githubusercontent.com/25112506/26875452-e6e5d548-4b4f-11e7-8198-0b84f7f6e854.png)

**Comment by sophron** [comment]
I don't see any wrong setting on `readthedocs`. My guess is that `sphinx` is probably running from a different path.

**Comment by blackHatMonkey** [comment]
@sophron Take a look at [this](https://docs.readthedocs.io/en/latest/faq.html#my-project-isn-t-building-with-autodoc) as it might help debug this issue.

**Comment by sophron** [comment]
Docs updated.
