### ISSUE TITLE
Using one wireless interface

### ISSUE THREAD

**Issue by khaldunkhaleel** [wifiphisher/wifiphisher#63]
I think this script should be modified like what I mentioned

**Comment by sophron** [comment]
Thanks for mentioning it.

**Comment by Labseb** [comment]
It would be good that we can select an interface for the AP without to have one other for jamming.

I would like to use "-aI" with "--nojamming" -> Impossible

**Comment by sophron** [comment]
@Labseb I meant to say you need to use the latest development version. Try `git clone https://github.com/sophron/wifiphisher` and use this version instead.

**Comment by Labseb** [comment]
ok, sorry, i will try it !
Thank's

2017-01-05 16:03 GMT+01:00 George Chatzisofroniou <notifications@github.com>
:

**Comment by Labseb** [comment]
i think you can close this Issue
