### ISSUE TITLE
Wifiphisher networkmanager help

### ISSUE THREAD

**Issue by GeraltofRiviaX1** [wifiphisher/wifiphisher#641]
When I try to run the program I get this, I am not very good with Linux so if someone could guide me on how to fix this. I've searched the issue but didn't find any luck.
```
root@kali:~/wifiphisher# wifiphisher
[*] Starting Wifiphisher 1.3GIT at 2017-06-14 16:14
[!] Interface "ALL" is controlled by NetworkManager.You need to manually set the devices that should be ignored by NetworkManager using the keyfile plugin (unmanaged-directive). For example, '[keyfile] unmanaged-devices=interface-name:"ALL"' needs to be added in your NetworkManager configuration file.
[+] Captured credentials:
[!] Closing
```

**Comment by andronixist** [comment]
Having exact same issue

**Comment by sophron** [comment]
We should fix this soon.

For now just disable the NetworkManager, i.e. "/etc/init.d/network-manager stop".

**Comment by anakin1028** [comment]
@GeraltofRiviaX1 @andronixist we have fixed this issue? can you help pull the latest commit and try again?

**Comment by blackHatMonkey** [comment]
@GeraltofRiviaX1 This issue have been fixed if not feel free to open it again.
