### ISSUE TITLE
Wifiphisher stoped my networkmanager, even after reboot

### ISSUE THREAD

**Issue by squashen** [wifiphisher/wifiphisher#643]
Downloaded latest wifiphisher with dbus. When started network-manager vas closed directly on first start.
But when i closed the tool and type as usual "service network-manager start" nothing happend. 
Rebooted my computer and still no wifi icon in upper right corner.
Whats the command to let dbus start networkmanager again?

**Comment by anakin1028** [comment]
The tool should recover the network-manager it self so you don't need to manually start the NetworkManager. have you try the command : `/etc/init.d/network-manager restart` and can you help post the output of `nmcli nm` ?

**Comment by squashen** [comment]
![20170616_015517](https://user-images.githubusercontent.com/28822593/27206358-56b372b6-5237-11e7-90e0-23999431693b.jpg)

Seems that network-manager is on, becouse when i type the nmcli command before restarting it complain about networksmanager not was on. But still no internet and no wifi icon in uper right corner

**Comment by squashen** [comment]
So it seems that networkmanager no longer manage any of my devices.
Have checked  networkmanager.conf and switch managed=false to true.
Restarted again, tryed "nmcli dev set wlan0 managed yes", but still say not managed when typ "nmcli d" noticed that my wlan0 that i used as ap has still the 10.0.0.1 ip when i type "ifconfig" even if wifiphisher is closed.

**Comment by squashen** [comment]
I solved it. I type    "nmcli n on" and al device got managed and the icon showed up :)

**Comment by squashen** [comment]
I solved it. I type    "nmcli n on" and al device got managed and the icon showed up :)

**Comment by anakin1028** [comment]
good. Can you tried to run `wifiphisher` again and see if the icon still miss?

**Comment by squashen** [comment]
Started wifiphisher, icon disapear. Close it, still missing, had to typ restart network-manager before nmcli and then "nmcli n on " and icon showed up

**Comment by anakin1028** [comment]
@squashen thanks for you help. If possible can you help to comment out the lines in the file : `pywifiphisher.py` under `wifiphisher/wifiphisher` like the following

```python
#if not args.internetinterface:
#    kill_interfering_procs()
```

and try to run the tool again?

**Comment by anakin1028** [comment]
From the description, I think `dbus` does the right job at the beginning, it disable the NetworkManager, but after that the function `kill_interfering_procs` kills the process `NetworkManager` and thus the recovering process may be fail to enable the Networking.

On my machine, since my `NetworkManager` always restarts automatically even after calling `airmon-ng check kill`, so the recover success after exiting the tool.

I think in the long term we should remove the function `airmon-ng check kill` and change to our custom function.

**Comment by squashen** [comment]
When i close the tool icon showed up again when i had comment out those lines^^

**Comment by anakin1028** [comment]
yeah that what I thought too : )

**Comment by anakin1028** [comment]
@sophron @blackHatMonkey for now to solve the problem @squashen has met : do you think we can implement our own killing function that we don't kill the NetworkManager but kill other processes listed by `airmon-ng check list`

Here is the processes list that `airmon-ng` denotes as interfering:
```
PROCESSES="wpa_action\|wpa_supplicant\|wpa_cli\|dhclient\|ifplugd\|dhcdbd\|dhcpcd\|udhcpc\|NetworkManager\|knetworkmanager\|avahi-autoipd\|avahi-daemon\|wlassistant\|wifibox"
```

we may remove the `NetworkManager` and `knetworkmanager` since we have already disabled it in the first. how do you think?

**Comment by sophron** [comment]
Apart from `NetworkManager`, I am not sure how the rest of the processes can be a trouble for us. Maybe we don't have to kill anything?

**Comment by sophron** [comment]
Yes, we can have our own killer method. By the way, `airmon-zc` should be better than `airmon-ng`.

**Comment by anakin1028** [comment]
I just know that if `wpa_supplicant` is running, our tool will fail to run since `wpa_supplicant` is controlling this interface. I am not so sure about other processes.

**Comment by sophron** [comment]
The other processes are important to be killed too. For example, `dhclient` can try obtaining addresses when you do not expect it.

**Comment by anakin1028** [comment]
so I guess our own process killer may focus the following processes first:
```
wpa_action\|wpa_supplicant\|wpa_cli\|dhclient\dhcdbd\|dhcpcd\|udhcpc
```

**Comment by sophron** [comment]
@anakin1028 No, I would kill all the processes that exist in the `airmon-zc` list to make sure that noone messes with our interfaces. All processes in that list have a reason to be killed.

**Comment by sophron** [comment]
Except NetworkManager that we now stop using DBus.

**Comment by anakin1028** [comment]
OK I agree with that . I have checked the processes listed `airmon-zc` are same as in the `airmon-ng`. we can just kill those processes except with `NetworkManager`, and warn the users that the interfering processes are being killed.

**Comment by ridu123** [comment]
I have the same problem, but "nmcli n on" not help me, "service network-manager --full-restart" not help me.  Still no wifi icon in upper right corner, i have no idea....

**Comment by squashen** [comment]
What does only "nmcli" show for output?

**Comment by squashen** [comment]
And "nmcli n" ? activated or not?

**Comment by sophron** [comment]
We just pushed a commit. Check out to the latest revision and let us know if it's working as expected.

**Comment by black-meet** [comment]
just type (service NetworkManager start) and it will work very well
