### ISSUE TITLE
No Fake AccesPoint Page

### ISSUE THREAD

**Issue by Kali620** [wifiphisher/wifiphisher#647]
When my real accespoint go offline,i don't see the fake accespoint page...and ther isn't any HTTP REQUEST...why?
Jamming interface (default interface of my laptop)
Ap interface (KRAUN300)
i'm using Kali2.0 and wifiphisherV1.3

**Comment by sophron** [comment]
You will have to be more detailed in your description. What do you mean by "the real accesspoint go offline"?

**Comment by Kali620** [comment]
When I select the network...and the accespoint go offline*

**Comment by sophron** [comment]
The target access point never goes offline. We mount a <a href="https://en.wikipedia.org/wiki/Wi-Fi_deauthentication_attack">deauthentication attack</a> that kicks out clients.

You should see HTTP requests when they happen. Have you tried connecting  to the rogue Access Point and requesting a page?

**Comment by Kali620** [comment]
Okay okay,it work very well...thank
