### ISSUE TITLE
No connection after using Wifiphisher

### ISSUE THREAD

**Issue by vas4oo** [wifiphisher/wifiphisher#648]
I have downloaded Wifiphisher from github and try some new stuff. After i close the program i have no internet conection. I try with wired connection and still don't have. Restarting the network-manager and nothig. I have second wi fi adapter TP-LINK TLWN722N. When i pluged the second adapter the light doesn't not flashing. When i enabled monitoring mode the light is flashing, and when i stop it the ligh die down. Can someone help with this problem (Sorry for my bad English)

**Comment by anakin1028** [comment]
have you tried the command `nmcli n on`? And also when do you leave the wifiphisher program? Did you press ctrl-c in the main terminal which displays the http requests and deauthenticated clients?

**Comment by vas4oo** [comment]
Thank you nmcli n on worked for me. I press ctrl+c when the program check for wireless network.

**Comment by anakin1028** [comment]
You should press `esc` during ap selection. Then after the progam exits, you only need to restart the NetworkManager

**Comment by vas4oo** [comment]
Thank you very much for helping.
