### ISSUE TITLE
Duplicate of #650

### ISSUE THREAD

**Issue by Stenugin** [wifiphisher/wifiphisher#651]
Such a problem, how to solve it?
I have 2 WiFi Adapters,one in the laptop and one USB adapter. 
![image](https://user-images.githubusercontent.com/25420201/27508471-63c3315e-58ee-11e7-80a0-a81335131483.jpg)

**Comment by anakin1028** [comment]
Hi, can you check the discussion in #650 first?

**Comment by Stenugin** [comment]
I have the same problem, but I did not understand how he solved it

**Comment by anakin1028** [comment]
What's the output of `iwconfig` from your terminal

**Comment by RandyChange** [comment]
Hello @anakin1028 , and sorry for "taking over" this issue, but I thought you could help me out fast here, with this information provided: https://Thomasbear-live.tinytake.com/sf/MTcyMzgzMl81NzA1OTgx

It is the alfa awus051nh v2 I am using. It should support everything.

**Comment by anakin1028** [comment]
Try the following : 
```shell
ifconfig wlan0 down
iwconfig wlan0 mode monitor
```
see if it is workable to change the adapter card to monitor mode.

**Comment by blackHatMonkey** [comment]
@RandyChange In addition to what @anakin1028 said I can only see one wireless adapter. However you are using `wifiphisher` without any extra arguments. Running `wifiphisher` without any arguments assumes that you have two wireless adapters (one for the AP and one for MON).

**Comment by RandyChange** [comment]
@anakin1028 Does unfortunately not fix it. :/
https://Thomasbear-live.tinytake.com/sf/MTcyMzg3NF81NzA2MDYz

**Comment by RandyChange** [comment]
@blackHatMonkey Ah, maybe that's the problem.. I am doing this on a Laptop, shouldn't I be able to use it's inbuilt wifi card along with my alfa adapter, or am I mistaken?? :)

I am running kali inside vmware

**Comment by blackHatMonkey** [comment]
@RandyChange From what you have posted the system only sees one wireless adapter. So make sure you can see both adapters and try again.

**Comment by anakin1028** [comment]
Do you use virtual box or native Kali?

**Comment by anakin1028** [comment]
from your screen shot I can see your adapter supports the monitor mode. so if you have only card now, you can use the following command without launching deauthentication attack:
`wifiphisher -nJ`

**Comment by RandyChange** [comment]
@blackHatMonkey I have tried that for some days before getting my adapter today. Any instructions I can follow to get my VMware to use my internal Wifi card??

@anakin1028 I use Kali in a VM in VMware, if that answers your question??
Also, I figured I can do that yeah, but I would really like to be able to "jam". Do you know if I can use my internal/inbuilt card along my adapter, or if I need two adapters besides my laptops card?

**Comment by anakin1028** [comment]
@RandyChange I guess you need to set the network setting to bridge on the host machine so that the traffic can be redirected to the virtual machine.
you can do some googling about this : )

**Comment by RandyChange** [comment]
@anakin1028 Sounds like it should be possible with the laptop card and my adapter only :)
However I have tried it for a long time, but I will google on then..
Any chance to can say anything out from this? https://Thomasbear-live.tinytake.com/sf/MTcyMzkwOV81NzA2MTUx

**Comment by anakin1028** [comment]
yes, you should see the internal wireless card by using `iwconfig`

**Comment by RandyChange** [comment]
@anakin1028 Yeah.. It's just not happening haha :p ..

Having a problem just getting wifi to work again right now.. must have used some command which prevents it. Hard times being new to this hah.

**Comment by gudi13** [comment]
@RandyChange try this

ifconfig
iwconfig
cd ~/Desktop
wget http://linuxwireless.org/download/com...
tar -jxvf compat-wireless-2010-06-26-p.tar.bz2
ls
cd compat-*
ls
make unload
make load
clear
iwconfig

**Comment by RandyChange** [comment]
@gudi13
Thanks buddy, I will try that in a bit when I have solved my other problem.. RIght my VM can see everything but I cannot connect to the internet at all - not even see the thingy I connect through.. :p 
https://Thomasbear-live.tinytake.com/sf/MTcyNDQwM181NzA3MjI2

**Comment by gudi13** [comment]
@RandyChange ok, i have this problem too right now, if you get the solution teel me! ty

**Comment by RandyChange** [comment]
@gudi13 kinda just reinstalling Kali right now.. Noone has any idea what the problem is or how to fix it. :/
