### ISSUE TITLE
Using only one card to do deauthentication and lunching AP

### ISSUE THREAD

**Issue by anakin1028** [wifiphisher/wifiphisher#652]
@sophron @blackHatMonkey 

If users default use the command `wifiphisher`, it will require two adapter cards and I think this is a little inconvient to users.

After introducing [roguehostapd](https://github.com/wifiphisher/roguehostapd) we can send the broadcast deauthentication (Since after lunching AP we cannot sniff the frames on the air, we can only broadcast the Deauthentication from the target AP's MAC address) command from wifiphisher to the hostapd process. This is the constraint of one adater card. How do you think?

**Comment by RandyChange** [comment]
Not sure if I understand this correctly.. But if you mean that it is could be possible to run it all perfectly fine with 1 card instead of 2, it would be awesome. If that is possible I vote for that haha.
(deauth and AP at the same time, with 1 wifi adapter)

**Comment by sophron** [comment]
I think we can create a second vif (virtual interface) and set it to monitor mode. We can pass the first to hostapd (that will turn it to AP mode) and use the second for deauthentication.

The only issue here is that we won't be able to do channel hopping in this case. Both vifs should be in the same channel. That means that our AP should be on the same channel as the target AP to broadcast the DEAUTH frames.

We should have this ready for v1.4.

**Comment by anakin1028** [comment]
It's possible to do this operation in SW, but I'm not so sure if the vendors' HW can support one `AP` and the other is `monitor` on the same card. I have seen some Linux driver does not allow to add new virtual interface as `monitor`, thus we may suffer the compatibility issues if we implements in this way. How do you think?

**Comment by sophron** [comment]
I think most of them do support this combination but yes, we need to do some research first. Run `iw list` and see the section `valid interface combinations`

**Comment by RandyChange** [comment]
@sophron 
Do you have any ETA for v1.4??? 
It would be so awesome to be able to AP AND deauth at the same time with one card :) I hope this is possible.

**Comment by anakin1028** [comment]
@sophron  looks good. I may implement this when `extension manager` is merged.

**Comment by mpkosewski** [comment]
> It's possible to do this operation in SW, but I'm not so sure if the vendors' HW can support one AP and the other is monitor on the same card. I have seen some Linux driver does not allow to add new virtual interface as monitor, thus we may suffer the compatibility issues if we implements in this way. How do you think?

I've seen apps create a couple virtual interfaces with the Alfa chips before (sometimes by mistake) and they still seemed to work. Specifically the AWUS036NH, being one of their more powerful cards.

**Comment by anakin1028** [comment]
@mpkosewski thanks. Yes I have tried this for my `TL-WN722N` and it works.

**Comment by minanagehsalalma** [comment]
@sophron @anakin1028  my suggestion would solve the problem https://github.com/wifiphisher/wifiphisher/issues/495

**Comment by anakin1028** [comment]
> @sophron @alternatexp i meant in the beginning make the jamming interface stop the jamming and start a scan searching for our target (using BSSID) updating the deauth with the new channel every five minutes without making any changes to the ap interface ... and make it optional

This approach is not workable in my view for the following two reasons:
  * If the interface has been chosen as AP, then it has to be fixed in one channel to transmit the beacons on the target channel. So it's not possible to do a scan search after the AP is lunching. [Though I know some vendors support the AP scan feature for some scenarios]

  * If we only do the scan on the begining then we may only get the subset of clients so we cannot deauth all the clients on that channel.

However, I agree with if we use one card to do both deauth and lunch AP, the deauth process may not be efficient enough to deauthenticate the clients and force them to auto-connect to our fakeap. This needs some experiements.

**Comment by minanagehsalalma** [comment]
Why not...  Like i said we most turn off our fake ap and start the attack
from the begging  every specific amount of time with the same victim ap so
we refresh the channel so we can deauthenticat clients again and do the
attack with one card.. What do you think 😀😊😊?

**Comment by anakin1028** [comment]
No. We cannot turn off the fakeAP once we have started it. If we turned of the fakeAP, the clients connected to the fakeAP would be disconnected since we didn't send the beacons on the target channel.

**Comment by minanagehsalalma** [comment]
But it wouldn't take more than one minute  to start the attack again ..
This better than not  deauthenticat  all the clients after restarting the
ap

**Comment by anakin1028** [comment]
On the theory view like I said before we should not stop the fakeAP once we have launched it since we never know when the victims have connected to our fakeAP and users may feel strange why the clients has gotten the dhcp release but it loses connection after that because that we have restarted the fakeAP.

The only two approaches are:
  * @sophron purposes: create one more virtual interface stick with the same fakeAP interface to do the deauth process. [This approach may suffer the performance issue since we use one card to do both deauth and lunch AP. We should have experiments on it.] 

  * Just hack with the hostapd, and let it send the broadcast deauthentication for the `BSSIDs` it has listened on the `ap selection phase.`

**Comment by minanagehsalalma** [comment]
That what fluxion do..  But we will face the channel changeing problem and
to avoid disconnecting the clients problem the script will restart  the
attack just  in the case of no connected clients after a time to allow them
to connect 😎😎

**Comment by anakin1028** [comment]
OK. I guess I have captured what you interpret. Do you mean after there is no clients connected to fakeAP for a while we change back to the `ap selection phase` and let the user select the AP again? 
If so, I think we will not do this change for v1.4 in my personal view unless @sophron and @blackHatMonkey  have other opinions.

But it still has problem for the deauth process when the fakeAP is lunched. Does `fluxion` also sends broadcast deauthentication under attacking stage? 

Nerveless it's an interesting idea, I'll check the source code of `fluxion` for the implementation details.

**Comment by sophron** [comment]
I am not sure I understand the problem. Do we want to mount deauthentication attack against different APs (same ESSID, different channel) or do we want to change our rogue AP's channel?

For the first one, we can implement it some point in the future by improving the relevant module. For the second question, I don't see what we gain for doing that.

In any case, this looks something that we should discuss on #495.

**Comment by minanagehsalalma** [comment]
@sophron  bro let it here 😊 😊 😊  `Do you mean after there is no clients connected to fakeAP for a while we change back to the ap selection phase and let the user select the AP again?
`
yes but it should be automatic and do this process on the same ap without the user input

**Comment by anakin1028** [comment]
@minanagehsalalma, thanks. I fully understand what you describe. But let's discuss this issue on the original thread. This will make the discussion more focus on your issue : )

**Comment by anakin1028** [comment]
@RandyChange @mpkosewski 
I have purposed a PR for doing this item. If you're interested in this, you can do the following to help test.

```
git fetch
git merge origin jam_ap_in_one_interface
git checkout jam_ap_in_one_interface # switch to the PR branch
```
And do the test. After testing is done, you can switch to master branch:
`git checkout master`

**Comment by mpkosewski** [comment]
Sure I be happy to help. Had a slow start today and have a few errands to run that shouldn't take long. But other than that, yeah I be happy to help. 

Have fresh new kali install and also have the new AWUS036ACH which I haven't full tested out 100% yet but has amazing performance thus far

**Comment by Esser420** [comment]
Is this implemented yet?
Yes it is perfectly possible to send deauthentication packets with scapy while the AP is running.
The only limitation is that the Deauthentication packets will only be sent on one channel, the same that the AP is running on. If clients are connected to the real AP on another channel they will not be affected by this.
I think that in "automatic mode" the tool should detect if the user has more than one Wi-Fi card (which it already does) and if not then it should choose to deuathenticate on the same card as the AP.

I have this working on my "Evil-Twin Framework" project :P 
Although your phishing pages are much better!

**Comment by anakin1028** [comment]
@Esser420 The implementation is almost done. Like you say, we'll check how many card the users have, if they have two cards above we don't need to use this feature. This feature only enable when users have one card supporting both monitor and ap mode.

We need to do the final verification and add test cases. You can also pull the commit on `jam_ap_in_one_interface` and check whether this feature work on your system : )

**Comment by yungtravla** [comment]
This would be f***ing genius...

I think it is possible if you take into consideration:

  - To **not** host a rogue AP/send deauth packets **yet** unless client interaction has been found on the target AP
  - Packets are piped and we should therefore be able to create a virtual interface

**Comment by anakin1028** [comment]
For the first suggestion: I remember our recon module will show how many clients are connected to the access points. Tool users can use this index to determine if they want to start attacking.

**Comment by anakin1028** [comment]
hi all, #675 has been merged. You can pull the latest commit from master to use this feature : )

**Comment by RandyChange** [comment]
@anakin1028 
Wait.. So what you are saying is, that I am able to open a VM, plug one compatible card into my laptop and then be able to get the whole solution from WiFi Phisher? :)

**Comment by anakin1028** [comment]
Almost all the features! You can use `wifiphisher` to do jamming for one card now.
But features using frequency hopping cannot support by single card like the `-dE` option

**Comment by RandyChange** [comment]
@anakin1028 
But I am able to "jam a router" and host the AP the targets will connect to with one card??
In other words, I am able to get credentials or launch payloads with one card now?

I have lost my Kali USB, which is the reason I am asking instead of testing myself right now - so thanks for answering!

**Comment by anakin1028** [comment]
@RandyChange No problem. You can deauthenticate the router and lunch the fake access point under the same card now : )

* You can use the following command:
`./wifiphsiher`

and then just select the target router from ap-selection as before.

* one thing need to remember if you want to observe the auth-connect behavior your router should be no security (i.e. OPEN).

**Comment by anakin1028** [comment]
typo : auto-connect

**Comment by RandyChange** [comment]
@anakin1028 
Sounds amazing! I will try it when I get the change.

However, sorry to sound stupid, but what do you mean by "one thing need to remember if you want to observe the auto-connect behavior your router should be no security (i.e. OPEN)."??
The fake AP is always "OPEN", right? - so a bit confused by this, and your auto-connect statement?

**Comment by anakin1028** [comment]
@RandyChange NP. Feel free to ask any questions.

* Fact : command `./wifiphisher` will lunch OPEN fakeAP with the same ESSID if the target router as you say.

What I mean is the following:

* Before lunching wifiphisher, the victim device is connecting to the target router say ESSID=haha
Here the `target router` should have no security in order to observe auto-connect to the fake Access Point lunched by wifiphisher.

* If the target router say ESSID=haha has WPA2 security you have to manually connect to the fake AccessPoint since the security is not matching (i.e. The target router has WPA2 while the access point lunched by wifiphisher has OPEN security)

* However if you know the passphrase of the target router and let say it has the password: `12345678` with WPA2 security then you can lunch wifiphisher by the command `./wifiphisher -pK 12345678`. Now the fake access point will have the same security as the target router. I guess auto-connect behavior will also work in this case.

The victim device will be deauthenticated from target router in the above three cases and the main point is whether you need to manually connect to the fake Access Point lunched by wifiphisher.

**Comment by anakin1028** [comment]
If you are interesting in this topic @sophron also has a clear explanation in the bottom of thread #560.

**Comment by RandyChange** [comment]
@anakin1028 
Thanks for the clear explanation anakin!

So overall, the only way to get auto-connect to work properly is, if you target an already "open-security" router, which could be at cafe's for example, right?
- This however, would only be with the goal of harvesting passwords(i.e social media passwords..) or launching payloads, and not the WiFi-Password, right? (because there isn't one hehe)

In every other scenario in which you try to get the WiFi-password, it would be protected of course, meaning that a manual SE connect has to happen. So auto-connect would never work against personal WiFi-router targets, right?

Does all of this seem to be understood correctly? :)

**Comment by anakin1028** [comment]
If you don't know the password of the WPA/WPA2 personal access point, indeed auto-connect cannot happen.

Another possibility is:
Since user may find the same ESSID lunched by wifiphisher and manually connect to it then we can use `firmware-upgrade` phishing scenario to phish the WPA2 passphrase.

**Comment by anakin1028** [comment]
The following is the protocol for the connection process and this will help you understand why security has needed to be matched between the target AP and the fake AP lunched by wifiphisher in order for auto-connection.
```
Client  -------> Probe Request  ---> Access Point
Client  < ------- Probe Response --- Access Point (Client will parse the security information element in probe response and will abort here if the security is not match)
Client  --------> Auth ------------> Access Point
Client < -------  Auth ------------- Access Point
Client ------------> Associate Request ------> Access Point
Client < ------------Associate Response ------- Access Point (If the target AP is OPEN security then done!)

Client < ------------Fourway handshake ----------> Access Point (if target AP has TKIP or CCMP security)
```

**Comment by RandyChange** [comment]
@anakin1028 
Thank you for all the your answers. Guess I am all good for now.
I will test it out some time, and if something comes up, I'll get in contact.

Have a nice day! :)

**Comment by RandyChange** [comment]
@anakin1028 
Also, could you by any chance recommend a compatible card which is not a dongle, but a USB? Using a dongle and I hate it hehe.
The new TL-WN722N (v2) does not work.

**Comment by anakin1028** [comment]
Yes. Indeed WN722N now use Realtek chipset and Kali default doesn't support it.
I will recommend `AWUS036NHA` from `ALFA-Network` and I also use this adaptor and `WN722N-V1` to do the test for wifiphisher.

**Comment by RandyChange** [comment]
Wish I had the WN722H-V1 and not the V2.. (fail, yes..)
I currently have the AWUS051NH V2.

I guess I said it wrong before, but I was trying to ask if you know any compatible one which does not have a cord like our AWUS*.. has. Just one which looks like the WN722N without a cord. Hope that makes sense haha.. I do not seem to be able to find one myself

**Comment by RandyChange** [comment]
ah..
https://hakshop.com/collections/wireless-gear/products/ralink-rt3070-usb-wifi-adapter

This one seems to be fine actually, right?, so I am sorry for all the fuss haha.

**Comment by anakin1028** [comment]
I haven't used that one for doing test so I cannot guarantee it has full compatibility for our program.

**Comment by RandyChange** [comment]
Ah, thought it was the chipset that decided it, and not the software?

**Comment by anakin1028** [comment]
Yes. Chipset will define it, but you also need to concern about the driver for this chipset.

For example, from description in the link you provide it supports both monitor and ap mode but can it support operation for ap and monitor together?

Wifiphisher needs the driver has a good compatibility for the kernel module `nl80211` since it uses the python module `pyric` which is highly dependent on this kernel module. So the chipset vendor's driver becomes important for this reason.

**Comment by RandyChange** [comment]
Haha damn, did not know all of that.. It is being sold for the whole purpose of penetration testing so I think it may support it, but no idea..

If you have time and want, can you then explain me how I find out if it is able to do that(all at once if I understood correctly).? do I have to ask the manufacturer/seller or..?

Also wondering about it with my AWUS051NH V2 hehe

**Comment by anakin1028** [comment]
I guess AWUS051NH should work fine.
You can have a look at the following link:
[iw introduction](https://wireless.wiki.kernel.org/en/users/documentation/iw)

This link will introduce important commands for `iw` and `pyric` is designed based on the philosophy of `iw`. 

If you want to test if the adaptor is compatible you can manually use the following commands:
```
iw phy phy0 interface add mon0 type monitor # let's say you have default adaptor wlan0/phy0 and add mon0 as a new virtual interface
ifconfig wlan0 up
hostapd hostapd.conf # lunch hostapd on wlan0
wireshark # use wireshark and see if mon0 can sniff the frames on the air
```

Since wifiphisher just mimics the above commands via python module `Pyric` wifiphisher should work successfully if the above commands works fine.

**Comment by anakin1028** [comment]
Briefly you can ask vendor whether the Card can use one interface to lunch soft AP while the other virtual interface to do injection and receive layer2 frames in monitor mode (tx/rx) simultaneously.

**Comment by RandyChange** [comment]
Thank you, I will take a look at it soon.

**Comment by EOS123** [comment]
Does AWUS036ACH need two identical AWUS036ACH in the Wifiphisher suite?

**Comment by RandyChange** [comment]
@anakin1028 
Hello buddy
I finally got to try and test it but ran into a few problems: http://prntscr.com/gjhkpu 

I open my VM, went into the WiFi Phisher folder and dit a "git pull *.git" followed by the python setup stuff as written in your README - that is how to update it, right?
Then I ran "wifiphisher" and got the following output as seen in the screenshot linked to above.

I have connected my card and turned off the "wired network" it gets from my host machine.

Tell me if you need any more information. :)

**Comment by EOS123** [comment]
HiWhat two wireless adapters do you use? Can you tell me? I am still choosing the adapter, I don't know which is the best.
 

    Thomas <notifications@github.com> 于 2017年9月11日, 星期一, 上午 2:45 写道：
 

 @anakin1028
Hello buddy
I finally got to try and test it but ran into a few problems: http://prntscr.com/gjhkpuI open my VM, went into the WiFi Phisher folder and dit a "git pull *.git" followed by the python setup stuff as written in your README - that is how to update it, right?
Then I ran "wifiphisher" and got the following output as seen in the screenshot linked to above.I have connected my card and turned off the "wired network" it gets from my host machine.Tell me if you need any more information. :)—

**Comment by blackHatMonkey** [comment]
@RandyChange 
Can you do a fresh `git clone` and see you encounter the same problem?

**Comment by blackHatMonkey** [comment]
@EOS123 You can checkout #558 to see a list of adapters that people have used successfully 😄 .

**Comment by RandyChange** [comment]
@blackHatMonkey 
removed wifiphisher folder > git clone https://github.com/wifiphisher/wifiphisher.git > python setup.py install > wifiphisher > http://prntscr.com/gji27v

So unfortunately about the same :/

**Comment by EOS123** [comment]
Please ask your questions on the page, which can be solved generally.How to Hack WPA/WPA2 Wi-Fi | No WPS | No BruteForce | Fluxion Tool | Extreme Hacking

  
|  
|   |  
How to Hack WPA/WPA2 Wi-Fi | No WPS | No BruteForce | Fluxion Tool | Extreme Hacking
 Guys I forked the fluxion link to my github account only for you guys as the original is down now , I doesn'...  |  |

  |

 
 

    Thomas <notifications@github.com> 于 2017年9月11日, 星期一, 上午 3:20 写道：
 

 @blackHatMonkey
removed wifiphisher folder > git clone https://github.com/wifiphisher/wifiphisher.git > python setup.py install > wifiphisher > http://prntscr.com/gji27vSo unfortunately about the same :/—

**Comment by RandyChange** [comment]
@blackHatMonkey 
I btw have tried to updating my system and such "normal stuff", with no luck. :/

**Comment by anakin1028** [comment]
I'm not sure your adaptor can set mac address. You can use with `-iNM` option and try again.
Like : `wifiphisher -iNM` to not to change MAC address

**Comment by mpkosewski** [comment]
Damn this thread got huge haha

But as far as RandyChange's issue, I not sure why your mac address is set as it is because your first 6 character's "00:00:00" specifically are what's invalid. The first 6 digits of any Mac address are vendor specific. 

Since you are running kali, you could try to use "macchanger"  to change the mac address to a valid one. It's pretty simple to use.

**Comment by mpkosewski** [comment]
Also instead of asking the vendor directly (assuming you already bought the adapter) the "iw info" cmd will tell you specifically what modes your wifi adapters support

**Comment by anakin1028** [comment]
@mpkosewski our program will now default spoof the MAC address with `00:00:00` as the OUI and randomize the remaining three bytes.

**Comment by RandyChange** [comment]
@mpkosewski 
I will try it when I get home from studies, thank you. :)

@anakin1028 
But from what I understand, his solution will not change anything from what you are saying? Do you have anything else I can try when I get to that point?

**Comment by anakin1028** [comment]
@RandyChange. From the picture you are posting:
I see the Exception Error message:
```
InvalidMacAddressError: The provided MAC...
```

This MAC address is default spoofing by `wifiphisher` and our program try to change you permanent MAC address to the one you see : `00:00:00:d2:7d:3c`. It looks like this MAC address is failed to spoof and our program raise Exception. 

That's why I suggest you maybe you can disable the spoofing MAC address function by providing `-iNM` option.

**Comment by RandyChange** [comment]
@anakin1028 
Ah, missed your first reply in all the hassle hehe!
I will try that when home and report back :)

**Comment by anakin1028** [comment]
Sure. Thanks : )

**Comment by RandyChange** [comment]
@anakin1028 
Heya again - Just tested it.. Screenshot: http://prntscr.com/gjry6l

I did as you said and it actually started up and began to find the hotspots. I choose mine and got 4 options and normally and tried two of them, as you can see in the above screenshot.
However, when choosing one of them, it just went back to the normal CMD window, waited 5 seconds or so and then just "ended" as you again can see in the screenshot.
Hope this is enough information otherwise just tell me what you need..

So...
- with the -iNM parameter it let me through, which concludes that something is wrong with the MAC feature I guess? (would this give some security issues on my end while testing? If not, why are you changing the MAC address? :) )

- It just closes down after trying to launch the attack I think.

**Comment by anakin1028** [comment]
Can you post the output of `which dnsmasq`? If there is nothing you can have a look for #720.

Yeah. It is better to spoof the MAC address as for the anonymous issue.
I'm not aware about there is something wrong with the `mac-spoofing` feature since three of my adaptors are capable to change mac-address by this feature...

Can you manually use `macchanger` to test if your adaptor can change mac-address?

**Comment by RandyChange** [comment]
@anakin1028 
Is this the information you asked for ? : http://prntscr.com/gjto5m

Also, seems like I am able to use the macchanger, so that is a bit weird.. :/
: http://prntscr.com/gjtq0d

**Comment by RandyChange** [comment]
@anakin1028 
Just tried running wifiphisher again, and got this error now: http://prntscr.com/gjtvvn

Guess this is after I have manually changed the MAC-address.. (Here I still got to the point of choosing which hotspot to attack and which attack to use - and then it just closed down again and showed the output in the screenshot)

**Comment by anakin1028** [comment]
This is just what I guess: I think your adaptor cannot set the mac address via `nl80211` interface. Since the module `pyric` relies on `nl80211` to send the command to the `driver` of the adaptor.

I think we should solve the problem why `wifiphisher` exits abruptly...

**Comment by anakin1028** [comment]
@RandyChange can you checkout the branch `warnmsg_dnsmasq_hostapd` and try to run again with the `-iNM` case. In that branch I print the warning message when the `hostapd` or `dnsmasq` is failed to run.

**Comment by RandyChange** [comment]
@anakin1028 
You are putting my "skills" to the test regarding git haha..

Just to be sure I am doing what you want me to.. 
Remove current wifiphisher folder -> git clone https://github.com/wifiphisher/wifiphisher.git -b warnmsg_dnsmasq_hostapd -> sudo python setup.py install -> wifiphisher -INM...

Would this be okay?? (Never cloned a specific branch down before) :)

**Comment by anakin1028** [comment]
you can just do the following:
```
git fetch
git checkout -b warnmsg_dnsmasq_hostapd origin warnmsg_dnsmasq_hostapd
```

Then you are switching to that branch. you don't need to do `python setup.py install` again.

after testing done you can switch back to master by:
`git checkout master`

**Comment by RandyChange** [comment]
@anakin1028 
http://prntscr.com/gjua18 

Wish I new a bit more about this, so this wasn't the current problem haha.

**Comment by anakin1028** [comment]
sorry I have typo:
`git checkout -b warnmsg_dnsmasq_hostapd origin/warnmsg_dnsmasq_hostapd`

**Comment by RandyChange** [comment]
@anakin1028 
Np hehe, that seemed to switch it!

Here is the new attemp: http://prntscr.com/gjud65

Btw, I do not need to do anything about my connection, right?? 
When launching wifiphisher -iNM I have a "wired" connection, and ONE connected wifi adapter. Just some info if that maybe has something to do with anything... 

I also see it selecting for for wlan0 and wlan1. I understand it being able to select one of them because of my adapter, but not the second one, now what I only have one you know.

**Comment by anakin1028** [comment]
Have you changed your adaptor's mac address by `macchanger`? Can you shut down the machine and don't change the mac address and try again.

Yes, I know you just have one adaptor and the `wlan1` is created by the program.

**Comment by RandyChange** [comment]
I did change it back, but I just initialized a update or some stuff, so it will reboot when done. After this is done I'll try again.

**Comment by RandyChange** [comment]
@anakin1028 
Ah, that went a bit faster than expected..
http://prntscr.com/gjumnw

**Comment by anakin1028** [comment]
can you try these commands as mentioned in #728 I'm thinking if there is some dependency you are not able to resolve.

```
sudo apt-get install net-tools
sudo apt-get install dnsmasq
sudo apt-get install dnsmasq-base
```
and reinstall wifiphisher.

**Comment by RandyChange** [comment]
Master branch or?

**Comment by anakin1028** [comment]
you can switch back to master.

**Comment by RandyChange** [comment]
Okay.
Only "apt-get install dnsmasq" installed anything new.
But with no difference to the output unfortunately.. :/ : http://prntscr.com/gjuv4q

**Comment by anakin1028** [comment]
Okay. I think it is the problem of `hostapd` : 
Can you manually lunch hostapd? you can follow the instruction in #731

**Comment by RandyChange** [comment]
@anakin1028 
Uhmm hehe... http://prntscr.com/gjvakn
Do I have to find some other hostapd.conf on the system and replace the file or??

**Comment by face0b1101** [comment]
@anakin1028 Sorry to join in here, but I've been following the thread and have almost exactly the same errors as @RandyChange.

@RandyChange you've got to run hostapd on the conf file's location. So in your case it's probably `hostapd ~/Desktop/hostapd.conf`

Output of hostapd:

`root@######:~/github/wifiphisher# hostapd hostapd.conf`
`Configuration file: hostapd.conf`
`Could not read interface wlan1 # change w flags: No such device`
`nl80211: Driver does not support authentication/association or connect commands`
`nl80211: deinit ifname=wlan1 # change w disabled_11b_rates=0`
`Could not read interface wlan1 # change w flags: No such device`
`nl80211 driver initialization failed.`
`wlan1 # change w: interface state UNINITIALIZED->DISABLED`
`wlan1 # change w: AP-DISABLED` 
`hostapd_free_hapd_data: Interface wlan1 # change w wasn't started`

The output is the same when run for both wlan0 and wlan1.

I am running Kali 2017 Rolling (not VM) with these:
wlan0: Built-in WLAN (iwlwifi) Intel Corporation Wireless 7265 (rev 59)
wlan1: Alfa AWUS036ACH (8812au) Realtek Semiconductor Corp. RTL8812AU 802.11a/b/g/n/ac WLAN Adapter

**Comment by RandyChange** [comment]
I have found a folder name hostapd etc/hostapd with a single file named "ifupdown.sh"

**Comment by RandyChange** [comment]
This is the output from doing what face said:
http://prntscr.com/gjvist

**Comment by face0b1101** [comment]
If I change my hostapd.conf to:

```
interface=wlan1
driver=nl80211
beacon_int=100
hw_mode=g
channel=1
ssid=TestAP
```

Then I can create an AP:

```bash
root@######:~/github/wifiphisher# hostapd hostapd.conf 
Configuration file: hostapd.conf
Using interface wlan1 with hwaddr 06:80:b2:19:7f:0b and ssid "TestAP"
wlan1: interface state UNINITIALIZED->ENABLED
wlan1: AP-ENABLED 
```

So it seems that if I specify the driver to use, nl80211, and give the AP an SSID then all is good...
Doesn't help me run WiFiPhisher any better though

**Comment by RandyChange** [comment]
@face0b1101 
I do not know much about this, so guess we'll have to wait for @anakin1028 to come up with something haha..

**Comment by blackHatMonkey** [comment]
@RandyChange Since this issue is not related to thread at all, can you open a new issue and post the errors in there please?

**Comment by RandyChange** [comment]
@blackHatMonkey
Yeah I can do that. Would it be okay if I just refer to this thread and tell the lines which has to do with it? (since we already have tried some stuff and such?)

**Comment by djdisikd** [comment]
Currently can it be used with one interface only?

**Comment by minanagehsalalma** [comment]
Here what i think that could solve the problem 
Using airodump-ng  -c option (to scan the same single channel of the ap) Or iwlist [interface] frequency
![IMG_20190505_131547](https://user-images.githubusercontent.com/20546638/57193134-47810400-6f38-11e9-9b77-e616a2517aea.png)
The steps 
![IMG_20190505_131507](https://user-images.githubusercontent.com/20546638/57193142-641d3c00-6f38-11e9-8d6c-45126bdfcd69.png)
*user

@anakin1028 @RandyChange @sophron @Jinovas  @djdisikd @blackHatMonkey @face0b1101 
Does any one have better idea ?

**Comment by fedwat82** [comment]
> Currently can it be used with one wifi adapter only?

it should be, because LINSET can do it, doing de-auth and make AP with just single adapter TL-WN722N ver.1.0, 
but i just wonder if WIFIPHISHER can't do it the same, because i dont see victim FAKE AP while it doing de-auth.

**Comment by minanagehsalalma** [comment]
Linset/fluxion  can do it with single adapter but not with channel hopping
!

**Comment by nominomoses** [comment]
in my opinion i find using a modem and wifiphisher much easier where i use
wifiphisher -iI ppp0 -aI wlan0 -eI wlan1
So the modem provides the internet while the wlan0 supports the rogue AP and it works perfectly
if anyone has a solution for when one is using wifi please lemme know

**Comment by tylerw500** [comment]
I'm pretty sure you're all looking at this wrong or at least not seeing something correct here. 
You're going to want 2 wireless adapters for this tool to correctly function due to lack of range and lack of the internal card perhaps. If you had 2 equally as strong cards that can push your evil twin well within range of your intended target.

**Comment by minanagehsalalma** [comment]
@tylerw500 

> You're going to want 2 wireless adapters for this tool to correctly function due

no you don't , check out fluxion it works more than perfect using just a single wifi adapter put in mind adapters like alfa are superb.

**Comment by tylerw500** [comment]
> @tylerw500
> 
> > You're going to want 2 wireless adapters for this tool to correctly function due
> 
> no you don't , check out fluxion it works more than perfect using just a single wifi adapter put in mind adapters like alfa are superb.

We're not talking Fluxion (good tool to keep around) but agree yes 1 adapter WILL work but the efficiency of just 1 good card and 1 built in card not as good all alfa would defeat the purpose. Just use 2 good cards at once for more results. More likely that target will auto connect to a stronger connect guaranteed.

**Comment by minanagehsalalma** [comment]
> 1 built in card

@tylerw500  and who mentioned an built in card ? it sucks why would one use anything like that ? 

> More likely that target will auto connect to a stronger connect guaranteed.

clearly you don't understand what you are talking about ... the auto connect part is called Karma which isn't good enough no more and also i don't know if it's possible to run AP + deauth +karma using only a single adapter.

**Comment by fedwat82** [comment]
hey guys
we're talked about "Using only one card to do deauthentication and lunching AP"
and i used linset and fluxion within just single TL-WN722N ver 1.0 , 
work perfectly, i could have 5 neighbour wifi password at that time.
so why do we have make this complicated? use fluxion, simple, and not wasted time
