### ISSUE TITLE
Everything work but deauth/jamming not working

### ISSUE THREAD

**Issue by lwj88** [wifiphisher/wifiphisher#660]
First, I know this issue is similar to many previous issue and the questions inside FAQ but my issue is different. Everything working and but the deauth/jamming not working. I tried my wifi and I did not deauth/jammed by wifiphisher (using phone) the wifiphisher showing it is deauthing. Since it is my own wifi so of course it is near to my adapters. My adapters are TL-WN722N AP, monitor, packet injection supported. Please help, thanks.

**Comment by anakin1028** [comment]
@lwj88 what command do you use? Do you use `-essid` option? Also can you use `wireshark` or `tcpdump` to capture and post it in this thread?

**Comment by lwj88** [comment]
No, I did not use -essid option. I will try again later, because my friend also having this problem before and after replug the adapter the jamming work again. If still not working then I will do what you request me to do.

**Comment by anakin1028** [comment]
OK thanks. Since we have a bug for using the `-essid` option now; otherwise deauthentication should work well.

**Comment by lwj88** [comment]
@anakin1028 thanks for replies, the jamming is now work but after I try my wifi and found out that the client wont auto connect, and after searching in the wifiphisher issues find out that client must manually connect the fake AP. I will try again on peak hour. Hope wifiphisher got new way that can force client to auto connect.
