### ISSUE TITLE
UnboundLocalError: local variable 'row_number' referenced before assignment

### ISSUE THREAD

**Issue by usama7628674** [wifiphisher/wifiphisher#662]
After running wifiphisher and scaning access points and selecting any AP it showed me this
```
root@kali:~# wifiphisher
[*] Starting Wifiphisher 1.3GIT at 2017-07-03 18:38
[+] Sending SIGKILL to wpa_supplicant
[+] Sending SIGKILL to dhclient
[+] Selecting wlan1 interface for the deauthentication attack
[+] Selecting wlan0 interface for creating the rogue Access Point
[+] Changing wlan0 MAC addr (BSSID) to 00:00:00:47:29:a1
[+] Changing wlan1 MAC addr (BSSID) to 00:00:00:b2:63:be
[*] Cleared leases, started DHCP, set up iptables
Traceback (most recent call last):
  File "/usr/local/bin/wifiphisher", line 11, in <module>
    load_entry_point('wifiphisher==1.3', 'console_scripts', 'wifiphisher')()
  File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.3-py2.7.egg/wifiphisher/pywifiphisher.py", line 776, in run
    engine.start()
  File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.3-py2.7.egg/wifiphisher/pywifiphisher.py", line 653, in start
    template = tui_template_obj.gather_info(args.phishingscenario, self.template_manager)
  File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.3-py2.7.egg/wifiphisher/common/tui.py", line 80, in gather_info
    template_names)
  File "/usr/lib/python2.7/curses/wrapper.py", line 43, in wrapper
    return func(stdscr, *args, **kwds)
  File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.3-py2.7.egg/wifiphisher/common/tui.py", line 193, in display_info
    row_number += 2
UnboundLocalError: local variable 'row_number' referenced before assignment
```

**Comment by anakin1028** [comment]
@usama7628674, I have fixed this issue. Can you pull the latest commit and try again?

**Comment by usama7628674** [comment]
I'm using extra phishing pages that caused these erros.Without using these pages wifiphiser works fine
but I pulled latest commit and now it stuck at scanning AP section so I removed gopro-phish and now it stuck at Phishing scenario section.If I select any scenario like facebook-login or any other by hitting enter it 
doesn't select anyone.But if I use command line section all phishing scenarios works

**Comment by anakin1028** [comment]
hmm.. the modification should not affect with the AP selection stage. Does wifiphisher work fine for the latest commit if you don't add any phishing scenarios?

**Comment by usama7628674** [comment]
It works fine before and after latest commit

**Comment by anakin1028** [comment]
OK. I'll try to add more phishing scenarios and see if this happens.

**Comment by anakin1028** [comment]
@usama7628674 I have proposed a PR for fixing this issue.
Can you help to double confirm that? You can pull the code on the branch: `refactor_tui` by the following commands:

```shell
git fetch
git merge origin refactor_tui
git checkout refactor_tui
```

And do the test. After the test is done, you can switch to the master branch by:
```
git checkout master
```

**Comment by usama7628674** [comment]
Ok now it's working fine.I can  select templates but there is still one problem I have 10 phishing
pages but at the template selection screen I can see only nine because it's not scrolling down but still
I can select 10th template using down arrow key other than that it's working pretty well.
the proposed PR request works correctly.

**Comment by anakin1028** [comment]
good to hear about that. I'm not so sure I have captured your last question. When you press the `down arrow key`, will it jump to another page to show your 10th phishing scenario?

**Comment by usama7628674** [comment]
@anakin1028 
No it didn't jump to another page.It's showing me only 9 templates and after that higlighter goes to 10th template but it's not scrolling down to show me 10th template.

**Comment by usama7628674** [comment]
@anakin1028 
Now it's jumping to another page and I can see all 10 templates and all are working fine.Thanks for
your help and replies.

**Comment by anakin1028** [comment]
You're welcome : ) 
I will close this issue once this PR is merged.
