### ISSUE TITLE
Network manager dissapeared and no network after closing wifiphisher

### ISSUE THREAD

**Issue by oasqalani** [wifiphisher/wifiphisher#665]
after using the phisher and closing it , network icon disappeared , even restart doesn't get it back  , no network manager or Internet  connectivity , please help

**Comment by usama7628674** [comment]
Here's you can do to resolve the problem
iw wlan0 del (or check interface using iwconfig and change accordingly)
airmon-ng start wlan0
airodump-ng wlan0mon
ctrl+c
airmon-ng stop wlan0mon
service network-manager restart
nmcli n
nmcli n on

write these commands in terminal and report back

**Comment by anakin1028** [comment]
I think you can use command `nmcli n on` first and see if the icon is popped up. The problem is that you may have terminated the wifiphisher abruptly. This is a problem we may solve in the future.  

In the ap selection section, try to use `ESC` to leave and only press `ctrl-C` in the final terminal section (i.e. section displayed the HTTP resquests/Deauth client/DHCP lease).

**Comment by oasqalani** [comment]
thanks for your reply , obviously i closed the vm after hours of searching , so when i opened it i skipped the turning monitor mode off section and checked the processes below
root@KALI:/home/phantom# airmon-ng start wlan0

Found 2 processes that could cause trouble.
If airodump-ng, aireplay-ng or airtun-ng stops working after
a short period of time, you may want to run 'airmon-ng check kill'

   PID Name
   650 NetworkManager
  1076 wpa_supplicant

PHY	Interface	Driver		Chipset


root@KALI:/home/phantom# service network-manager restart
root@KALI:/home/phantom# nmcli n
disabled
root@KALI:/home/phantom# nmcli n on
root@KALI:/home/phantom# 


then nothing happened

**Comment by oasqalani** [comment]
@anakin1028  i closed it using Ctrl+c , then it showed the part of the credentials and all this stuff , but i dont know why this happened , thanks :)

**Comment by anakin1028** [comment]
@oasqalani can you post the output of `nmcli n` after you use the command `nmcli n on`?

**Comment by anakin1028** [comment]
Also can you post `nmcli dev status`. We need to check your devices are managed by NetworkManager or not.

**Comment by oasqalani** [comment]
@anakin1028 
`root@KALI:/home/phantom# nmcli n`
disabled
`root@KALI:/home/phantom# nmcli n on`
`root@KALI:/home/phantom#`

thats it , nothing happened

**Comment by anakin1028** [comment]
So after you type `nmcli n on`, `nmcli n` still shows `disabled`?

**Comment by oasqalani** [comment]
@anakin1028 
`root@KALI:/home/phantom# nmcli dev status`
DEVICE  TYPE      STATE        CONNECTION 
eth0    ethernet  unavailable  --         
lo      loopback  unmanaged    --         
`root@KALI:/home/phantom# `


and after using nmcli n again it shows enabled

**Comment by anakin1028** [comment]
OK. That means the Networking is now starting. But the strange part is from the output of `nmcli dev status`, there is no wireless devices.

**Comment by oasqalani** [comment]
@anakin1028  because im on a vmware machine , i tried to remove and add the usb wifi card , it showed up the wifi logo , but still the wired connection logo that is shared with the host is missing

**Comment by oasqalani** [comment]
@anakin1028  i tried to reinstall the network manager from scratch and it started perfectly , closing the phisher abruptly was the mistake , however thank you so much for that help and care 👍

**Comment by anakin1028** [comment]
you're welcome : )
