### ISSUE TITLE
Wifi not working since using wifiphisher

### ISSUE THREAD

**Issue by shetty87** [wifiphisher/wifiphisher#669]
I ran wifiphisher last night and worked fine but since I've ran it I can't connect my wifi to the internet, it's missing from the drop down section. 

Anyone had this issue? I don't want to do a fresh install :(  I'm using Kali Linux

**Comment by anakin1028** [comment]
have you tried `nmcli n on`? can you post the output of `nmcli n`?

**Comment by shetty87** [comment]
Root@kali:~# nmcli n
disabled

**Comment by shetty87** [comment]
Nmcli n on worked!

I love you man xxx lol

**Comment by anakin1028** [comment]
Nice to hear about that : p

**Comment by sophron** [comment]
Many users seem to be getting this. Can we catch a `SIGHUP` or a `KeyboardInterrupt` and start the network manager on exit?
