### ISSUE TITLE
Captive portal for older IOS devices

### ISSUE THREAD

**Issue by fracorallo** [wifiphisher/wifiphisher#678]
The wifiphisher attack does not work anymore against the newest versions of iOS, i tried different versions to be sure. I think Apple corrected this Security issue.

**Comment by fracorallo** [comment]
The iPhone does not connect to the open-key AP, neither when you deassociate Phone from the router manually

**Comment by anakin1028** [comment]
Does the target AccessPoint has security or 
just  open? Can you use wireshark to sniff the frames and post the capture on this thread?

**Comment by fracorallo** [comment]
The target AccessPoiny has security. I'm not sure to be able to do what you ask

**Comment by anakin1028** [comment]
Ok. If the target AP has security then the victim cannot auto connect to our fake AP.
You can try to set the target AP to no-security, and  check whether auto-connect happen or not.

**Comment by fracorallo** [comment]
I've Just tried to create an open AP with
" wifiphisher -nJ -e test " but after connecting with the iPhone nothing happens, neither with NetworkManager mode, nor Oauth mode, nor Firmware Upgrade.

**Comment by fracorallo** [comment]
With older versions of iOS it is working instead

**Comment by anakin1028** [comment]
@fracorallo 
If you use the command : `wifiphisher -nJ -e test`, this means you will create a no-security fakeAP and if the attacked target AP has security (WPA2/WPA/WEP), then auto-connect cannot happen (also `-nJ` option means no deauth, you will lose the deauthing process to make auto-connect happen)

What I mean in the previous comment is you change the attacked target AP to no security and just use the following command:
`wifiphisher`
And make sure you have two wireless cards. Let one card lunch the fakeAP and the other one forge the deauth frames.

**Comment by fracorallo** [comment]
I'm not testing auto connecting capabilities. I'm saying that after connecting in whatever way you want, to some AP (maybe open, maybe a fake AP of a real encrypted target), so after connection being established,  the script is not able to finalize Oauth requests, nor fake page password requests! It Just doesn't work

**Comment by anakin1028** [comment]
Do you mean if once the victim has connected to the target AP (whatever the security), it cannot associate to our fakeAP even if you manaually disassociate to the original AP?

If so it really depends on the iOS's NetworkManager's design. If the iOS's NetworkManager doesn't send the probe request to the Open-Key AP by default, even if we lunch the same ESSID as the target AP, it will not associate to our fakeAP.

**Comment by fracorallo** [comment]
I'll try to be more clear. Two situations and two problems:
- Take a wpa-secured AP: you start your fake AP, the victim sees the fake AP and try to connect to it, but the victim phone seems to "remember" the old secured AP and doesn't let connecting to the fake AP even if has much stronger power. If the victim disassociate from the wpa-secured AP, then the connection to the fake-AP works but without Oauth or firmware upgrade capabilities.
- Take an open AP: The victim sees the fake AP and connects to it (or auto-connects), the iPhone successfully connects to the fake AP, but then nothing works, no Oauth, no FirmwareUpgrade, no fake pages redirecting.
I tried this two situations with two different Apple devices, with older and newer operating system. The newer one has this problems.

**Comment by anakin1028** [comment]
Thanks for your clearly update~

> Take a wpa-secured AP: you start your fake AP, the victim sees the fake AP and try to connect to it, but the victim phone seems to "remember" the old secured AP and doesn't let connecting to the fake AP even if has much stronger power. If the victim disassociate from the wpa-secured AP, then the connection to the fake-AP works but without Oauth or firmware upgrade capabilities.

   Yes. Since the fake AP doesn't have the same security with the target AP. Like you say, the victim will remember the old setting, and after we reply the probe reponse to the victim, the victim will discover that the security is not matched.

> Take an open AP: The victim sees the fake AP and connects to it (or auto-connects), the iPhone successfully connects to the fake AP, but then nothing works, no Oauth, no FirmwareUpgrade, no fake pages redirecting.

This one is a little strange. From wifiphisher main terminal, do you see we are giving the dhcp release to the victim?

We may need the pcap capture to dig more. You can first check your device name by the command: `iw dev` and then use the command `wireshark wlan0` to capture the frames (i.e. change `wlan0` to the one you observe from `iw dev`).

**Comment by anakin1028** [comment]
Ok. I'll compare the capture with iPhone7.  Have you tried to manually  enter a web page and see if it redirect to the phishing page?

**Comment by fracorallo** [comment]
Yes I tried it, didn't work

**Comment by anakin1028** [comment]
@fracorallo thanks for your capture:

* Quick Summary:
Captive Portal will be workable for iOS device, if we return `http 200` back to the http request with
URI equal to `/hotspot-detect.html` and from the capture you have given to us I can see wifiphisher has replied this message, but your device seems to drop this frame on the higher protocol layer.

This is the capture from your device:

As you can see wifiphisher has replied with `http OK`, but the device doesn't request the phishing pages.
![cannot_work](https://user-images.githubusercontent.com/6182530/28373180-4844a922-6cd4-11e7-8a62-0ed648daba84.png)

Here is my device with iOS version: 10.3.2 (This is the newest iOS version)
After replying the `/hotspot-detect.html`, my device starts to request other resources.

![workable](https://user-images.githubusercontent.com/6182530/28373332-a5b8cdae-6cd4-11e7-9e5f-afec0bd28407.png)

And from your capture I can see under the `linker level (layer2 in OSI model)`, your device replies with `ACK` and that means your device has received this `http 200` frame. But I'm not sure if your device has dropped this frame on the higher protocol layer.

![ack](https://user-images.githubusercontent.com/6182530/28373790-c7d3fba6-6cd5-11e7-9780-a917b3c79c79.png)

**Comment by anakin1028** [comment]
If you are interested in this problem, you may want to use `tcpdump` on your device and check the behavior on the protocol layer upper than `layer2`.

**Comment by fracorallo** [comment]
Ok you're right. I tried with another iPhone with the latest version of iOS and it worked perfectly. Then i tried with my iPhone and it didn't work. So it must be something related to my iPhone settings maybe. I tried to delete safari cache but nothing. Then i made this test: successfully connected with my iPhone but no phishing pages appeared, then connected to the AP also with the other working iPhone and the phishing page appeared simultaenously on both the iPhones. 
I could try to force-restart the iPhone to solve the problem but we may not know what was the reason of this problem. How do I do the tcpdump test that you said?

**Comment by anakin1028** [comment]
@fracorallo, thanks for your update : )

I haven't done this before though. Maybe you need to do some research about it.
Here is a tutorial about this but I have no time to verify it.
https://useyourloaf.com/blog/remote-packet-capture-for-ios-devices/

**Comment by fracorallo** [comment]
Ok Anakin thank you for your help and explanation (I thought wifiphisher was not anymore working fiuu :D). I'll make some research for this. 

Do I have to close this issue on github ?

**Comment by anakin1028** [comment]
You're welcome : )
We can keep it open. If you have new discoveries you can update here to help community~

**Comment by sophron** [comment]
I'm closing this. @fracorallo if you have any more discoveries, please open a new issue.
