### ISSUE TITLE
How to use another network adapters?

### ISSUE THREAD

**Issue by ganduras** [wifiphisher/wifiphisher#681]
When I start wifiphisher he in using the notebook wifi adapter which is wlan0 , and the wifi antenna wlan1 . I have another wifi antenna that is more powerful and is wlan2. How to change the default adapter to use?

**Comment by anakin1028** [comment]
You can use `-jI` and `aI` options to select deauth and AP card respectively.
Like the following:
`wifiphisher -aI wlan0 -jI wlan2` then wlan0 is ap interface and wlan2 is the jamming interface.
