### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'stop'

### ISSUE THREAD

**Issue by slavisam87** [wifiphisher/wifiphisher#684]
**Version**: commit a15a2984edf4287f50b12320eb79d46cfe93ead5

**Description**: I just installed/setup the 1.3 version on Kali Linux and simply running "sudo python bin/wifiphisher" for the very first time.
`root@kali:~/wifiphisher# sudo python bin/wifiphisher
[*] Starting Wifiphisher 1.3GIT ( https://wifiphisher.org ) at 2017-07-25 15:37
[!] Failed to find an interface with AP mode
[+] Captured credentials:
Traceback (most recent call last):
  File "bin/wifiphisher", line 12, in <module>
    run()
  File "/root/wifiphisher/wifiphisher/pywifiphisher.py", line 777, in run
    engine.start()
  File "/root/wifiphisher/wifiphisher/pywifiphisher.py", line 607, in start
    self.stop()
  File "/root/wifiphisher/wifiphisher/pywifiphisher.py", line 504, in stop
    self.access_point.on_exit()
  File "/root/wifiphisher/wifiphisher/common/accesspoint.py", line 186, in on_exit
    self.hostapd_object.stop()
AttributeError: 'NoneType' object has no attribute 'stop'
`
iw list:
`root@kali:~/wifiphisher# iwlist
Usage: iwlist [interface] scanning [essid NNN] [last]
              [interface] frequency 
              [interface] channel 
              [interface] bitrate 
              [interface] rate 
              [interface] encryption 
              [interface] keys 
              [interface] power 
              [interface] txpower 
              [interface] retry 
              [interface] ap 
              [interface] accesspoints 
              [interface] peers 
              [interface] event 
              [interface] auth 
              [interface] wpakeys 
              [interface] genie 
              [interface] modulation
` 
iwconfig:
`root@kali:~/wifiphisher# iwconfig
eth0      no wireless extensions.
lo        no wireless extensions
wlan0mon  IEEE 802.11  ESSID:off/any  
          Mode:Managed  Access Point: Not-Associated   Tx-Power=20 dBm   
          Retry short limit:7   RTS thr:off   Fragment thr:off
          Encryption key:off
          Power Management:off
`

**Comment by anakin1028** [comment]
@slavisam87. It's the same issue as #683. We have some issue about the newly import module `roguehostapd`. You can track this issue on that thread : )
