### ISSUE TITLE
Issue running attack "Attribute error"

### ISSUE THREAD

**Issue by StratoMusic** [wifiphisher/wifiphisher#687]
Hello everyone, ive spent hours trying to get wifiphisher to work properly but i just cant seem to get it to work.

Ive read this topic and tried to follow:

https://github.com/wifiphisher/wifiphisher/issues/683

im getting this error while running attack:

Traceback (most recent call last):
File "./wifiphisher", line 12, in

File "/root/wifiphisher/wifiphisher/pywifiphisher.py", line 777, in run
engine.start()
File "/root/wifiphisher/wifiphisher/pywifiphisher.py", line 766, in start
curses.wrapper(tui_main_object.gather_info, main_info)
File "/usr/lib/python2.7/curses/wrapper.py", line 43, in wrapper
return func(stdscr, *args, **kwds)
File "/root/wifiphisher/wifiphisher/common/tui.py", line 610, in gather_info
is_done = self.display_info(screen, info)
File "/root/wifiphisher/wifiphisher/common/tui.py", line 733, in display_info
self.print_http_requests(screen, 14, http_output)
File "/root/wifiphisher/wifiphisher/common/tui.py", line 634, in print_http_requests
request_type = match.group(1)
AttributeError: 'NoneType' object has no attribute 'group'

i have tried all of the above but still cant seem to fix

This is what i have on this path, might be useful as its kinda different from the one mentioned on the previous topic.

root@Valhalla:/usr/local/lib/python2.7/dist-packages# ls
blessings-1.6-py2.7.egg                   PyRIC-0.1.6.3-py2.7.egg
dbus_python-1.2.4-py2.7-linux-x86_64.egg  roguehostapd
easy-install.pth                          roguehostapd-1.1.5.dist-info
pip                                       wifiphisher-1.3-py2.7.egg
pip-9.0.1.dist-info
root@Valhalla:/usr/local/lib/python2.7/dist-packages#

**Comment by anakin1028** [comment]
Can you pull the latest commit to test if this bug fix?

**Comment by StratoMusic** [comment]
Yes i just downloaded hours ago doing

Git clone http://github.com/wifiphisher/wifiphisher.git

Then cd to location, ran the installer

Then cd to bin, and launch.

I did airmon-ng check kill before launching otherwise it gives error of network manager active.

**Comment by anakin1028** [comment]
I just push a new commit. Can you pull the newest one?

**Comment by StratoMusic** [comment]
Amazing man, it seems to be working now, will continue testing the following hours, thank you!!!

**Comment by anakin1028** [comment]
sure, thanks : )

**Comment by StratoMusic** [comment]
for some reason, now after trying to select a network to attack i get the "YOU HAVE SELECTED"

IT gets stuck on that, i already restarted and still.

**Comment by StratoMusic** [comment]
I noticed something weird after turning off pc after succesfully using it.

Now it wont turn off completely, it get stuck with message like:

NMI watchdog bug soft lockup cpu#0 stuck for 23s!

Blocking rcu node structures


And more stuff that just keep on going, need to hard turn off pc and restart.

Maybe thats why wifiphisher getting stuck now.

**Comment by StratoMusic** [comment]
Weird the issue of those messages on shutdown dissapeared after unplugging laptop charger lol.

But the wifiphisher is still getting stuck after choosing network to attack.


Im posting every detail i can to help other people.

**Comment by StratoMusic** [comment]
Fixed the stuck on network selection by removing some of the extra phishing pages i had. seems to take longer when they are on the folder.

**Comment by anakin1028** [comment]
Yes. We have fixed the stuck issue in other branch. Have a look for #662
