### ISSUE TITLE
Plugin update not loading apk

### ISSUE THREAD

**Issue by StratoMusic** [wifiphisher/wifiphisher#688]
Hello, 

Ive went ahead and tried to load payload from metasploit for android (apk)

When opening up on browser already connected on fake ap, it doesnt downloads the shell.apk i chose, instead it prompts download for a "update.exe" which obviously cant be run and wasnt the payload i chose.

How to fix?

**Comment by anakin1028** [comment]
I'm not so sure I have captured what you mean. Do you use the `Browser Plugin` template?

**Comment by StratoMusic** [comment]
Yes using the plugin update template.

It asks me to select payload, correct? I selected my apk payload created with metasploit.

But when prompted with the page and clicking download on mobile phone, the file it downloads it is a .exe not the apk payload i specified.

**Comment by anakin1028** [comment]
have you changed the modified the `config.ini` on the `data/phishing-pages/plugin_update` to change the update path to your file?

**Comment by anakin1028** [comment]
try to change the PayloadPath and the update_path to your desired payload
```shell
[info]
Name: Browser Plugin Update
Description: A generic browser plugin update page that can be used to serve payloads to the victims.
PayloadPath: plugin_update/static/update/update.exe

[context]
# If you change the line below, make sure you change the PayloadPath above accordingly
update_path: static/update/update.exe

```

**Comment by sophron** [comment]
@anakin1028 The issue here is different.

@StratoMusic wants to deliver an .apk but we rename the .apk to .exe. This is a bug from our side.

**Comment by StratoMusic** [comment]
Exactly, infact, i wouldnt know i needed to go and change that config file since when choosing the plugin attack it asks me on the terminal for the path of file...

In which case i specified it for my apk but didnt seem to use it.

**Comment by anakin1028** [comment]
Got it. Thanks for you two 's explanation : )

**Comment by anakin1028** [comment]
@StratoMusic we have a PR for fixing this issue. If you want to test, you can pull the branch for #694. 
Thanks.
