### ISSUE TITLE
Failed to find an interface with AP mode

### ISSUE THREAD

**Issue by darkworks** [wifiphisher/wifiphisher#689]
latest version , 1.3

i have installed v1.3 of wifiphisher when i run it  i get

> 
> [*] Starting Wifiphisher 1.3GIT ( https://wifiphisher.org ) at 2017-07-30 14:34
> [!] Failed to find an interface with AP mode
> [+] Captured credentials:
> [!] Closing

Am using Alfa AWUS036NHA card which works ok with wifite on wps attacks 

rfkill list   result is 

> 1: phy1: Wireless LAN
> 	Soft blocked: no
> 	Hard blocked: no

Supported interface modes:

> 		 * IBSS
> 		 * managed
> 		 * AP
> 		 * AP/VLAN
> 		 * monitor
> 		 * mesh point
> 		 * P2P-client
> 		 * P2P-GO
> 

any idea to make it working ...

**Comment by anakin1028** [comment]
It seems that you only have one card. Try to use `wifiphisher -nJ` instead.

**Comment by darkworks** [comment]
ya wifiphisher -nJ   worked , 
however not disconnecting users from AP , tried on my home router ... am still connected , it would be good if it contentiously disconnect users from original AP

**Comment by anakin1028** [comment]
Currently we have to use two cards to do deauth and lunch ap respectively. I have purpose a PR for jamming in one interface. You can pull the branch : `jam_ap_in_one_interface` to do the test.

**Comment by darkworks** [comment]
ya it worked :) no it deauth it same time ... however iphone not connecting with it ,  earlier with main branch version which i used with -nj which were not deauth it same time the AP created iphone was able to connect , however with this it not connect ... i connected PC after 2nd try as it first it showed taking more time than usual.

**Comment by anakin1028** [comment]
Do you mean even if you manually choose the fakeAP, iphone will not connect to the fakeAP?

Can you use `wireshark` to capture the frames as `.pcap` file and post the file in this thread?
```shell
wireshark wlan0 #choose the monitor mode one
```

**Comment by anakin1028** [comment]
Also notice that if your target attacking AP has security, iPhone will not auto-connect to our fakeAP.
