### ISSUE TITLE
[!] The provided interface "eth0" is invalid!

### ISSUE THREAD

**Issue by ConnorPatterson** [wifiphisher/wifiphisher#690]
Description: Program outputs error "[!] The provided interface "eth0" is invalid!"  The AP can be run without a specified --internetinterface, but then the AP doesn't give Internet access to connecting clients that have submitted credentials to the phishing page.  Otherwise, the eth0 interface appears to be configured properly, the machine is connected to the Internet.

Script output: 
![wp1](https://user-images.githubusercontent.com/26098605/28834698-3fc61030-76a0-11e7-9128-cc0bfbfbc67b.png)
![wp2](https://user-images.githubusercontent.com/26098605/28834697-3fb662d4-76a0-11e7-997c-8f282cdab6df.png)

The script is the most recent version, cloned from Github.

**Comment by anakin1028** [comment]
@ConnorPatterson, thanks for filling the bug report : ) 
We have a PR for fixing this. After the PR is merged this should be fixed.

**Comment by ConnorPatterson** [comment]
Thank you, looking forward to it :)
