### ISSUE TITLE
Deauth module refactor

### ISSUE THREAD

**Issue by blackHatMonkey** [wifiphisher/wifiphisher#691]
@anakin1028 @sophron While looking at the code for `deauth` I noticed a check which was left from the previous version.

```python
104 # check if the packet has a dot11 layer
105 if packet.haslayer(dot11.Dot11):
```
I was wondering if you know using this
```python
dot11.sniff(
                iface=self._interface,
                prn=self._process_packet,
                count=1,
                store=0,
                stop_filter=self._stopfilter)
```
gurantees a packet with `dot11` header?

**Comment by anakin1028** [comment]
@blackHatMonkey. Yes I think `dot11.sniff` only get the `layer2` frames, and we can do some test by removing the check for `packet.haslayer`

**Comment by blackHatMonkey** [comment]
@anakin1028 @sophron Currently we are doing a try catch when grabbing the channel for the packet in case of a frenzy like so:
```python
# obtain the channel for this packet
try:
    # channel is in the third IE of Dot11Elt
    channel = ord(packet[dot11.Dot11Elt][2].info)
    channels.append(str(channel))
except (TypeError, IndexError):
     # just return empty channel and packet
     return ([], [])
```
 Does the client care about channel when processing deauth/disassociation? if so can we remove it since in case of a frenzy we are adding all the channels?

**Comment by blackHatMonkey** [comment]
@sophron @anakin1028  Another thing I noticed was in the `extention` the `self._packets_to_send` dictionary is never cleared in any way. I think we should at some point clear it since after running the tool for a while my **guess** is that it will use a huge chunck of memory and will contain many duplicate entries.

**Comment by anakin1028** [comment]
@blackHatMonkey 
  

1. > Currently we are doing a try catch when grabbing the channel for the packet in case of a frenzy like so:

Indeed frenzy will sweep all the channels and send the deauth frames. But notice that a specific client can only stay on the fixed channel (which the associated AccessPoint stayed at), we only need to send the deauth frame on that channel and we don't want send that deauth frame cross all the channels.

For example:
```
     Client 1 connected to AP1 [Channel 6]
     Client 2 connect to AP2 [Channel 11]
     Client 3 connect to AP1 [Channel 6]
```
Then frenzy mode should work like following:
```
     Send Deauth(Client1, AP1) and Deauth(Client3, AP1) on Channel 6
     Send Deauth(Client2, AP2) on Channel 11
```

Instead of:
```
Send Deauth(Client1, AP1), Deauth(Client2, AP2), Deauth(Client3, AP1) 
for both channel 6 and channel 11
```
Since doing so just waste resource, Client1 won't receive the deauth frame on channel 11 while Client 2 won't receive the deauth frame on channel 6.

2. 

> @sophron @anakin1028 Another thing I noticed was in the extention the self._packets_to_send dictionary is never cleared in any way. I think we should at some point clear it since after running the tool for a while my guess is that it will use a huge chunck of memory and will contain many duplicate entries.

I'm not sure what do you mean by duplicate entries since we'll check the client already in our client list in deauth module, right? If the clients are already included in the deauth list, we'll not include them again.
However, indeed memory may be increasing since the clients may leave Network, but our program will not remove them in the deauth list when they leave.

**Comment by blackHatMonkey** [comment]
@anakin1028
>Since doing so just waste resource, Client1 won't receive the deauth frame on channel 11 while Client 2 won't receive the deauth frame on channel 6.

You are right :smile:

>I'm not sure what do you mean by duplicate entries since we'll check the client already in our client list in deauth module, right? If the clients are already included in the deauth list, we'll not include them again.
However, indeed memory may be increasing since the clients may leave Network, but our program will not remove them in the deauth list when they leave.

Yes I missed the fact that we add the clients to non valid list.


Looking at this section of the code:
```python
# in case the receiver is the access point
if receiver == bssid:
    # add the sender to the client list
    self._observed_clients.append(sender)

    # create and add deauthentication packets for client
    self.packets_to_send += self._craft_packet(sender,
                                                                         receiver,
                                                                         bssid)
    self.packets_to_send += self._craft_packet(receiver,
                                                                         sender,
                                                                          bssid)

# in case the sender is the access point
elif sender == bssid:
    # add the receiver to the client list
    self._observed_clients.append(receiver)

    # create and add deauthentication packets for client
    self.packets_to_send += self._craft_packet(receiver,
                                                                         sender,
                                                                         bssid)
    self.packets_to_send += self._craft_packet(sender,
                                                                         receiver,
                                                                          bssid)
```
What happens when you are in frenzy mode and packet is from another access point. Do we need to keep track of the observed access points as well.

Another question given this code
```python
 self.packets_to_send = self._craft_packet(self._data.target_ap_bssid,
                                           constants.WIFI_BROADCAST,
                                            self._data.target_ap_bssid)
```
which is currently in the `__init__` would it be okay to move it to `_craft_packet` or where do you think is the best place.

**Comment by anakin1028** [comment]
>What happens when you are in frenzy mode and packet is from another access point. Do we need to keep track of the observed access points as well.

I think we don't need to track the observed access points since sending deauth frame only make sense when there are stations associated to the access point. 

[BTW] I have tried to track the access point since when we are in frenzy mode, we don't have target BSSID so I have to keep track the BSSIDs on the air and send those broadcast frames. But after doing this, I found it's too busy to send the broadcast deauth frames, and not able sends the unicast frames, so I remove that part for performance issue.

>Another question given this code

The problem is broadcast frame should only include once since we don't want to duplicate include the same format frame in `packets_to_send dictionary`. I think the best way is to create one more common function in each `extension module` called `extension_init`, and do the stuffs only need to be done once.
Like the `lure10` module, currently we parse the beacon in `get_packet` and use a flag to make sure it only does once. If we add this `init` common function, we can also move `beacon parsing` in this newly added function.

**Comment by anakin1028** [comment]
I miss one of your questions:
In frenzy mode, I will extract the BSSID from the sniffed frames and use it as the AP's MAC address. We only need to record client list, since AP always need to send to one client(unless broadcast), right: )

**Comment by blackHatMonkey** [comment]
@anakin1028 Thanks for the answers :smile:.
We currently have this
```ptyhon
# Do not send deauth for our rogue access point
if bssid == self._data.rogue_ap_mac:
    return ([], [])
```
only in the frenzy section of the code. Don't we need to check it all the time even in case `--essid` is not set?

**Comment by anakin1028** [comment]
@blackHatMonkey No problem : )

No we don't need. The problem of `--essid` is that we don't know the MAC address of the target AP. Since there may be multiple AP with different MAC address but all map to the same ESSID. So when I do this feature I have to sniff on the air and extract the BSSID excluding our own AP address [We don't want to deauth our rogue AP; otherwise the victims will not connect to us : (].

If we don't use `--essid`, we'll have the attacking AP's MAC address and we can simply fill the BSSID of the deauth frame with this target AP's MAC address.

**Comment by blackHatMonkey** [comment]
@anakin1028 Just noticed something so correct me if I'm wrong but in `get_packet` we are returning `self.packets_to_send`. Going back to our conversation about adding duplicates imagine this scenario:
```
first run:
new client added

deauth: self.packets_to_send = [client1]
extenstions: self.packets_to_send = [client1]

second run:
new client added

deauth: self.packets_to_send = [client1, client2]
extenstions: self.packets_to_send = [client1, client1, client2]

...
```
which grows the `self.packets_to_send` exponentially.

**Comment by anakin1028** [comment]
Correct. This is a bug for the current Deauth module.

**Comment by anakin1028** [comment]
I found another bug for our Deauth module. The deauth module doesn't check the sniff channel number is in the `range(1, 14)`. Since the frame may be malformed. 

Like the following capture:
![channel_number_not_valid](https://user-images.githubusercontent.com/6182530/28975295-16317ce0-796c-11e7-9858-b3c46da51640.png)

Do you think you can also fix this in this issue? We may also define a new constant: `ALL_2G_CHANNELS = range(1, 14)` since this list seems to be used across modules [i.e. `recon.py` and `deauth.py`].

**Comment by anakin1028** [comment]
@blackHatMonkey 
After thinking for a while, I think this problem may not be easy to reproduce in your environment (i.e. Need busy air condition), so I just create a PR for this.

**Comment by blackHatMonkey** [comment]
@anakin1028 Do you know why we are catching an `IndexError` here:
```python

# obtain the channel for this packet
try:
    # channel is in the third IE of Dot11Elt
    channel = ord(packet[dot11.Dot11Elt][2].info)
    channels.append(str(channel))
except (TypeError, IndexError):
    # just return empty channel and packet
    return ([], [])
```
From what I can see `ord` only throws a `TypeError`.

**Comment by anakin1028** [comment]
When we do `packet[dot11.Dot11Elt][2]` we are trying to index the `Information Element` which contains the channel number. The frame may be malformed due to busy air and doesn't contain that element so we need to protect for that case.

**Comment by blackHatMonkey** [comment]
@anakin1028 What about this
```python
if receiver in non_valid_list and sender in non_valid_list:
```
should this be a `and` or an `or`?

**Comment by blackHatMonkey** [comment]
So to give you more contex which of these is a valid packet that we must process:
```
1. sender = INVALID
receiver = "11:11:11:11:11:11"
bssid = "11:11:11:11:11:11"

2. sender = "00:00:00:00:00:00"
receiver = INVALID
bssid = "11:11:11:11:11:11"

3. sender = INVALID
receiver = INVALID
bssid = "11:11:11:11:11:11"
```

**Comment by anakin1028** [comment]
I think the problem we have now is that we mix the invalid MAC addresses with the observed clients.
We should separate them.
With the invalid MAC address : like one defined as 00:00:00:00:00:00 should be `and`. 
For the observed clients we should use `or`

**Comment by blackHatMonkey** [comment]
@anakin1028  So would this be the correct logic:
```python
if ((receiver in constants.NON_CLIENT_ADDRESSES and  sender in constants.NON_CLIENT_ADDRESSES) or
    (receiver in self._observed_clients or sender in self._observed_clients)):
```

**Comment by anakin1028** [comment]
@blackHatMonkey 

After thinking for a while I think the current logic is correct.

First if we want to check if the MAC address is valid, it should be `and` logic as I said before:

```python
if receiver not in constants.NON_CLIENT_ADDRESSES and sender not in constants.NON_CLIENT_ADDRESSES: # we don't want the INVALID MAC in both sender and receiver's MAC addresses.
``` 

For the second one (i.e. the one we want to check if we already include the observed clients), there is no difference between using `and` and `or`. Either one of sender or receiver is the AP's MAC address and this MAC address should always `not in non_valid_list`. That means one of the following condition always be true:

```python
* receiver not in non_valid_list
* sender not in non_valid_list
```

So this equivalence to only check if client is in non-valid list.

**Comment by anakin1028** [comment]
More solid examples:

```shell
1. sender : INVALID (i.e. something like 00:00:00:00:00:00)
    receiver : INVALID
    BSSID : 00:11:22:33:44:55
    action : discard frame
2. sender : INVALID
    receiver : 00:11:22:33:44:55
    BSSID : 00:11:22:33:44:55
    action : discard
3. Notice that the following condition also pass the if check:
    sender: 11:22:33:44:55:66 (other AP)
    receiver: 38:ec:11:00:00:01 (client)
    BSSID: 11:11:11:11:11:11 (The target attacking AP (i.e. not in frenzy mode))
    But we'll do the following check in the if condition:
    if sender == BSSID:
        craft deauth
    elif receiver == BSSID:
        craft deauth

    so it is safe. 
```

**Comment by blackHatMonkey** [comment]
@anakin1028 Lets forget about the code and list all of our test cases:

NON FRENZY MODE
============

1. **sender**: INVALID
    **receiver**: INVALID
    **BSSID**: ---------------
    **action**: discard frame

2.  **sender** : INVALID
    **receiver** : VALID
    **BSSID**: ---------------
    **action** : discard frame

3.  **sender**: VALID
    **receiver**: INVALID
    **BSSID**: ---------------
    **action**: discard frame

4.  **sender**: VALID
    **receiver**: BSSID
    **BSSID**: ---------------
    **action**: add **sender** as client

5.  **sender**: BSSID
    **receiver**: VALID
    **BSSID**: ---------------
    **action**: add **receiver** as client

6.  **sender**: VALID
     **receiver**: VALID
     **BSSID**: ---------------
     **action**: add **receiver** and **sender** as client

FRENZY MODE
=========

7.  **sender** : INVALID
   **receiver**: INVALID
    **BSSID**: ---------------
    **action**: add **BSSID** as client

8.  **sender** : INVALID
    **receiver** : VALID
    **BSSID** : ---------------
    **action** : add **BSSID** and **receiver** as client

9.  **sender**: VALID
    **receiver**: INVALID
    **BSSID**: ---------------
    **action**: add **BSSID** and **sender** as client

10.  **sender**: VALID
    **receiver**: BSSID
    **BSSID**: ---------------
    **action**: add **BSSID** and **sender** as client

11.  **sender**: BSSID
    **receiver**: VALID
    **BSSID**: ---------------
    **action**: add **BSSID** and **receiver** as client

12.  **sender**: VALID
    **receiver**: VALID
    **BSSID**: ---------------
    **action**: add **BSSID**, **sender** and **receiver** as client

These are all the cases that I could think of. Let me know if any of them is wrong. Also can you think of a case where the BSSID is going to be somehow invalid?

**Comment by anakin1028** [comment]
@blackHatMonkey 
For Non-Frenzy mode:

case 6:
sender: VALID
receiver: VALID
BSSID: ---------------
action: add receiver and sender as client 

Why do we have to add both sender and receiver as client? Either one of them must be the AccessPoint, right?

**Comment by anakin1028** [comment]
For Frenzy mode: 7, 8, 9 case : I think we should discard frame since there is invalid mac address in the frame.

In case 10 and 11, we don't need to add BSSID in the client list since it is the AP's MAC address.
I think we don't need case 12, since one of VALID mac address is eaual to BSSID (AP's MAC) and we don't need to add it.

**Comment by anakin1028** [comment]
For BSSID invalid case: I can only think about the test for non-frenzy mode, since we have a target AP MAC address can be used as reference.

so we can do the following test:

case a:
   to_ds = 0 and from_ds = 0 
   if packet.addr3 != target_ap_mac:
        discard frame
case b.
    to_ds = 1 and from_ds = 0
    if packet.addr1 != target_ap_mac:
        discard frame
case c:
    to_ds = 0 and from_ds = 1
    if packet.addr2 != target_ap_mac:
        discard frame

**Comment by anakin1028** [comment]
@blackHatMonkey I try to make things more clear and make sure we are on the same page:

There are four kinds of addressing format in 802.11 frames defined by the two bits `from_ds` and `to_ds`
You can think ds (i.e. distributed system) as AccessPoint and the ds_value is defined in scapy as:
`packet.FCfield & 0x3` (i.e. The first two bits of control field in the header)

1. **from_ds = 1 to_ds = 1**
     This is called WDS frame, and if we received this kind of frame, just drop it.
2. **from_ds = 1 to_ds = 0**

     from_ds = 1 means this frame comes from AP, so we have the following address mapping:

     * address 1 (Receiver address) : Client's MAC address
     * address 2 (Transmitter address) : AP's MAC address (BSSID)
     * address 3 (Source address) : The mac address of a computer which is connected to the AP by   
                                                     ethernet. 

3. **from_ds = 0 to_ds=1**

     to_ds = 1 means this frame comes from client, so we have the following address mapping:
     
     * address 1 (Receiver address) : AP's MAC address (BSSID)
     * address 2 (Transmitter address) : Client's MAC address
     * address 3 (Destination address) : The mac address of a computer which connected to the AP by ethernet.

4. **from_ds = 0 to_ds=0**
     
     In 802.11 terms, we call these frames are control and management frames. 
     like : `Beacon, Probe Request, Probe Response... etc`

      For example:
      case 1: we know Probe response are sent from AP so the address format will like the following:
 
       *address 1 (Receiver) : Client's MAC address
       *address 2 (Transmitter) : AP's MAC address
       *address 3 (BSSID) : AP's MAC address 

        case 2: we know Associate Request are sent from client to AP so the address format will like the following:

          *address 1 (Receiver) : AP's MAC address
          *address 2 (Transmitter) : Client's MAC
          *address 3 (BSSID) : AP's MAC address

So from the above, we can have some summary:
   **1. address 1 is alway Receiver's MAC address and address 2 is always Transmitter's MAC address**
   
   **2.  BSSID is nothing but the AP's MAC address and we can observe that one of the address 1 and address 2 will be the AP's MAC address**

   **3 One of the common test system we have is like the following:**
```
     STA <-----(wireless)----->AP <--- (ethernet)----->Another computer
 (TA or RA)                     (TA or RA)                            (SA or DA)     
 ```
So back to our test cases:

> NON FRENZY MODE

    sender: INVALID
    receiver: INVALID
    BSSID: ---------------
    action: discard frame
    ---> Anakin : Correct
-------------------------------------------------------------------------------------------------------------------------
    sender : INVALID
    receiver : VALID
    BSSID: ---------------
    action : discard frame
    ---> Anakin : Correct
-------------------------------------------------------------------------------------------------------------------------
    sender: VALID
    receiver: INVALID
    BSSID: ---------------
    action: discard frame
    ---> Anakin : Correct
--------------------------------------------------------------------------------------------------------------------------
    sender: VALID
    receiver: BSSID
    BSSID: ---------------
    action: add sender as client
    ---> Anakin: Correct (I assume the BSSID you mention here is the target AP's MAC address)
----------------------------------------------------------------------------------------------------------------------------
    sender: BSSID
    receiver: VALID
    BSSID: ---------------
    action: add receiver as client
    ---> Anakin: Correct (I assume the BSSID here is the target AP's MAC address)
-----------------------------------------------------------------------------------------------------------------------------
    sender: VALID
    receiver: VALID
    BSSID: ---------------
    action: add receiver and sender as client
    ---> Anakin : No. What if one of MAC address is equal to the MAC address of another AP's MAC address? Remember that one of address 1 and address 2 is equal to the BSSID and BSSID is just AP's MAC address. I think this case can be re-written as follow:

     sender: VALID != target AP's MAC
     receiver: VALID != target AP's MAC
     BSSID: VALID (other AP's MAC)
     action: discard frame.


> FRENZY MODE
   ---> Anakin: @blackHatMonkey you may see my newest PR for how to extracting the BSSID from
                       address 1, address 2 and address 3. I assume here the BSSID is correctly extracted.

    sender : INVALID
    receiver: INVALID
    BSSID: ---------------
    action: add BSSID as client
    ---> Anakin: Discard this frame since both sender and receiver's MAC address are invalid why should we keep this?
-------------------------------------------------------------------------------------------------------------------------
    sender : INVALID
    receiver : VALID
    BSSID : ---------------
    action : add BSSID and receiver as client
    ---> Anakin: Discard this frame, again we should not keep the mac address in the frame if one of the MAC address is invalid.
---------------------------------------------------------------------------------------------------------------------------
    sender: VALID
    receiver: INVALID
    BSSID: ---------------
    action: add BSSID and sender as client
    ---> Anakin: Discard this frame, same as above two cases.
-----------------------------------------------------------------------------------------------------------------------------
    sender: VALID
    receiver: BSSID
    BSSID: ---------------
    action: add BSSID and sender as client
    ---> Anakin: Add sender only. (BSSID is the AP's MAC address, we don't need to include this.)
------------------------------------------------------------------------------------------------------------------------------
    sender: BSSID
    receiver: VALID
    BSSID: ---------------
    action: add BSSID and receiver as client
    ---> Anakin: Add receiver only.
------------------------------------------------------------------------------------------------------------------------------
    sender: VALID
    receiver: VALID
    BSSID: ---------------
    action: add BSSID, sender and receiver as client
    ---> Anakin: We don't need this case since one of the sender and receiver
           must be equal to the BSSID.

**Comment by blackHatMonkey** [comment]
@anakin1028 Thanks for the in depth explanation. I'm made #700 so If you can review when you have some time that would be great 😄 .

**Comment by anakin1028** [comment]
@blackHatMonkey sure I'll review in the next few days : )
