### ISSUE TITLE
Duplicate of #634

### ISSUE THREAD

**Issue by mpkosewski** [wifiphisher/wifiphisher#693]
can't get any normal network activity up and running after installing new version and running once. I restarted new kali build, restarted network manager, i manually brought up internal wifi device and manually set txpower, and also tried using LAN but still, no network connection or activity to be seen. network manager icon in top right is also gone.

**Comment by mpkosewski** [comment]
is there a way to uninstall this? I forgot how last time

**Comment by anakin1028** [comment]
have you tried `nmcli n on` ?

**Comment by mpkosewski** [comment]
that worked actually ty @_@. what is that?

**Comment by anakin1028** [comment]
This is the same problem with #634. We'll fix this soon. 

When wifiphisher is starting, we'll stop the `networking` to let the `NetworkManager` not interfere with wifiphisher.  If you leave the wifiphisher abruptly (i.e. by `ctrl-C`) the current program will not restore the networking properly. I think if you leave the program by `pressing ESC` in the main terminal[The one display `deauth`, `DHCP`, and `HTTP` sections], it should be fined.
