### ISSUE TITLE
Mac OS support

### ISSUE THREAD

**Issue by boff64** [wifiphisher/wifiphisher#695]
Please make installation file for Mac OS or tell me how to run it on Mac OS. Good work.

**Comment by anakin1028** [comment]
Thanks for your post. We currently plan for Kali Linux only.

**Comment by sophron** [comment]
@boff64 While we don't have any plans on porting the tool to MacOS, you are still able to run it under a Kali Linux VM (i.e. using VirtualBox or VMWare).

**Comment by Eiswolf** [comment]
Hi @sophron,

Are you sure that it is possible to run hostapd on a VM with a usb adapter like ALFA AWUS036H ? I had a working configuration on a Linux laptop but with a Kali in VMWare with Mac Os as host OS, it is not working. Do you already tried it ?

**Comment by blackHatMonkey** [comment]
@Eiswolf Although I have not tried MAC OS specifically it should work just fine. Make sure that the USB is properly setup and connected.

**Comment by Eiswolf** [comment]
Ok i'll retry it with another wireless adapter. Thanks dude !
