### ISSUE TITLE
Error in installation: dbus?

### ISSUE THREAD

**Issue by ushasha** [wifiphisher/wifiphisher#696]
Hello, fresh kali VM install, fresh git clone of wifiphisher. upon starting the program, all i have is this 
```
Traceback (most recent call last):
  File "/usr/local/bin/wifiphisher", line 11, in <module>
    load_entry_point('wifiphisher==1.3', 'console_scripts', 'wifiphisher')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 561, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2631, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2291, in load
    return self.resolve()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2297, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.3-py2.7.egg/wifiphisher/pywifiphisher.py", line 23, in <module>
    import wifiphisher.common.interfaces as interfaces
  File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.3-py2.7.egg/wifiphisher/common/interfaces.py", line 9, in <module>
    import dbus
ImportError: No module named dbus
```
checking dbus in kali with apt,, it results already to the latest version (dbus is already the newest version (1.10.20-1)).

what could i do? thanks

**Comment by anakin1028** [comment]
Looks like the dbus service doesn't start on your system. Can you try the following two commands:

`service dbus restart` or `/etc/init.d/dbus restart` ?

**Comment by ushasha** [comment]
Nothing to do... Tried with both commands but I have always the same error message

**Comment by anakin1028** [comment]
Ok.
Can you tried if the following command is work for your system:
This command will dump the Dbus-services on your system.
```shell
dbus-send --system            \
  --dest=org.freedesktop.DBus \
  --type=method_call          \
  --print-reply               \
  /org/freedesktop/DBus       \
  org.freedesktop.DBus.ListNames
```

If the above command is Ok, the dbus service should be fine for your system.

It may neil down to the python module problem. Have you tried the following command:
`pip install dbus-python` to make sure the dbus module is installed.

**Comment by ushasha** [comment]
root@kali:~# dbus-send --system            \
>   --dest=org.freedesktop.DBus \
>   --type=method_call          \
>   --print-reply               \
>   /org/freedesktop/DBus       \
>   org.freedesktop.DBus.ListNames
method return time=1501942680.100017 sender=org.freedesktop.DBus -> destination=:1.64 serial=3 reply_serial=2
   array [
      string "org.freedesktop.DBus"
      string ":1.8"
      string "org.freedesktop.systemd1"
      string "org.freedesktop.ModemManager1"
      string "org.freedesktop.NetworkManager"
      string "org.freedesktop.Accounts"
      string "org.freedesktop.RealtimeKit1"
      string ":1.60"
      string ":1.61"
      string ":1.62"
      string ":1.40"
      string ":1.63"
      string ":1.41"
      string ":1.64"
      string "org.freedesktop.PolicyKit1"
      string ":1.20"
      string ":1.42"
      string ":1.43"
      string ":1.22"
      string ":1.44"
      string ":1.23"
      string "org.freedesktop.PackageKit"
      string ":1.45"
      string ":1.24"
      string ":1.46"
      string ":1.25"
      string "com.redhat.NewPrinterNotification"
      string ":1.49"
      string "com.redhat.PrinterDriversInstaller"
      string "org.gnome.DisplayManager"
      string "org.freedesktop.UDisks2"
      string "org.freedesktop.login1"
      string ":1.50"
      string "org.freedesktop.ColorManager"
      string ":1.51"
      string ":1.52"
      string ":1.30"
      string ":1.53"
      string ":1.54"
      string ":1.10"
      string ":1.32"
      string ":1.33"
      string ":1.56"
      string ":1.12"
      string "org.freedesktop.UPower"
      string ":1.34"
      string ":1.57"
      string ":1.0"
      string ":1.58"
      string ":1.1"
      string ":1.14"
      string ":1.59"
      string ":1.2"
      string ":1.15"
      string ":1.37"
      string ":1.3"
      string ":1.16"
      string ":1.38"
      string ":1.4"
      string ":1.39"
      string ":1.5"
      string ":1.6"
   ]
root@kali:~# pip install dbus-python
Requirement already satisfied: dbus-python in /usr/local/lib/python2.7/dist-packages/dbus_python-1.2.4-py2.7-linux-i686.egg


i really don't understand...it's a brand new kali vm, it should work as is...

**Comment by anakin1028** [comment]
Ok. So your dbus works for your VM system. Can you show the output of `ldconfig -p | grep dbus` ?

**Comment by anakin1028** [comment]
Also output the following two commands:

* `uname -a`
* "ls /usr/local/lib/python2.7/dist-packages"

**Comment by ushasha** [comment]
root@kali:~# ldconfig -p | grep dbus
	libwvdbus.so.4.6 (libc6) => /usr/lib/libwvdbus.so.4.6
	libdbus-1.so.3 (libc6) => /lib/i386-linux-gnu/libdbus-1.so.3
	libdbus-glib-1.so.2 (libc6) => /usr/lib/i386-linux-gnu/libdbus-glib-1.so.2
root@kali:~# 
root@kali:~#     uname -a
Linux kali 4.9.0-kali3-686-pae #1 SMP Debian 4.9.18-1kali1 (2017-04-04) i686 GNU/Linux
root@kali:~#     ls /usr/local/lib/python2.7/dist-packages
blessings-1.6-py2.7.egg                 PyRIC-0.1.6.3-py2.7.egg
certifi                                 roguehostapd-1.1.6-py2.7.egg
certifi-2017.7.27.1.dist-info           tornado
dbus_python-1.2.4-py2.7-linux-i686.egg  tornado-4.5.1.dist-info
easy-install.pth                        wheel
pbkdf2-1.3-py2.7.egg                    wheel-0.29.0.dist-info
pip                                     wifiphisher-1.3-py2.7.egg
pip-9.0.1.dist-info

**Comment by anakin1028** [comment]
Ok from `uname -a` and `.so` we know your machine is 32bits so they match correctly. From the`ls` I guess your dbus module is not correctly installed since I only see the egg folder, and you may not do the easy install in that folder.

can you pip uninstall dbus-python? And make sure the dbus folder is removed and try to pip install dbus-python?

If this still not work, can you output ls again?
Thanks

**Comment by ushasha** [comment]
root@kali:~# pip uninstall dbus-python
Uninstalling dbus-python-1.2.4:
  /usr/local/lib/python2.7/dist-packages/dbus_python-1.2.4-py2.7-linux-i686.egg
Proceed (y/n)? y
  Successfully uninstalled dbus-python-1.2.4
Traceback (most recent call last):
  File "/usr/local/bin/pip", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/pip/__init__.py", line 233, in main
    return command.main(cmd_args)
  File "/usr/local/lib/python2.7/dist-packages/pip/basecommand.py", line 252, in main
    pip_version_check(session)
  File "/usr/local/lib/python2.7/dist-packages/pip/utils/outdated.py", line 102, in pip_version_check
    installed_version = get_installed_version("pip")
  File "/usr/local/lib/python2.7/dist-packages/pip/utils/__init__.py", line 838, in get_installed_version
    working_set = pkg_resources.WorkingSet()
  File "/usr/local/lib/python2.7/dist-packages/pip/_vendor/pkg_resources/__init__.py", line 644, in __init__
    self.add_entry(entry)
  File "/usr/local/lib/python2.7/dist-packages/pip/_vendor/pkg_resources/__init__.py", line 700, in add_entry
    for dist in find_distributions(entry, True):
  File "/usr/local/lib/python2.7/dist-packages/pip/_vendor/pkg_resources/__init__.py", line 1949, in find_eggs_in_zip
    if metadata.has_metadata('PKG-INFO'):
  File "/usr/local/lib/python2.7/dist-packages/pip/_vendor/pkg_resources/__init__.py", line 1463, in has_metadata
    return self.egg_info and self._has(self._fn(self.egg_info, name))
  File "/usr/local/lib/python2.7/dist-packages/pip/_vendor/pkg_resources/__init__.py", line 1823, in _has
    return zip_path in self.zipinfo or zip_path in self._index()
  File "/usr/local/lib/python2.7/dist-packages/pip/_vendor/pkg_resources/__init__.py", line 1703, in zipinfo
    return self._zip_manifests.load(self.loader.archive)
  File "/usr/local/lib/python2.7/dist-packages/pip/_vendor/pkg_resources/__init__.py", line 1643, in load
    mtime = os.stat(path).st_mtime
OSError: [Errno 2] No such file or directory: '/usr/local/lib/python2.7/dist-packages/dbus_python-1.2.4-py2.7-linux-i686.egg'
root@kali:~# pip install dbus-python
Collecting dbus-python
  Downloading dbus-python-1.2.4.tar.gz (612kB)
    100% |████████████████████████████████| 614kB 31kB/s 
Building wheels for collected packages: dbus-python
  Running setup.py bdist_wheel for dbus-python ... error
  Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-sMms7n/dbus-python/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmpy8Kj3ypip-wheel- --python-tag cp27:
  running bdist_wheel
  running build
  creating /tmp/pip-build-sMms7n/dbus-python/build
  creating /tmp/pip-build-sMms7n/dbus-python/build/temp.linux-i686-2.7
  checking whether make supports nested variables... yes
  checking whether to enable maintainer-specific portions of Makefiles... no
  checking for a BSD-compatible install... /usr/bin/install -c
  checking whether build environment is sane... yes
  checking for a thread-safe mkdir -p... /bin/mkdir -p
  checking for gawk... gawk
  checking whether make sets $(MAKE)... yes
  checking whether UID '0' is supported by ustar format... yes
  checking whether GID '0' is supported by ustar format... yes
  checking how to create a ustar tar archive... gnutar
  checking build system type... i686-pc-linux-gnu
  checking host system type... i686-pc-linux-gnu
  checking for native Windows host... no
  checking how to print strings... printf
  checking for style of include used by make... GNU
  checking for gcc... gcc
  checking whether the C compiler works... yes
  checking for C compiler default output file name... a.out
  checking for suffix of executables...
  checking whether we are cross compiling... no
  checking for suffix of object files... o
  checking whether we are using the GNU C compiler... yes
  checking whether gcc accepts -g... yes
  checking for gcc option to accept ISO C89... none needed
  checking whether gcc understands -c and -o together... yes
  checking dependency style of gcc... gcc3
  checking for a sed that does not truncate output... /bin/sed
  checking for grep that handles long lines and -e... /bin/grep
  checking for egrep... /bin/grep -E
  checking for fgrep... /bin/grep -F
  checking for ld used by gcc... /usr/bin/ld
  checking if the linker (/usr/bin/ld) is GNU ld... yes
  checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
  checking the name lister (/usr/bin/nm -B) interface... BSD nm
  checking whether ln -s works... yes
  checking the maximum length of command line arguments... 1572864
  checking how to convert i686-pc-linux-gnu file names to i686-pc-linux-gnu format... func_convert_file_noop
  checking how to convert i686-pc-linux-gnu file names to toolchain format... func_convert_file_noop
  checking for /usr/bin/ld option to reload object files... -r
  checking for objdump... objdump
  checking how to recognize dependent libraries... pass_all
  checking for dlltool... no
  checking how to associate runtime and link libraries... printf %s\n
  checking for ar... ar
  checking for archiver @FILE support... @
  checking for strip... strip
  checking for ranlib... ranlib
  checking command to parse /usr/bin/nm -B output from gcc object... ok
  checking for sysroot... no
  checking for a working dd... /bin/dd
  checking how to truncate binary pipes... /bin/dd bs=4096 count=1
  checking for mt... mt
  checking if mt is a manifest tool... no
  checking how to run the C preprocessor... gcc -E
  checking for ANSI C header files... yes
  checking for sys/types.h... yes
  checking for sys/stat.h... yes
  checking for stdlib.h... yes
  checking for string.h... yes
  checking for memory.h... yes
  checking for strings.h... yes
  checking for inttypes.h... yes
  checking for stdint.h... yes
  checking for unistd.h... yes
  checking for dlfcn.h... yes
  checking for objdir... .libs
  checking if gcc supports -fno-rtti -fno-exceptions... no
  checking for gcc option to produce PIC... -fPIC -DPIC
  checking if gcc PIC flag -fPIC -DPIC works... yes
  checking if gcc static flag -static works... yes
  checking if gcc supports -c -o file.o... yes
  checking if gcc supports -c -o file.o... (cached) yes
  checking whether the gcc linker (/usr/bin/ld) supports shared libraries... yes
  checking whether -lc should be explicitly linked in... no
  checking dynamic linker characteristics... GNU/Linux ld.so
  checking how to hardcode library paths into programs... immediate
  checking whether stripping libraries is possible... yes
  checking if libtool supports shared libraries... yes
  checking whether to build shared libraries... yes
  checking whether to build static libraries... no
  checking for inline... inline
  checking whether /usr/bin/python version is >= 2.6... yes
  checking for /usr/bin/python version... 2.7
  checking for /usr/bin/python platform... linux2
  checking for /usr/bin/python script directory... ${prefix}/lib/python2.7/site-packages
  checking for /usr/bin/python extension module directory... ${exec_prefix}/lib/python2.7/site-packages
  configure: Using $PYTHON-config: /usr/bin/python-config
  checking for Python headers using /usr/bin/python-config --includes... -I/usr/include/python2.7 -I/usr/include/i386-linux-gnu/python2.7
  checking whether those headers are sufficient... yes
  checking for Python library linker flags using /usr/bin/python-config... -L/usr/lib/python2.7/config-i386-linux-gnu -L/usr/lib -lpython2.7 -lpthread -ldl  -lutil -lm  -Xlinker -export-dynamic -Wl,-O1 -Wl,-Bsymbolic-functions
  checking for git... /usr/bin/git
  checking whether you want to build HTML docs... if possible
  checking whether you want to build API docs... if possible
  checking python module: docutils... yes
  checking for epydoc... no
  checking python module: epydoc... no
  checking epydoc 3... checking for dbus-run-session... /usr/bin/dbus-run-session
  checking for rst2html... rst2html
  checking for pkg-config... no
  checking for DBUS... no
  configure: error: in `/tmp/pip-build-sMms7n/dbus-python/build/temp.linux-i686-2.7':
  configure: error: The pkg-config script could not be found or is too old.  Make sure it
  is in your PATH or set the PKG_CONFIG environment variable to the full
  path to pkg-config.
  
  Alternatively, you may set the environment variables DBUS_CFLAGS
  and DBUS_LIBS to avoid the need to call pkg-config.
  See the pkg-config man page for more details.
  
  To get pkg-config, see <http://pkg-config.freedesktop.org/>.
  See `config.log' for more details
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-build-sMms7n/dbus-python/setup.py", line 106, in <module>
      'build_ext': BuildExt,
    File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
      dist.run_commands()
    File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
      self.run_command(cmd)
    File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
      cmd_obj.run()
    File "/usr/local/lib/python2.7/dist-packages/wheel/bdist_wheel.py", line 179, in run
      self.run_command('build')
    File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
      self.distribution.run_command(command)
    File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
      cmd_obj.run()
    File "/tmp/pip-build-sMms7n/dbus-python/setup.py", line 62, in run
      cwd=builddir)
    File "/usr/lib/python2.7/subprocess.py", line 186, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command '['/tmp/pip-build-sMms7n/dbus-python/configure', '--disable-maintainer-mode', 'PYTHON=/usr/bin/python', '--prefix=/tmp/pip-build-sMms7n/dbus-python/build/temp.linux-i686-2.7/prefix']' returned non-zero exit status 1
  
  ----------------------------------------
  Failed building wheel for dbus-python
  Running setup.py clean for dbus-python
Failed to build dbus-python
Installing collected packages: dbus-python
  Running setup.py install for dbus-python ... error
    Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-sMms7n/dbus-python/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-spPNI5-record/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    creating /tmp/pip-build-sMms7n/dbus-python/build
    creating /tmp/pip-build-sMms7n/dbus-python/build/temp.linux-i686-2.7
    checking whether make supports nested variables... yes
    checking whether to enable maintainer-specific portions of Makefiles... no
    checking for a BSD-compatible install... /usr/bin/install -c
    checking whether build environment is sane... yes
    checking for a thread-safe mkdir -p... /bin/mkdir -p
    checking for gawk... gawk
    checking whether make sets $(MAKE)... yes
    checking whether UID '0' is supported by ustar format... yes
    checking whether GID '0' is supported by ustar format... yes
    checking how to create a ustar tar archive... gnutar
    checking build system type... i686-pc-linux-gnu
    checking host system type... i686-pc-linux-gnu
    checking for native Windows host... no
    checking how to print strings... printf
    checking for style of include used by make... GNU
    checking for gcc... gcc
    checking whether the C compiler works... yes
    checking for C compiler default output file name... a.out
    checking for suffix of executables...
    checking whether we are cross compiling... no
    checking for suffix of object files... o
    checking whether we are using the GNU C compiler... yes
    checking whether gcc accepts -g... yes
    checking for gcc option to accept ISO C89... none needed
    checking whether gcc understands -c and -o together... yes
    checking dependency style of gcc... gcc3
    checking for a sed that does not truncate output... /bin/sed
    checking for grep that handles long lines and -e... /bin/grep
    checking for egrep... /bin/grep -E
    checking for fgrep... /bin/grep -F
    checking for ld used by gcc... /usr/bin/ld
    checking if the linker (/usr/bin/ld) is GNU ld... yes
    checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
    checking the name lister (/usr/bin/nm -B) interface... BSD nm
    checking whether ln -s works... yes
    checking the maximum length of command line arguments... 1572864
    checking how to convert i686-pc-linux-gnu file names to i686-pc-linux-gnu format... func_convert_file_noop
    checking how to convert i686-pc-linux-gnu file names to toolchain format... func_convert_file_noop
    checking for /usr/bin/ld option to reload object files... -r
    checking for objdump... objdump
    checking how to recognize dependent libraries... pass_all
    checking for dlltool... no
    checking how to associate runtime and link libraries... printf %s\n
    checking for ar... ar
    checking for archiver @FILE support... @
    checking for strip... strip
    checking for ranlib... ranlib
    checking command to parse /usr/bin/nm -B output from gcc object... ok
    checking for sysroot... no
    checking for a working dd... /bin/dd
    checking how to truncate binary pipes... /bin/dd bs=4096 count=1
    checking for mt... mt
    checking if mt is a manifest tool... no
    checking how to run the C preprocessor... gcc -E
    checking for ANSI C header files... yes
    checking for sys/types.h... yes
    checking for sys/stat.h... yes
    checking for stdlib.h... yes
    checking for string.h... yes
    checking for memory.h... yes
    checking for strings.h... yes
    checking for inttypes.h... yes
    checking for stdint.h... yes
    checking for unistd.h... yes
    checking for dlfcn.h... yes
    checking for objdir... .libs
    checking if gcc supports -fno-rtti -fno-exceptions... no
    checking for gcc option to produce PIC... -fPIC -DPIC
    checking if gcc PIC flag -fPIC -DPIC works... yes
    checking if gcc static flag -static works... yes
    checking if gcc supports -c -o file.o... yes
    checking if gcc supports -c -o file.o... (cached) yes
    checking whether the gcc linker (/usr/bin/ld) supports shared libraries... yes
    checking whether -lc should be explicitly linked in... no
    checking dynamic linker characteristics... GNU/Linux ld.so
    checking how to hardcode library paths into programs... immediate
    checking whether stripping libraries is possible... yes
    checking if libtool supports shared libraries... yes
    checking whether to build shared libraries... yes
    checking whether to build static libraries... no
    checking for inline... inline
    checking whether /usr/bin/python version is >= 2.6... yes
    checking for /usr/bin/python version... 2.7
    checking for /usr/bin/python platform... linux2
    checking for /usr/bin/python script directory... ${prefix}/lib/python2.7/site-packages
    checking for /usr/bin/python extension module directory... ${exec_prefix}/lib/python2.7/site-packages
    configure: Using $PYTHON-config: /usr/bin/python-config
    checking for Python headers using /usr/bin/python-config --includes... -I/usr/include/python2.7 -I/usr/include/i386-linux-gnu/python2.7
    checking whether those headers are sufficient... yes
    checking for Python library linker flags using /usr/bin/python-config... -L/usr/lib/python2.7/config-i386-linux-gnu -L/usr/lib -lpython2.7 -lpthread -ldl  -lutil -lm  -Xlinker -export-dynamic -Wl,-O1 -Wl,-Bsymbolic-functions
    checking for git... /usr/bin/git
    checking whether you want to build HTML docs... if possible
    checking whether you want to build API docs... if possible
    checking python module: docutils... yes
    checking for epydoc... no
    checking python module: epydoc... no
    checking epydoc 3... checking for dbus-run-session... /usr/bin/dbus-run-session
    checking for rst2html... rst2html
    checking for pkg-config... no
    checking for DBUS... no
    configure: error: in `/tmp/pip-build-sMms7n/dbus-python/build/temp.linux-i686-2.7':
    configure: error: The pkg-config script could not be found or is too old.  Make sure it
    is in your PATH or set the PKG_CONFIG environment variable to the full
    path to pkg-config.
    
    Alternatively, you may set the environment variables DBUS_CFLAGS
    and DBUS_LIBS to avoid the need to call pkg-config.
    See the pkg-config man page for more details.
    
    To get pkg-config, see <http://pkg-config.freedesktop.org/>.
    See `config.log' for more details
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-sMms7n/dbus-python/setup.py", line 106, in <module>
        'build_ext': BuildExt,
      File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
        dist.run_commands()
      File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/usr/lib/python2.7/dist-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/usr/lib/python2.7/distutils/command/install.py", line 601, in run
        self.run_command('build')
      File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/tmp/pip-build-sMms7n/dbus-python/setup.py", line 62, in run
        cwd=builddir)
      File "/usr/lib/python2.7/subprocess.py", line 186, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['/tmp/pip-build-sMms7n/dbus-python/configure', '--disable-maintainer-mode', 'PYTHON=/usr/bin/python', '--prefix=/tmp/pip-build-sMms7n/dbus-python/build/temp.linux-i686-2.7/prefix']' returned non-zero exit status 1
    
    ----------------------------------------
Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-sMms7n/dbus-python/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-spPNI5-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-sMms7n/dbus-python/
root@kali:~# ls /usr/local/lib/python2.7/dist-packages
blessings-1.6-py2.7.egg        PyRIC-0.1.6.3-py2.7.egg
certifi                        roguehostapd-1.1.6-py2.7.egg
certifi-2017.7.27.1.dist-info  tornado
easy-install.pth               tornado-4.5.1.dist-info
pbkdf2-1.3-py2.7.egg           wheel
pip                            wheel-0.29.0.dist-info
pip-9.0.1.dist-info            wifiphisher-1.3-py2.7.egg

**Comment by anakin1028** [comment]
You didn't install dbus successfully. 
try to install `pkg-config` first:

`apt-get install -y pkg-config`

https://stackoverflow.com/questions/23202146/cannot-find-pkg-config-error

**Comment by ushasha** [comment]
root@kali:~# apt-get install -y pkg-config
Reading package lists... Done
Building dependency tree       
Reading state information... Done
pkg-config is already the newest version (0.29-4+b1).
0 upgraded, 0 newly installed, 0 to remove and 1029 not upgraded.


looks like that's not the problem....wow...i'm thinking to erase everything and restart, but if the problem is in the original kali image, nothing would change :(

**Comment by ushasha** [comment]
... ...

checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for DBUS... no
configure: error: Package requirements (dbus-1 >= 1.6) were not met:

No package 'dbus-1' found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables DBUS_CFLAGS
and DBUS_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.


trying to install the tar.gz downloaded separately i end always with this error

**Comment by blackHatMonkey** [comment]
@ushasha I believe we came up withe same problem when trying to configure `travis` @anakin1028. I think it's a dependancy error. @ushasha Can you install `libdbus-1-dev` and try again 😄 .

**Comment by ushasha** [comment]
same error, dbus not found

**Comment by anakin1028** [comment]
hmm..
@ushasha, before you run `wifiphisher`
have you done `python setup.py install` ?

**Comment by ushasha** [comment]
omg....
i was sure i installed it...
it's working now, feel so ashamed...thank you everybody and sorry for have wasted your time with my problem

**Comment by anakin1028** [comment]
That's ok! So so you solve the problem by running python setup.py install?
Enjoy wifiphisher: p
