### ISSUE TITLE
what about making the wifiphisher rogue ap act like a really wpa\wpa2 protected wifi ?

### ISSUE THREAD

**Issue by minanagehsalalma** [wifiphisher/wifiphisher#709]
i was thinking if it will be good if wifiphisher rogue ap act like a really **wpa\wpa2** protected wifi
just to avoid ssl problems and  open network security Warning and all scenario pages problems and html and the Multiple browsers  number  and the really that the most Modern devices doesn't auto connect to the open wifi(s)....
and the idea is  to take a wpa handshake from the victim ap for validating the Received password from the rogue ap and make the rogue ap use a hard wpa auto generated password  & log the entered passwords into a text file for validating  wpa handshake from the victim ap 

and   i wish this idea to be sorted with the scenarios and  be named as wpa\wpa2 rogue ap

.**regards**

**Comment by anakin1028** [comment]
@minanagehsalalma we have already supported this function. You can provide the handshake pcap file by the `-hC` option, and we will validate the passphrase entered by the victims with the provided handshake file.

Later on, you can lunch the rogue ap with security by providing `-pK passphrase`.

**Comment by sophron** [comment]
As @anakin1028 stated, this is already implemented. See the `pK` option.

**Comment by minanagehsalalma** [comment]
@sophron  @anakin1028 no this not what i had meant .. what i mean is 1- we auto generate a random password 2- the user type the password into the  wpa protected wifi not into the phishing page 3- we receive the entered  password and log it into a text file 4- we test the received password with aircrack-ng on an wpa cracker on the provided handshake 5- if the password is correct  close every thing and pop up with a window that shows the valid password   6- if the password is wrong do nothing

![image](https://user-images.githubusercontent.com/20546638/30241458-eb9a9cee-9583-11e7-9ebf-1f48e342f52a.png)

**Comment by anakin1028** [comment]
I don't understand step1 and step2.  

* For step1: 
What's the reason you want to create a random generated password?

* For step2:
If we want to let victims enter password then the victims must first associated to our fakeAP and enter it on the phishing page, right? We currently implement this and we'll check if the users enter the correct password by pure python program.

**Comment by minanagehsalalma** [comment]
no i mean catch the password entered on a really wpa wifi not a phishing  page

**Comment by anakin1028** [comment]
Do you mean we just lunch an rogueAP and sniff the four-way handshake then use tools like aircrack for cracking the password?
 
If this is the idea why don't you just offline use aircrack for doing this?

**Comment by minanagehsalalma** [comment]
no  this not the idea what i mean is  make our rogueAP  wpa protected wifi  with any password . when the clients enter the password into  our rogueAP  wpa protected wifi we save it into a log file then validate it with a handshake

**Comment by anakin1028** [comment]
I still don't get it ... How do we get the password from the clients without using the phishing page?

**Comment by sophron** [comment]
I think @minanagehsalalma is proposing to get the password directly from the station. However, when the victim types the password, it is never transmitted in the air. The data is encrypted with the password and only the password on the other side (AP) can be used to decrypt it.

**Comment by minanagehsalalma** [comment]
@sophron  why isn't the ap is our and we can modify the hostpad. To do what ever we want

**Comment by sophron** [comment]
We can do what we want from our side, yes. But the client (victim) never sends the password. Read about how WPA works: https://en.wikipedia.org/wiki/Wi-Fi_Protected_Access

**Comment by sophron** [comment]
This is a downgrade attack that might make sense and we should consider researching more.

**Comment by minanagehsalalma** [comment]
@sophron  so do you say yes for my idea ??

**Comment by anakin1028** [comment]
Changing to WEP will not work neither. WEP crack relies on collecting large amount of frames by using the same shared key so that the brute force attack will success. Lunching fake AP has no role in this kind of attack.

**Comment by anakin1028** [comment]
This link serves as a reference
http://www.oyyas.com/hacking-h23.php

**Comment by minanagehsalalma** [comment]
@anakin1028  so it's useless. i am  so sorry to waste your time 😢😢😢😢

**Comment by anakin1028** [comment]
No problem! Discussion makes us better : )

**Comment by minanagehsalalma** [comment]
@anakin1028 Certainly

**Comment by syzygy98** [comment]
Isn't it possible to gain access to a wpa2 protected router by creating a modified fake AP with wpa2 protection, then deauthenticate client from real AP, block real AP, then wait for client to connect to our fake wpa2 AP, receive connection data, stop blocking real AP, then send this data to initiate a connection on another interface to the real ap, we get the answer, then send it to the client, we receive answer from client, send it to real AP... This way we comlete a real 4-way handshake with real AP, so at the end we have a working connection to the real AP, hopefully a router with default admin password, so we can check/modify wifi settings... Sorry for poor English.

**Comment by minanagehsalalma** [comment]
The handshake will only have the encrypted password not the really one so
how you supposed to make vitcim connect to the fake ap without he know it's
password  ?!?!

**Comment by anakin1028** [comment]
@syzygy98 your idea will fail for the following reason:

If our fakeAP has same SSID and also has WPA2 encryption with the attacking AP, our fakeAP may send `4-1` with `ANONCE` to the victim station and the station will feedback 4-2 to us (I guess this is the connection data you have mentioned?).

However, our fakeAP will fail to send `4-3` since 4-3 require us to know the preshared key of WPA2. we need the preshared key to compute the MIC to the victim station.

**Comment by minanagehsalalma** [comment]
As ankin says how will you know the old password in first place and if you
know it the attack will be useless...

**Comment by minanagehsalalma** [comment]
@anakin1028 `Changing to WEP will not work neither. WEP crack relies on collecting large amount of frames by using the same shared key so that the brute force attack will success. Lunching fake AP has no role in this kind of attack.`

but what about this. will it work ?? with this [Cracking WEP with No clients Connected Backtrack 5
](https://www.youtube.com/watch?v=csGM2gI4V64)

**Comment by himanshu608** [comment]
> i was thinking if it will be good if wifiphisher rogue ap act like a really **wpa\wpa2** protected wifi
> just to avoid ssl problems and open network security Warning and all scenario pages problems and html and the Multiple browsers number and the really that the most Modern devices doesn't auto connect to the open wifi(s)....
> and the idea is to take a wpa handshake from the victim ap for validating the Received password from the rogue ap and make the rogue ap use a hard wpa auto generated password & log the entered passwords into a text file for validating wpa handshake from the victim ap
> 
> and i wish this idea to be sorted with the scenarios and be named as wpa\wpa2 rogue ap
> 
> .**regards**

Hey did u find any way to create password protected fake ap??
