### ISSUE TITLE
Cannot Load my  custom phishing page

### ISSUE THREAD

**Issue by phspade** [wifiphisher/wifiphisher#715]
Hello Team, 

Just having an error while loading my template. :(
![screenshot at 2017-08-23 21-18-09](https://user-images.githubusercontent.com/18681023/29617943-25887ea0-8849-11e7-817d-c4fed73779cd.png)

You can check my codes [here](https://github.com/phspade/wifiphisher-phishing-page)

**Comment by phspade** [comment]
Let me know if my code has an error with wifiphisher  :)

**Comment by sophron** [comment]
Apparently, Wifiphisher fails to find your scenario. 

Does it work when you run the binary directly (`python bin/wifiphisher`)? My guess is that you have put your scenario under the downloaded Wifiphisher directory but not in the system installed directory.

After putting your scenario under the `phishing-pages` directory, re-install the tool (i.e. `python setup.py install --force`)  and try again.

**Comment by phspade** [comment]
oh thanks for the fast response.. How should i do it?

**Comment by phspade** [comment]
Where should i put my phishing page then?

**Comment by phspade** [comment]
Oh.. i get it.. wait..

**Comment by phspade** [comment]
ha.. it works:D Thanks @sophron

**Comment by sophron** [comment]
You are welcome.

**Comment by phspade** [comment]
BTW, im having trouble using my wlan0 as Jamming Interface and it comes up with an error.. what should i do here ?
![screenshot at 2017-08-23 22-22-53](https://user-images.githubusercontent.com/18681023/29620981-0ba60468-8852-11e7-888b-6afeb1e7334e.png)

**Comment by anakin1028** [comment]
@phspade
I just pushed a commit to fix that problem. Can you pull the latest commit and try again?

**Comment by phspade** [comment]
Hello @anakin,

Yeah sure.. Ill ping you.. when it comes up with error again.. Thanks BTW

**Comment by anakin1028** [comment]
sure! you can use the following command to fetch the commits : )
```
git fetch
git merge origin master
```

**Comment by phspade** [comment]
oh i just did.. and it works well.. No errors. 🗡 
Thanks for the fix..

**Comment by anakin1028** [comment]
glad to hear about that : )
