### ISSUE TITLE
Error when using extra-phishing-pages on the current version

### ISSUE THREAD

**Issue by Ad3t0** [wifiphisher/wifiphisher#717]
**Version**: Use `git show | grep commit` command and paste here the output.

commit 43932eef872387001526f7ac4d30283cfe4db9ae

**Description**: Give a more analytical description here. The output of the `iw list` and `iwconfig` commands may be helpful.

When using
https://github.com/wifiphisher/extra-phishing-pages

I have a lot to learn so please excuse my lack of knowledge on the matter.  I spent hours and hours trying to figure out why it's having the error. I kept circling back to the config.ini it seemed to me like its not finding data for the name value within it. However regardless of what I change in it I get the same results. While troubleshooting I used only the google template to see if I could make one work eventually switching to a different thinking it may be the google one without any luck. I attempted to change countless things within the template directory trying to get at least a different error or something without luck. I eventually reverted back to where it was working without any additional templates and then added them back and tested it yet again with some things that I modified in an attempt to fix it and I still recieve the error.

**Script output**: Paste the output of the tool, including any stack traces.
```
  File "/usr/local/bin/wifiphisher", line 11, in <module>
    load_entry_point('wifiphisher==1.3', 'console_scripts', 'wifiphisher')()
  File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.3-py2.7.egg/wifiphisher/pywifiphisher.py", line 855, in run
    engine = WifiphisherEngine()
  File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.3-py2.7.egg/wifiphisher/pywifiphisher.py", line 488, in __init__
    self.template_manager = phishingpage.TemplateManager()
  File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.3-py2.7.egg/wifiphisher/common/phishingpage.py", line 303, in __init__
    self._templates[page] = PhishingTemplate(page)
  File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.3-py2.7.egg/wifiphisher/common/phishingpage.py", line 61, in __init__
    self._display_name = info['name']
KeyError: 'name'
```

**Comment by phspade** [comment]
I fix this issue by this method.
* First download the **Latest** Wifiphisher
* Once you download the zip or clone the wifiphisher. place your phishing page to:
`wifiphisher/wifiphisher/data/phishing-page`
* Once you paste your phishing page there. Install the wifiphisher.
* `sudo python setup.py install`

Let me know if you still having a trouble

**Comment by Ad3t0** [comment]
Thanks for the reply, I had tried that previously and I just did it again to make double sure I had tried it that way and I had no success. Same error.

**Comment by sophron** [comment]
From your error message it's clear that in the `config.ini` of the phishing scenario you are using, `name` is not defined.

When you are using custom phishing scenarios, you need to make sure that you are editing the right files. If you are changing the files in the directory you downloaded online (and not in the installed directory), you should call the binary directly, e.g. `python bin/wifiphisher`. Otherwise, you should do what @phspade describes.

**Comment by Ad3t0** [comment]
I never changed or modified config.ini and the format mirrors the preloaded templates config.ini.

**Comment by blackHatMonkey** [comment]
@Ad3t0 Can you post which of the templates caused the errors?

**Comment by iobj** [comment]
Hello I have the same issue, I placed the "extra phishing" pages in the phishing folder and reinstalled it and I am getting the error not locally found :/

**Comment by sophron** [comment]
@lobj You already got a response: https://github.com/wifiphisher/wifiphisher/issues/584#issuecomment-335692078

**Comment by sophron** [comment]
I'm closing this. Feel free to re-open if it's indeed a bug from our side and not a mis-configured phishing page.

**Comment by tarsicle** [comment]
Im also having a similar issue. New computer, fresh install of Kali. Clone latest version, 1.4 GIT. Copied device-modal folder into the phishing-pages folder. Execute sudo python setup.py install. Installs with no error. Running the wifiphisher command in new terminal gets:


`[*] Starting Wifiphisher 1.4GIT ( https://wifiphisher.org ) at 2018-01-24 13:23
Traceback (most recent call last):
  File "/usr/local/bin/wifiphisher", line 11, in <module>
    load_entry_point('wifiphisher==1.4', 'console_scripts', 'wifiphisher')()
  File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.4-py2.7.egg/wifiphisher/pywifiphisher.py", line 616, in run
    engine = WifiphisherEngine()
  File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.4-py2.7.egg/wifiphisher/pywifiphisher.py", line 235, in __init__
    self.template_manager = phishingpage.TemplateManager()
  File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.4-py2.7.egg/wifiphisher/common/phishingpage.py", line 308, in __init__
    self.add_user_templates()
  File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.4-py2.7.egg/wifiphisher/common/phishingpage.py", line 389, in add_user_templates
    user_templates = self.find_user_templates()
  File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.4-py2.7.egg/wifiphisher/common/phishingpage.py", line 366, in find_user_templates
    is_valid, output = self.is_valid_template(name)
  File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.4-py2.7.egg/wifiphisher/common/phishingpage.py", line 333, in is_valid_template
    tdir = os.listdir(os.path.join(dir_path, constants.SCENARIO_HTML_DIR))
OSError: [Errno 2] No such file or directory: '/usr/local/lib/python2.7/dist-packages/wifiphisher-1.4-py2.7.egg/wifiphisher/data/phishing-pages/device-modal/html/'
`

It seems to be looking for "html" folder which isnt there in the extra phishing pages. Removing the extra phishing scenarios and reinstalling wifiphisher everything works fine.

**Comment by sophron** [comment]
@tarsicle This should work now, after we merged https://github.com/wifiphisher/extra-phishing-pages/pull/17.
