### ISSUE TITLE
Wifiphisher closing immediately after capturing credentials

### ISSUE THREAD

**Issue by rlstric1** [wifiphisher/wifiphisher#720]
**Version**: 1.3

**Description**: Command ran: wifiphisher -aI wlan2 -jI wlan1
It seems as though wifiphisher is starting to work initially but after it states it's starting the fake access point it displays:
Show your support!
Follow us: 'twitter url'
Like us: 'facebook url'
Captured credentials
Closing

then the program quits.  I've tried to look all over and no one really seems to answer this.

Running on pi3 Kali Linux

UPDATE: I've noticed that even if I try to make an AP without jamming (wifiphisher --nojamming --essid "FREE WIFI" -p oauth-login) it always closes with the captured credentials immediately after trying to make a fake AP. Do I have a dependency missing, if so how do I check?

**Comment by anakin1028** [comment]
@rlstric1
1. Do you clone from github and do `python setup.py install` or did `pip install wifiphisher`?
2.  Can you post the output of `ldconfig -p |grep libnl`?
3. If you are comfortable with hostapd, you can try to lunch fakeAP manually. See if there is any dependence issue with hostapd.

**Comment by rlstric1** [comment]
1. python setup.py install
2. No output to terminal
3. I've never used hostapd before but what I did find out if that the setup.py did not install so I had to `apt-get intall hostapd` myself, which makes me wonder what else did not install.

**Comment by anakin1028** [comment]
@rlstric1
Ok that means you don't have the libnl dependency.
Try to follow the section 5 of the following link:
http://www.pietervanos.net/knowledge/debian-install-hostapd-2/

**Comment by anakin1028** [comment]
@rlstric1 I'm also curious about what OS do you use?
And during `python setup.py install` do we show any warning message about `hostapd` is not install?

**Comment by rlstric1** [comment]
@anakin1028 I get an error on the libng-dev apt-get saying: E: Package 'libnl-dev' has no installation candidate

I'm using the latest Kali linux ARM img.  I don't recall seeing anything during the setup.py.

Should I delete the directory and retry?

**Comment by anakin1028** [comment]
we can try to focus to solve the libnl dependency issue first.
what if  `apt-get install libnl-3-dev` and `apt-get install libnl-genl-3-dev` ?

**Comment by rlstric1** [comment]
I'm getting failure to resolve errors on those.

**Comment by anakin1028** [comment]
same error as `libnl-dev` ?

**Comment by rlstric1** [comment]
no `libnl-dev` error is, E: Package 'libnl-dev has no installation candidate/

`apt-get install libnl-3-dev` error is, failure to fetch

**Comment by rlstric1** [comment]
If I even do `apt-get update` it's just a temporary failure to resolve 'http.kali.org

**Comment by rlstric1** [comment]
okay so I was able to install libnl-3-dev and libnl-genl-3-dev.  Something was wrong with my network card so I rebooted and I installed them but libnl-dev still gives me the candidate error

**Comment by anakin1028** [comment]
ok forget about `libnl-dev`. can you try to lunch wifiphisher again? see if it works for you?

**Comment by rlstric1** [comment]
if I do `wifiphisher -aI wlan0 -jI wlan2` I get the same as the beginning where it closes immediately after the captured credentials message

if I do `wifiphisher --nojamming --essid "WIFI" -p oauth-login` I get an error chain where the final is: File 'usr/local/lib/python2.7/dist-packages/PyRIC-0.1.6.3-py2.7.egg/pyric/pyw.py', line 1340, in modeset raise pyric.error(e.errno, e.strerror)

I can try to snag a snapshot on my pi and upload it.

**Comment by anakin1028** [comment]
can you try the following:
Use your favorite editor and save the following lines in a file(named as say hostapd.conf).
Change the `interface=wlan0` to the wlan# you have on your system (you can observe by `iw dev`)
then try the command : `hostapd ./hostapd.conf` and see if the AccessPoint is successfully lunched?
```
interface=wlan0
ssid=xxxx
hw_mode=g
ieee80211n=1
channel=6
beacon_int=100
preamble=1
max_num_sta=255
rts_threshold=2347
fragm_threshold=2346
logger_syslog=-1
logger_syslog_level=2
logger_stdout=1
logger_stdout_level=2
ctrl_interface=/var/run/hostapd
ctrl_interface_group=0
macaddr_acl=0
auth_algs=3
ignore_broadcast_ssid=0
wmm_enabled=1
wmm_ac_bk_cwmin=4
wmm_ac_bk_cwmax=10
wmm_ac_bk_aifs=7
wmm_ac_bk_txop_limit=0
wmm_ac_bk_acm=0
wmm_ac_be_cwmin=4
wmm_ac_be_cwmax=10
wmm_ac_be_aifs=7
wmm_ac_be_txop_limit=0
wmm_ac_be_acm=0
wmm_ac_vi_cwmin=3
wmm_ac_vi_cwmax=4
wmm_ac_vi_aifs=2
wmm_ac_vi_txop_limit=94
wmm_ac_vi_acm=0
wmm_ac_vo_cwmin=3
wmm_ac_vo_cwmax=4
wmm_ac_vo_aifs=2
wmm_ac_vo_txop_limit=47
wmm_ac_vo_acm=0
```

**Comment by rlstric1** [comment]
output is:
Failed to create interface mon.wlan0: -95 (Operation not supported)
wlan0: Could not connect to kernel driver
Using interface wlan0 hwaddr xx:xx:xx:xx:xx:xx and ssid "xxxx"
wlan0:interface state UNINITIALIZED -> ENABLED
wlan0: AP-ENABLED
wlan0:INTERFACE-DISABLED
wlan0:INTERFACE-ENABLED

it looks like it's still working it's been that way for a couple minutes

**Comment by rlstric1** [comment]
I tried to run the --nojamming script again while letting the hostapf.conf run and got: Failed to set beacon parameters

**Comment by anakin1028** [comment]
Are you sure `wlan0` support `AP` mode?
can you follow the instructions in #719 to check the supported modes for your adapters?

**Comment by anakin1028** [comment]
And `wifiphisher` will lunch the hostapd automatically so you don't need to manually lunch it.
We just need to make sure your hostapd can successfully lunch and there is no dependency issue.

**Comment by rlstric1** [comment]
I'm trying different network cards, wlan0 was my onboard adapter but I tried with 2 others and got the same results, should the hostapd.conf finish? I let it run for over 5 minutes and it has not finished completely

**Comment by rlstric1** [comment]
I unplugged both network adapters and tried one at a time and the first one gave me this output from ./hostapd.conf:
nl80211: Could not configure driver mode
nl80211: deinit ifname=wlan1 disabled_llb_rates=0
nl80211 driver initialization failed.
wlan1: interface state UNINITIALIZED ->DISABLED
wlan1: DISABLED
hostapd_free_hapd_data: Interface wlan1 wasn't started

**Comment by anakin1028** [comment]
```
Failed to create interface mon.wlan0: -95 (Operation not supported)
wlan0: Could not connect to kernel driver
```
From the above output I guess the dependency is not really solved.
Maybe you can remove hostapd and install again. hostapd will not finish unless you `ctrl-c` with that command.

**Comment by rlstric1** [comment]
how do you remove hostapd

**Comment by anakin1028** [comment]
The overall concept is `hostapd` -> `nl80211 (libnl)` -> `device driver`
you can uninstall by `apt-get purge hostapd`

**Comment by rlstric1** [comment]
Okay I finished reinstalling I ran `wifiphisher -aI wlan1 -jI wlan2` and got the same results as I started.

`wifiphisher --nojamming --essid "xxx" -p oauth-login -aI wlan1` also gave me that same deal, it closing immediately after trying to create a fake AP

**Comment by usama7628674** [comment]
try the following commands in terminal

apt-get install dnsmasq
apt-get install dnsmasq-base

**Comment by rlstric1** [comment]
They were both already installed

**Comment by usama7628674** [comment]
Try to install following libraries
libnl-3-200:amd64
libnl-3-dev:amd64
libnl-genl-3-200:amd64
libnl-genl-3-dev:amd64
libnl-route-3-200:amd64

**Comment by rlstric1** [comment]
Unable to locate all of those packages

**Comment by usama7628674** [comment]
Try to install them manually using the following website
https://packages.debian.org

**Comment by rlstric1** [comment]
arm64 or amd64?

**Comment by usama7628674** [comment]
use this command in terminal
uname -r
you will see your architecture at the end of line

**Comment by rlstric1** [comment]
4.4.50-v7 is the only output

**Comment by usama7628674** [comment]
are you using kali linux

**Comment by rlstric1** [comment]
if I apt-get install, all those packages you listed earlier without the amd64 tag I get messages stating that they're already installed. Yes I'm running Kali on a pi3

**Comment by usama7628674** [comment]
use this command 
dpkg -l
and search them individually

**Comment by rlstric1** [comment]
what should I be looking for for each?

**Comment by usama7628674** [comment]
If you found all those packages then it means they are installed

**Comment by rlstric1** [comment]
They're all installed but with the tag, :armhf

**Comment by usama7628674** [comment]
got to /etc/ and open interfaces  file with any text editor and change should be like this
auto wlan1
iface wlan1 inet manual


replace wlan1 with your interface
and use wifiphisher with this command
go to /wifiphisher/bin and open terminal

python wifiphisher --nojamming

**Comment by rlstric1** [comment]
there is no interfaces file

**Comment by usama7628674** [comment]
Ok my mistake the file should be in this location
/etc/network

**Comment by rlstric1** [comment]
interfaces or interfaces.d

**Comment by usama7628674** [comment]
open interfaces with text editor and paste here the the file input

**Comment by rlstric1** [comment]
auto lo
iface lo inet loopback

auto eth0
iface eth0 ined dhcp

(I added)
auto wlan1
iface wlan1 inet manual

**Comment by usama7628674** [comment]
auto lo                                 to auto wlan1
iface lo inet loopback           to      iface wlan1 inet manual

**Comment by rlstric1** [comment]
Okay I changed lo -> wlan1

`python wifiphisher --nojamming` automatically trys to use wlan0 I have to explicitly tell it to use wlan1 with `-aI wlan1`

**Comment by usama7628674** [comment]
so change wlan1 to wlan0 in interfaces file

**Comment by usama7628674** [comment]
use only your internal adapter and unplug all usb adapters

**Comment by rlstric1** [comment]
Okay, I changed wlan1 -> wlan0 and unplugged and ran `wifiphisher --nojamming` but it got stuck one line after Starting wifiphisher and my pi froze

**Comment by usama7628674** [comment]
Does your internal adapter support AP mode?

**Comment by rlstric1** [comment]
No that's why I need a wireless adpater

**Comment by usama7628674** [comment]
so now use another adpater and use this command
iwconfig
you will see two wlanX interfaces one is your internal and other one is external note the interface name 
of external card and put it in interfaces file

**Comment by rlstric1** [comment]
I chaned the interfaces to wlan1, ran `python wifiphisher --nojamming`, it tried to use my wlan0 (interal)

if I run `wifiphisher --nojamming -aI wlan1`, it begins listing other APs

**Comment by usama7628674** [comment]
so now you are seeing other AP

**Comment by rlstric1** [comment]
yes, if I select on to attack I get back to where I started in the beginning of this thread. It closing immediately after trying to start a fake AP

**Comment by usama7628674** [comment]
select any access point and then it will show you some templates and select any one of them
like oauth-login and after that it will start fake access point

**Comment by rlstric1** [comment]
it closes after trying to start a fake AP

**Comment by usama7628674** [comment]
In my pc I'm experiencing the same so I installed dnsmasq and dnsmasq-base and got it working

**Comment by rlstric1** [comment]
I have both of them installed version 2.77-2

**Comment by usama7628674** [comment]
First I remove both of them and tried wifiphisher but it closes stating "starting fake access point"
and then I installed both of them and now it's working fine for me.

**Comment by rlstric1** [comment]
I must be missing something else related to starting a fake AP then but I'm not sure what it is or why this keeps happening. I don't see any other threads about it

**Comment by usama7628674** [comment]
Yes I'm also thinking you are missing something

**Comment by rlstric1** [comment]
Okay so I tried to install again from `sudo python setup.py install` and something came up from trying to install ifconfig stating: `Don't know how to install ifconfig for you distribution, rerun after installing manually`

**Comment by rlstric1** [comment]
Okay so I fixed it:
`sudo apt-get install net-tools` for ifconfig and now it's able to get to the DHCP HTTP screen.  Now it's been there for a couple minutes I'm not sure if it's working completely though

**Comment by usama7628674** [comment]
here is my dpkg -l file,download it and take a look maybe something you're missing
https://www.sendspace.com/file/01mk9r

**Comment by usama7628674** [comment]
here is my dpkg -l file,download it and take a look maybe something you're missing
https://www.sendspace.com/file/01mk9r

**Comment by usama7628674** [comment]
In this way I hope you'll resolve the problem

**Comment by rlstric1** [comment]
I'll take a look but one thing I noticed that's where is when my card is displaying other APs all the PWR's are at 0%, even my own

**Comment by usama7628674** [comment]
Ignore that continue further

**Comment by usama7628674** [comment]
Connect your pc or android with fake-access point and see it it's working fine

**Comment by usama7628674** [comment]
sometimes for it shows PWR 100% even for those AP that are far away from my house

**Comment by usama7628674** [comment]
I don't believe it because I'm getting less than 30% signal so how can PWR be 100%

**Comment by rlstric1** [comment]
I had to manually connect to the fake AP because the power of my router was higher than that of my network adapter even though I'm sitting next to my Pi.

I was deauthenticated fine but had to connect manually and have no received an authentication page when trying to access the internet

**Comment by rlstric1** [comment]
All websites I try to access have server not found errors

**Comment by usama7628674** [comment]
Yes you have to connect manually it doesn't connect automatically.That is fine
try http://czone.com.pk

**Comment by usama7628674** [comment]
sometimes it doesn't redirect to fake page when using https sites

**Comment by rlstric1** [comment]
what triggers the redirect?

**Comment by usama7628674** [comment]
connect to fake AP and then try to use http sites on your browser

**Comment by usama7628674** [comment]
so that it'll take you to oauth-login or whatever template you selected,creating Fake AP with wifiphisher

**Comment by rlstric1** [comment]
no sites trigger an authentication to display

**Comment by usama7628674** [comment]
Please explain everything now from start to end now you got it working

**Comment by rlstric1** [comment]
Removed wifiphisher
Reinstalled
Manually installed packages that setup.py gave errors on (Mine was ifconfig/setuptools)

**Comment by usama7628674** [comment]
and now explain it's working

**Comment by usama7628674** [comment]
run it now and then tell me

**Comment by rlstric1** [comment]
It runs and gets into the DHCP HTTP screen where it waits for someone to connect
Successfully registers someone connect but does not trigger oauth.

**Comment by usama7628674** [comment]
so now you're connected to Fake AP with oauth-login template but doesn't getting oauth page
you're testing it on android or windows

**Comment by rlstric1** [comment]
I tested both Android and Windows.

I even set up a "free WiFi" open hotspot, connected, and no trigger for oauth

**Comment by anakin1028** [comment]
Do you get dhcp release? 
Is this possible for you to use wireshark or tcpdump on the ap interface and post the capture on This thread?

**Comment by rlstric1** [comment]
Yeah I'm able to DHCP release, I'll see if I can use Wireshark when I get home.

**Comment by rlstric1** [comment]
What would I be looking for in the wireshark capture, ARP and DHCP protocols?

**Comment by anakin1028** [comment]
OK. you can see if there is any `http` request and response.
Have you tried just type ip address `10.0.0.1` on the browser of the victim device?

**Comment by anakin1028** [comment]
@rlstric1 the original problem for this issue is sloved by install `dnsmasq` so I'll close this issue.
If you have more questions or problems for the program feel free to open the new issues : )
