### ISSUE TITLE
permisson denied

### ISSUE THREAD

**Issue by Farazrao786** [wifiphisher/wifiphisher#721]
Before opening a new issue, please make sure that what you are about to report has not been reported already. If not, use the following template for reporting.

**Version**: Use `git show | grep commit` command and paste here the output.

**Description**: Give a more analytical description here. The output of the `iw list` and `iwconfig` commands may be helpful.

**Script output**: Paste the output of the tool, including any stack traces.

**Comment by usama7628674** [comment]
You need to give permission a script to run it.For example
`chmod +x scriptname.py`
In this case `chmod +x setup.py`

**Comment by sophron** [comment]
Please fill the issue template if you want to get helped.
