### ISSUE TITLE
problem with wifiphisher

### ISSUE THREAD

**Issue by Haidermahdi** [wifiphisher/wifiphisher#725]

**Comment by anakin1028** [comment]
I didn't see any description from your post?

**Comment by anakin1028** [comment]
If you have problem feel free to reopen it with description :)

**Comment by Haidermahdi** [comment]
Sorry my friend ..i put the description but after 2 minutes i fix it so i delete the description. I'm new in github I don't have idea how to close my question..sorry again

**Comment by anakin1028** [comment]
Ok, no worries : ) Next time you can add comment and close it : )
