### ISSUE TITLE
hangs on ssl warning page

### ISSUE THREAD

**Issue by eitanhindi** [wifiphisher/wifiphisher#727]
first i must say, its the best tool i ever had!

i took a good view over all the regarding topics on it, and still didnt realize it ...
Everything works perfect except for one unfriendly behavior:
As I connected my Android (2 devices checked) to fake AP, I m always redirected to SSL page warning from Google. And it hangs there. I need to manually write URL to get the captive portal.(obvious no user will ever do it)
its redirect all the time to "http://www.google.com" which show the warning page.

is there way to set up other url for captive portal instead of "http://www.google.com"?

- Any answer I see regarding this topic, is that wifiphisher auto detect https and redirect to http , but its not what happaning.

What can I do to prevent the popup to ssl warning page?

in one of the issues i saw someone who made completely new url for popup, how to do that?

im using the latest wifiphisher.
There are no errors all along.
thank u...

**Comment by sophron** [comment]
Hi @eitanhindi,

There is no trivial way to bypass HSTS currently. Furthermore, we don't get to choose the URL that the victim device will hit (in this case, http://www.google.com).

This default attack mode is mostly intended against captive portal mechanisms. If you are targeting individuals it's probably more effective to provide the victims with Internet (using the `-iI` option) and then 1) wait for the victim to initiate an HTTP connection and throw the phishing page then (you will have to do this manually though, it's not currently automated) or 2) perform other kind of man-in-the-middle attacks (have a look at Beef framework). These are just ideas. There are multiple attack scenarios that can happen.

**Comment by eitanhindi** [comment]
ok, got u.
good tip!
thank u

**Comment by blackHatMonkey** [comment]
@eitanhindi I'm closing this issue. Feel free to open it again if you want to.
