### ISSUE TITLE
Wifiphisher closes due to dependency of dnsmasq failed to resolve

### ISSUE THREAD

**Issue by SimpleHero** [wifiphisher/wifiphisher#728]
I have install it using the command python setup.py install. then after that opened a new terminal at the bin folder of wifiphisher. then run the command "wifiphisher" or "./wifiphisher" and select a wifi then a 1-4 method of hacking. I choose 2 for firmwire upgrade? then after that it runs but suddenly it says [!] Closing.

**Comment by usama7628674** [comment]
Use these commands 
`sudo apt-get install net-tools`
`sudo apt-get install dnsmasq`
`sudo apt-get install dnsmasq-base`
and reinstall wifiphisher.

**Comment by anakin1028** [comment]
@SimpleHero what os do you use?
@usama7628674 is this issue same as #720 ?

**Comment by usama7628674** [comment]
The description resembles with #720 but above commands fixed that #720 issue.

**Comment by anakin1028** [comment]
@usama7628674 thanks. I guess the target OS doesn't install dnsmasq. 
I think we need to add warning message when `dnsmasq` fork fail.

**Comment by usama7628674** [comment]
Yes sure.Maybe target doesn't install `net-tools` as was the issue mentioned by user
in #720

**Comment by sysroot255** [comment]
Can you try this 👍 
before : nmcli n off 
run wifiphisher and try

when you have finish : nmcli n on and restart network-manager services.

**Comment by SimpleHero** [comment]
@usama7628674 I'm going to try now the commands you said.

@anakin1028 i'm using kali linux 2017.1 x64. Using live persistence method through bootable USB.

**Comment by SimpleHero** [comment]
It finally worked. Thanks @usama7628674. All I need now is another adapter for deauth. Any idea how can i find a adapter that is capable of monitor mode, injection and this netlink? Only if you know guys.

**Comment by usama7628674** [comment]
Glad you solved the issue.For adapter I recommend you to get Alfa AWUS036NHA.I hope this adater won't disappoint you.

**Comment by anakin1028** [comment]
Cool. great to hear about that and thanks for @usama7628674 too : )

What card do you use now? If your card can run `python bin/wifiphisher` successfully from the latest commit on the github then jamming and fakeAP can run on you card now.

#652 lists two cards (ALFA-AWUS036NHA and TPLINK-WN722N-V1) that I have tested and can be used as monitor and AP.

**Comment by usama7628674** [comment]
and also tp-link wn722n-v1 the @anakin1028 mentioned above.

**Comment by anakin1028** [comment]
@SimpleHero the issue has been solved and feel free to open new issue if you find the new problem.

**Comment by SimpleHero** [comment]
@anakin1028 thanks a lot.

I have search TP-LINK WN722N. They said that v1 is capable of monitor mode while v2 is not.

**Comment by anakin1028** [comment]
Yes. Correct. V2 uses Realtek's chipset and cannot support monitor mode.
