### ISSUE TITLE
How to redirect victims on portal like Wifiphisher?

### ISSUE THREAD

**Issue by m0rpheus1337** [wifiphisher/wifiphisher#729]
Hi everybody,

It's not an issue. I'm writing my own script to create fake AP (even if wifiphisher is a better script). I want to redirect victim on a server. First, I used "iptables", but it's not a good way because the victim must open a browser and a page to be redirected.

With wifiphisher, we are redirected automatically to the portal even if the browser is closed. I want to do that on my program. I found "radius" and "diameter" protocol but Anakin said they didn't used this method.

If you can give me some info to do that, I'll take it !
Thanks you !

**Version**: Latest

**Comment by anakin1028** [comment]
@m0rpheus1337 thanks for posting issue on the github : ) @sophron has answered it in the thread #618. 

You can have a look there first and there are more discussion in the thread #524. 
I will close this issue as it's duplicated with #524. If you have more questions we can discuss in #524 :)
