### ISSUE TITLE
pyric.error: [Errno 5] Input/output error

### ISSUE THREAD

**Issue by jamalhck** [wifiphisher/wifiphisher#732]
```
root@lap:~/Downloads/wifiphisher-1.3/wifiphisher-1.3# python ./bin/wifiphisher
[*] Starting Wifiphisher 1.3 at 2017-09-09 03:15
[+] Selecting wlan1 interface for the deauthentication attack
[+] Selecting wlan0mon interface for creating the rogue Access Point
Traceback (most recent call last):
  File "./bin/wifiphisher", line 12, in <module>
    run()
  File "/root/Downloads/wifiphisher-1.3/wifiphisher-1.3/wifiphisher/pywifiphisher.py", line 776, in run
    engine.start()
  File "/root/Downloads/wifiphisher-1.3/wifiphisher-1.3/wifiphisher/pywifiphisher.py", line 616, in start
    self.network_manager.up_ifaces([ap_iface, mon_iface])
  File "/root/Downloads/wifiphisher-1.3/wifiphisher-1.3/wifiphisher/common/interfaces.py", line 245, in up_ifaces
    pyw.up(card)
  File "/usr/lib/python2.7/dist-packages/pyric/pyw.py", line 589, in up
    if iosock is None: return _iostub_(up, card)
  File "/usr/lib/python2.7/dist-packages/pyric/pyw.py", line 2260, in _iostub_
    return fct(*argv)
  File "/usr/lib/python2.7/dist-packages/pyric/pyw.py", line 594, in up
    _flagsset_(card.dev, _setf_(flags, ifh.IFF_UP), iosock)
  File "/usr/lib/python2.7/dist-packages/pyric/pyw.py", line 1969, in _flagsset_
    raise pyric.error(e.errno, e.strerror)
pyric.error: [Errno 5] Input/output error
```

The wifi cards cannot be used after oppening wifiphisher, have to restart the laptop to make it work.

iwconfig:

root@lap:~/Downloads/wifiphisher-1.3/wifiphisher-1.3# iwconfig
usb0      no wireless extensions.

eth0      no wireless extensions.

wlan0mon  IEEE 802.11  ESSID:off/any  
          Mode:Managed  Access Point: Not-Associated   Tx-Power=20 dBm   
          Retry short limit:7   RTS thr:off   Fragment thr:off
          Encryption key:off
          Power Management:off
          
lo        no wireless extensions.

wlan1     IEEE 802.11  Mode:Monitor  Frequency:2.422 GHz  Tx-Power=20 dBm   
          Retry short limit:7   RTS thr:off   Fragment thr:off
          Power Management:on

Someone please HELP!!
Tried everything updating packages etc.

**Comment by anakin1028** [comment]
* Q1: What are the wireless cards do you use?
* Q2: from the log: `self.network_manager.up_ifaces([ap_iface, mon_iface])` it seems the version is outdated. Can you pull the latest commits from github and try again? you can do by the following:
```
git fetch
git merge origin master
python setup.py install
```
And try to run `wifiphisher` again by `python bin/wifiphisher`

**Comment by jamalhck** [comment]
A1:

root@DESKTOP-S9M6GJH:~/Downloads/wifiphisher-1.3/wifiphisher-1.3# airmon-ng

PHY	Interface	Driver		Chipset

phy1	wlan0		rt2800pci	Ralink corp. RT3290 Wireless 802.11n 1T/1R PCIe
phy0	wlan1		mt7601u		Ralink Technology, Corp. MT7601U

Both of my cards are capable of monitor mode, and injection.
wlan1 is a small usb dongle. wlan0 built in laptop

A2:

Can you please specify a bit more on how to use those commands.
Ends up with this: fatal: Not a git repository (or any of the parent directories): .git

Sorry for my ignorance, but I'm new in linux.

By the way, wifiphisher 1.3 worked today, without doing anything, but I've just checked again after restarting the laptop and still the same error 5.

**Comment by usama7628674** [comment]
Try cloning the script again using the given commands

`git clone https://github.com/wifiphisher/wifiphisher.git`

`cd wifiphisher`

`sudo python setup.py install`

**Comment by anakin1028** [comment]
> phy1	wlan0	rt2800pci	Ralink corp. RT3290 Wireless 802.11n 1T/1R PCIe
phy0	wlan1	mt7601u	Ralink Technology, Corp. MT7601U


I haven't test our program with those two adaptors. I think you can try if the following commands and see if there is any workable for you:
```
python bin/wifiphisher -aI wlan0 -jI wlan1 # jamming with wlan1 and lunch AP with wlan0
python bin/wifiphisher -aI wlan1 -jI wlan0 # jamming with wlan0 and lunch AP with wlan1
python bin/wifiphisher -aI wlan1 -nJ # no jamming just lunch Access Point with wlan1
python bin/wifiphisher -aI wlan0 -nJ # no jamming just lunch Access point with wlan0
```

And you can follow with the commands that @usama7628674 provides and see if the above commands are workable for you or not : )

**Comment by jamalhck** [comment]
@usama7628674 I tried that, but it's still the same.

@anakin1028 Tried all 4 commands, and got this same error on all 4:

`root@DESKTOP-S9M6GJH:~/wifiphisher# python ./bin/wifiphisher[*] Starting Wifiphisher 1.3GIT ( https://wifiphisher.org ) at 2017-09-10 19:55
[+] Selecting wlan2 interface for the deauthentication attack
[+] Selecting wlan1 interface for creating the rogue Access Point
Traceback (most recent call last):
  File "./bin/wifiphisher", line 12, in <module>
    run()
  File "/root/wifiphisher/wifiphisher/pywifiphisher.py", line 885, in run
    engine.start()
  File "/root/wifiphisher/wifiphisher/pywifiphisher.py", line 661, in start
    self.network_manager.set_interface_mac_random(ap_iface)
  File "/root/wifiphisher/wifiphisher/common/interfaces.py", line 528, in set_interface_mac_random
    self.set_interface_mac(interface_name, new_mac_address)
  File "/root/wifiphisher/wifiphisher/common/interfaces.py", line 490, in set_interface_mac
    raise InvalidMacAddressError(mac_address)
wifiphisher.common.interfaces.InvalidMacAddressError: The provided MAC address 00:00:00:a4:39:8a is invalid
`
Then I restarted the laptop and checked again, and got this:

`root@DESKTOP-S9M6GJH:~/wifiphisher# python ./bin/wifiphisher
[*] Starting Wifiphisher 1.3GIT ( https://wifiphisher.org ) at 2017-09-10 20:26
[+] Selecting wlan1 interface for the deauthentication attack
[+] Selecting wlan0 interface for creating the rogue Access Point
[+] Sending SIGKILL to wpa_supplicant
[+] Sending SIGKILL to dhclient
[+] Sending SIGKILL to NetworkManager
[+] Changing wlan0 MAC addr (BSSID) to 00:00:00:9c:79:39
[*] Cleared leases, started DHCP, set up iptables
[+] Selecting Network Manager Connect template
[*] Starting the fake access point...
[+] Show your support!
[+] Follow us: https://twitter.com/wifiphisher
[+] Like us: https://www.facebook.com/Wifiphisher
[+] Captured credentials:
[!] Closing
root@DESKTOP-S9M6GJH:~/wifiphisher# 
`
Afer this I tried:

python bin/wifiphisher -aI wlan0 -nJ # no jamming just lunch Access point with wlan0

and got it working!! Lets see if it works for a while, will give an update.


Thanks for your help, much appreciated.

pd.: I think my wireless cards are weak, which wireless cards do you recommend. I've seen the ALFA awus036h, is there anything that does the same job but a bit cheaper?

**Comment by jamalhck** [comment]
The deauthentication does not work with that command, just realized. Any alternatives? Thanks.

**Comment by anakin1028** [comment]
Can you test the above commands with `-iNM`?

**Comment by anakin1028** [comment]
Looks like your adaptor cannot set mac address
