### ISSUE TITLE
Logging feature needed. + another simple idea

### ISSUE THREAD

**Issue by HorneyAttorney** [wifiphisher/wifiphisher#733]
This tool needs Logging feature..

When a phishing AP is up and a victim joins, so many GET requested are processed, some apps tend to run a connection automatically when the phone is connected to wifi or mobile data is enabled.

Since wifiphisher terminal shows only 4 lines, they disappear very fast, these lines might include captured credentials.
Now, imagine three victims trying to connect, the terminal gets messy, and after I stop the AP there is only 1 line of credentials and maybe 2, some go missing.

Logging the whole session to check after you take the AP down would be very helpful.

===========================

Another simple idea.
What if there's a feature in the tool that will allow me to create an AP with wlan0, jam target AP with wlan1, and then bridge connection from wlan2 or eth0 and let the victim connect to the internet though the fake AP, and then hijack the data.

I mean, if I can be MITM just to get wifi password, why not get everything?

**Comment by anakin1028** [comment]
Yes. we're planning to implement the logging feature and there are some issues (i.e. like #704) have pointed out that.

About the second idea: wifiphisher can do data hijacking by providing the option : `-iI eth0` or `-iI wlan2` to bridge the internet connection. The whole command would something like the following:
`wifiphisher -aI wlan0 -jI wlan1 -iI wlan2`

**Comment by anakin1028** [comment]
I'll close this issue since it's duplicated with #704. Feel free to open new issues if you have other problems for the tool : )
