### ISSUE TITLE
Duplicate of #745

### ISSUE THREAD

**Issue by MattIraq** [wifiphisher/wifiphisher#743]
I am using last version kali linux with Wifiphisher version 1.3 and alfa AWUS051NH v.2

when I start the Wifiphisher -nJ  I got the gray page for the networks information but I can not find any network even my router network!! 

Can you help me with that problem !!

![screen shot 2017-09-13 at 7 50 19 pm](https://user-images.githubusercontent.com/17963460/30392924-9a857f2a-98be-11e7-81af-6c78a8bb203d.png)

**Comment by sophron** [comment]
I guess this was resolved since you posted #745?
