### ISSUE TITLE
Static path for template configuration and html file

### ISSUE THREAD

**Issue by DarkReef** [wifiphisher/wifiphisher#744]
I raise this issue because `PhishingTemplate` have a static path for configuration and html files which must be at root of the template directory. Can we rework this class into more dynamic structure?

**Comment by sophron** [comment]
Hi @DarkReef,

What kind of dynamic structure do you have in mind? I explained my opinion on this on #712.

**Comment by DarkReef** [comment]
Hello, @sophron 
I agree with your opinion, but, as I understand, #712 is no longer relevant.
So, I suggest change the `PhishingTemplate` a bit, add a custom path to the configuration file, maybe add the category field and rework the template search. IMO, we shouldn't return the name of the directory with the template, we should return the `PhishingTemplate` instance.

**Comment by sophron** [comment]
Most of these sound like code refactoring changes. I recommend you to submit a Pull Request with all the changes you recommend and we can discuss them there.

**Comment by DarkReef** [comment]
Ew, this not really it, just a suggestion
I'm useless in such thing like code refactoring, really sorry

**Comment by blackHatMonkey** [comment]
This has been implemented in #734.
