### ISSUE TITLE
I can't find my fake access point

### ISSUE THREAD

**Issue by Matt7Be** [wifiphisher/wifiphisher#745]
Hello 
I am using last version kali linux with Wifiphisher version 1.3 and alfa AWUS051NH v.2
I followed all the step but I got two problem

1- I didn't get so much networks around me !!

2- I can't find my fake access point after I chose the network !!

![screen shot 2017-09-13 at 10 31 21 pm](https://user-images.githubusercontent.com/17963460/30400695-fdbc9a56-98d7-11e7-99e7-632a0a8e35fe.png)

![screen shot 2017-09-13 at 10 32 13 pm](https://user-images.githubusercontent.com/17963460/30400702-023afa32-98d8-11e7-966f-a88f551e2e42.png)

![screen shot 2017-09-13 at 10 32 56 pm](https://user-images.githubusercontent.com/17963460/30400707-05e78a6a-98d8-11e7-872a-21f6602c8d8f.png)

![img_0093](https://user-images.githubusercontent.com/17963460/30400813-72be29e6-98d8-11e7-8a50-d5885f4cad3e.PNG)

**Comment by anakin1028** [comment]
After entering the main terminal of wifiphisher (shows the deauth/dhcp/http) can you post the output of the following:
```
iw dev 
iwconfig
```

**Comment by MattIraq** [comment]
@anakin1028 
This is the output 

![screen shot 2017-09-14 at 10 58 46 pm](https://user-images.githubusercontent.com/17963460/30455457-4d894f3e-99a0-11e7-9b57-527ef43b3db2.png)

**Comment by anakin1028** [comment]
From the output looks like the AP is lunching. Have you use other devices to see if the fake AP is available to them?

If you have another adaptor and has the monitor mode capability, you can sniff the channel 6(the channel which your fakeAP lunched) and see if there is beacon on the air for your fakeAP.
```
iwconfig wlan0 mode monitor
ifconfig wlan0 up
iwconfig wlan0 channel 6
wireshark
```

**Comment by MattIraq** [comment]
@anakin1028 
I used different devices to check if there is a fake AP but i got same result there is no fake AP
even I tried with different networks to clone the fake AP!!

This only adaptor I have and its work good with other tools!!

**Comment by anakin1028** [comment]
Can you pull the latest commit in wifiphisher and do the test again? We have fixed a network-manager interfering problem recently.

If this still doesn't work,  can you follow the instructions listed in #738 to lunch the hostapd and see if your device can find it?

**Comment by MattIraq** [comment]
@anakin1028 

Now I can't find access point around me even my router!!

![screen shot 2017-09-15 at 5 55 57 pm](https://user-images.githubusercontent.com/17963460/30491944-2d8a20ce-9a3f-11e7-9892-bb92e8e16a28.png)

**Comment by sophron** [comment]
My guess is that your card tends to fall out.

@anakin1028 A good idea here is to use Pyric's `pyw.validcard(w0)` before doing the actual operations (e.g. before looking for around APs or before starting the AP) to make sure that the card is up and running.
