### ISSUE TITLE
HELP ME 

### ISSUE THREAD

**Issue by gudi13** [wifiphisher/wifiphisher#755]
Hello, i start the wifiphisher and.

> [*] Starting Wifiphisher 1.3GIT ( https://wifiphisher.org ) at 2017-09-22 01:03
[+] Selecting wlan1 interface for the deauthentication attack
[+] Selecting wlan0mon interface for creating the rogue Access Point
[+] Sending SIGKILL to wpa_supplicant
[+] Changing wlan0mon MAC addr (BSSID) to 00:00:00:1c:da:e5
[*] Cleared leases, started DHCP, set up iptables
[+] Selecting OAuth Login Page template
[*] Starting the fake access point...
[+] Show your support!
[+] Follow us: https://twitter.com/wifiphisher
[+] Like us: https://www.facebook.com/Wifiphisher
[+] Captured credentials:
[!] Closing

> someone can help me?

**Comment by face0b1101** [comment]
I had the same output, I hesitate to say the same problem as I don't know what's going on behind the scenes.

Try killing network manager prior to starting Wifiphisher, it worked for me

**Comment by anakin1028** [comment]
It should be ok for the latest commit on the github. Can you output the commit id by:

`git show|grep commit`

**Comment by anakin1028** [comment]
@gudi13 I guess this issue is resolved for you right? I'll close this first and feel free to reopen it if you want : )
