### ISSUE TITLE
Mana-toolkit not working

### ISSUE THREAD

**Issue by Tusharsharma86** [wifiphisher/wifiphisher#758]
I am facing issue in creating a Fake AP using mana-toolkit on Kali Linux. I am able to successfully create a AP, it connects to my android device (with internet access) and after 30 secs it gets disconnected, even though the fake AP is getting displayed in WiFi scanning list, but cannot be connected again.

After this, it does not get connect again. Options tried -
1. Changing the channels in hosted-mana.conf
2. changing wifi names
3. Restarting Kali Linux
4. Plugging in all USB ports

It just works for 30 secs and then disconnects. Please help.

**Comment by Tusharsharma86** [comment]
I got the solution to this. Closing this thread.

**Comment by sophron** [comment]
Just a friendly notice that this is Wifiphisher project, not MANA Toolkit.

**Comment by Tusharsharma86** [comment]
Yes it was out of curiosity which I asked and I have opened seperate thread
for MANA.

**Comment by sans-byte** [comment]
If u got the fix of this issue please share it with us

**Comment by AY0N** [comment]
Can you please share the solving method here?
