### ISSUE TITLE
-iI not providing internet access. 

### ISSUE THREAD

**Issue by J0akes** [wifiphisher/wifiphisher#760]
running wifiphisher with the option -iI eth0 doesnt provide internet access to users. 

I am running kali rolling 2017.2 in a virtual box using a bridged adapter for eth0 and wifiphisher 1.3 . 

Also, I noticed that my phone will successfully get de-authed, but wont automatically connect to the new, identical AP that wifiphisher makes. Instead it just looks like there is now "J0akes Wifi" and "J0akes Wifi" again that shows up, just one doesn't have a password, and my phone see's it as having no internet connection (without connecting to it), my windows 10 desktop see's it the same.

IMO this makes things pretty obvious that an attack is going on, or at least may set off alarm bells in some users minds.

Is this something that I'm doing wrong?

**Comment by anakin1028** [comment]
From your description your devices hasn't connected to the fakeAP. You can try to manually connect to the fakeAP and see if this work for you.

Can you post the following information too:
1) The  command you use in this thread? 
2)`ifconfig` when the tool enters the main terminal

**Comment by J0akes** [comment]
Yes that's correct. 
My devices do not connect to the fakeAP, but yes they do indeed get deauthenticated from the realAP.
Connecting manually, my devices do not get served the phishing page, which I understand is a known thing. However fakeAP does not have internet access.

The command I run is this:
wifiphisher -iI eth0 

ifconfig when it's running is:

```
eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.1.121  netmask 255.255.255.0  broadcast 192.168.1.255
        inet6 fe80::a00:27ff:fe8d:4afe  prefixlen 64  scopeid 0x20<link>
        inet6 fd89:4efe:a3a7:0:a00:27ff:fe8d:4afe  prefixlen 64  scopeid 0x0<global>
        ether 08:00:27:8d:4a:fe  txqueuelen 1000  (Ethernet)
        RX packets 42  bytes 4085 (3.9 KiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 22  bytes 1951 (1.9 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
        loop  txqueuelen 1000  (Local Loopback)
        RX packets 26  bytes 1518 (1.4 KiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 26  bytes 1518 (1.4 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

wlan0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1400
        inet 10.0.0.1  netmask 255.255.255.0  broadcast 10.0.0.255
        inet6 fe80::200:ff:fed3:965a  prefixlen 64  scopeid 0x20<link>
        ether 00:00:00:d3:96:5a  txqueuelen 1000  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 7  bytes 712 (712.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

wlan1: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        unspec 00-00-00-BD-86-2C-30-3A-00-00-00-00-00-00-00-00  txqueuelen 1000  (UNSPEC)
        RX packets 1797  bytes 342825 (334.7 KiB)
        RX errors 0  dropped 543  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
```


I actually got it working:

I have to manualy kill networkmanager because of this error:
```

wifiphisher -iI eth0

[*] Starting Wifiphisher 1.3GIT ( https://wifiphisher.org ) at 2017-09-24 00:33
[!] Interface "ALL" is controlled by NetworkManager.You need to manually set the devices that should be ignored by NetworkManager using the keyfile plugin (unmanaged-directive). For example, '[keyfile] unmanaged-devices=interface-name:"ALL"' needs to be added in your NetworkManager configuration file.
[+] Show your support!
[+] Follow us: https://twitter.com/wifiphisher
[+] Like us: https://www.facebook.com/Wifiphisher
[+] Captured credentials:
[!] Closing
"

```
However, if I just run this: 

```
wifiphisher
"
[*] Starting Wifiphisher 1.3GIT ( https://wifiphisher.org ) at 2017-09-24 00:38
[+] Selecting wlan1 interface for the deauthentication attack
[+] Selecting wlan0 interface for creating the rogue Access Point
[+] Sending SIGKILL to wpa_supplicant
[+] Sending SIGKILL to dhclient
[+] Sending SIGKILL to NetworkManager
[+] Changing wlan0 MAC addr (BSSID) to 00:00:00:09:ae:5e
[*] Cleared leases, started DHCP, set up iptables
```
"

Then use esc key to end

Then run 

wifiphisher -iI eth0

It runs with no errors but does not give fakeAP internet.

**Comment by anakin1028** [comment]
You cannot stop the service of NetworkManager since you need `eth0` to have the internet connection.
Before you run the command `wifiphisher -iI eth0`, you need to modify the configuration file:`/etc/NetworkManager/NetworkManager.conf` and add `keyfile` section to let the NetworkManager not controll the `wlan0` and `wlan1`

have a look for the following link and see the section of `Alternate KEYFILE method`
http://support.qacafe.com/knowledge-base/how-do-i-prevent-network-manager-from-controlling-an-interface/
