### ISSUE TITLE
Phishing scenarios not being listed

### ISSUE THREAD

**Issue by tarsicle** [wifiphisher/wifiphisher#763]
Wifiphisher v1.3GIT running Kali Linux 2017.1 on a Raspberry Pi 3.

git show | grep commit output is:
commit 324a855c49c5d04519f8064962118ba9783dfb6e

For some reason the only phishing scenario that is being listed is the 'Network Manager Connect' even tho I have all of the default as well as extra phishing pages installed in the phishing-pages folder.

They are in /root/wifiphisher/wifiphisher/data/phishing-pages/

As well as /usr/local/lib/python2.7/dist-packages/wifiphisher-1.3-py2.7.egg/wifiphisher/wifiphisher/data/phishing-pages/

Copied them to the root/wifiphisher folder before running the setup.py. I'm not sure what has changed for me as they were working a few days ago. I have removed both wifiphisher directories as well as /usr/local/bin/wifiphisher, cloned then reinstalled and the problem is still persisting.

**Comment by sophron** [comment]
Can you try running the binary directly using `python bin/wifiphisher` instead of simple `wifiphisher`?

**Comment by tarsicle** [comment]
I don't have have that file in my bin folder. 

I get 'python: can't open file 'bin/wifiphisher': [Errno 2] No such file or directory. 

Did you mean python /usr/local/bin/wifiphisher ? 
Running that I still get the same issue as described above. Only one scenario listed.

**Comment by sophron** [comment]
Are you inside the `wifiphisher` directory?

Are you <a href="https://github.com/wifiphisher/wifiphisher/archive/master.zip">downloading the right version</a>?

**Comment by tarsicle** [comment]
The only wifiphisher directories I have are the ones listed in my first post. Running python bin/wifiphisher gave me the error listed above as there is no wifiphisher file in 'bin'. Mine was installed in /usr/local/bin/ by the installer.

I installed using the instructions in the readme. git clone https://github.com/wifiphisher/wifiphisher.git. Then I copied the phishing pages to the correct folder. Then ran the python setup.py install.

It was working fine a few days ago I'm not sure what went wrong.

**Comment by sophron** [comment]
Can you `cd /root/wifiphisher/wifiphisher/` and then `python bin/wifiphisher`?

**Comment by tarsicle** [comment]
Same error. 'python: can't open file 'bin/wifiphisher': [Errno 2] No such file or directory'

**Comment by tarsicle** [comment]
Going back one directory to cd root/wifiphisher

Then running python bin/wifiphisher opens wifiphisher. But same issue with only one scenario.

**Comment by sophron** [comment]
Just to make things clear. If you `ls -la /root/wifiphisher/wifiphisher/data/phishing-pages/` you can see the phishing scenarios. However, when you `python bin/wifiphisher` you can't see them during the template selection menu. Is that the case?

**Comment by tarsicle** [comment]
Yup. Exactly.

**Comment by blackHatMonkey** [comment]
@tarsicle Can you run the `tree` command in the `wifiphisher` directory and post the results.

**Comment by tarsicle** [comment]
I have my pi on the bench right now, I'm removing the internal antenna and soldering a sma lead so I can attach a proper antenna. Once I get it back together I will.

**Comment by blackHatMonkey** [comment]
Sure 😄.

**Comment by tarsicle** [comment]
Update. Fresh install of kali and wifiphisher all is well. Suspecting it may be a failing SD card as a couple other directory related errors came up in other applications once I got the PI back together. Thank you for the help.
