### ISSUE TITLE
Fritz Box AVM Template

### ISSUE THREAD

**Issue by gitty8** [wifiphisher/wifiphisher#768]
Add Logo and template possible? 

https://upload.wikimedia.org/wikipedia/de/6/68/Fritz%21_Logo.svg

Login Page
https://imgur.com/a/mCoCF

MAC
http://www.coffer.com/mac_find/?string=avm

**Comment by sophron** [comment]
Hi @gitty8, 

In this master repo we only support the four basic scenarios.

You can however post your request on the <a href="https://github.com/wifiphisher/extra-phishing-pages">extra-phishing-pages</a> repo and someone from the community may write it for you there.

**Comment by gitty8** [comment]
done
https://github.com/wifiphisher/extra-phishing-pages/issues/13
