### ISSUE TITLE
Duplicate of #699

### ISSUE THREAD

**Issue by 0xyg3n** [wifiphisher/wifiphisher#771]
Hello,
You have created an awesome project, i really like the oauth option ; it would be great if you add as a feature after the post request of the login to allow the victim to browse the internet normally, i also have some ideas and i would like to contribute to your project i am a cyber-security (penetration tester) consultant and in my free time i code in different languages, i mostly like python so i think i could help. :)

ps: what i mean in a short meaning is , that it would be great if the victim after the post request was allowed to browse the internet you can do that with iptables easily and with create_ap .

**Comment by sophron** [comment]
Hi @0xyg3n,

That would be awesome! We are always looking for new developers to join our team.

The best way to contribute is by forking the project and implementing a new feature (see "improvements" tagged issues) or tackling a bug (see "bug" tagged issues). Then submit a Pull Request and our team will review it and provide feedback as soon as possible.

Your idea is described on #699. You are more than welcome to implement it. If you need any help, feel free to post your questions here or reach me directly at sophron <at> latthi <dot> com (jabber / email).
