### ISSUE TITLE
Enter the path for the payload as an argument

### ISSUE THREAD

**Issue by Emberborne** [wifiphisher/wifiphisher#774]
I created a bash file with only one command (wifiphisher --nojamming -aI wlan0 -e test -p plugin_update), and when I run it, it prompts me to enter the path for the payload. Is there a way to insert this path automatically in the terminal, so that I don't have to do it manually? My dream is that I run the bash script, and it automaticaly starts wifiphisher with the given parameters and the given path (which are in a bash script).

Thanks, youre doing a great job with this tool, it helped me more than once!

**Comment by sophron** [comment]
Hi @Emberborne,   

I'm afraid this is not currently possible. I'm adding the "enhancement" tag. It is an easy feature to implement so I expect one of our team members will add it within the next month.

**Comment by Emberborne** [comment]
Cool thanks. I imagine you will add a "-path" parameter. It's very useful for embedded devices with no user input possible(eg raspberry pi).

 I would create a bash file with a wifiphisher command with all the arguments necessary for a plugin update attack that does not need any user input. The dream would be to power on the rasp with no monitor/ssh and see the magic happen!

**Comment by sophron** [comment]
@Emberborne I just pushed a commit that introduces `--payload-path` argument. Please update to the latest revision and let me know if it works for you.

**Comment by Emberborne** [comment]
Is there a way I can make a donation? Because this is world class service. Thanks to your payload plugin update attack vector, I managed to watch an mp4 file from the wifi captive portal in the plane, from my phone with better sound and graphics. I've never seen a project as well maintained and serious as this one. It makes wireless audits much simpler, instead of doing this stuff manually with commands and old tools. PS: Are you the guy who did a presentation of wifiphisher in London a year ago?

**Comment by sophron** [comment]
Thank you @Emberborne. No, we don't currently accept donations but we do appreciate your feedback :)

Yes, I did the presentation "Introducing Wifiphisher" at BSidesLondon2015.

**Comment by Emberborne** [comment]
Nice presentation... I've seen you've updated the help files with the new argument. Is it me, or the tp link wn722n only supports a few channels for master mode (ap mode). I've read it somewhere, but can't remember where. But I definitely know it supports channel 6 for ap mode, so if one day you have to pick a default channel for ap's, choose the 6th.

**Comment by yungtravla** [comment]
This is a good idea, as well as selecting the path to an external phishing scenario folder via command line. I'm sick of going through the maze of wfphshr folders to simply add a scenario

**Comment by sophron** [comment]
Thanks @Emberborne. I'm closing the issue since the feature was implemented.

**Comment by yungtravla** [comment]
derp =E
