### ISSUE TITLE
issuez

### ISSUE THREAD

**Issue by yungtravla** [wifiphisher/wifiphisher#775]
```
hey guys, so i just installed the new source and didnt 
notice anything different in terms of user experience.
Like we still can't enable a captive portal with -iI, 
simple but super useful things like that. Uninstalling 
wifiphisher is also a manual task, but the worst thing
```

**Comment by yungtravla** [comment]
By the way: i decided to cut my response short, at about 5 lines, cause i felt like it

**Comment by travlatrusn01** [comment]
![kwaaafi](http://thetombradleyshow.com/wp-content/uploads/2015/01/coffee.jpg)

**Comment by yungtravla** [comment]
<h1>MODDING WIFIPHISHER BE LIKE</h1>

![image](https://user-images.githubusercontent.com/29265684/31847093-0793f67a-b659-11e7-9af8-dac0bf329156.png)

**Comment by yungtravla** [comment]
robot no understand joke
