### ISSUE TITLE
Hostapd install problem

### ISSUE THREAD

**Issue by jadbara** [wifiphisher/wifiphisher#779]
When I was booting kali from a **memory flash**, I was able to install hostapd
Now I'm booting from the **HDD** , and when **Setup.py** asks to install hostapd I get the response:

`[*] hostapd not found in /usr/sbin/hostapd, install now? [y/n] y
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package hostapd

[-] Unable to install the 'hostapd' package!
[*] This process requires a persistent internet connection!
Please follow the link below to configure your sources.list
http://docs.kali.org/general-use/kali-linux-sources-list-repositories
[+] Run apt-get update for changes to take effect.
[+] Rerun the script to install hostapd.
[!] Closing
`
I've opened the link above and tried to modify **sources.list**  but nothing works. help please

**Comment by usama7628674** [comment]
First clear your sources.list and add the following lines.
`# deb-src http://http.kali.org/kali kali-rolling main contrib non-free`
`deb http://http.kali.org/kali kali-rolling main contrib non-free`

then `apt-get update && apt-get install hostapd`
