### ISSUE TITLE
output: No handlers could be found for logger "wifiphisher.pywifiphisher"

### ISSUE THREAD

**Issue by ferromariano** [wifiphisher/wifiphisher#784]
Hey guys,

Real newbie here, so please, very little bear with me :P

**Version**: 
- wifiphisher: latest version (v: 1.3GIT)
- python: 2.7

**Description**: I run "wifiphisher -nJ" or "wifiphisher" or "wifiphisher *any*" and output **No handlers could be found for logger "wifiphisher.pywifiphisher"**

**Script output**: 
```
#: wifiphisher -nJ
[*] Starting Wifiphisher 1.3GIT ( https://wifiphisher.org ) at 2017-10-16 06:20
**No handlers could be found for logger "wifiphisher.pywifiphisher"**
[!] Failed to find an interface with AP mode
[+] Show your support!
[+] Follow us: https://twitter.com/wifiphisher
[+] Like us: https://www.facebook.com/Wifiphisher
[+] Captured credentials:
[!] Closing
```

**Comment by ferromariano** [comment]
Close issues. 

I did not walk, but I'm pretty sure it's my installation fault.

Sorry

**Comment by VANTA-B** [comment]
I have a similar issue and need prominent help
