### ISSUE TITLE
KRACK Attacks

### ISSUE THREAD

**Issue by yungtravla** [wifiphisher/wifiphisher#786]
WPA2 = compromised

Would be cool to implement this:

https://www.youtube.com/watch?v=Oh4WURZoR98

**Comment by usama7628674** [comment]
They don't release the tools yet and companies will be rolling patches next week but still most of the devices will remain vulnerable.

**Comment by usama7628674** [comment]
It's a hot topic in WiFi community.

**Comment by yungtravla** [comment]
sure is!

**Comment by djdisikd** [comment]
Did you try before? Does it works?

**Comment by yungtravla** [comment]
usaname7628674 said:


> @yungtravla They don't release the tools yet and companies will be rolling patches next week but still most of the devices will remain vulnerable.
https://www.krackattacks.com/#tools

**Comment by djdisikd** [comment]
When will they release the tools?

**Comment by travlatrusn01** [comment]
@djdisikd read the website...

> It will be released once everyone has had a reasonable chance to update their devices (and we have had a chance to prepare the code repository for release).

**Comment by usama7628674** [comment]
https://github.com/vanhoefm/krackattacks-test-ap-ft
Tool to check if AP is vulnerable to krack attack.The script got leaked.
**Note: This is not an attack script.**
For further details follow the link above.

**Comment by djdisikd** [comment]
How do I update the devices to prevent the attack?

**Comment by yungtravla** [comment]
@djdisikd by pressing yes on your phone when it asks you to update

might have to do it manually if there is a patch for your router firmware

**Comment by sophron** [comment]
Hi guys,

KRACK attack is not really in the scope of what we do. The scope of our tool is limited to rogue Access Points and not Wi-Fi attacks in general. 

We could potentially discover any APs vulnerable to KRACK during the reconnaissance phase if users are interested on that.

**Comment by djdisikd** [comment]
My phone doesn't have software updates to update for a long time.

**Comment by blackHatMonkey** [comment]
I completely agree with @sophron on this. `wifiphisher` isn't intended as a single program that implements all the wireless attacks.

**Comment by yungtravla** [comment]
lol

@sophron said:

> The scope of our tool is limited to rogue Access Points and not Wi-Fi attacks in general.

Is that right? So all the WPS button attack stuff, Lure10, etc.. are the unmentioned exceptions? **Technically** speaking, capturing handshakes is regarded as a different attack type too.

I don't see any scope regarding this project, it's gone in all sorts of directions.

If KRACKS is outside of your abilities (and I don't see how you could feel that way since it wasn't released), just say so :)

**Comment by yungtravla** [comment]
and @djdisikd

try hop on wifi in case you disabled updates over cellular.
