### ISSUE TITLE
No handlers could be found for logger "wifiphisher.pywifiphisher" on Kali Linux 2017.2

### ISSUE THREAD

**Issue by VANTA-B** [wifiphisher/wifiphisher#788]
Before opening a new issue, please make sure that what you are about to report has not been reported already. If not, use the following template for reporting.

**Version**: Use `git show | grep commit` command and paste here the output.

**Description**: Give a more analytical description here. The output of the `iw list` and `iwconfig` commands may be helpful.

**Script output**: Paste the output of the tool, including any stack traces.

**Comment by VANTA-B** [comment]
I am not a professional at this so please kindly consider and help accordingly

**Comment by blackHatMonkey** [comment]
@VANTA-B Can you please post the exact error here.

**Comment by VANTA-B** [comment]
How do I do that exactly?

**Comment by anakin1028** [comment]
Maybe you can copy the error log on the screen and post it on this thread.
Also is command listed below workable for you?
`wifiphisher --logging`

Thanks

**Comment by VANTA-B** [comment]
#: wifiphisher -nJ
[*] Starting Wifiphisher 1.3GIT ( https://wifiphisher.org ) at 2017-10-16 06:20
**No handlers could be found for logger "wifiphisher.pywifiphisher"**
[!] Failed to find an interface with AP mode
[+] Show your support!
[+] Follow us: https://twitter.com/wifiphisher
[+] Like us: https://www.facebook.com/Wifiphisher
[+] Captured credentials:
[!] Closing

**Comment by VANTA-B** [comment]
This is what I could do

**Comment by VANTA-B** [comment]
Help needed

**Comment by blackHatMonkey** [comment]
@VANTA-B It seems that you don't have a wireless adapter that supports AP mode. You can take a look at #558 for a list of adapters that are proven to work 😄.

**Comment by VANTA-B** [comment]
Thank you **blackhatmonkey** and **anakin1028**
