### ISSUE TITLE
Run wifiphisher on startup

### ISSUE THREAD

**Issue by zerocolTHS** [wifiphisher/wifiphisher#794]
How on earth can i run the command " screen wifiphisher --nojamming --essid "FREE WI-FI" -p oauth-login " attached to screen on startup i have tried  a few different ways on Raspbian but none seem to work. 
Wuld be handy to boot up headless and leave for a while then go back to it later and see results.

**Comment by Commander-Crash** [comment]
I have this same issue. Right now the only thing i can think of to fix this Issue is to use wifiphisher 1.0

**Comment by JetseVerschuren** [comment]
Have you've tried init.d?
If not you can use [this tutorial](http://www.stuffaboutcode.com/2012/06/raspberry-pi-run-program-at-start-up.html).

**Comment by blackHatMonkey** [comment]
I'm closing this issue because this issue and #795 are identical. You can continue the discussion over at #795 😄 .

**Comment by sophron** [comment]
@zerocolTHS What exactly is not working? Do you have issues running the script under `rc.d` or running the script at all?

**Comment by zerocolTHS** [comment]
This script run's fine normally but no matter how i try it on startup nothing, It just doesn't run at all. 
Even tried with out the screen command but i can never get the AP created.  
I'm using Linux raspberrypi 4.9.39-v7+ #1021 SMP Mon Jul 24 11:32:18 BST 2017 armv7l GNU/Linux

**Comment by blackHatMonkey** [comment]
@zerocolTHS That is because you are using the `--essid` option. When you specify `-essid` option it no longer goes through the AP selection phase. Try running it without `-essid` option 😄 .

**Comment by zerocolTHS** [comment]
@blackHatMonkey  IF i don't select the -essid option it clones a nearby AP which i don't want to do.  ? 

I would like to start screen then run wifiphisher --nojamming --essid "FREE WI-FI" -p oauth-login  on startup.

**Comment by zerocolTHS** [comment]
Right my startup script is 
```
#! /bin/sh
# /etc/init.d/wifip

### BEGIN INIT INFO
# Provides:          wifip
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Simple script to start a program at boot
# Description:       A simple script from www.stuffaboutcode.com which will start / stop a program a boot / shutdown.
### END INIT INFO

# If you want a command to always run, put it here
screen -dm sudo wifiphisher --nojamming --essid "FREE WI-FI" -p oauth-login
exit 0
```
`

The wifiphisher part is working now but i'm not getting a screen to re-attach to.
Thanks for every ones help so far,

**Comment by JetseVerschuren** [comment]
Can you run `screen -ls`?

**Comment by zerocolTHS** [comment]
```
screen -ls
No Sockets found in /var/run/screen/S-pi.
```
It work's fine manually  just not on autostart.

**Comment by JetseVerschuren** [comment]
Can you add `echo 1 > /test.txt` to your run script before `exit 0`. Then reboot and then execute `sudo cat /test.txt`?

**Comment by zerocolTHS** [comment]
```
sudo cat /test.txt
1

```

**Comment by blackHatMonkey** [comment]
@zerocolTHS Take a look at [this](https://serverfault.com/questions/233084/how-do-i-use-crontab-to-start-a-screen-session). `crontab` might work better for you.

**Comment by zerocolTHS** [comment]
omg it worked.

I did 
crontab -e

Then added this to bottom of the file
`@reboot screen -dmS wifip sudo wifiphisher --nojamming --essid "FREE WI-FI" -p oauth-login
`
Then screen -r and all works great. 

Thanks very much for all your help.
