### ISSUE TITLE
Does Panda 300 mbps wirless N adapter support AP mode ??

### ISSUE THREAD

**Issue by AnEvilInsideMe** [wifiphisher/wifiphisher#797]

**Comment by JetseVerschuren** [comment]
Assuming you mean the Panda PAU05 a quick google search leads me to [this](https://elinux.org/RPI-Wireless-Hotspot) page. It says:

> Panda Wireless PAU03, PAU05, PAU06, PAU07, PAU09 Wireless N USB Adapters support Access Point

**Comment by AnEvilInsideMe** [comment]
Thanx bro

**Comment by ARROOT** [comment]
Does Panda PAU06  300 mbps wirless N adapter support AP mode ??

**Comment by usama7628674** [comment]
@ARROOT Yes it does support Ap mode.

**Comment by ARROOT** [comment]
Thanks  a lot
