### ISSUE TITLE
[!] hostapd failed to lunch! arch linux , need help

### ISSUE THREAD

**Issue by ls4cfk** [wifiphisher/wifiphisher#803]
[al3x@ls4cfk ~]$ sudo su
[sudo] password for al3x: 
[root@ls4cfk al3x]# aireplay-ng -9 wlp3s0
ioctl(SIOCSIWMODE) failed: Device or resource busy
14:00:28  Trying broadcast probe requests...
14:00:28  Injection is working!
14:00:30  Found 1 AP 

14:00:30  Trying directed probe requests...
14:00:30  10:FE:ED:A6:59:F0 - channel: 1 - 'you shall not pass'
14:00:30  Ping (min/avg/max): 1.412ms/19.454ms/173.595ms Power: -12.77
14:00:30  30/30: 100%

[root@ls4cfk al3x]# wifiphisher
[*] Starting Wifiphisher 1.3GIT ( https://wifiphisher.org ) at 2017-11-10 14:00
[+] Selecting wlp3s0 interface for the deauthentication attack
[+] Selecting wlp0s20u3 interface for creating the rogue Access Point
[+] Sending SIGKILL to wpa_supplicant
[+] Sending SIGKILL to NetworkManager
[+] Changing wlp0s20u3 MAC addr (BSSID) to 00:00:00:6c:b2:3b
[+] Changing wlp3s0 MAC addr to 00:00:00:35:ec:35
[*] Cleared leases, started DHCP, set up iptables
[+] Selecting Firmware Upgrade Page template
[*] Starting the fake access point...
[!] hostapd failed to lunch!
[+] Show your support!
[+] Follow us: https://twitter.com/wifiphisher
[+] Like us: https://www.facebook.com/Wifiphisher
[+] Captured credentials:
[!] Closing
[root@ls4cfk al3x]#

**Comment by oberon2007** [comment]
I guess you will likely need **roguehostapd**. I have just created a new package of it in the AUR:
[**roguehostapd-git**](https://aur.archlinux.org/packages/roguehostapd-git/)
Please try that one.
Can I in turn ask you what you have installed in regards of dbus-python? Have a look at my [issue here](https://github.com/wifiphisher/wifiphisher/issues/804) - For me the script doesn't even launch :wink:

**Comment by oberon2007** [comment]
Btw. I am using the latest git snapshot, not the Arch stable package of **wifiphisher**.

**Comment by ls4cfk** [comment]
@oberon2007 thnx , i installed roguehostapd-git and it is working now.
