### ISSUE TITLE
Fake AP in Windows

### ISSUE THREAD

**Issue by vimdale** [wifiphisher/wifiphisher#809]
I want to create a fake AP with my windows that can accept any password
I have esp8266 to deauther my victim. 
router then I 
Want to make clone on my pc 
After the clone capture the victim password 
Is that possible?

**Comment by blackHatMonkey** [comment]
@vimdale That's not possible. Take a look at [this](https://github.com/wifiphisher/wifiphisher/issues/709#issuecomment-343158021) comment. Also `wifiphisher` is a `linux` only tool.

**Comment by sophron** [comment]
We don't support native Windows. You can run Wifiphisher under a Linux VM.
