### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by Emberborne** [wifiphisher/wifiphisher#813]
_I have seen across numerous posts across this repository people wanting to sniff creds when using an interface connected to the internet alongside their Ap interface. Like anakin said in issue #742, this is not very practical and alternatives like the [WiFi-pumpkin](https://github.com/P0cL4bs/WiFi-Pumpkin) already fulfill this._ 

What I propose is a fake ap with no internet connection, but with a captive portal saying that you are only allowed to visit 10 sites; when the user would press/click on one of the sites icon (eg. amazon banner) he would be redirected to a page where he would need to 'login to your amazon account'. The goal is to make it clear to the user that's he is not going to enjoy a site unless he logins into it's page, which would of course be a wifiphisher phishing page.
We could even try to generate a fake ssl certificate for our phishing pages so that the user sees a green lock in the url bar. Most users who even see the green lock won't be bothered to click/press it to check the name. 

I'm very open to critics =D

**Comment by sophron** [comment]
> What I propose is a fake ap with no internet connection, but with a captive portal saying that you are only allowed to visit 10 sites; when the user would press/click on one of the sites icon (eg. amazon banner) he would be redirected to a page where he would need to 'login to your amazon account'. The goal is to make it clear to the user that's he is not going to enjoy a site unless he logins into it's page, which would of course be a wifiphisher phishing page.

What are the benefits of the phishing scenario that you describe over our `oath-login` page that we currently provide?

> We could even try to generate a fake ssl certificate for our phishing pages so that the user sees a green lock in the url bar. Most users who even see the green lock won't be bothered to click/press it to check the name.

We cannot fake the authenticity of registered domains, but we could possibly give to the user the opportunity to provide an SSL cert for a domain he/she controls in addition to #741.

**Comment by Emberborne** [comment]
How many oath-login pages do you have?
The facebook one is not the most convincing one, so I think that you should include on the page _'Why do we do this'_ and write an explanation like _'Our wifi has a special partnership with facebook wifi'_
A bit like on the plugin update with the FAQ [here](https://wifiphisher.org/ps/plugin_update/).

> We cannot fake the authenticity of registered domains, but we could possibly give to the user the opportunity to provide an SSL cert for a domain he/she controls in addition to #741.

That would be a good idea, people are more aware of https and so it would reassure them. Domains are cheap, so yeah it's definitely worth it.

**Comment by sophron** [comment]
> The facebook one is not the most convincing one so I think that you should include on the page 'Why do we do this' and write an explanation like 'Our wifi has a special partnership with facebook wifi'

I agree that the `oauth-login` page can become more convincing. It is intended to be a general social media OAuth page, not only about Facebook.

We love Pull Requests. Feel free to submit a Pull Request with your ideas :)
