### ISSUE TITLE
https certificate Google

### ISSUE THREAD

**Issue by cacaocaca** [wifiphisher/wifiphisher#815]
Hi i use kali linux Linux kali 4.13.0-kali1-686-pae #1 SMP Debian 4.13.10-1kali1 (2017-11-03) i686 GNU/Linux and wifiphiser last version, so i have look that on my android if i text on chrome bar direct while wifiphiser is active "blabla" google show me the page with https convert on http and say so "Caution for steal password ecc" so , you know some method for bypass it and show direct fake page ? Becouse is useless if don work with google becouse all user use Google . I think that is it the principal problem  becouse as i have already say is useless if don t work correct with google. Thanks and comgratulation for deaut very fast you have do one good work , not even fluxion deauth so :+1:

**Comment by Ammonh** [comment]
Most web browsers will throw you that warning when connecting to your routers web interface, so technically it will be the same experience for the victim. So to your point, the program is not unless. You comment is! ;)

**Comment by cacaocaca** [comment]
Most web browsers ? Which browser you are talking about i use chrome and no show it and this no happen always. But the problem is other becouse the ignorant people that click on fake ap or if have saved connect automatically he connect direct and look the page " STEAL PASSWORD " the ignorant people don t know what to do when chrome say "add exception for this site " or do no trust equally and close connection, and no is true that the technically it will be the same experience for the victim when he connect on the router with same warning becouse he never connect on the router for it much wifi connection have a password of default becouse the people work on different different sectors as "bricklayer,waiter,fruit seller,painter" and i do no think this type of guys know it,same experience with me friend that have one bazar "store small where sell a bit of everything" he have ask me as uninstall one application on your android device , this means that the person that do one work where do no have contact with pc is totally ignorant on this matter but know just facebook whatsapp for easy chat . So my point no is useless and no is hard use this program but i know just that with wifipisher never i've had one connection of the victim becouse so if some people is ignorant on this matter this does no mean that do not know how to read "Steal password ".

**Comment by sophron** [comment]
Hi @cacaocaca, 

By default, Wifiphisher will try to simulate the same experience as a valid captive portal does. And this is what a user will experience when connecting to a public hotspot.  

If however, one wants to use Wifiphisher to get a man-in-the-middle position and then bypass HSTS / HTTPS he can use various other tricks. For example one may use Wifiphisher in combination with evilgnx tool. 

Please note that Wifiphisher should be used for legal purposes and only. Hacking your "friend that has one bazaar" is not recommended.

**Comment by cacaocaca** [comment]
Man-in-the-middle ? How can i do man-in-the-middle if before i can t connect on the local network ? O_o

**Comment by usama7628674** [comment]
@cacaocaca   Here you go
https://github.com/kgretzky/evilginx
