### ISSUE TITLE
Suggestion for addition to fake pages to improve response.

### ISSUE THREAD

**Issue by zinzer** [wifiphisher/wifiphisher#816]
The fake AP firmware upgrade page asks for a WPA2 Pre-Shared key or a WPA2 password. In my experience many average home computer users would not be sure what is required or where to look for this information. In fact this request is likely to prompt them to seek help from someone with better knowledge and who is more likely to realise that the page is fake and part of an attack.

I suggest that something like "This password can be found on the label attached to your wifi router" is added to the fake pages to help victims comply with the request and so improve effectiveness.

**Comment by anakin1028** [comment]
The password is configured by the victims. I'm not sure why your suggestion is more convinced for the victim unless the users use the default password for the AP?

**Comment by zinzer** [comment]
Yes. I believe that most users keep the default password.
1. Because I have asked family, friends and PC shop customers.
2. Because passwords I have found using other hacking tools are clearly default.

Maybe a better addition to the fake pages would be "The default password can be found on the label attached to your wifi router".  This message would not affect victims who have changed their passwords are probably more likely to know what is required anyway.

**Comment by sophron** [comment]
Even if most people don't change the default PSK, asking them to find it on the router itself will raise suspicion to the most experienced users. 

We cannot default to this but you are free to edit the HTML page directly according to your needs.

**Comment by arcaniussainey** [comment]
This is slightly unrelated, but why can hackers not create thier own ap type, and say that its wpa. What if instead of having a passphrase, the passphrase is like 
`Passphrase = "*"
if Passphrase == UserPass:
    alert.wifiphisher(UserPass)`
with the asterix meaning all passwords, and then printing the password to the hacker/user/pentester. Even if this was a re-invent the wheel situation couldn't it help?

**Comment by JetseVerschuren** [comment]
It is not possible because of the 4 way handshake cryptographic's nature.
