### ISSUE TITLE
Ask router password instead of WiFi password

### ISSUE THREAD

**Issue by djdisikd** [wifiphisher/wifiphisher#817]
We can copy the target AP WiFi password and SSID and jam the target AP so the client will be connect to ours and put the router password

**Comment by sophron** [comment]
I don't understand the difference of "router password" and "WiFi password". Maybe you mean a phishing scenario that grabs the router's admin-portal password? There's already #238 for this.

**Comment by djdisikd** [comment]
Yeah I mean grabs the router admin password
