### ISSUE TITLE
Errno1 

### ISSUE THREAD

**Issue by abdozekaa** [wifiphisher/wifiphisher#818]
Before opening a new issue, please make sure that what you are about to report has not been reported already. If not, use the following template for reporting.

**Version**: Use `git show | grep commit` command and paste here the output.

**Description**: Give a more analytical description here. The output of the `iw list` and `iwconfig` commands may be helpful.

**Script output**: Paste the output of the tool, including any stack traces.
![screenshot_2017-11-26_15-56-57](https://user-images.githubusercontent.com/24819172/33241791-7f5c351e-d2d3-11e7-8a94-dbb7a933cdc9.png)

**Comment by mowshon** [comment]
Run as root.
```
sudo wifiphisher
```

**Comment by abdozekaa** [comment]
I get failed to connect to socket /var/run/dbus/system_run_socket .. no file found

**Comment by blackHatMonkey** [comment]
@abdozekaa You are running an old version of the tool. Please get the latest from Github and try again.

**Comment by abdozekaa** [comment]
I deleted everything and redownload using git clone .. installed and get the same error failed to connect to sockt /var/run/dbus/system_bus_socket file or directory not found

**Comment by blackHatMonkey** [comment]
@abdozekaa Can you post the exact output?

**Comment by abdozekaa** [comment]
![screenshot_2017-11-26_15-56-57](https://user-images.githubusercontent.com/24819172/33493120-c7206bac-d6c7-11e7-8928-a0f1ff43801c.png)

**Comment by abdozekaa** [comment]
![screenshot_2017-12-01_16-43-00](https://user-images.githubusercontent.com/24819172/33493192-eef5fb9c-d6c7-11e7-8816-ac984c6ef4bd.png)

**Comment by abdozekaa** [comment]
The previous screenshot when i typed #wifiphisher 
This screenshot when i type #python bin/wifiphisher 
![screenshot_2017-12-01_16-50-54](https://user-images.githubusercontent.com/24819172/33493489-d6e0ee9e-d6c8-11e7-8a5b-a6708233918a.png)

**Comment by blackHatMonkey** [comment]
@abdozekaa Do you have `dbus-python` installed?

**Comment by abdozekaa** [comment]
How to know if it's installed or not ?

**Comment by blackHatMonkey** [comment]
Just run `pip2 install dbus-python`. This should install it if needed.

**Comment by abdozekaa** [comment]
Requirements already satisfied ... i guess it is intalled
