### ISSUE TITLE
Wifiphisher - No interface with monitor mode found

### ISSUE THREAD

**Issue by Someone847** [wifiphisher/wifiphisher#820]
Hello guys, i am new here and i have one question for you. I installed Kali Linux 2017.3 on VMWare Workstation Player and everything works normal, i downloaded wifiphisher, good installed wifiphisher, but when i tried to run wifiphisher (type wifiphisher in terminal) i get an error:

Starting Wifiphisher 1.3GIT ( https://wifiphisher.org ) at 2017-11-30 13:46
No handlers could be found for logger "wifiphisher.pywifiphisher"
[!] Failed to find an interface with monitor mode
[+] Show your support!
[+] Follow us: https://twitter.com/wifiphisher
[+] Like us: https://www.facebook.com/Wifiphisher
[+] Captured credentials:
[!] Closing 

Here is the photo of the error: https://i.stack.imgur.com/ExYdl.png

**Comment by JetseVerschuren** [comment]
Have you plugged in a usb wifi adapter with monitor mode?

**Comment by Someone847** [comment]
JetseVerschuren Thank you soo much bro, i purchased Atheros USB Wifi Adapter with Monitor Mode and now everything works fine, thanks bro <3

**Comment by nagyar9966** [comment]
Need wifi adapter?
