### ISSUE TITLE
Wireless interface dont support AP mode. HELP!!

### ISSUE THREAD

**Issue by omermujtaba** [wifiphisher/wifiphisher#821]
Hi, I am using an Alfa card. Its chipset is Ralink Technology, Corp. MT7601U.
But i am getting error of AP mode not supported. 

Can someone suggest a fix of this issue or suggest me some wifi adapters that support AP mode. 

Thankyou :)

**Comment by blackHatMonkey** [comment]
Hi @omermujtaba Can you post the result of running
```
iw list
```
after connecting all your adapters?

**Comment by MarkusHaas2002** [comment]
I prefer the PAU05

**Comment by arcaniussainey** [comment]
not all adapters work such as my chromebooks, which uses mlan and cannot broadcast a network. It may be helpful if someone created a list of devices that support it
