### ISSUE TITLE
redirect to specific dns name instead of "10.0.0.1"

### ISSUE THREAD

**Issue by m7md2112** [wifiphisher/wifiphisher#822]
if we could redirect all requests to custom dns name instead of ip we will pass https alarm by original Let's Encrypt - Free SSL/TLS Certificates . is there any method to do that ???

**Comment by sophron** [comment]
You can use the `--iI` option to provide the victims with Internet. Then you are free to manually (or with the use of other tools) to redirect the victims to a domain that you  own.
