### ISSUE TITLE
interface.py error 

### ISSUE THREAD

**Issue by EastwindZL** [wifiphisher/wifiphisher#823]
The latest version of Kali is used!

The following error occurred in running wifiphisher
![tim 20171207170617](https://user-images.githubusercontent.com/29472751/33707113-45afdc34-db71-11e7-8993-286c4723b8b2.jpg)

thanks!!

**Comment by anakin1028** [comment]
We'll fix it soon. It should be an known issue. Can you supply with `-iNM` first and see if tool works for you?

**Comment by EastwindZL** [comment]
Thank you very much

**Comment by anakin1028** [comment]
@EastwindZL this should be fixed for now.
