### ISSUE TITLE
Faking https connection [enhancement]

### ISSUE THREAD

**Issue by arcaniussainey** [wifiphisher/wifiphisher#832]
So tech savy people dont like to give up thier info, and they check for https. I noticed that https doesnt appear in the captive portal on chrome, so could wifiphisher have a div with this image at the top left:
![screenshot 2017-12-26 at 4 22 03 pm](https://user-images.githubusercontent.com/28377119/34364942-f960f830-ea58-11e7-842b-636ea4528553.png)
 and green https with the url at the top of the page. I have gotten it to look pretty realistic at times, and i feel is would be usefull. Should i make a pull request for it?

edit:
 it might also need the back/reload buttons, and the snazzy bar.

**Comment by arcaniussainey** [comment]
Another idea:
            if someone knows how to create adobe flash plugins.games then they can create a fake webpage combined with the fullscreen api to get a full screen interactive expierience. users could also create javascript and use it to contain several pages/nodes to change the page instead of linking.

**Comment by sophron** [comment]
We could fake the "https" box with the HTML5 fullscreen API: https://feross.org/html5-fullscreen-api-attack/

If someone implement this, I will happily merge it.

**Comment by sophron** [comment]
Web phishing techniques are no longer part of our scope (unless we bridge information from Wi-Fi). Users may use Wifiphisher in conjunction with Beef to perform these kind attacks to the connected victim stations.
