### ISSUE TITLE
Question about Phishing Scenarios

### ISSUE THREAD

**Issue by SymphonicFlute** [wifiphisher/wifiphisher#839]
Hello there, I'd like to ask about "Network Manager Connect" and Firmware Upgrade Page" scenarios.

Let's start with the former. I tried to launch the former on WEP encryption AP, and it successfully executed the command whenever I tried to surf the internet through browser (No Connection Page) but the problem arised that there was no pop-up asking to re-insert the connection password.

While for the latter (Firmware upgrade page), it did not deauth the connection automatically. I found the clone network ap on the list of available network, but my connection stills connect to the original connection rather than the fake. I had to connect manually (disconnect the original connection and then connect) to the fake connection and then the firmware upgrade page will only appeared.

Both were tried using my Android. 

Any solution to this? Thanks!

**Comment by anakin1028** [comment]
What command do you use? The two cases are only different in phishing scenarios so if the first case the victim can associate to the rogue-ap, the second case should also be ok.

If you can reproduce, you can post the monitor mode sniffer and the sniffer for the ap interface on this thread.

**Comment by anakin1028** [comment]
Also if the target ap is WPA2 encrypted it will not auto connect to our open rogue AP

**Comment by anakin1028** [comment]
@SymphonicFlute I have answered this bug in #854. You can follow the instructions on that issue to fix this problem.
