### ISSUE TITLE
No one connecting to the network

### ISSUE THREAD

**Issue by Edsam2001** [wifiphisher/wifiphisher#843]
**Version**: 1.3

**Description**: every things installed and working fine

I can see all wireless network around my self (almost 10), I have tried all of them for at least one week,
nobody connect to fake AP.

two issue was checked by myself
1-I have been connecting to fake AP, it's working great for me but no one connect or can't connect
2-I have been thinking may I'm not enough close to victim wireless network, so I have tried to be more close, just a door between us, but after many hours still no one connect to fake AP except me!!
 
what do you thinks guys, if you need any more information please let me know

**Comment by djdisikd** [comment]
Me too.

**Comment by anakin1028** [comment]
Need to verify two things:
1. Is the target AP WPA2 encrypted?
2. Also are you sure there are victims connected to the target AP?

**Comment by anakin1028** [comment]
If the victims are connected to the WPA2 encrypted target AP then it won't auto connect to our rogue AP. You can also use wireshark and post the sniffed pcap file in this thread we can help to check it.

**Comment by RedGhost99** [comment]
anakin, can you please elaborate a bit. A vast majority of endpoints are now connecting using WPA2. If WPA2 will not auto-connect to the rogue AP, what's the point? Is there a way to force them to re-connect? I am having the same problem as the OP. Fake AP is up, but nothing ever connects to it (version 1.4).

**Comment by Edsam2001** [comment]
@anakin1028 @RedGhost99 @djdisikd 

1- I have a plenty of WIFI networks , and I'm sure I tested all of the different type of encryption.
actually my interested is WPA2
2-I saw inside application how many clients is connected to the AP and then I choose which one going to be target.
as I can see deauthentication and Jamming happen many times and number of clients goes down, but they still not connect to rogue AP.

any suggestions or need any more info, I'm using Kali Linux most updated version

**Comment by Deviilo** [comment]
Need help same issue here even i have le captured handshake file if any one can help me

**Comment by anakin1028** [comment]
WPA2 will not auto connect because that we don't know the PSK of the target AP so the four way handshake will not be successful for our rouge AP unless the victims find that they are disconnected and manually connect to our rogue AP.

**Comment by anakin1028** [comment]
@RedGhost99 this an normal phenomenon, since the target AP is WPA2 there is no way to force them auto connect to our Rogue AP.

Many mall, coffee shop use OPEN AP with captive portal and wifiphisher will be good under that scenario.

**Comment by Edsam2001** [comment]
@anakin1028 , So why in the website of this project at How it Work second section they wrote:
Wifiphisher sniffs the area and copies the target access point's settings. It then creates a rogue wireless access point that is modeled by the target.
we don't even expect it connect automatically, but at least one person which disconnected should hit connect manually after one week continuously attacks. 
if it was design just working with none WPA2 encryption, there was no need to copies the target access point or either use it as wpa2 password cracker,
I think there is some things wrong here
can any body explain more please?

**Comment by Edsam2001** [comment]
@sophron / @blackHatMonkey 
do you guys have any idea about this issue?

**Comment by anakin1028** [comment]
@Edsam2001,  you can just try by yourself and use another device to manually connect to the rogueAP and see if this works for you. 

We need to copy the `ssid, channel number，...` and some basic information to craft our rogue AP. But as I said before, we don't know the password of the target AP, so we definitely cannot create an 100% similar AP. 

Wifiphisher is a tool to phish the credentials of the victims. The way it leverages is to create a rogueAP and if the victims connect to the rogueAP it then display the phishing pages by the captive portal to phish the credentials. The tool is not used to crack password but to use rogue AP to do the phishing things.

**Comment by djdisikd** [comment]
If the victim is not connected to any WiFi, can we force it to connect to our fake network?

**Comment by Edsam2001** [comment]
So with the @anakin1028 descriptions I think this tools isn't good for phishing any WPA2 WiFi network 
and useless for me , Thank you guys

**Comment by anakin1028** [comment]
Not necessarily, The tool will deauthenticate the WPA2 network and if the victims feel they are disconnected they may manually connect to the same SSID rogue AP.

**Comment by Edsam2001** [comment]
this was expected but never happened over 10 different WiFi network for one week non stop trying

**Comment by djdisikd** [comment]
Which one is better the wps-pbc phishing or the wifi password phishing?

**Comment by Edsam2001** [comment]
@djdisikd second one is better, but it seem not working

**Comment by roccomuso** [comment]
It's basically useless with WPA2. This should be pointed out on the readme file.

**Comment by sophron** [comment]
@Edsam2001, @roccomuso, @djdisikd I think you haven't understand the internals of the tool. 

There are many reasons why victims would not connect to the rogue AP: https://wifiphisher.readthedocs.io/en/latest/faq.html#why-some-victim-users-do-not-automatically-connect-to-the-rogue-access-point

We rely on Evil Twin (cloning the target network) if the target network is of Open type or the PSK is known to us. I wouldn't recommend cloning a password-protected network and waiting for the user to manually connect (even though it may happen in extreme cases). Mount other kind of attacks, such as KARMA and Known Beacons that will make victims *automatically* associate with the rogue AP. Wifiphisher supports much more than the "Evil Twin".
