### ISSUE TITLE
Lost internet connection after using wifiphisher

### ISSUE THREAD

**Issue by tooosh** [wifiphisher/wifiphisher#847]
Before opening a new issue, please make sure that what you are about to report has not been reported already. If not, use the following template for reporting.

**Version**: Use `git show | grep commit` command and paste here the output.

**Description**: Give a more analytical description here. The output of the `iw list` and `iwconfig` commands may be helpful.

**Script output**: Paste the output of the tool, including any stack traces.

**Comment by tooosh** [comment]
Please help!
Today after using wifiphisher i lost internet connection. I tried to restart networkmanager, tried puting wlan0 up,when i type nmcli m the output is eth0: unavailable and nothing else

**Comment by tooosh** [comment]
Nmcli n output: enabled

**Comment by anakin1028** [comment]
So is the internet workable for you again?

**Comment by anakin1028** [comment]
Feel free to reopen it if you have more questions.
