### ISSUE TITLE
Does Alfa AWUS 1900 supports AP mode in wifiphisher?

### ISSUE THREAD

**Issue by djdisikd** [wifiphisher/wifiphisher#849]
I tried search the web and there is no information.

**Comment by anakin1028** [comment]
Not so sure about this. Maybe you can just consult with the vendors of the adaptor.

**Comment by blackHatMonkey** [comment]
@djdisikd Based on [this](https://forums.kali.org/showthread.php?36296-EXTREME-WIFI-SUPPORT-Alfa-Networks-AWUS1900-WORKING) post it seems that it does support monitor mode. **BUT DO YOUR OWN RESEARCH**.

**Comment by djdisikd** [comment]
I have already follow the instructions in the web but still no luck

**Comment by anakin1028** [comment]
Maybe it support monitor mode only. You can use `iw phy phy0 info` to see what modes does this adaptor support.
