### ISSUE TITLE
No module named wifiphisher.common.constants

### ISSUE THREAD

**Issue by Tsadoq** [wifiphisher/wifiphisher#851]
When i launch pywifiphisher.py i have this error, i the python version is the 2.7

`Traceback (most recent call last):
  File "pywifiphisher.py", line 19, in <module>
    from wifiphisher.common.constants import *
ImportError: No module named wifiphisher.common.constants
`
Last version of Kali with everything updated && upgraded

**Comment by anakin1028** [comment]
How do you run wifiphisher? By `python bin/wifiphisher` under wifiphisher directory?
