### ISSUE TITLE
Unable to install custom pages

### ISSUE THREAD

**Issue by q0elet** [wifiphisher/wifiphisher#854]
I'm having some issues with the custom pages. I put them in the folder where there are the other "phishing portal" and i tried both launching the setup.py or not but i always have these errors:

> Starting Wifiphisher 1.4GIT ( https://wifiphisher.org ) at 2018-01-27 11:30
> Traceback (most recent call last):
>   File "wifiphisher", line 17, in <module>
>     
>   File "/root/wifiphisher/wifiphisher/pywifiphisher.py", line 616, in run
>     engine = WifiphisherEngine()
>   File "/root/wifiphisher/wifiphisher/pywifiphisher.py", line 235, in __init__
>     self.template_manager = phishingpage.TemplateManager()
>   File "/root/wifiphisher/wifiphisher/common/phishingpage.py", line 308, in __init__
>     self.add_user_templates()
>   File "/root/wifiphisher/wifiphisher/common/phishingpage.py", line 389, in add_user_templates
>     user_templates = self.find_user_templates()
>   File "/root/wifiphisher/wifiphisher/common/phishingpage.py", line 366, in find_user_templates
>     is_valid, output = self.is_valid_template(name)
>   File "/root/wifiphisher/wifiphisher/common/phishingpage.py", line 333, in is_valid_template
>     tdir = os.listdir(os.path.join(dir_path, constants.SCENARIO_HTML_DIR))
> OSError: [Errno 2] No such file or directory: '/root/wifiphisher/wifiphisher/data/phishing-pages/device-modal/html/'

WHat am I doing wrong? thx

**Comment by anakin1028** [comment]
@q0elet you can follow my changes in the following PR link:
[PR for fixing custom template issue](https://github.com/wifiphisher/extra-phishing-pages/pull/17)

The problem is we move the html files under the html directory. That is for example:
```
google-login: # orignal
   -- config.ini
   -- index.html
   -- license.txt
   -- loading.html
   -- static
changes to
google-login
   -- config.ini
   -- html # directory
       --- index.html
       --- license.txt
       --- loading.thml
       --- static
```

**Comment by q0elet** [comment]
Yeah now it works, thx

**Comment by anakin1028** [comment]
Should be ok if you pull the latest commit in extra-phishing-pages repo now.
