### ISSUE TITLE
SSL cerificates issue

### ISSUE THREAD

**Issue by Giova84** [wifiphisher/wifiphisher#856]
I setup the AP with internet access `wifiphisher -iI eth0 --essid "MyAP" -pK 1234567890`
then I setup two iptables rules, to redirect any request (of the clients connetcted to my hotspot) to a specific website (eg: if you attempts to browse any site, you will always go to this website)
```
iptables -t nat -A PREROUTING -p tcp --dport 443 -j DNAT --to-destination $IPADDRESS_OF_WEBSITE
iptables -t nat -A PREROUTING -p tcp --dport 80 -j DNAT --to-destination $IPADDRESS_OF_WEBSITE
```
Doesn't matter on which IP address I force the redirect (could also be google.com), from the clients connected to AP I always get "This Connection is Untrusted" ERR_CERTIFICATE_COMMON_NAME_INVALID.

Since everything is ok with the captive portal of wifiphisher, maybe there is something else to set? I miss something?

**Comment by Giova84** [comment]
UPDATE:

I also get "This Connection is Untrusted" ERR_CERTIFICATE_COMMON_NAME_INVALID in another circumstance, when I create the AP without internet access, but on another device, a Samsung S7 (with Android Nougat 7.0); is strange, because on a similar device (Sony Xperia X Compact with Nougat 7.1.1) I didn't get this alert from Chrome:  the Captive Portal is correctly displayed without the warning message.

**Comment by sophron** [comment]
Yes, this is how SSL and HSTS work. Have a look at #727.
