### ISSUE TITLE
Captive Portal Problem

### ISSUE THREAD

**Issue by Mikewins1** [wifiphisher/wifiphisher#858]
Everything seems to work fine..  It deauths and then is able to get handshake and then moves to captive portal.  When I use my phone to connect to the captive portal on Rouge AP I am notified that "connection is not private" and will not let me pass that screen.  It wont give me the site to type in my Creds.  I also tried my computer and 3 friends phones and each is notified that that the connection is not private  How can I get it to actually show the site to enter creds?  Should I run something else?  Please help.  IO have spent days trying...

**Comment by yasinsaeed007** [comment]
@Mikewins1 

The Access point your making its always fake and dont support SSL ..

simply try http dont use https

if your victim browsing your AP using https he will also see the same warning page..

so better hope for the best and its always http non SSL :)

**Comment by sophron** [comment]
Have a look at #727.
