### ISSUE TITLE
ImportError: No module named hostapd_build.build_files

### ISSUE THREAD

**Issue by Nik100** [wifiphisher/wifiphisher#860]
Hello!
sudo python setup.py install

  File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 250, in run_setup
    _execfile(setup_script, ns)
  File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 45, in _execfile
    exec(code, globals, locals)
  File "/tmp/easy_install-jzeW0A/roguehostapd-1.1.7/setup.py", line 9, in <module>
    from ctypes.util import find_library
ImportError: No module named hostapd_build.build_files

Can you help?

**Comment by Nik100** [comment]
OS: Kali linux for Raspberry - 2018

**Comment by anakin1028** [comment]
@sophron, I guess this issue will be solved once we upload the correct `roguehostapd` folder (including build_files folder) to pip server.

**Comment by yasinsaeed007** [comment]
Nik100 i have fixed my issue and i took me 1 week to figure out what was the issue..
follow these steps and let me know if you can post my report.

simply paste these command in terminal

> 

which flex /*Sanity check to make sure flex is installed*/
which bison /*Sanity check to make sure bison is installed*/
``

**Comment by christmex** [comment]
guys, someone can help me ... 

Traceback (most recent call last):
  File "/usr/local/bin/wifiphisher", line 11, in <module>
    load_entry_point('wifiphisher==1.4', 'console_scripts', 'wifiphisher')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 570, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2755, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2409, in load
    return self.resolve()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2415, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.4-py2.7.egg/wifiphisher/pywifiphisher.py", line 20, in <module>
    import wifiphisher.common.extensions as extensions
  File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.4-py2.7.egg/wifiphisher/common/extensions.py", line 11, in <module>
    import scapy.layers.dot11 as dot11
  File "/usr/local/lib/python2.7/dist-packages/scapy/layers/dot11.py", line 12, in <module>
    from scapy.packet import *
  File "/usr/local/lib/python2.7/dist-packages/scapy/packet.py", line 39
    class Packet(BasePacket, metaclass = Packet_metaclass):
                                       ^
SyntaxError: invalid syntax


i get the error like that.

**Comment by yasinsaeed007** [comment]
christmex please my instructions I can help you solve this issue...

simply paste these command in terminal

which flex /Sanity check to make sure flex is installed/
which bison /Sanity check to make sure bison is installed/

Please post my result.

**Comment by Nik100** [comment]
With Wifiphisher v1.3 all right, thank you, brothers)

**Comment by Nik100** [comment]
/usr/bin/flex
/usr/bin/make
/usr/bin/flex

/usr/bin/bison
/usr/bin/make
/usr/bin/bison

**Comment by yasinsaeed007** [comment]
Nik100 now do me a favor 
download 
https://github.com/thom311/libnl/releases/download/libnl3_4_0/libnl-3.4.0.tar.gz

and install it properly

 Install libnl by running the following commands:

./configure --prefix=/usr     \
            --sysconfdir=/etc \
            --disable-static  &&
make

To test the results, issue: make check.

Now, as the root user:

make install

If you wish to install the API documentation, as the root user:

mkdir -vp /usr/share/doc/libnl-3.4.0 &&
tar -xf ../libnl-doc-3.4.0.tar.gz --strip-components=1 --no-same-owner \
    -C  /usr/share/doc/libnl-3.4.0

once you done that come back with result of logs

To test the results, issue: make check.

**Comment by Nik100** [comment]
sudo ./configure --prefix=/usr --sysconfdir=/etc --disable-static && make
sudo: ./configure: command not found

what is It?

**Comment by yasinsaeed007** [comment]
extract the folder on desktop  

Open Terminal

type 

cd libnl-3.4.0

than enter
./configure --prefix=/usr
than enter this 
--sysconfdir=/etc
than enter this
--disable-static &&
than enter this :)
make

wait for loading

To test the results, issue: 

enter
make check.
enter
type sudo su
enter
make install

please let me know when you completed these steps.. since you doing wrong

**Comment by anakin1028** [comment]
@Nik100, we have updated a new version of roguehostapd.
can you do the `python setup install` again see if the install process works for you now?

**Comment by Nik100** [comment]
I did:
https://github.com/thom311/libnl/releases/download/libnl3_4_0/libnl-3.4.0.tar.gz
mkdir -vp /usr/share/doc/libnl-3.4.0 && tar -xf /home/pi/libnl-3.4.0.tar.gz --strip-components=1 --no-same-owner -C /usr/share/doc/libnl-3.4.0
cd /usr/share/doc/libnl-3.4.0/
./configure
make
make install

And all right!

See any operating system documentation about shared libraries for
more information, such as the ld(1) and ld.so(8) manual pages.
----------------------------------------------------------------------
 /bin/mkdir -p '/usr/local/etc/libnl'
 /usr/bin/install -c -m 644 etc/pktloc etc/classid '/usr/local/etc/libnl'
make[1]: Leaving directory '/usr/share/doc/libnl-3.4.0'

**Comment by yasinsaeed007** [comment]
yes you done it... now simply download https://github.com/wifiphisher/roguehostapd.git

cd Desktop
git clone https://github.com/wifiphisher/roguehostapd.git

and install it using these commands

cd roguehostapd # Switch to the roguehostapd directory
python setup.py install # Build the shared library of hostapd

when you completed the installation simply go back to wifiphisher and 

sudo python setup.py install 

and all done :)

**Comment by anakin1028** [comment]
@yasinsaeed007, thanks for your help. After resolving the dependency of netlink library, doesn't `python setup.py install` in `wifiphisher` build the `roguehostapd` automatically?

**Comment by Nik100** [comment]
https://github.com/thom311/libnl/releases/download/libnl3_4_0/libnl-3.4.0.tar.gz
mkdir -vp /usr/share/doc/libnl-3.4.0 && tar -xf /home/pi/libnl-3.4.0.tar.gz --strip-components=1 --no-same-owner -C /usr/share/doc/libnl-3.4.0
cd /usr/share/doc/libnl-3.4.0/
./configure
make
make install

git clone https://github.com/wifiphisher/wifiphisher.git
cd wifiphisher
sudo python setup.py install

And see:
Finished processing dependencies for wifiphisher==1.4


git clone https://github.com/wifiphisher/roguehostapd.git
cd roguehostapd
sudo python setup.py install
sudo python run.py -i wlan0 -ssid SOLO


And see:
Writing /usr/local/lib/python2.7/dist-packages/roguehostapd-1.1.2.egg-info

**Comment by yasinsaeed007** [comment]
@anakin1028 

thats the most common problem with this wifiphisher 1.4 you have to go through each and every files manually so did i?
this is common bug sometime it does takes things automatically and sometime it won't let you

so i hope you fix that :)

**Comment by yasinsaeed007** [comment]
@Nik100 

You don't need to run other files,,, now simply use your programm

sudo wifiphisher

in the main folder of wifiphisher :)

**Comment by Nik100** [comment]
But "sudo python run.py -i wlan0 -ssid SOLO"
python: can't open file 'run.py': [Errno 2] No such file or directory

**Comment by Nik100** [comment]
wifiphisher All right, thank you!!

**Comment by yasinsaeed007** [comment]
:) i hope it has solved your issue :)

**Comment by Nik100** [comment]
What about It?
sudo python run.py -i wlan0 -ssid SOLO
python: can't open file 'run.py': [Errno 2] No such file or directory

**Comment by anakin1028** [comment]
@Nik100 you need to `cd roguehostapd` and then run that command.

**Comment by yasinsaeed007** [comment]
@Nik100 

you said you installed roguehostapd

simply go to your wifiphisher folder

and type in wifiphisher in terminal all done

**Comment by anakin1028** [comment]
@yasinsaeed007 so do you mean even you run `python setup.py install` in wifiphisher, roguehostapd doesn't get built?

**Comment by Nik100** [comment]
Thank you))
sudo python cd roguehostapd/run.py -i wlan

All right.

**Comment by anakin1028** [comment]
@Nik100 yes! You can play with `roguehostapd` to get the feel how AP is working :)

**Comment by Nik100** [comment]
Nice)

**Comment by anakin1028** [comment]
@yasinsaeed007 from #861 the log you post, I guess indeed `python setup.py install` in wifiphisher triggers building process in roguehostapd. However we are missing a folder for the pip folder which cause the build process for roguehostapd fail.

We'll add netlink library dependency check and automatically build or interactively ask user to build this if required in the future.

Thanks for your help :)

**Comment by yasinsaeed007** [comment]
@anakin1028 
Thank you bro , i hope you guys fix these issues and and bring new update on wifiphisher :)

**Comment by anakin1028** [comment]
yeah, the `roguehostapd` has been updated so if you do `pip uninstall roguehostapd` and `pip uninstall wifiphisher` then just do `python setup.py install` in wifiphisher it should be ok to build both roguehostapd and wifiphisher.
