### ISSUE TITLE
New bugs in wifiphisher

### ISSUE THREAD

**Issue by yasinsaeed007** [wifiphisher/wifiphisher#863]
Since last fixed yesterday,

now it has new problem, when you host AP you can't just attack specified wifi , it will also host other wifi which has strong signals,whenever i host AP of victim i can also see my 2 wifis open there too,,, so its all together 3 open wifis ,, kindly suggest

**Comment by yasinsaeed007** [comment]
how to solve this issue :/

**Comment by anakin1028** [comment]
Do you mean you want to death all the Open AP?

**Comment by anakin1028** [comment]
You can use `wifiphisher -e SSID` this command will deauthenticate all the APs near by.

If you want to deauthenticate all the AP with same essid you can apply `-dE` option

**Comment by yasinsaeed007** [comment]
@anakin1028 no buddy you didn't get me,, i am saying when i am making attack on 1 person 

for example victim ABC

and my1 and my2 

so i Select the ABC and when you check the network there are 3 AP created

ABC , MY1 , MY3 

I hope you get my point

**Comment by anakin1028** [comment]
Sorry, I still don't get it from your description. The following is I try to guess the scenario you have said:

The victim is connecting to the AP: ABC
The idea case for wifiphisher is creating another fake AP with same name:ABC.

But you see one more AP created with another name?

**Comment by yasinsaeed007** [comment]
@anakin1028 exactly

I have attacked and supposed to create ABC but MY1 and MY2 other wifi in public also created with this attack which makes it bad looking and it look fishy :/

**Comment by sophron** [comment]
This is probably because your network manager has stored this network (ESSID + encryption type) more than once. Try to manually "forget" (or delete) all saved networks from your network manager's settings.

**Comment by yasinsaeed007** [comment]
I simply selected one attack ABC

and in the wifi list you will be able to see
more wifis

ABS <--
MY1 <--
MY2 <--

all open and related to same attack

**Comment by yasinsaeed007** [comment]
i even deleted them and even tried from new phone and laptop

**Comment by sophron** [comment]
Are you using the "-kB" option?

Or maybe these are related to KARMA attack. Which OS are you using?

**Comment by yasinsaeed007** [comment]
It was perfectly fine a day before yesterday, but after that little change from you guys it has started this problem, 

i am using Kali 2017.3 ...

**Comment by yasinsaeed007** [comment]
i am simply using default script --> sudo wifiphisher and it launchs everything v1,4

**Comment by sophron** [comment]
Yes, I mean from which devices are you checking the APs?

**Comment by yasinsaeed007** [comment]
Samsung, Iphone, another windows 7

all showing the same .. but using other software for attacks are fine..

**Comment by yasinsaeed007** [comment]
only wifiphisher has landed me to these bugs

**Comment by sophron** [comment]
Only your devices (that have connected to these networks) are seeing these networks. The other victim devices may also see not these specific networks but other networks they have associated with in the past.

Read more about the KARMA attack: https://insights.sei.cmu.edu/cert/2015/08/instant-karma-might-still-get-you.html

It is not a bug. It is a feature.

We don't currently have an option for turning it off (as we can't imagine many reasons for it) but we may introduce a switch in the future.

**Comment by yasinsaeed007** [comment]
ok i got it,, you can make some amendments to get rid of this feature since there are other attacking softwares which has this option removed or never exist, i extremly like wifiphisher i hope in next update we get more to see anyway thank you so much for helping me out,, i will close the case :)

**Comment by sophron** [comment]
This is a feature for getting more victims connected to the rogue AP. So if a client looks for ‘ABS’, it is ‘ABS’ to them (even while it may be ‘MY1’ to someone else).

**Comment by yasinsaeed007** [comment]
I understood ... i didnt see this feature before in your script, but since yesterday it has started appear, seem more legit to stalk on wifi, plus if that karma attack it will connect victim wifi automatically :)

Thank you so much for being so helpful,
