### ISSUE TITLE
Create custom phising scenario

### ISSUE THREAD

**Issue by christmex** [wifiphisher/wifiphisher#866]
Hi evryone, i need your help , i want to create costume phising scenario, how ?? . please help me.

**Comment by anakin1028** [comment]
Hi, you can put the custom scenario in the following directory:

wifiphisher/data/phishing-pages

**Comment by christmex** [comment]
yeah thanks dude, but i mean i want to create a costume scenario phising for specific target .

**Comment by anakin1028** [comment]
Hi please see the below instructions:

https://github.com/wifiphisher/extra-phishing-pages/blob/master/README.md

**Comment by christmex** [comment]
thanks anakin, and now, how to step by step to create a scenario, i have create ,but cant work . thanks for your attention

**Comment by Likgn07** [comment]
I want to change the text ' The wifi network "afjdjd" requires a WPA2 password.' to another letter how to do?

**Comment by sophron** [comment]
An updated guide on custom phishing scenario creation lies here: http://wifiphisher.readthedocs.io/en/latest/custom_phishing_scenario.html
