### ISSUE TITLE
after i updated my kali machine wifiphisher not working.

### ISSUE THREAD

**Issue by robertcanare** [wifiphisher/wifiphisher#867]
Before opening a new issue, please make sure that what you are about to report has not been reported already. If not, use the following template for reporting.

**Version**: Use `git show | grep commit` command and paste here the output.

**Description**: Give a more analytical description here. The output of the `iw list` and `iwconfig` commands may be helpful.
![screenshot from 2018-02-19 14-53-43](https://user-images.githubusercontent.com/33864725/36365603-3911122e-1585-11e8-8732-1b371d1dcee8.png)

**Script output**: Paste the output of the tool, including any stack traces.

**Comment by anakin1028** [comment]
Can you try the command below:
`sudo apt-get install python-dbus`?

**Comment by robertcanare** [comment]
sudo apt-get install python-dbus is not working even sudo apt-get remove python-dbus and install it again, but i try to download python-dbus from .deb file and install it now its working
