### ISSUE TITLE
PBKDF2 IMPORT ERROR

### ISSUE THREAD

**Issue by Gamerxxgp** [wifiphisher/wifiphisher#869]
Hi there am here to report a problem about pbkdf2 srry am pretty much new here 
i ve been trying to use wifiphisher but seems like i have a problem with pbkdf2 
i have already installed pbkdf2 i upgraded my dist to make sure i have all set up to date but it didnt work here is what i get when i execute wifiphisher with root 
<html>
<body>
<code> wifiphisher -e idk
Traceback (most recent call last):
  File "/usr/local/bin/wifiphisher", line 11, in <module>
    load_entry_point('wifiphisher==1.4', 'console_scripts', 'wifiphisher')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 572, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2755, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2408, in load
    return self.resolve()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2414, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.4-py2.7.egg/wifiphisher/pywifiphisher.py", line 29, in <module>
    import wifiphisher.common.opmode as opmode
  File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.4-py2.7.egg/wifiphisher/common/opmode.py", line 14, in <module>
    import wifiphisher.extensions.handshakeverify as handshakeverify
  File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.4-py2.7.egg/wifiphisher/extensions/handshakeverify.py", line 13, in <module>
    from pbkdf2 import PBKDF2
ImportError: cannot import name PBKDF2  </code>
</body>
</html>

Hope someone can help 
Will be waiting to hear further from you

**Comment by JetseVerschuren** [comment]
Have you installed wifiphisher using pip?

**Comment by Gamerxxgp** [comment]
@JetseVerschuren 
i followed the instructions in the package and used "python setup.py install"

**Comment by JetseVerschuren** [comment]
Can you post the output of the setup script?

**Comment by Gamerxxgp** [comment]
@JetseVerschuren 
<html>
<body>
<pre>running install
running bdist_egg
running egg_info
writing requirements to wifiphisher.egg-info/requires.txt
writing wifiphisher.egg-info/PKG-INFO
writing top-level names to wifiphisher.egg-info/top_level.txt
writing dependency_links to wifiphisher.egg-info/dependency_links.txt
writing entry points to wifiphisher.egg-info/entry_points.txt
reading manifest file &apos;wifiphisher.egg-info/SOURCES.txt&apos;
reading manifest template &apos;MANIFEST.in&apos;
writing manifest file &apos;wifiphisher.egg-info/SOURCES.txt&apos;
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/wifiphisher
creating build/bdist.linux-x86_64/egg/wifiphisher/extensions
copying build/lib.linux-x86_64-2.7/wifiphisher/extensions/wpspbc.py -&gt; build/bdist.linux-x86_64/egg/wifiphisher/extensions
copying build/lib.linux-x86_64-2.7/wifiphisher/extensions/knownbeacons.py -&gt; build/bdist.linux-x86_64/egg/wifiphisher/extensions
copying build/lib.linux-x86_64-2.7/wifiphisher/extensions/__init__.py -&gt; build/bdist.linux-x86_64/egg/wifiphisher/extensions
copying build/lib.linux-x86_64-2.7/wifiphisher/extensions/lure10.py -&gt; build/bdist.linux-x86_64/egg/wifiphisher/extensions
copying build/lib.linux-x86_64-2.7/wifiphisher/extensions/handshakeverify.py -&gt; build/bdist.linux-x86_64/egg/wifiphisher/extensions
copying build/lib.linux-x86_64-2.7/wifiphisher/extensions/deauth.py -&gt; build/bdist.linux-x86_64/egg/wifiphisher/extensions
copying build/lib.linux-x86_64-2.7/wifiphisher/__init__.py -&gt; build/bdist.linux-x86_64/egg/wifiphisher
creating build/bdist.linux-x86_64/egg/wifiphisher/data
copying build/lib.linux-x86_64-2.7/wifiphisher/data/wifiphisher-known-open-wlans -&gt; build/bdist.linux-x86_64/egg/wifiphisher/data
creating build/bdist.linux-x86_64/egg/wifiphisher/data/cert
copying build/lib.linux-x86_64-2.7/wifiphisher/data/cert/server.pem -&gt; build/bdist.linux-x86_64/egg/wifiphisher/data/cert
creating build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages
creating build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/firmware-upgrade
copying build/lib.linux-x86_64-2.7/wifiphisher/data/phishing-pages/firmware-upgrade/config.ini -&gt; build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/firmware-upgrade
creating build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/firmware-upgrade/html
copying build/lib.linux-x86_64-2.7/wifiphisher/data/phishing-pages/firmware-upgrade/html/loading.html -&gt; build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/firmware-upgrade/html
copying build/lib.linux-x86_64-2.7/wifiphisher/data/phishing-pages/firmware-upgrade/html/upgrading.html -&gt; build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/firmware-upgrade/html
creating build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/firmware-upgrade/html/static
creating build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/firmware-upgrade/html/static/font-awesome-4.7.0
creating build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/firmware-upgrade/html/static/font-awesome-4.7.0/css
copying build/lib.linux-x86_64-2.7/wifiphisher/data/phishing-pages/firmware-upgrade/html/static/font-awesome-4.7.0/css/font-awesome.css -&gt; build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/firmware-upgrade/html/static/font-awesome-4.7.0/css
copying build/lib.linux-x86_64-2.7/wifiphisher/data/phishing-pages/firmware-upgrade/html/static/font-awesome-4.7.0/css/font-awesome.min.css -&gt; build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/firmware-upgrade/html/static/font-awesome-4.7.0/css
creating build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/firmware-upgrade/html/static/font-awesome-4.7.0/fonts
copying build/lib.linux-x86_64-2.7/wifiphisher/data/phishing-pages/firmware-upgrade/html/static/font-awesome-4.7.0/fonts/fontawesome-webfont.svg -&gt; build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/firmware-upgrade/html/static/font-awesome-4.7.0/fonts
copying build/lib.linux-x86_64-2.7/wifiphisher/data/phishing-pages/firmware-upgrade/html/static/font-awesome-4.7.0/fonts/fontawesome-webfont.ttf -&gt; build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/firmware-upgrade/html/static/font-awesome-4.7.0/fonts
copying build/lib.linux-x86_64-2.7/wifiphisher/data/phishing-pages/firmware-upgrade/html/static/font-awesome-4.7.0/fonts/fontawesome-webfont.woff2 -&gt; build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/firmware-upgrade/html/static/font-awesome-4.7.0/fonts
copying build/lib.linux-x86_64-2.7/wifiphisher/data/phishing-pages/firmware-upgrade/html/static/font-awesome-4.7.0/fonts/fontawesome-webfont.woff -&gt; build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/firmware-upgrade/html/static/font-awesome-4.7.0/fonts
copying build/lib.linux-x86_64-2.7/wifiphisher/data/phishing-pages/firmware-upgrade/html/static/font-awesome-4.7.0/fonts/fontawesome-webfont.eot -&gt; build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/firmware-upgrade/html/static/font-awesome-4.7.0/fonts
copying build/lib.linux-x86_64-2.7/wifiphisher/data/phishing-pages/firmware-upgrade/html/static/font-awesome-4.7.0/fonts/FontAwesome.otf -&gt; build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/firmware-upgrade/html/static/font-awesome-4.7.0/fonts
copying build/lib.linux-x86_64-2.7/wifiphisher/data/phishing-pages/firmware-upgrade/html/static/bootstrap.min.js -&gt; build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/firmware-upgrade/html/static
copying build/lib.linux-x86_64-2.7/wifiphisher/data/phishing-pages/firmware-upgrade/html/static/jquery.min.js -&gt; build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/firmware-upgrade/html/static
copying build/lib.linux-x86_64-2.7/wifiphisher/data/phishing-pages/firmware-upgrade/html/static/bootstrap.min.css -&gt; build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/firmware-upgrade/html/static
copying build/lib.linux-x86_64-2.7/wifiphisher/data/phishing-pages/firmware-upgrade/html/bootstrap.min.js -&gt; build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/firmware-upgrade/html
copying build/lib.linux-x86_64-2.7/wifiphisher/data/phishing-pages/firmware-upgrade/html/index.html -&gt; build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/firmware-upgrade/html
copying build/lib.linux-x86_64-2.7/wifiphisher/data/phishing-pages/firmware-upgrade/html/jquery.min.js -&gt; build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/firmware-upgrade/html
copying build/lib.linux-x86_64-2.7/wifiphisher/data/phishing-pages/firmware-upgrade/html/bootstrap.min.css -&gt; build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/firmware-upgrade/html
creating build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/plugin_update
copying build/lib.linux-x86_64-2.7/wifiphisher/data/phishing-pages/plugin_update/config.ini -&gt; build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/plugin_update
creating build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/plugin_update/html
creating build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/plugin_update/html/static
creating build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/plugin_update/html/static/js
copying build/lib.linux-x86_64-2.7/wifiphisher/data/phishing-pages/plugin_update/html/static/js/jquery.js -&gt; build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/plugin_update/html/static/js
copying build/lib.linux-x86_64-2.7/wifiphisher/data/phishing-pages/plugin_update/html/static/js/bootstrap.min.js -&gt; build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/plugin_update/html/static/js
creating build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/plugin_update/html/static/images
copying build/lib.linux-x86_64-2.7/wifiphisher/data/phishing-pages/plugin_update/html/static/images/favicon.ico -&gt; build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/plugin_update/html/static/images
copying build/lib.linux-x86_64-2.7/wifiphisher/data/phishing-pages/plugin_update/html/static/images/plugins.png -&gt; build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/plugin_update/html/static/images
creating build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/plugin_update/html/static/update
copying build/lib.linux-x86_64-2.7/wifiphisher/data/phishing-pages/plugin_update/html/static/update/update.exe -&gt; build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/plugin_update/html/static/update
creating build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/plugin_update/html/static/css
copying build/lib.linux-x86_64-2.7/wifiphisher/data/phishing-pages/plugin_update/html/static/css/theme.css -&gt; build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/plugin_update/html/static/css
copying build/lib.linux-x86_64-2.7/wifiphisher/data/phishing-pages/plugin_update/html/static/css/bootstrap.min.css -&gt; build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/plugin_update/html/static/css
creating build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/plugin_update/html/js
copying build/lib.linux-x86_64-2.7/wifiphisher/data/phishing-pages/plugin_update/html/js/jquery.js -&gt; build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/plugin_update/html/js
copying build/lib.linux-x86_64-2.7/wifiphisher/data/phishing-pages/plugin_update/html/js/bootstrap.min.js -&gt; build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/plugin_update/html/js
creating build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/plugin_update/html/images
copying build/lib.linux-x86_64-2.7/wifiphisher/data/phishing-pages/plugin_update/html/images/favicon.ico -&gt; build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/plugin_update/html/images
copying build/lib.linux-x86_64-2.7/wifiphisher/data/phishing-pages/plugin_update/html/images/plugins.png -&gt; build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/plugin_update/html/images
creating build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/plugin_update/html/update
copying build/lib.linux-x86_64-2.7/wifiphisher/data/phishing-pages/plugin_update/html/update/update.exe -&gt; build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/plugin_update/html/update
creating build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/plugin_update/html/css
copying build/lib.linux-x86_64-2.7/wifiphisher/data/phishing-pages/plugin_update/html/css/theme.css -&gt; build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/plugin_update/html/css
copying build/lib.linux-x86_64-2.7/wifiphisher/data/phishing-pages/plugin_update/html/css/bootstrap.min.css -&gt; build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/plugin_update/html/css
copying build/lib.linux-x86_64-2.7/wifiphisher/data/phishing-pages/plugin_update/html/index.html -&gt; build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/plugin_update/html
creating build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/wifi_connect
copying build/lib.linux-x86_64-2.7/wifiphisher/data/phishing-pages/wifi_connect/config.ini -&gt; build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/wifi_connect
creating build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/wifi_connect/html
copying build/lib.linux-x86_64-2.7/wifiphisher/data/phishing-pages/wifi_connect/html/dinosaur.png -&gt; build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/wifi_connect/html
copying build/lib.linux-x86_64-2.7/wifiphisher/data/phishing-pages/wifi_connect/html/question.png -&gt; build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/wifi_connect/html
copying build/lib.linux-x86_64-2.7/wifiphisher/data/phishing-pages/wifi_connect/html/opensans.ttf -&gt; build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/wifi_connect/html
copying build/lib.linux-x86_64-2.7/wifiphisher/data/phishing-pages/wifi_connect/html/loading.html -&gt; build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/wifi_connect/html
copying build/lib.linux-x86_64-2.7/wifiphisher/data/phishing-pages/wifi_connect/html/opensans.css -&gt; build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/wifi_connect/html
copying build/lib.linux-x86_64-2.7/wifiphisher/data/phishing-pages/wifi_connect/html/mac-network-manager.css -&gt; build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/wifi_connect/html
creating build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/wifi_connect/html/static
copying build/lib.linux-x86_64-2.7/wifiphisher/data/phishing-pages/wifi_connect/html/static/dinosaur.png -&gt; build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/wifi_connect/html/static
copying build/lib.linux-x86_64-2.7/wifiphisher/data/phishing-pages/wifi_connect/html/static/question.png -&gt; build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/wifi_connect/html/static
copying build/lib.linux-x86_64-2.7/wifiphisher/data/phishing-pages/wifi_connect/html/static/opensans.ttf -&gt; build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/wifi_connect/html/static
copying build/lib.linux-x86_64-2.7/wifiphisher/data/phishing-pages/wifi_connect/html/static/opensans.css -&gt; build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/wifi_connect/html/static
copying build/lib.linux-x86_64-2.7/wifiphisher/data/phishing-pages/wifi_connect/html/static/mac-network-manager.css -&gt; build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/wifi_connect/html/static
copying build/lib.linux-x86_64-2.7/wifiphisher/data/phishing-pages/wifi_connect/html/static/wifi-icon.png -&gt; build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/wifi_connect/html/static
copying build/lib.linux-x86_64-2.7/wifiphisher/data/phishing-pages/wifi_connect/html/static/style.css -&gt; build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/wifi_connect/html/static
copying build/lib.linux-x86_64-2.7/wifiphisher/data/phishing-pages/wifi_connect/html/static/win-behavior.js -&gt; build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/wifi_connect/html/static
copying build/lib.linux-x86_64-2.7/wifiphisher/data/phishing-pages/wifi_connect/html/static/chrome-offline.css -&gt; build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/wifi_connect/html/static
copying build/lib.linux-x86_64-2.7/wifiphisher/data/phishing-pages/wifi_connect/html/static/behavior.js -&gt; build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/wifi_connect/html/static
copying build/lib.linux-x86_64-2.7/wifiphisher/data/phishing-pages/wifi_connect/html/wifi-icon.png -&gt; build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/wifi_connect/html
copying build/lib.linux-x86_64-2.7/wifiphisher/data/phishing-pages/wifi_connect/html/style.css -&gt; build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/wifi_connect/html
copying build/lib.linux-x86_64-2.7/wifiphisher/data/phishing-pages/wifi_connect/html/win-behavior.js -&gt; build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/wifi_connect/html
copying build/lib.linux-x86_64-2.7/wifiphisher/data/phishing-pages/wifi_connect/html/index.html -&gt; build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/wifi_connect/html
copying build/lib.linux-x86_64-2.7/wifiphisher/data/phishing-pages/wifi_connect/html/chrome-offline.css -&gt; build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/wifi_connect/html
copying build/lib.linux-x86_64-2.7/wifiphisher/data/phishing-pages/wifi_connect/html/behavior.js -&gt; build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/wifi_connect/html
creating build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/oauth-login
copying build/lib.linux-x86_64-2.7/wifiphisher/data/phishing-pages/oauth-login/config.ini -&gt; build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/oauth-login
creating build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/oauth-login/html
copying build/lib.linux-x86_64-2.7/wifiphisher/data/phishing-pages/oauth-login/html/oauth.html -&gt; build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/oauth-login/html
copying build/lib.linux-x86_64-2.7/wifiphisher/data/phishing-pages/oauth-login/html/license.txt -&gt; build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/oauth-login/html
creating build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/oauth-login/html/static
creating build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/oauth-login/html/static/js
copying build/lib.linux-x86_64-2.7/wifiphisher/data/phishing-pages/oauth-login/html/static/js/index.js -&gt; build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/oauth-login/html/static/js
copying build/lib.linux-x86_64-2.7/wifiphisher/data/phishing-pages/oauth-login/html/static/js/jquery.min.js -&gt; build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/oauth-login/html/static/js
creating build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/oauth-login/html/static/css
copying build/lib.linux-x86_64-2.7/wifiphisher/data/phishing-pages/oauth-login/html/static/css/font-awesome.min.css -&gt; build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/oauth-login/html/static/css
copying build/lib.linux-x86_64-2.7/wifiphisher/data/phishing-pages/oauth-login/html/static/css/roboto.css -&gt; build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/oauth-login/html/static/css
copying build/lib.linux-x86_64-2.7/wifiphisher/data/phishing-pages/oauth-login/html/static/css/reset.css -&gt; build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/oauth-login/html/static/css
copying build/lib.linux-x86_64-2.7/wifiphisher/data/phishing-pages/oauth-login/html/static/css/style.css -&gt; build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/oauth-login/html/static/css
creating build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/oauth-login/html/js
copying build/lib.linux-x86_64-2.7/wifiphisher/data/phishing-pages/oauth-login/html/js/index.js -&gt; build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/oauth-login/html/js
copying build/lib.linux-x86_64-2.7/wifiphisher/data/phishing-pages/oauth-login/html/js/jquery.min.js -&gt; build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/oauth-login/html/js
creating build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/oauth-login/html/css
copying build/lib.linux-x86_64-2.7/wifiphisher/data/phishing-pages/oauth-login/html/css/font-awesome.min.css -&gt; build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/oauth-login/html/css
copying build/lib.linux-x86_64-2.7/wifiphisher/data/phishing-pages/oauth-login/html/css/roboto.css -&gt; build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/oauth-login/html/css
copying build/lib.linux-x86_64-2.7/wifiphisher/data/phishing-pages/oauth-login/html/css/reset.css -&gt; build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/oauth-login/html/css
copying build/lib.linux-x86_64-2.7/wifiphisher/data/phishing-pages/oauth-login/html/css/style.css -&gt; build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/oauth-login/html/css
copying build/lib.linux-x86_64-2.7/wifiphisher/data/phishing-pages/oauth-login/html/index.html -&gt; build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/oauth-login/html
copying build/lib.linux-x86_64-2.7/wifiphisher/data/wifiphisher-mac-prefixes -&gt; build/bdist.linux-x86_64/egg/wifiphisher/data
creating build/bdist.linux-x86_64/egg/wifiphisher/data/locs
copying build/lib.linux-x86_64-2.7/wifiphisher/data/locs/.gitkeep -&gt; build/bdist.linux-x86_64/egg/wifiphisher/data/locs
creating build/bdist.linux-x86_64/egg/wifiphisher/common
copying build/lib.linux-x86_64-2.7/wifiphisher/common/constants.py -&gt; build/bdist.linux-x86_64/egg/wifiphisher/common
copying build/lib.linux-x86_64-2.7/wifiphisher/common/phishingpage.py -&gt; build/bdist.linux-x86_64/egg/wifiphisher/common
copying build/lib.linux-x86_64-2.7/wifiphisher/common/accesspoint.py -&gt; build/bdist.linux-x86_64/egg/wifiphisher/common
copying build/lib.linux-x86_64-2.7/wifiphisher/common/extensions.py -&gt; build/bdist.linux-x86_64/egg/wifiphisher/common
copying build/lib.linux-x86_64-2.7/wifiphisher/common/uimethods.py -&gt; build/bdist.linux-x86_64/egg/wifiphisher/common
copying build/lib.linux-x86_64-2.7/wifiphisher/common/tui.py -&gt; build/bdist.linux-x86_64/egg/wifiphisher/common
copying build/lib.linux-x86_64-2.7/wifiphisher/common/interfaces.py -&gt; build/bdist.linux-x86_64/egg/wifiphisher/common
copying build/lib.linux-x86_64-2.7/wifiphisher/common/phishinghttp.py -&gt; build/bdist.linux-x86_64/egg/wifiphisher/common
copying build/lib.linux-x86_64-2.7/wifiphisher/common/recon.py -&gt; build/bdist.linux-x86_64/egg/wifiphisher/common
copying build/lib.linux-x86_64-2.7/wifiphisher/common/firewall.py -&gt; build/bdist.linux-x86_64/egg/wifiphisher/common
copying build/lib.linux-x86_64-2.7/wifiphisher/common/__init__.py -&gt; build/bdist.linux-x86_64/egg/wifiphisher/common
copying build/lib.linux-x86_64-2.7/wifiphisher/common/macmatcher.py -&gt; build/bdist.linux-x86_64/egg/wifiphisher/common
copying build/lib.linux-x86_64-2.7/wifiphisher/common/opmode.py -&gt; build/bdist.linux-x86_64/egg/wifiphisher/common
copying build/lib.linux-x86_64-2.7/wifiphisher/pywifiphisher.py -&gt; build/bdist.linux-x86_64/egg/wifiphisher
byte-compiling build/bdist.linux-x86_64/egg/wifiphisher/extensions/wpspbc.py to wpspbc.pyc
byte-compiling build/bdist.linux-x86_64/egg/wifiphisher/extensions/knownbeacons.py to knownbeacons.pyc
byte-compiling build/bdist.linux-x86_64/egg/wifiphisher/extensions/__init__.py to __init__.pyc
byte-compiling build/bdist.linux-x86_64/egg/wifiphisher/extensions/lure10.py to lure10.pyc
byte-compiling build/bdist.linux-x86_64/egg/wifiphisher/extensions/handshakeverify.py to handshakeverify.pyc
byte-compiling build/bdist.linux-x86_64/egg/wifiphisher/extensions/deauth.py to deauth.pyc
byte-compiling build/bdist.linux-x86_64/egg/wifiphisher/__init__.py to __init__.pyc
byte-compiling build/bdist.linux-x86_64/egg/wifiphisher/common/constants.py to constants.pyc
byte-compiling build/bdist.linux-x86_64/egg/wifiphisher/common/phishingpage.py to phishingpage.pyc
byte-compiling build/bdist.linux-x86_64/egg/wifiphisher/common/accesspoint.py to accesspoint.pyc
byte-compiling build/bdist.linux-x86_64/egg/wifiphisher/common/extensions.py to extensions.pyc
byte-compiling build/bdist.linux-x86_64/egg/wifiphisher/common/uimethods.py to uimethods.pyc
byte-compiling build/bdist.linux-x86_64/egg/wifiphisher/common/tui.py to tui.pyc
byte-compiling build/bdist.linux-x86_64/egg/wifiphisher/common/interfaces.py to interfaces.pyc
byte-compiling build/bdist.linux-x86_64/egg/wifiphisher/common/phishinghttp.py to phishinghttp.pyc
byte-compiling build/bdist.linux-x86_64/egg/wifiphisher/common/recon.py to recon.pyc
byte-compiling build/bdist.linux-x86_64/egg/wifiphisher/common/firewall.py to firewall.pyc
byte-compiling build/bdist.linux-x86_64/egg/wifiphisher/common/__init__.py to __init__.pyc
byte-compiling build/bdist.linux-x86_64/egg/wifiphisher/common/macmatcher.py to macmatcher.pyc
byte-compiling build/bdist.linux-x86_64/egg/wifiphisher/common/opmode.py to opmode.pyc
byte-compiling build/bdist.linux-x86_64/egg/wifiphisher/pywifiphisher.py to pywifiphisher.pyc
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying wifiphisher.egg-info/PKG-INFO -&gt; build/bdist.linux-x86_64/egg/EGG-INFO
copying wifiphisher.egg-info/SOURCES.txt -&gt; build/bdist.linux-x86_64/egg/EGG-INFO
copying wifiphisher.egg-info/dependency_links.txt -&gt; build/bdist.linux-x86_64/egg/EGG-INFO
copying wifiphisher.egg-info/entry_points.txt -&gt; build/bdist.linux-x86_64/egg/EGG-INFO
copying wifiphisher.egg-info/requires.txt -&gt; build/bdist.linux-x86_64/egg/EGG-INFO
copying wifiphisher.egg-info/top_level.txt -&gt; build/bdist.linux-x86_64/egg/EGG-INFO
zip_safe flag not set; analyzing archive contents...
wifiphisher.common.constants: module references __file__
creating &apos;dist/wifiphisher-1.4-py2.7.egg&apos; and adding &apos;build/bdist.linux-x86_64/egg&apos; to it
removing &apos;build/bdist.linux-x86_64/egg&apos; (and everything under it)
Processing wifiphisher-1.4-py2.7.egg
removing &apos;/usr/local/lib/python2.7/dist-packages/wifiphisher-1.4-py2.7.egg&apos; (and everything under it)
creating /usr/local/lib/python2.7/dist-packages/wifiphisher-1.4-py2.7.egg
Extracting wifiphisher-1.4-py2.7.egg to /usr/local/lib/python2.7/dist-packages
wifiphisher 1.4 is already the active version in easy-install.pth
Installing wifiphisher script to /usr/local/bin

Installed /usr/local/lib/python2.7/dist-packages/wifiphisher-1.4-py2.7.egg
Processing dependencies for wifiphisher==1.4
Searching for tornado==4.5.3
Best match: tornado 4.5.3
Adding tornado 4.5.3 to easy-install.pth file

Using /usr/lib/python2.7/dist-packages
Searching for scapy==2.3.3
Best match: scapy 2.3.3
Adding scapy 2.3.3 to easy-install.pth file

Using /usr/lib/python2.7/dist-packages
Searching for roguehostapd==1.1.2
Best match: roguehostapd 1.1.2
Adding roguehostapd 1.1.2 to easy-install.pth file

Using /usr/local/lib/python2.7/dist-packages
Searching for pbkdf2==1.3
Best match: pbkdf2 1.3
Adding pbkdf2 1.3 to easy-install.pth file

Using /usr/lib/python2.7/dist-packages
Searching for dbus-python==1.2.4
Best match: dbus-python 1.2.4
Processing dbus_python-1.2.4-py2.7-linux-x86_64.egg
dbus-python 1.2.4 is already the active version in easy-install.pth

Using /usr/local/lib/python2.7/dist-packages/dbus_python-1.2.4-py2.7-linux-x86_64.egg
Searching for PyRIC==0.1.6.3
Best match: PyRIC 0.1.6.3
Processing PyRIC-0.1.6.3-py2.7.egg
PyRIC 0.1.6.3 is already the active version in easy-install.pth

Using /usr/local/lib/python2.7/dist-packages/PyRIC-0.1.6.3-py2.7.egg
Finished processing dependencies for wifiphisher==1.4
                                                               
</pre>
</code>
</html>

**Comment by anakin1028** [comment]
@Gamerxxgp can you try the following:

```
pip uninstall pbkdf2
pip install pbkdf2
#then run wifiphisher again
```

**Comment by Gamerxxgp** [comment]
@anakin1028 
<html>
<body>
This what i get when i execute that command
<br>
<code>
root@kali:~# pip uninstall pbkdf2
Not uninstalling pbkdf2 at /usr/lib/python2.7/dist-packages, outside environment /usr
</code>
</body>
</html>

**Comment by Gamerxxgp** [comment]
<html>
<body>
After thinking for long in this problem 
<br>
I finally solved it. The prob was in my pip 
<code> 
<pre>pip install --upgrade pip==8.1.2</pre>
<pre>pip install --upgrade pip</pre>
</code>
And then i tried again
<code>
<pre>pip uninstall pbkdf2</pre>
<pre>pip install  pbkdf2</pre>
</code>
I think am facing a different prob now XD
<br>
Thanks for helping everyone :D
</body>
</html>

**Comment by anakin1028** [comment]
Sure. Feel free to open new issues if you have other problems with tool.

**Comment by eskahacker** [comment]
please help me to solve this:
https://github.com/wifiphisher/wifiphisher/issues/1583
