### ISSUE TITLE
qS function working but not perfect.

### ISSUE THREAD

**Issue by namnntt** [wifiphisher/wifiphisher#876]
I see -qS function working in code. But a login session with the wrong password also causes the evil twin AP to stop. 
So the trap will not perfect. 
Thanks you.

**Comment by anakin1028** [comment]
If you are using firmware upgrade scenario, you may give a pre-captured fourway handshake pcap file, then tool will do the sanity check.

**Comment by anakin1028** [comment]
@namnntt If you have more suggestions feel free to reopen new issues :) So far we have an enhancement with -hC argument to address this issue.
