### ISSUE TITLE
Rogue AP 5 GHz 

### ISSUE THREAD

**Issue by cento789** [wifiphisher/wifiphisher#878]
Hi guys, I have a problem.. I notice that the jamming against the 2.4 GHz channel is so very good, in fact my devices get disconnected, but the 5 GHz still running very well.. How can I jamming to the 5 GHz?

**Comment by blackHatMonkey** [comment]
@cento789 as of yet we don't have any support for 5GHz. That might change in the future :smile:.

**Comment by cento789** [comment]
Ok thank you for your reply. I just wanted to be sure that it wasn't supported
