### ISSUE TITLE
installation error

### ISSUE THREAD

**Issue by Chandel19** [wifiphisher/wifiphisher#879]
![screenshot-20180302230228-658x121](https://user-images.githubusercontent.com/34957448/36913042-a8615ae8-1e6e-11e8-958f-035f1b6df34f.png)

**Comment by JetseVerschuren** [comment]
Try `pip install setuptools`

**Comment by Chandel19** [comment]
![screenshot-20180303115414-769x68](https://user-images.githubusercontent.com/34957448/36931347-cf106e5c-1ed9-11e8-95dd-4c3a81ec0ae6.png)

**Comment by JetseVerschuren** [comment]
And if you use apt `apt-get install -y python-setuptools`?

**Comment by MasterJi24** [comment]
How to fix

"TypeError: 'NoneType' object is not iterable"

when i start to boot in wifiphisher

**Comment by JetseVerschuren** [comment]
@MasterJi24 Please open a new issue

**Comment by anakin1028** [comment]
@MasterJi24 can you open a new issue as @JetseVerschuren suggest and post the full stderr on that thread?
