### ISSUE TITLE
Kali not loading correctly after wifiphisher installation

### ISSUE THREAD

**Issue by crueltyguy** [wifiphisher/wifiphisher#881]
Hi,

I now installed wifiphisher 1.4 on kali usb portable.
when i restarted the system, it does not load properly, and show me:
"wlan0 failed to set tx queue parameters"

no GUI/UI is loaded, i can hit Enter and run shell commands only.

any advice before I install the system again...?

thanks.

**Comment by anakin1028** [comment]
can you show the stdout for us? What's the output on your terminal?

**Comment by crueltyguy** [comment]
already reinstalled kali.. problem is i am afraid to use wifiphisher now.
________________________________

**Comment by crueltyguy** [comment]
yeah sure i'll try. i'll post when happens, thanks!
________________________________
