### ISSUE TITLE
Android system internet may not be available. 

### ISSUE THREAD

**Issue by zerocolTHS** [wifiphisher/wifiphisher#888]
Not sure if this has been asked before i couldn't find anything, but how can i fix this issue saying no internet.  
I tried adding internet interface but then the portal is skipped. 
Command used
`wifiphisher --noextensions --essid "Starbucks" -p oauth-login -kB`

![29433049_1896487613725631_8241197137489035264_o](https://user-images.githubusercontent.com/9049886/37727602-2d67911a-2d30-11e8-9f95-9d92c23a483c.png)

**Comment by sophron** [comment]
The "Internet may not be available" is shown by Android only after you have connected to the network at least once.

Why does it bother you? A typical captive portal with OAuth would behave the same way.

**Comment by zerocolTHS** [comment]
It doesn't really bother me as such, it makes me think people would disconnect after seeing that and not even see the oauth login page. 
Thank's for the quick response.

**Comment by sophron** [comment]
It's not possible to avoid this message when deploying a captive portal. 

#739 will eventually solve this.
