### ISSUE TITLE
Incorrect SSID shown in phishing page when KARMA attack is lunched

### ISSUE THREAD

**Issue by anakin1028** [wifiphisher/wifiphisher#889]
Wifiphisher now equips with KARMA attack! There is an issue with the current phishing page information with KARMA attack. That is we assume the users will only connect to the ESSID either by `-e SSID` or the ESSID selected in `ap selection curses section`.

This is the wrong assumption when victims are getting connected to our rogue AP by KARMA attack since the SSID user want to connect may be different with our rogue AP. The following is the snap shot from my MAC book:
<img width="898" alt="2018-03-23 10 26 49" src="https://user-images.githubusercontent.com/6182530/37835003-18ec4ca6-2eea-11e8-8ea2-213d0e6551fc.png">

The user intends to connect with `SSID: dlink (加入dlink which means to connect to SSID dlink)` but our phishing page shows `CHT Wi-Fi Auto`. This is because I select `CHT Wi-Fi Auto` in AP selection stage.

The quick way to solve this is to remove the SSID and Brand of AP information on the phishing page. Any good ideas are also welcome!

**Comment by sophron** [comment]
The best solution is to get the ESSID that the victim station is looking for and use it when rendering the page. 

The ESSID of the victim station is a useful information either way. In wireless pentests, the client may need that information as part of the reporting process. We should store it somewhere along with all victim's information (#835).
