### ISSUE TITLE
Install roguehostapd automatically instead of installing it manually

### ISSUE THREAD

**Issue by djdisikd** [wifiphisher/wifiphisher#890]
It is better to install Wi-Fi phisher with roguehostapd in one tool instead of installing it separately

**Comment by sophron** [comment]
When you run `setup.py` on Wifiphisher, it should automatically install it.

**Comment by djdisikd** [comment]
I clone wifiphisher and I run python setup.py install it does not install automatically

**Comment by sophron** [comment]
@djdisikd Sorry for the late response.

If roguehostapd fails to install in your system, you will have to manually compile and install it. 

I don't think we can do much more here. Roguehostapd offers many great features for Wifiphisher but it's written in native C for its low level operations. Setup cannot get simpler at this point.

@anakin1028 may have some more thoughts on this.
