### ISSUE TITLE
Language "es"

### ISSUE THREAD

**Issue by jeblaje** [wifiphisher/wifiphisher#895]
Que tal comunidad con respecto a la interface web me gustaria contribuir en el idioma español ;) SALUDOS...

**Comment by sophron** [comment]
Thank you.

We don't offer a language option. A user may manually edit the HTML files accordingly.

**Comment by jeblaje** [comment]
Mi pregunta es:

Donde se encuentran estos archivos???

Gracias...

2018-03-31 2:43 GMT-05:00 George Chatzisofroniou <notifications@github.com>:
