### ISSUE TITLE
Password crypted

### ISSUE THREAD

**Issue by Midas101** [wifiphisher/wifiphisher#896]
Hi Guys!
need help please.
first i'm sorry for my english :)
I hack a wifi is successful but.
the pass is encrypt or what I do not know:

[+] Captured credentials:
bloc=u6Cy9aTro6X98fX27vW79ru99L657b_r9KGvubG518L22MvY2Y6PhM6PlIHFgo7LyMLM3caWz9OGnomTmNPBx6nm4Pr_q-P8vcXFxOTBtLD4jvuLjKuOraCgqq_X9Yf3xZqRkZuZl5vk25eSypORldHf2NbQjtiLipfe2dqW2YR5fnwkL2smPn1xb3EjYSsxND0uYmtiSAgcfAkaZTQidFgdDAxeXFJPBg4TE0ZaVlcbCkVOSkITHhcTHkAUFxVCPjsul1xVjf..|tp=3&ext=u62n89_a8rWW4sCRk6TtiuD24ursuJiu54aS46CnvbiPoNSqiYHTqN-Hj93S9o2nsZbtyMS4v8CSysrllM7Dlue0urTs47vPw-6Sxr2SlryjiPKk2KGiov6qqful-_7rldPP2Z2Sj83LkITIzpTZ0tiYjdHJ3tvOjNfC8dLTZXz.|tp=3&trtm=1522328545733
req=7L6pvPP9vK7hrfWs9ID2ic3v7Liem5rvkuqVkZG1x-ep266trd6CqIzViPKa09PQmMnFlc_OxcDBwcHM1tDWm-6138rFufS-7ue-vKjn4OGo6rug_e6y9f_x9uD5r6qy2czHk5uCyZ5ed1tnXP..|tp=3&qt=conf
[!] Closing

if someone can help me.
thks

**Comment by sophron** [comment]
Hi @Midas101,

Which scenario did you use?

**Comment by Midas101** [comment]
Hi!
with a Fake "network manager"

**Comment by sophron** [comment]
I'm afraid this is a false positive. The software matched this as a credential but it's actually a POST request directed somewhere else but not to our phishing page.

I mark this as a bug. We should filter out POST requests such this.

**Comment by Midas101** [comment]
thank you for your quick reply.
so I did not hack the wifi password!

**Comment by anakin1028** [comment]
@Midias101 can you use wireshark to sniff on the rogue ap interface and post the pcap file in this thread so that we know how to filter this false alarm message?

**Comment by sophron** [comment]
@anakin1028 I believe all we have to do is to check the HTTP Host header and make sure that the request was directed to our phishing page and not somewhere else.

**Comment by sophron** [comment]
I was wrong that we could verify the HTTP Host header as it always points to the outside domain.

I fixed this by putting some regex when parsing the POST values.
