### ISSUE TITLE
ImportError: No module named setuptools

### ISSUE THREAD

**Issue by biba19** [wifiphisher/wifiphisher#897]
I  follow the instruction  to install Social CCN Sim ( CCN simulator ) when I tap 

`sudo python setup.py install`

it gives: 

`Traceback (most recent call last):
  File "setup.py", line 10, in <module>
    from setuptools import setup, find_packages
ImportError: No module named setuptools`

 
Any help?

**Comment by JetseVerschuren** [comment]
Try `pip install setuptools`

**Comment by biba19** [comment]
@JetseVerschuren i already tried `pip install setuptools` and  it gives : 
`requirement already satisfied (use --upgrade to upgrade) : distribute in /usr/lib/python2.7/dist-packages
cleanning up...`
