### ISSUE TITLE
scapy.layers.dot11 has no 'EAPOL' member in latest version

### ISSUE THREAD

**Issue by sophron** [wifiphisher/wifiphisher#898]
It looks like latest Scapy fails:

https://travis-ci.org/wifiphisher/wifiphisher/builds/362092234

This only interferes with the `handshake_verify` module.

**Comment by anakin1028** [comment]
Maybe we can try to use `scapy.VERSION` to maintain backward compatibility. Since scapy moves EAPOL to another module from dot11.
