### ISSUE TITLE
Cant choose network since 1.3

### ISSUE THREAD

**Issue by deoeztuerk** [wifiphisher/wifiphisher#899]
wifiphisher starts but i  cant choose a network 
given options are UP DOWN and EXIT

Exit closes wifiphisher 
strg C interrupts it 

Iam using the Kali Nano Version.

maybe some dependencies are missing but i get no errors

**Comment by sophron** [comment]
What you are saying is that Wifiphisher won't display any networks in the area?

Can you see these networks with any other way? E.g. can you use Wireshark and monitor the traffic around you?

**Comment by deoeztuerk** [comment]
it Displays all Networks in the área monitor Mode Works too. I just cant choose a network on the Overview 

In wifiphisher 1.2 all works

**Comment by deoeztuerk** [comment]
In wifiphisher 1.2 i used ctrl c to stop searching then the number to choose the network

**Comment by sophron** [comment]
In the latest versions you just press "Enter" to select your network.

**Comment by deoeztuerk** [comment]
Yes and this does Not work

**Comment by deoeztuerk** [comment]
I made it work i used a External keyboard and it worked 

The internal Keyboard enter Works on terminal and anywhere Else but Not in Your wifiphisher

**Comment by sophron** [comment]
Interesting. Thanks for posting this.

@anakin1028 I wonder if we changed something relevant since Wifiphisher v1.2.

**Comment by deoeztuerk** [comment]
Probaly the enter Key never worked 
I just suggest to Change the Selection to a key

**Comment by anakin1028** [comment]
hmm.. looks like no difference in ap-selection between 1.2 and current version of wifiphisher. We have used curses section for ap selection in v1.2.

**Comment by blackHatMonkey** [comment]
Hey @deoeztuerk can you try it with the latest `github` version?
