### ISSUE TITLE
Do I need any other WiFi adapter rather than the built-in laptop's one?

### ISSUE THREAD

**Issue by StanleySathler** [wifiphisher/wifiphisher#905]
Hello guys 👋 
First of all, congratulations! This tool looks awesome!

I've been reading the docs to learn how to use it and now I'm in doubt about one thing:

_One wireless network adapter that supports AP & Monitor mode and is capable of injection. For advanced mode, you need two cards; one that supports AP mode and another that supports Monitor mode. Drivers should support netlink._

In my case, I have a Macbook Air 13" Early-2015. Since it supports WiFi, I'm considering it has a _built-in WiFi adapter_. Is that right? In this case, do I need any other thing rather than my laptop?

By the way, I'm already aware that I should try it in a Kali Linux. I'm gonna use it as Live-CD while testing the tool.

Thanks in advance.

**Comment by sophron** [comment]
Hi @StanleySathler,

Thanks for your kind words.

> In my case, I have a Macbook Air 13" Early-2015. Since it supports WiFi, I'm considering it has a built-in WiFi adapter. Is that right? In this case, do I need any other thing rather than my laptop?

Yes, the built-in Wi-Fi adapter should work fine as long as it supports Monitor & AP mode.

> By the way, I'm already aware that I should try it in a Kali Linux. I'm gonna use it as Live-CD while testing the tool.

That's fine.
