### ISSUE TITLE
error after intallation when I run command: sudo python setup.py install 

### ISSUE THREAD

**Issue by ahrazrafiq** [wifiphisher/wifiphisher#908]
Traceback (most recent call last):
  File "setup.py", line 10, in <module>
    from setuptools import setup, find_packages, Command
ImportError: No module named setuptools

**Comment by sophron** [comment]
See #897.

**Comment by ahrazrafiq** [comment]
It tells me to import setup,command, find packages which are in python, how
to do it??

**Comment by ahrazrafiq** [comment]
i already tried pip install setuptools and it gives :
requirement already satisfied (use --upgrade to upgrade) : distribute in /usr/lib/python2.7/dist-packages cleanning up
