### ISSUE TITLE
problem with Roguehostapd

### ISSUE THREAD

**Issue by nadisoft** [wifiphisher/wifiphisher#909]
hey have a nice day when i start wifiphisher and start attack i see message of install script Roguehostapd and i install it and still not work please help me
![screenshot from 2018-04-17 04-38-14](https://user-images.githubusercontent.com/11483296/38847467-45867452-41f1-11e8-8a46-c9511831505f.png)

**Comment by sophron** [comment]
For some reason, the installer failed to automatically install `roguehostapd` in your system. You can either try to compile & install it manually or force the usage of hostapd as described in the error message.

**Comment by evaexe** [comment]
I had the same issue, 
Even if i clone the git of RogueHostpasd, and use the setup, Wifiphisher don't found roguehostpad

**Comment by evaexe** [comment]
![screenshot from 2018-04-18 21-24-43](https://user-images.githubusercontent.com/8714901/38953454-164c4126-434f-11e8-9bc8-d00a259d08d7.png)

**Comment by anakin1028** [comment]
I'm not sure roguehostapd is installed correctly on your system. Can you go to roguehostapd folder and run
```
python run.py -iwlan0 #change wlan0 to the WLAN interface on your system.
```
To see if roguehostapd launch successfully?

**Comment by evaexe** [comment]
![screenshot from 2018-04-19 17-43-12](https://user-images.githubusercontent.com/8714901/39002737-79b87950-43f9-11e8-8654-40677b861940.png)

**Comment by djdisikd** [comment]
I have the same issue, please fix it as soon as possible

**Comment by g0rbe** [comment]
I have the same problem too
`setup.py install`

![screenshot at 2018-04-26 20-34-10](https://user-images.githubusercontent.com/36860942/39325082-95859cba-4991-11e8-83e4-7dd226578770.png)

Then run:
`wifiphisher -nE -aI wlan1 -e test -p oauth-login`

![screenshot at 2018-04-26 20-35-44](https://user-images.githubusercontent.com/36860942/39325146-c137bc30-4991-11e8-9e78-3f828e6a9a7a.png)

**Comment by sophron** [comment]
Can you do a `whereis roguehostapd`?

**Comment by g0rbe** [comment]
`roguehostapd:      `
Cant find

**Comment by sophron** [comment]
Which distro are you using?

**Comment by g0rbe** [comment]
Parrot

**Comment by vladimirtrifkovic** [comment]
I solve the problem as follows:
1. check your soruces.list of kali and add "deb http://http.kali.org/kali kali-rolling main contrib non-free" if it not exists.
2. do "apt-get update"
3. do "git clone https://github.com/wifiphisher/roguehostapd.git" in your wifiphisher directory
4. navigate to wifiphisher/roguehostapd/ direcory and do "python setup.py install"

If some notification shows that you need smt to install, than do it as it says.

Hope it will help.

I want also to add that attack with the following option:

" -jI EXTENSIONSINTERFACE | --extensionsinterface EXTENSIONSINTERFACE | Manually choose an interface that supports monitor mode for running the extensions. Example: -jI wlan1
-- | -- | -- "

works at me with "-eI wlan1"

**Comment by sophron** [comment]
Thanks @vladimirtrifkovic, we fixed the typo.

**Comment by brunolopes446** [comment]
Have the same problem and I'm doing everything correctly.

**Comment by sophron** [comment]
@brunolopes446 Can you elaborate?

Are you getting the error message that `roguehostapd` is installed? Have you tried to manually build it?

**Comment by brunolopes446** [comment]
@sophron Sure!

when running wifiphisher from the command line:
```
[*] Starting the fake access point...
[!] Roguehostapd is not installed in the system! Please install roguehostapd manually (https://github.com/wifiphisher/roguehostapd) and rerun the script. Otherwise, you can run the tool with the --force-hostapd option to use hostapd but please note that using Wifiphisher with hostapd instead of roguehostapd will turn off many significant features of the tool.
[+] Show your support!
```
Already build it manually

`locate roguehostapd` says it is in **/usr/local/lib/python2.7/dist-packages/**

I also did the following:
 _"git clone https://github.com/wifiphisher/roguehostapd.git" in your wifiphisher directory
navigate to wifiphisher/roguehostapd/ directory and do "python setup.py install"_

Output of installation command attached:
[log.txt](https://github.com/wifiphisher/wifiphisher/files/1973740/log.txt)

**Comment by anakin1028** [comment]
@brunolopes446 Do you also use Parrot? Or Kali Linux?

**Comment by brunolopes446** [comment]
@anakin1028 Kali 2018.1

**Comment by sophron** [comment]
@brunolopes446 Thanks for reporting. Can you run `pip uninstall roguehostapd` and re-build the shared library after cloning from Github? Let us know if that works.

**Comment by brunolopes446** [comment]
@sophron Issue persists.
Pastebin: [https://pastebin.com/VVidEcNz](https://pastebin.com/VVidEcNz)
Already upgraded to Kali 2018.2, and the problem remains.

**Comment by gfbalestrin** [comment]
Same problem here, using kali 2018.2

**Comment by gfbalestrin** [comment]
I thing i fixed the problem. The roguehostapd was not finding the lib libhostapd.so. 

OSError: /usr/local/lib/python2.7/dist-packages/roguehostapd-1.2.3-py2.7.egg/roguehostapd/hostapd-2_6/hostapd/libhostapd.so: cannot open shared object file: No such file or directory

On kali 2018.2 i found the lib in this directory:
find / -iname libhostapd.so
/usr/local/lib/python2.7/dist-packages/roguehostapd-1.1.2-py2.7-linux-x86_64.egg/roguehostapd/hostapd-2_6/hostapd/libhostapd.so

So i created the path and copy the lib:
mkdir -p /usr/local/lib/python2.7/dist-packages/roguehostapd-1.2.3-py2.7.egg/roguehostapd/hostapd-2_6/hostapd/
cp usr/local/lib/python2.7/dist-packages/roguehostapd-1.2.3-py2.7.egg/roguehostapd/hostapd-2_6/hostapd/libhostapd.so /usr/local/lib/python2.7/dist-packages/roguehostapd-1.2.3-py2.7.egg/roguehostapd/hostapd-2_6/hostapd/

Now works!

**Comment by brunolopes446** [comment]
@anakin1028 
Thank you, but it didn't work:
```

root@kali:~/Downloads/wifiphisher# pip uninstall roguehostapd
Uninstalling roguehostapd-1.1.2:
  /usr/local/lib/python2.7/dist-packages/roguehostapd-1.1.2-py2.7-linux-x86_64.egg
Proceed (y/n)? y
  Successfully uninstalled roguehostapd-1.1.2
root@kali:~/Downloads/wifiphisher# pip install roguehostapd --no-cache-dir
Requirement already satisfied: roguehostapd in /usr/local/lib/python2.7/dist-packages/roguehostapd-1.2.3-py2.7.egg

```

@gfbalestrin 
Your solution worked, but you have a mistake on your last command (the source path is wrong).
The correct fix is:

```

mkdir -p /usr/local/lib/python2.7/dist-packages/roguehostapd-1.2.3-py2.7.egg/roguehostapd/hostapd-2_6/hostapd/

cp /usr/local/lib/python2.7/dist-packages/roguehostapd-1.1.2-py2.7-linux-x86_64.egg/roguehostapd/hostapd-2_6/hostapd/libhostapd.so /usr/local/lib/python2.7/dist-packages/roguehostapd-1.2.3-py2.7.egg/roguehostapd/hostapd-2_6/hostapd/

```

PS: @gfbalestrin, where/how did you found that OSError?

**Comment by sophron** [comment]
@brunolopes446 There seems to be some conflicting versions of `roguehostapd` in your system. You uninstalled version 1.1.2 but version 1.2.3 was left intact. 

Can you make sure that all versions of roguehostapd have been completely uninstalled before running "pip install roguehostapd --no-cache-dir"?

**Comment by gfbalestrin** [comment]
@brunolopes446  Sorry, at the time of placing the commands I erred the order here

i found the error when i executed the script "run.py" from roguehostapd directory

**Comment by fahadsattiofficial** [comment]
@brunolopes446  did you fixed this error ? if you did then please tell me how do i get rid of this error ? which method you choosed from above advices ?

**Comment by brunolopes446** [comment]
@fahadsattiofficial Read my last answer, where I posted the correct fix.

**Comment by DeXtmL** [comment]
It seems i have to revive this old issue.
Cloned and setup today, same problem remains.

Things I tried:
1. clone roguehostapd into wifiphisher dir then "setup install"
2. pip install roguehostapd

none of them work.

Solution:
@brunolopes446  's last solution works for me

Kali 2018.2

**Comment by djdisikd** [comment]
I have problem too, I can't install it

**Comment by itm1960** [comment]
I too have this problem, but @brunolopes446's solution gives an error for me:
```
root@kali:/usr/lib/python2.7/dist-packages/roguehostapd# mkdir -p /usr/local/lib/python2.7/dist-packages/roguehostapd-1.2.3-py2.7.egg/roguehostapd/hostapd-2_6/hostapd/
root@kali:/usr/lib/python2.7/dist-packages/roguehostapd# cp /usr/local/lib/python2.7/dist-packages/roguehostapd-1.1.2-py2.7-linux-x86_64.egg/roguehostapd/hostapd-2_6/hostapd/libhostapd.so /usr/local/lib/python2.7/dist-packages/roguehostapd-1.2.3-py2.7.egg/roguehostapd/hostapd-2_6/hostapd/
cp: cannot stat '/usr/local/lib/python2.7/dist-packages/roguehostapd-1.1.2-py2.7-linux-x86_64.egg/roguehostapd/hostapd-2_6/hostapd/libhostapd.so': No such file or directory

```

I'm running Kali Linux 2018.2 in a VirtualBox VM, and installed wifiphisher 1.4 using:
```apt-get install wifiphisher```

When I run wifiphisher I get: 
```Roguehostapd is not installed in the system!```

So I tried @brunolopes446's solution but it gives an error for me:
```
root@kali:/usr/lib/python2.7/dist-packages/roguehostapd# mkdir -p /usr/local/lib/python2.7/dist-packages/roguehostapd-1.2.3-py2.7.egg/roguehostapd/hostapd-2_6/hostapd/
root@kali:/usr/lib/python2.7/dist-packages/roguehostapd# cp /usr/local/lib/python2.7/dist-packages/roguehostapd-1.1.2-py2.7-linux-x86_64.egg/roguehostapd/hostapd-2_6/hostapd/libhostapd.so /usr/local/lib/python2.7/dist-packages/roguehostapd-1.2.3-py2.7.egg/roguehostapd/hostapd-2_6/hostapd/
cp: cannot stat '/usr/local/lib/python2.7/dist-packages/roguehostapd-1.1.2-py2.7-linux-x86_64.egg/roguehostapd/hostapd-2_6/hostapd/libhostapd.so': No such file or directory

```

I'm using two USB wifi adapters:
- Netgear A6100ac
- Alfa AWUS036H (based on Realtek RTL8187)

Any idea how I can get Roguehostapd working?

**Comment by anakin1028** [comment]
@itm1960  in your case the shared library is even not get built in version 1.1.2, so the co command shows that it can not find the .so file. Can you remove all the roguehostapd directories under dist-packages(including 1.1.2 and 1.2
3) and try to do `pip install roguehostapd --no-cache-dir`?

**Comment by username836** [comment]
How to compile it and install myself ?

**Comment by zeb777** [comment]
I have a bran new install of Roguehost apd and wifiphisher, I've ran the 'python setup.py install' on both and launched wifiphisher. Once I find my text network any attach method I get I receive:

[!] Roguegostapd is not installed in the system!

**Comment by username836** [comment]
That's what happened to me!

**Comment by sophron** [comment]
I believe this is fixed now. Please reopen if needed.

**Comment by shaswata56** [comment]
It's not fixed yet. Getting the same problem on Parrot OS.
