### ISSUE TITLE
Wifiphisher Stuck at Starting

### ISSUE THREAD

**Issue by dxtr12** [wifiphisher/wifiphisher#921]
Hello,

I've just installed Wifiphisher on Xubuntu 16.04, but when I run it it stuck on the first line : 
[*] Starting Wifiphisher 1.4GIT ( https://wifiphisher.org ) at 2018-05-11 20:22
I tried to restart network manager and reinstall wifiphisher with no success
What could be the issue

**Comment by sophron** [comment]
Looks like something is wrong with the wireless cards.

Can you see any interfaces if you type `iwconfig` and `ifconfig`?

**Comment by dxtr12** [comment]
Please find hereunder output of ifconfig and iwconfig:

iwconfig : 
wlp3s0    IEEE 802.11abgn  ESSID:"FLATDX"  
          Mode:Managed  Frequency:2.437 GHz  Access Point: 84:16:F9:98:0C:3A   
          Bit Rate=1 Mb/s   Tx-Power=20 dBm   
          Retry short limit:7   RTS thr:off   Fragment thr:off
          Encryption key:off
          Power Management:off
          Link Quality=70/70  Signal level=-40 dBm  
          Rx invalid nwid:0  Rx invalid crypt:0  Rx invalid frag:0
          Tx excessive retries:0  Invalid misc:5705   Missed beacon:0

enp2s0    no wireless extensions.

lo        no wireless extensions.


ifconfig:
enp2s0    Link encap:Ethernet  HWaddr 1c:39:47:dd:44:46  
          UP BROADCAST MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)

lo        Link encap:Local Loopback  
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:88613 errors:0 dropped:0 overruns:0 frame:0
          TX packets:88613 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1 
          RX bytes:6535274 (6.5 MB)  TX bytes:6535274 (6.5 MB)

wlp3s0    Link encap:Ethernet  HWaddr 74:df:bf:67:e6:69  
          inet addr:192.168.100.32  Bcast:192.168.100.255  Mask:255.255.255.0
          inet6 addr: fe80::a9d6:4e3e:229e:6fb7/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:2979113 errors:0 dropped:0 overruns:0 frame:0
          TX packets:3378913 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:2762092843 (2.7 GB)  TX bytes:635035341 (635.0 MB)

**Comment by sophron** [comment]
Can you disconnect from the wireless network that you are connected and try again?

**Comment by dxtr12** [comment]
Oh It's working now , I did the following : Sudo service network-manager restart
Thank you so much for your support

**Comment by sophron** [comment]
Sure, have a nice weekend.
