### ISSUE TITLE
I can't perform KARMA 

### ISSUE THREAD

**Issue by jeskudero** [wifiphisher/wifiphisher#922]
commit 23cda6efe070b3c45a5c1c2c4edc424256225060
I cant perform KARMA attack.
I run this:
`wifiphisher -aI wlan1 -nE --essid "WIFI-free" -p tknika-login`

But my mobile phone has saved an open network called "WIFI". And doesn't connect it.
If i dont put the --essid option, it shows me the available essid networks to choose one of them (evil twin).

I can't find any option in the help commands to perform this kind of attack

Thanks

**Comment by JetseVerschuren** [comment]
Can you post the full output of wifiphisher.

**Comment by anakin1028** [comment]
To do the test,
You can lunch the rogue AP with a SSID different than "WIFI",  say "testssid" and use your phone to manually connect to "WIFI" and see if the phone connect to the rogue ap.

 KARMA attack doesn't require the rogue AP 's said is same as the target AP.

**Comment by anakin1028** [comment]
For your first experiement, you are just forcing your phone to connect to our rogue AP which does not what KARMA attack means.

**Comment by jeskudero** [comment]
I have tested rigth now and if i connect manually to that previos network "WIFI"  it works.

**Comment by anakin1028** [comment]
Ok. If you don't provide `-nE` argument tool will output something like KARMA attack success.

**Comment by jeskudero** [comment]
```
root@josu-CX62-6QD:~/wifiphisher# wifiphisher -aI wlan1  --essid "WIFI" -p tknika-login 
[*] Starting Wifiphisher 1.4GIT ( https://wifiphisher.org ) at 2018-05-15 08:52
[-] --apinterface (-aI) and --extensionsinterface (-eI)(or --noextensions (-nE)) are used in conjuction.
```

**Comment by anakin1028** [comment]
Do you have two adaptor cards on your machine? If yes, you can simply supply another interface name to the `-eI` interface. Actually you don't even need to supply the interface name, since tool will automatically find the correct interface to lunch AP and monitor mode.

**Comment by jeskudero** [comment]
Yes it works now.
But i use this other interface to provide internet access to de users. After they submit the credentials in the phishing page i modify iptables and let them forward traffic to access internet.
And now it doesnt work fine. I will make more probes.

**Comment by anakin1028** [comment]
If your interface can supply virtual interface s. That is you can use one adaptor to lunch both AP and monitor, then you can use the command `wifiphisher -iI wlan0`. Wifiphisher will try to use one adaptor to lunch both AP and monitor:)

**Comment by jeskudero** [comment]
But with the -iI it forwards all the traffic without going to phishing page.
I'm trying differents ways but it doesnt works as i want.

**Comment by sophron** [comment]
Hi @jeskudero,

Some devices are no longer sending probe request frames for previously connected networks unless that network is hidden (ssid broadcasting is disabled). That's why we have introduced the Known Beacons attack.

What is the OS of the device that you are expecting to automatically associate with the rogue access point?

**Comment by jeskudero** [comment]
I'm doing tests with android 7.0 and laptop (ubuntu 16.04).
i tested with mana-toolkit and it performs well KARMA.
i have tried to do the KARMA attack with the 2 wireless interfaces and when they send credentials let them access internet through the eth0 and it works.
I want it to made a demo for my students, so its enaugth.

Thanks

**Comment by brandontict** [comment]
I thought -kB ( Known Beacons ) was similar to KARMA ?

**Comment by sophron** [comment]
It's not. Have a look here: https://census-labs.com/news/2018/02/01/known-beacons-attack-34c3/

I'm planning to update the README soon to clarify the difference between these two.

**Comment by brandontict** [comment]
I see that wifiphisher uses a dictionary of common ESSIDs .

Would it be possible to use the device probe requests and create a small dictionary with that information? So basically a Known Beacon attack , with ESSID from the device's probe requests ? 


Thank you for sharing this project.

**Comment by brandontict** [comment]
Thank you for clearing that up 👍  

I've noticed using known beacons , it states when device probes  and says "( KARMA ) " next to it .
