### ISSUE TITLE
Where do I put Roguehostapd?

### ISSUE THREAD

**Issue by GGGunrunner** [wifiphisher/wifiphisher#935]
Trying the latest version...

`git clone wifiphisher` - ok
`git clone roguehostapd` - ok
`(roguehostapd) - python setup.py install` - ok
`(wifiphisher) - python setup.py install` - ok

then i run `/bin/wifishipher` and it says
"`Roguehostapd` is not installed in the system!"

Should I manually move some files to some place?

**Comment by JetseVerschuren** [comment]
Can you post the full `setup.py` logs?

**Comment by GGGunrunner** [comment]
Installed /usr/local/lib/python2.7/dist-packages/wifiphisher-1.4-py2.7.egg
Processing dependencies for wifiphisher==1.4
Searching for scapy==2.2.0
Best match: scapy 2.2.0
Adding scapy 2.2.0 to easy-install.pth file

Using /usr/lib/python2.7/dist-packages
Searching for roguehostapd==1.2.3
Best match: roguehostapd 1.2.3
Processing roguehostapd-1.2.3-py2.7.egg
roguehostapd 1.2.3 is already the active version in easy-install.pth

Using /usr/local/lib/python2.7/dist-packages/roguehostapd-1.2.3-py2.7.egg
Searching for pbkdf2==1.3
Best match: pbkdf2 1.3
Processing pbkdf2-1.3-py2.7.egg
pbkdf2 1.3 is already the active version in easy-install.pth

Using /usr/local/lib/python2.7/dist-packages/pbkdf2-1.3-py2.7.egg
Searching for tornado==4.5.3
Best match: tornado 4.5.3
Processing tornado-4.5.3-py2.7-linux-armv7l.egg
tornado 4.5.3 is already the active version in easy-install.pth

Using /usr/local/lib/python2.7/dist-packages/tornado-4.5.3-py2.7-linux-armv7l.egg
Searching for PyRIC==0.1.6.3
Best match: PyRIC 0.1.6.3
Processing PyRIC-0.1.6.3-py2.7.egg
PyRIC 0.1.6.3 is already the active version in easy-install.pth

Using /usr/local/lib/python2.7/dist-packages/PyRIC-0.1.6.3-py2.7.egg
Searching for backports-abc==0.5
Best match: backports-abc 0.5
Adding backports-abc 0.5 to easy-install.pth file

Using /usr/local/lib/python2.7/dist-packages
Searching for certifi==2018.1.18
Best match: certifi 2018.1.18
Processing certifi-2018.1.18-py2.7.egg
certifi 2018.1.18 is already the active version in easy-install.pth

Using /usr/local/lib/python2.7/dist-packages/certifi-2018.1.18-py2.7.egg
Searching for singledispatch==3.4.0.3
Best match: singledispatch 3.4.0.3
Adding singledispatch 3.4.0.3 to easy-install.pth file

Using /usr/local/lib/python2.7/dist-packages
Searching for six==1.10.0
Best match: six 1.10.0
Adding six 1.10.0 to easy-install.pth file

Using /usr/local/lib/python2.7/dist-packages
Finished processing dependencies for wifiphisher==1.4

(i skipped the rest because it didnt generate any errors)..
(running it on Raspberry Pi 3 Raspbian). probably have to try on x86 ubuntu/debian?

**Comment by sophron** [comment]
Hi @GGGunrunner,

We haven't yet test Wifiphisher on Raspbian so I'm sure there will be many issues there. It's on our list though and we should have an update on this in the upcoming few weeks.

**Comment by GGGunrunner** [comment]
Yes, but where should RogueAP be put anyway? 
System-wide in /usr/local or in ./wifiphisher dir, or one level higher?

**Comment by blackHatMonkey** [comment]
@GGGunrunner I had a similar [issue](https://github.com/wifiphisher/roguehostapd/issues/7). The solution that worked for me was
1. uninstall the `git` version; take a look at [this](https://stackoverflow.com/questions/1550226/python-setup-py-uninstall) if you don't know how.
2. run `[sudo] pip uninstall roguehostapd`. Run it with `sudo` and without.
3. `pip install roguehostapd --no-cache-dir`

Let me know if this works :smile_cat: .

**Comment by GGGunrunner** [comment]
root@:~# pip uninstall roguehostapd
Uninstalling roguehostapd-1.2.3:
  Would remove:
    /usr/local/lib/python2.7/dist-packages/examples/*
    /usr/local/lib/python2.7/dist-packages/roguehostapd-1.2.3.dist-info/*
    /usr/local/lib/python2.7/dist-packages/roguehostapd/*
Proceed (y/n)? y
  Successfully uninstalled roguehostapd-1.2.3

===

pip install roguehostapd --no-cache-dir
Looking in indexes: https://pypi.org/simple, https://www.piwheels.hostedpi.com/simple
Collecting roguehostapd
  Downloading https://files.pythonhosted.org/packages/ca/0e/67991a382656c30ec4f6197db8e96bf8d3b87cc0093254f0c97340fa7c53/roguehostapd-1.2.3.tar.gz (1.9MB)
    100% |--------------------------------| 1.9MB 199kB/s 
Installing collected packages: roguehostapd
  Running setup.py install for roguehostapd ... done
Successfully installed roguehostapd-1.2.3

===
root@:~/wifiphisher# wifiphisher                            
Traceback (most recent call last):
  File "/usr/local/bin/wifiphisher", line 11, in <module>
    load_entry_point('wifiphisher==1.4', 'console_scripts', 'wifiphisher')()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 560, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2648, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2302, in load
    return self.resolve()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2308, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python2.7/dist-packages/wifiphisher/pywifiphisher.py", line 27, in <module>
    import wifiphisher.common.accesspoint as accesspoint
  File "/usr/local/lib/python2.7/dist-packages/wifiphisher/common/accesspoint.py", line 7, in <module>
    from roguehostapd import hostapd_controller
ImportError: cannot import name hostapd_controller



All I can say - wifiphisher is now a tough one to install :)
I remember using it 1.5 years ago and it was all good.....

**Comment by anakin1028** [comment]
Hi, you are almost done~! Can you remove the wifiphisher, and install the newest version from github? It looks like you use a old version of wifiphisher which is inconsistent to the new version of roguehostapd.

**Comment by itz-8infinite** [comment]
Na the issue is still up coz wifiphisher is still unable to detect roguehostapd in my Kali Mint. i am using the latest version for roguehostapd and wifiphisher.

**Comment by itz-8infinite** [comment]
[*] Starting Wifiphisher 1.4GIT ( https://wifiphisher.org ) at 2019-01-26 17:16
[+] Timezone detected. Setting channel range to 1-13
[+] Selecting wlp2s0 interface for the deauthentication attack
[+] Selecting wfphshr-wlan0 interface for creating the rogue Access Point
[+] Changing wfphshr-wlan0 MAC addr (BSSID) to 00:00:00:bc:e9:da
[+] Changing wfphshr-wlan0 MAC addr (BSSID) to 00:00:00:4d:cd:67
[+] Sending SIGKILL to wpa_supplicant
[+] Sending SIGKILL to dhclient
[+] Sending SIGKILL to avahi-daemon
[+] Sending SIGKILL to avahi-daemon
[+] Sending SIGKILL to NetworkManager
[*] Cleared leases, started DHCP, set up iptables
[+] Selecting Firmware Upgrade Page template
[*] Starting the fake access point...
[!] Roguehostapd is not installed in the system! Please install roguehostapd manually (https://github.com/wifiphisher/roguehostapd) and rerun the script. Otherwise, you can run the tool with the --force-hostapd option to use hostapd but please note that using Wifiphisher with hostapd instead of roguehostapd will turn off many significant features of the tool.
[+] Show your support!
[+] Follow us: https://twitter.com/wifiphisher
[+] Like us: https://www.facebook.com/Wifiphisher
[+] Captured credentials:
[!] Closing

**Comment by softdream1981** [comment]
> @GGGunrunner I had a similar [issue](https://github.com/wifiphisher/roguehostapd/issues/7). The solution that worked for me was
> 
> 1. uninstall the `git` version; take a look at [this](https://stackoverflow.com/questions/1550226/python-setup-py-uninstall) if you don't know how.
> 2. run `[sudo] pip uninstall roguehostapd`. Run it with `sudo` and without.
> 3. `pip install roguehostapd --no-cache-dir`
> 
> Let me know if this works 😸 .

Work for me thank you.
