### ISSUE TITLE
Tp Link TL-WN722N not supported 

### ISSUE THREAD

**Issue by xTheFapper** [wifiphisher/wifiphisher#936]
Hey there,
ive tryed the tool with the Tp Link adapter but The Error Message not compatible comes.
So is there a way to use it or should i get an Alpha adapter?

**Comment by sophron** [comment]
Can you post the exact error message?

**Comment by minanagehsalalma** [comment]
@xTheFapper  the v2 of it is not supported

**Comment by strasharo** [comment]
TL-WN722N has multiple revisions. V 1.x have Atheros chipset, while V2 and V3 have Realtek ones, which are not compatible.

**Comment by xTheFapper** [comment]
Thanks for dour help I got the v2 here..

Bought the v1
