### ISSUE TITLE
cannot import hostapd_controller

### ISSUE THREAD

**Issue by Krishsinghal123** [wifiphisher/wifiphisher#940]
I've already referred issue #887 but the steps didn't work for me. When I run wifiphisher, it shows this error.

![iwconfi](https://user-images.githubusercontent.com/29298488/41044887-d6db35be-69c4-11e8-9023-463816b87a8a.png)

![wifiphis](https://user-images.githubusercontent.com/29298488/41044806-af195b78-69c4-11e8-8d97-6b8a00f2603b.png)

**Comment by blackHatMonkey** [comment]
@Krishsinghal123 Checkout [this](https://github.com/wifiphisher/wifiphisher/issues/935#issuecomment-394815829) solution I posted. This might work for you as well.

**Comment by Krishsinghal123** [comment]
Nope, still doesn't work. 
error ** cannot import name hostapd_controller**

**Comment by anakin1028** [comment]
Hi can you go to the dist-packages folder and manually remove all the roguehostapd prefixing folders?

Then try to use `pip install --no-cache-dir roguehostapd` 

I think pip uninstall doesn't remove all the folders on the dist-package folder.

**Comment by JetseVerschuren** [comment]
Did you install wifiphisher from Github? If not, try that.

**Comment by Krishsinghal123** [comment]
from github, this repo only. version 1.4

**Comment by Krishsinghal123** [comment]
I was trying to uninstall wifiphisher, command- sudo apt-get remove wifiphisher, it says not installed. How's this possible. I'll try using synaptic to install.

**Comment by Krishsinghal123** [comment]
I guess cloning the repo worked but not actually as there is still an error.
![wifi](https://user-images.githubusercontent.com/29298488/41165353-1087e6bc-6b5b-11e8-8b9a-af740b21e99e.png)

**Comment by anakin1028** [comment]
Ok now this means your adaptor doesn't support Monitor mode. Try to use no extension manager mode and this should work fine.

**Comment by anakin1028** [comment]
Try with `-e ESSID -nE`

**Comment by Krishsinghal123** [comment]
![phi](https://user-images.githubusercontent.com/29298488/41191180-2e6717da-6c09-11e8-8f88-4a27d763314c.png)

**Comment by anakin1028** [comment]
Looks like your adaptor doesn't support AP mode.

**Comment by Krishsinghal123** [comment]
and the solution for that is?

Also, can we crack any wpa/wpa2 wifi with wifiphisher? I'm thinking of getting an external adapter.

**Comment by anakin1028** [comment]
No wifiphisher cannot crack WPA and WPA2

**Comment by anakin1028** [comment]
To get full support for all the functionalities of Wifiphisher you need one adaptor supports both monitor mode and ap mode

**Comment by Krishsinghal123** [comment]
I mean to say hack. 

I'll buy a network adapter. Current adapter is Broadcom 4320, which is supported I don't know why isn't it working with wifiphisher.

**Comment by anakin1028** [comment]
Original problem is resolved, feel free to reopen it if you have more questions
