### ISSUE TITLE
Keeping one wifi interface alive

### ISSUE THREAD

**Issue by Tsadoq** [wifiphisher/wifiphisher#948]
I hope it's the correct place to ask. I have a remote machine where I'd like to use wifiphisher but, being headless the only way to control it it's through an SSH connection. This machine is connected to the "internet" network with it's own wifi card ( while I use for networking forensics et cetera an alpha that is connected and works). When I launch wifiphisher it kills the network manager killing down the interface I use to stay connected to that machine. How could I keep it alive so that the ssh is not killed?

**Comment by sophron** [comment]
Hi @Tsadoq,

This is a known issue (see #926). We have a PR almost ready (#939) so I expect this to be merged within the month.
