### ISSUE TITLE
error after select the template phisher

### ISSUE THREAD

**Issue by christmex** [wifiphisher/wifiphisher#952]
[*] Starting HTTP/HTTPS server at ports 8080, 443
Exception in thread Thread-6:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/root/wifiphisher/wifiphisher/common/phishinghttp.py", line 178, in runHTTPServer
    https_server.listen(ssl_port, address=ip)
  File "/usr/lib/python2.7/dist-packages/tornado/tcpserver.py", line 144, in listen
    sockets = bind_sockets(port, address=address)
  File "/usr/lib/python2.7/dist-packages/tornado/netutil.py", line 171, in bind_sockets
    sock.bind(sockaddr)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address already in use

i get this error when i after select the phishing template,  working but i'm not get the password of wifi, it just deauth

please help me
and after i use i want to turn on again my network manager and use the  ' service network-manager start' but i cant running again my network manager

**Comment by JetseVerschuren** [comment]
I think this means that a server is already listening on port 443. Try stopping/disabling other webservers if any running, you can try `service apache2 stop` if you're on kali

**Comment by christmex** [comment]
but im not use the apache server,

**Comment by christmex** [comment]
after reboot i'm just open wifiphisher

**Comment by christmex** [comment]
before, i say thanks for your attention, now i found what the problem, before i use wifiphisher i have to install vmware in my kali linux. so its that why i cant run my wifiphisher .

thanks. sorry cause my english so bad .

**Comment by christmex** [comment]
before, i say thanks for your attention, now i found what the problem, before i use wifiphisher i have to install vmware in my kali linux. so its that why i cant run my wifiphisher . 

thanks. sorry cause my english so bad .
