### ISSUE TITLE
Not an issue: Check preshare WPA key validity in the portal.

### ISSUE THREAD

**Issue by jeretc** [wifiphisher/wifiphisher#953]
Hello this is not an issue, will it be possible for client login to fake router upgrade page , the preshare key to check the validity if entered key is correct? If not correct than it asks to re-enter again.

**Comment by sophron** [comment]
Please see the `--handshake-capture` option.

**Comment by sophron** [comment]
By the way, I noticed your "cfp" template. It would be great if you could port this to Wifiphisher :)

If you are interested, we have a guide for creating custom phishing scenarios: http://wifiphisher.readthedocs.io/en/latest/custom_phishing_scenario.html
