### ISSUE TITLE
I can't connect to fake AP

### ISSUE THREAD

**Issue by sonozaki** [wifiphisher/wifiphisher#954]
Hi, I can't connect to my fake AP, I use raspberry pi 3 B+, the rogue AP is the integrated raspberry wifi card, I use another usb wifi for deauthentication (alfa AWUS036H), I can see the fake AP but i can't connect, the "dhcp leases" section on wifiphisher is empty.

I use kali linux arm.

Thanks.

**Comment by sophron** [comment]
Are you using the latest Wifiphisher version?

Have you tried to manually connect to the rogue AP? Do you see any errors?

**Comment by sonozaki** [comment]
Are you using the latest Wifiphisher version? 

Yes, I did download it with git clone.

Have you tried to manually connect to the rogue AP? 

Yes, and I can't connect to the rogue AP

Do you see any errors? 

No

**Comment by anakin1028** [comment]
It's difficult to Debug with this problem unless you can use wireshark to Capture the Layer2 and Layer2 sniffer log for us.

From Layer2 sniffer(for wireless), we can see if your client device get connected to the rogue AP.

From layer3 sniffer, we can see if your client send dhcp request to the rogue AP.

**Comment by sophron** [comment]
Please re-open if needed and post a traffic dump.
