### ISSUE TITLE
What does this mean?

### ISSUE THREAD

**Issue by djdisikd** [wifiphisher/wifiphisher#957]
![img_20180625_145506](https://user-images.githubusercontent.com/17978000/41834873-409f8c8a-7888-11e8-83b6-076c3ce6301a.jpg)
What it means I don't understand

**Comment by djdisikd** [comment]
Get request for http://www.bing.com/   ?

**Comment by sophron** [comment]
Hi @djdisikd,

Wifiphisher does not aim to be script-kiddie friendly. The output should be easy to understand if you have the required knowledge.
