### ISSUE TITLE
Unknown vendor - Update OUI database

### ISSUE THREAD

**Issue by djdisikd** [wifiphisher/wifiphisher#961]
I am hacking a TP-Link Archer C1200 router and widiphisher shows unknown vendor

Please fix it.

**Comment by sophron** [comment]
Here's the list with the OUIs that we use (comes from IEEE): https://github.com/wifiphisher/wifiphisher/blob/master/wifiphisher/data/wifiphisher-mac-prefixes

What are the first six digits of the MAC address? Either the OUI is unregistered or the MAC address of the router has been spoofed.

**Comment by djdisikd** [comment]
7C:8B:CA is the first 6 digits

**Comment by djdisikd** [comment]
I think is unregistered not spoofed

**Comment by sophron** [comment]
Looks like our database it's not up-to-date: https://hwaddress.com/oui-iab/7C-8B-CA

We will have to update it.

**Comment by djdisikd** [comment]
Okay.

**Comment by sophron** [comment]
Done in #972.

**Comment by Commander-Crash** [comment]
Can i update this OUI list locally? I have tried with "wifiphisher-mac-prefixes" However it does not apply the change. This seems trivial and wish i can just update it on the fly without waiting for devs to get around to it.

**Comment by sophron** [comment]
Yes, edit the file and then re-install Wifiphisher (i.e. run `python setup.py install` again).
