### ISSUE TITLE
No handlers could be found for logger "wifiphisher.interfaces" + network manager error

### ISSUE THREAD

**Issue by arismelachroinos** [wifiphisher/wifiphisher#965]
(Never seen this exact issue)

**Version**: commit 5ae21ab93e0dce85dd4bf76e68cc3b996aa33dea

**Description**: 
I have tested the Auth attack for facebook credentials before and it worked flawlessly. 
Now it gives me errors and then it seems like it starts but no AP visible.
I have tried it with 3 interfaces (that all support monitor mode even though I do not think its is needed on this attack) and I have tested it and I know it was working in the past with all of them. 
iwconfig before the attack:
![iwconfig before the attack](https://user-images.githubusercontent.com/21193898/42675921-ac3d1d50-867e-11e8-8101-a9270b3e0143.jpg)

**Script output**: 
![screenshot_1](https://user-images.githubusercontent.com/21193898/42675935-baecab9a-867e-11e8-9bda-4f7c25237ea7.jpg)
The command I am using is : wifiphisher --noextensions --essid "Free" -p oauth-login -kB
These two messages appear. Some times the network manager error does not appear, but only the second line. 

Do you have something in mind I could try?

Thank you

**Comment by JetseVerschuren** [comment]
Can you try it with `--logging`?

**Comment by sophron** [comment]
Hi @arismelachroinos,

Both of these messages are probably irrelevant with your problem. First one has to do with our logger functions while the second one with the lack of NetworkManager. 

May I ask in which distro are you trying this? Can you also run `ps -aux | grep hostapd` after running the tool to see if `hostapd` or `roguehostapd` are running successfully?

PS: Good job with your lscript! Just to mention that the original creator of Wifiphisher is myself (and not Dan) supported by an awesome community!

**Comment by arismelachroinos** [comment]
The program starts, the attack seems to start, however no AP is visible. I just tried the firmware upgrade attack as well, and I get the second error as well : 
![image](https://user-images.githubusercontent.com/21193898/42679488-c42ec592-868a-11e8-861f-d6fd9664b32a.png)
Again, the attack does not quit itself, I quit it to show you the errors that happen in the beginning fast, and because the attack does not work with those errors. All the attacks worked in the past.
I am running latest Kali Linux. 
The output of the command you gave me is : 
`root      38124  0.0  0.0  12840  1064 pts/2    S+   02:53   0:00 grep hostapd`

Thank you sir :) Sorry for not asking for the name of the original creator. Just updated the name.

**Comment by arismelachroinos** [comment]
Basicaly even if I just launch the tool with `wifiphisher` I see this error when launching. It is not no only a specific attack, it is when I launch wifiphisher. Have tried everything I thought and nothing, and the weired thing is that it worked a few days back and now it doesnt, and I havve changed nothing.

**Comment by arismelachroinos** [comment]
Just run fluxion to test if everything is okay there, and when I came back to wifiphisher, I get only the network manager error, and the attacks work

**Comment by sophron** [comment]
@arismelachroinos So, if I understand correctly, is it working now?

**Comment by arismelachroinos** [comment]
@sophron It is, however I get the network manager error. Is there something I can do about it or its normal and does not affect anything?

**Comment by sophron** [comment]
@arismelachroinos I just pushed a commit that fixes this. Can you update to the latest revision and confirm?

**Comment by arismelachroinos** [comment]
@sophron  
Okay so I updated and tried again, and the following is the result of many tries:
1) I do not get the network manager error anymore at all.
2) When I type just "wifiphisher" alone [image 1 top] , then I do get the interesting "No handlers could be found for logger "wifiphisher.interfaces"" error again. I did try it many times so this error is stable to me. 
3) Launching fluxion does not fix 2). Not sure why I thought so the other day.
4) So lets say I ignore this error. I select my network and then I select the firmware upgrade page attack. Everything seems to be working okay, as the new AP is visible to my phone, however when I connect to it, nothing happens. Just no connection notification. The notification that takes me to the login screen, does not appear.
5) When I launch the fb credentials attack [image 1 bottom] , I do not get any error whatsoever. So the network does show up, however when I connect into it from my phone, it just tells me to agree that there is no wifi connection. The message that takes me to the fb login screen is not there anymore for me. This was tested 3 times.
6) Something minor I noticed is that if I am running lets say the firmware upgrade attack, when I manually connect to the network from my phone, it shows up as a KARMA attack. Is this normal?

Image 1:
![screenshot_9](https://user-images.githubusercontent.com/21193898/42736137-7b90390c-8869-11e8-961d-3dd302cd3d0a.jpg)

Is there something I could try? Is there maybe something wrong with my system?

**Comment by sophron** [comment]
Hi @arismelachroinos and thanks for all the testing you are doing.

> I do not get the network manager error anymore at all.

Yes, my yesterday commit was about this.

> When I type just "wifiphisher" alone [image 1 top] , then I do get the interesting "No handlers could be found for logger "wifiphisher.interfaces"" error again. I did try it many times so this error is stable to me.
Launching fluxion does not fix 2). Not sure why I thought so the other day.

This does not affect anything. I'm planning to fix it during the week.

> So lets say I ignore this error. I select my network and then I select the firmware upgrade page attack. Everything seems to be working okay, as the new AP is visible to my phone, however when I connect to it, nothing happens. Just no connection notification. The notification that takes me to the login screen, does not appear.

You won't necessarily see this notification. It depends on the network manager and whether the network that you are trying to connect is known (i.e. you have connected to it in the past). 

> When I launch the fb credentials attack [image 1 bottom] , I do not get any error whatsoever. So the network does show up, however when I connect into it from my phone, it just tells me to agree that there is no wifi connection. The message that takes me to the fb login screen is not there anymore for me. This was tested 3 times.

What do you mean by "tells you to agree that there is no wifi connection".

The way to test if it's properly working or not, is by visiting an HTTP page and checking if the redirection to the phishing page is working.

> Something minor I noticed is that if I am running lets say the firmware upgrade attack, when I manually connect to the network from my phone, it shows up as a KARMA attack. Is this normal?

That's a bug from our side. I'll fix it soon.

**Comment by sophron** [comment]
@arismelachroinos I'm closing this. Feel free to re-open if needed.
