### ISSUE TITLE
DEAUTH doesnt work. help me pls

### ISSUE THREAD

**Issue by saxanaa** [wifiphisher/wifiphisher#970]
DEAUTH doesnt work. help me pls . i using 2 usp wifi adapters. Tp-link wn821n

**Comment by anakin1028** [comment]
Can you use wireshark to capture the pcap file and post here? Probably your adaptor doesn't support Monitor Mode TX.

**Comment by saxanaa** [comment]
this?
[555.zip](https://github.com/wifiphisher/wifiphisher/files/2196334/555.zip)

and i tried this command : aireplay-ng -9 wlan0 . and i got this  :
04:25:16  Trying broadcast probe requests...
04:25:16  Injection is working!
04:25:17  Found 2 APs

**Comment by anakin1028** [comment]
The pcap file you give is not captured by wireless interface. You can select the monitor mode interface to capture again. 

But from the log of `aireplay-ng` it looks like your adapter is workable for injection. How do you know DEATH is not work for Wifiphisher?

**Comment by sophron** [comment]
Please read the FAQ: http://wifiphisher.readthedocs.io/en/latest/faq.html#why-does-deauthentication-is-not-always-working

If you think you are dealing with a software bug, open a new issue and try to provide as much information as possible in order for a developer to be able to reproduce it.
