### ISSUE TITLE
Can ask client his/her full name in phishing page?

### ISSUE THREAD

**Issue by djdisikd** [wifiphisher/wifiphisher#980]
The full name might be the wifi password

If the client puts his/her name, we will capture it

**Comment by sophron** [comment]
The chances are extremely low. But you can adjust the phishing page or <a href="http://wifiphisher.readthedocs.io/en/latest/custom_phishing_scenario.html">create a phishing scenario</a> that fits your needs.

**Comment by djdisikd** [comment]
It is too complicated
