### ISSUE TITLE
No internet with fake AP

### ISSUE THREAD

**Issue by kantorth** [wifiphisher/wifiphisher#981]
<pre>git show | grep commit
commit 241d7da1c0cb8de56192266d26439974e989adbe
</pre>

I'm exceedingly new to this all, including github, so i apologize if this is an absolute mess, but here it is.
Prior, I had been using fluxion but i have just made the change to wifiphisher. I love the UI, but whenever I try to run it, i get an error "Errno 98] Address already in use". I don't know if it's a port issue, and if it is, I have no clue how to alleviate said issue. 

Here is the output, I get it both when the program starts AND when I close it. 

<pre><font color="#EF2929"><b>root@kali</b></font>:<font color="#729FCF"><b>~</b></font># wifiphisher
[<font color="#FCE94F">*</font>] Starting Wifiphisher 1.4GIT ( https://wifiphisher.org ) at 2018-07-29 01:56
[<font color="#4E9A06">+</font>] Selecting <font color="#4E9A06">wlan1</font> interface for the deauthentication attack
[<font color="#4E9A06">+</font>] Selecting <font color="#4E9A06">wlan0</font> interface for creating the rogue Access Point
[<font color="#CC0000">!</font>] The MAC address could not be set. (Tried 00:00:00:09:eb:fe)
[<font color="#FCE94F">*</font>] Cleared leases, started DHCP, set up iptables
[<font color="#4E9A06">+</font>] Selecting Network Manager Connect template
[<font color="#FCE94F">*</font>] Starting the fake access point...
[<font color="#FCE94F">*</font>] Starting HTTP/HTTPS server at ports 8080, 443
Exception in thread Thread-7:
Traceback (most recent call last):
  File &quot;/usr/lib/python2.7/threading.py&quot;, line 801, in __bootstrap_inner
    self.run()
  File &quot;/usr/lib/python2.7/threading.py&quot;, line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File &quot;/usr/local/lib/python2.7/dist-packages/wifiphisher-1.4-py2.7.egg/wifiphisher/common/phishinghttp.py&quot;, line 180, in runHTTPServer
    https_server.listen(ssl_port, address=ip)
  File &quot;/usr/local/lib/python2.7/dist-packages/tornado-4.5.3-py2.7-linux-x86_64.egg/tornado/tcpserver.py&quot;, line 142, in listen
    sockets = bind_sockets(port, address=address)
  File &quot;/usr/local/lib/python2.7/dist-packages/tornado-4.5.3-py2.7-linux-x86_64.egg/tornado/netutil.py&quot;, line 197, in bind_sockets
    sock.bind(sockaddr)
  File &quot;/usr/lib/python2.7/socket.py&quot;, line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address already in use
</pre>

**Comment by sophron** [comment]
Hi @kantorth,

That means that something else is binded to port 8080 or port 443. Wifiphisher needs these ports free for the HTTP/HTTPS server.

You can do a `netstat -tulpn | grep :80` and `netstat -tulpn | grep :443` to see what is there. You will have to kill this process and run Wifiphisher again. 

If for some reason you need that process alive and binded to that port, you can edit the file `wifiphisher/common/constants.py`, find the values `PORT` and `SSL_PORT` there and change them to something else.

**Comment by kantorth** [comment]
<pre><font color="#EF2929"><b>oot@kali</b></font>:<font color="#729FCF"><b>~/wifiphisher</b></font># netstat -tulpn | grep :80
tcp        0      0 0.0.0.0:80              0.0.0.0:*               LISTEN      24595/lighttpd      
<font color="#EF2929"><b>root@kali</b></font>:<font color="#729FCF"><b>~/wifiphisher</b></font># netstat -tulpn | grep :443
tcp        0      0 0.0.0.0:443             0.0.0.0:*               LISTEN      24595/lighttpd  </pre>


That's the output of those commands. Again, I'm really new to this, So I don't really know what I'm looking at here, let alone what commands to execute with this information.

Thanks for the reply, @sophron !

**Comment by sophron** [comment]
You can see that lighthttpd process is running. So you need to `/etc/init.d/lighttpd stop` and run Wifiphisher again.
