### ISSUE TITLE
Unmanaged devices

### ISSUE THREAD

**Issue by rollly00** [wifiphisher/wifiphisher#986]
This error : 

> You need to manually set the devices that should be ignored by NetworkManager using the keyfile plugin (unmanaged-directive). For example, '[keyfile] unmanaged-devices=interface-name:"wlan1"' needs to be added in your NetworkManager configuration file.

I edit NetworkManager.conf : 
```
[main]
plugins=ifupdown,keyfile

[ifupdown]
managed=true


[keyfile]
unmanaged-devices=mac:my-mac;interface-name:wlan1
```
But the error did not disappear.

**Comment by sophron** [comment]
I believe you need the add the quotes surrounding the interface name too.
