### ISSUE TITLE
Unable to install hostapd

### ISSUE THREAD

**Issue by djdisikd** [wifiphisher/wifiphisher#987]
![img_20180811_163752](https://user-images.githubusercontent.com/17978000/43992886-c3329fee-9db7-11e8-9d41-0e331d8ae60f.jpg)

**Comment by sophron** [comment]
The error message should be clear. Furthermore, this has to do with your Kali LInux installation and not Wifiphisher. Finally, you have opened this issue many times in the past years (e.g. #390).

Please don't open any more issues like this.
