### ISSUE TITLE
error 98 while using wifiphisher

### ISSUE THREAD

**Issue by joseph-sebastian720** [wifiphisher/wifiphisher#988]
.

**Version**:wifphisher

**Description**:while using it second time and always after that 
![screenshot from 2018-08-13 00-19-52](https://user-images.githubusercontent.com/42324177/44005479-cd055180-9e91-11e8-84d5-b865dc1344cb.png)
error 98 while trying to create fake AP.and while connecting to the fake AP it won't show the firmware upgrade signing page 

**Script output**: Paste the output of the tool, including any stack traces.

**Comment by anakin1028** [comment]
This looks like the port:8080 is used by other process on your system already. Maybe you can follow this link to solve the problem.
https://www.google.com.tw/url?sa=t&source=web&rct=j&url=https://stackoverflow.com/questions/17780291/python-socket-error-errno-98-address-already-in-use&ved=2ahUKEwjZg4nmpfncAhXCA4gKHeu6BscQjjgwAHoECAMQAQ&usg=AOvVaw2gTjFCifpqVVG0n46Pznac
