### ISSUE TITLE
Small error on terminal 

### ISSUE THREAD

**Issue by arismelachroinos** [wifiphisher/wifiphisher#989]
**Version**:  
commit 241d7da1c0cb8de56192266d26439974e989adbe

**Description**: 
Whenever I am launching an attack via the script menu, after I go to the sign in page on my phone, then some errors appear on terminal. They do not seem to affect anything, is this normal? Is there any way to fix those? I am almost sure the script has nothing to do with it, just saying if you know what it is. Also a temporal fix is to resize the window and the previous errors go away.
![screenshot_52](https://user-images.githubusercontent.com/21193898/44482833-213d6180-a652-11e8-93e8-d2edf8a9e543.jpg)

**Comment by corkskull** [comment]
I have the same problem, try choosing the target manually (In my case worked). Use wifiphisher -e TARGET.

**Comment by saadqais96** [comment]
I also have the same problem!!
I hope the solution

**Comment by JetseVerschuren** [comment]
Can you post a wireshark dump?

**Comment by sophron** [comment]
Hi @arismelachroinos,

This error is bothering us for quite some time now (see #914, #439).

The error shouldn't have any impact on the attack and one can possibly work around using --log option.

**Comment by sophron** [comment]
Let's stick to  #914, #439.
