### ISSUE TITLE
Dont open page for android  just in apple .

### ISSUE THREAD

**Issue by saadqais96** [wifiphisher/wifiphisher#991]

**Comment by JetseVerschuren** [comment]
Can you provide more information?

**Comment by saadqais96** [comment]
# #
![screenshot_ -](https://user-images.githubusercontent.com/40874037/44620307-ff192e80-a85f-11e8-8aea-7238281965d1.png) 
in samsung galaxy not open

**Comment by JetseVerschuren** [comment]
Try clicking advanced and then proceed to to insecure site. You mentioned in the title that apple did work. Do you mean that you don't get the error?

**Comment by saadqais96** [comment]
Samsung is not only converted to the counterfeit page

**Comment by dipusone** [comment]
I can confirm that on Samsung devices running android Orero the captive portal is not detected. On other android/ios/linux/windows it works.

**Comment by JetseVerschuren** [comment]
Can you post a Wireshark dump of your ap interface so we can diagnostic the issue.

**Comment by sophron** [comment]
#1029
