### ISSUE TITLE
Invalid Interface

### ISSUE THREAD

**Issue by brandontict** [wifiphisher/wifiphisher#992]
**Version**:
1.4 `00e937be6373baedaec45549e20fa34c2320e8aa`

**Description**: 

Using wlan1 (AWUS036ACH) as EXTENSIONSINTERFACE , built in wlan0  (Centrino Advanced-N 6235)  as the APINTERFACE and receiving this error. 

I have tried putting card into monitor mode manually and with airmon-ng .I've also tried to switch the card order around with same results. * Should I  use the stronger adapter as the AP instead of EXTENSION ? Both cards support monitor mode.

 **wifiphiser output**

`./wifiphisher -eI wlan1 -aI wlan0 -dE -kB
[*] Starting Wifiphisher 1.4GIT ( https://wifiphisher.org ) at 2018-08-25 22:24
[!] The provided interface "wlan1" is invalid!Interface wlan1 doesn't support monitor mode
`

**dmesg output** 

` dmesg | grep -i wlan1
[  269.442620] IPv6: ADDRCONF(NETDEV_UP): wlan1: link is not ready
`

Not sure if dmesg is relevant, but error is happening during and after executing wifiphisher  

**iwconfig output**

`iwconfig 
wlan1     unassociated  Nickname:"<WIFI@REALTEK>"
          Mode:Monitor  Frequency=2.462 GHz  Access Point: Not-Associated   
          Sensitivity:0/0  
          Retry:off   RTS thr:off   Fragment thr:off
          Encryption key:off
          Power Management:off
          Link Quality=0/100  Signal level=0 dBm  Noise level=0 dBm
          Rx invalid nwid:0  Rx invalid crypt:0  Rx invalid frag:0
          Tx excessive retries:0  Invalid misc:0   Missed beacon:0

eth0      no wireless extensions.

lo        no wireless extensions.

wlan0     IEEE 802.11  ESSID:"XXXX"  
          Mode:Managed  Frequency:2.462 GHz  Access Point: 
          Bit Rate=43.3 Mb/s   Tx-Power=15 dBm   
          Retry short limit:7   RTS thr:off   Fragment thr:off
          Encryption key:off
          Power Management:off
          Link Quality=44/70  Signal level=-66 dBm  
          Rx invalid nwid:0  Rx invalid crypt:0  Rx invalid frag:0
          Tx excessive retries:7  Invalid misc:22835   Missed beacon:0`

**Comment by sophron** [comment]
By default, Wifiphisher will automatically pick the right interfaces for you. If you are receiving this error, I'm afraid none of your cards (or the drivers associated with these adapters) support monitor mode.

**Comment by brandontict** [comment]
Thanks for the reply. 
 
airmon-ng & kismet work on both cards in monitor mode . 

Also packet injection on both cards. Tested via  aireplay-ng .
`aireplay-ng -9 wlan1
11:28:51  Trying broadcast probe requests...
11:28:52  Injection is working!
11:28:52  Found X APs
`
wifiphisher was working with both cards at first. I must of made a change , or an update to throw something off.

I've been using kimcoder's AWUS036ACH drivers [https://github.com/kimocoder/rtl8812au](url) . 

Does wifiphisher use airmon-ng to put the card into monitor mode? 

Racking my brain on what change may have happen to throw this error.

**Comment by kimocoder** [comment]
which branch of my drivers are you using?

**Comment by brandontict** [comment]
v5.15 

Should I be using 5.3.4?

**Comment by kimocoder** [comment]
v5.2.20 (actually v5.2.20.2) is the latest "stable"
v5.3.4 is experimental atm, but you may try it anyway, it works and it's a better base, more fixes but also is under active develop til.

**Comment by brandontict** [comment]
Great, That's what I will do. 

I really appreciate the work you are doing with the rtl8812 chip set ! 
As well as every one who made wifiphisher happen, Much gratitude all around .
