### ISSUE TITLE
not working in MacOS

### ISSUE THREAD

**Issue by menjilx** [wifiphisher/wifiphisher#993]
Hi everyone, I need your help why the program doesn't work on my machine?

Running on the VirtualBox Kali Linux 64
---
![image](https://user-images.githubusercontent.com/14908836/44633852-11f84400-a9c3-11e8-93c2-9a97fb15ff1e.png)

**Comment by sophron** [comment]
Hi @menjilx,

The error is self-explanatory.

You will have to bridge a wireless adapter that supports monitor mode from your host to your Kali Linux VM to run Wifiphisher.

**Comment by menjilx** [comment]
@sophron can you recommend an adapter that still works right now?

**Comment by sophron** [comment]
There are many: https://github.com/wifiphisher/wifiphisher/issues/558
