### ISSUE TITLE
Iptables Command Fails

### ISSUE THREAD

**Issue by blackHatMonkey** [wifiphisher/wifiphisher#996]
**Version**: 6a5b06233bfb1ef21061bb221b5bee83e66855d0

**Description**: `iptables` command fails.

**Script output**: 
Here is the data from the logs
```
wifiphisher.common.utilities - ERROR - iptables -t nat -A PREROUTING -p tcp --dport 80 -j DNAT--to-destination 10.0.0.1:8080 has failed with the following error:
Bad argument `10.0.0.1:8080'
Try `iptables -h' or 'iptables --help' for more information.

wifiphisher.common.utilities - ERROR - iptables -t nat -A PREROUTING -p udp --dport 53 -j DNAT--to-destination 10.0.0.1:53 has failed with the following error:
Bad argument `10.0.0.1:53'
Try `iptables -h' or 'iptables --help' for more information.

wifiphisher.common.utilities - ERROR - iptables -t nat -A PREROUTING -p tcp --dport 53 -j DNAT--to-destination 10.0.0.1:53 has failed with the following error:
Bad argument `10.0.0.1:53'
Try `iptables -h' or 'iptables --help' for more information.

wifiphisher.common.utilities - ERROR - iptables -t nat -A PREROUTING -p tcp --dport 443 -j DNAT--to-destination 10.0.0.1:443 has failed with the following error:
Bad argument `10.0.0.1:443'
Try `iptables -h' or 'iptables --help' for more information.
```

**Comment by JetseVerschuren** [comment]
When I run that iptables command on my machine I get the same iptables error.

**Comment by sophron** [comment]
@blackHatMonkey Are you sure you are using the latest revision?

There was a missing blank that @theguly fixed a while ago: https://github.com/wifiphisher/wifiphisher/commit/66d387053e293992d991922cb5bfd29081c4a57a

**Comment by blackHatMonkey** [comment]
@sophron You are correct. Somehow my test machine was still running that old code :confused:.

**Comment by N2Network** [comment]
Can anyone offer advice on this error?

[*] Starting Wifiphisher 1.4GIT ( https://wifiphisher.org ) at 2019-03-26 04:33
[+] Timezone detected. Setting channel range to 1-13
[+] Selecting wfphshr-wlan0 interface for the deauthentication attack
[+] Selecting wlan0 interface for creating the rogue Access Point
[+] Changing wlan0 MAC addr (BSSID) to 00:00:00:2f:29:b9
[!] The MAC address could not be set. (Tried 00:00:00:49:2d:b5)
[+] Sending SIGKILL to wpa_supplicant
[+] Sending SIGKILL to dhclient
[+] Sending SIGKILL to NetworkManager
No handlers could be found for logger "wifiphisher.common.utilities"
[*] Cleared leases, started DHCP, set up iptables
[+] Selecting Google Login template
[*] Starting the fake access point...
[*] Starting HTTP/HTTPS server at ports 8080, 443
[+] Show your support!
[+] Follow us: https://twitter.com/wifiphisher
[+] Like us: https://www.facebook.com/Wifiphisher
[+] Captured credentials:
[!] The MAC address could not be set. (Tried 9c:ef:d5:fd:d6:75)
ERROR:wifiphisher.common.utilities:iptables -F has failed with the following error:
iptables: Operation not supported.

ERROR:wifiphisher.common.utilities:iptables -X has failed with the following error:
iptables: Operation not supported.

ERROR:wifiphisher.common.utilities:iptables -t nat -F has failed with the following error:
iptables: Operation not supported.

ERROR:wifiphisher.common.utilities:iptables -t nat -X has failed with the following error:
iptables: Operation not supported.

**Comment by sophron** [comment]
@N2Network What distro are you using?

**Comment by N2Network** [comment]
I originally had it all setup on Debian Stretch. But I was having issues with Deauth and AWUS1900 so I just installed Linux kali-pi 4.14.93-Re4son-v7+ #1 SMP Thu Jan 24 12:44:19 AEDT 2019 armv7l GNU/Linux
