### ISSUE TITLE
error: [Errno 100] Network is down

### ISSUE THREAD

**Issue by christmex** [wifiphisher/wifiphisher#998]
commit 62ebce82fe54a718870afbde1615233ba783db3b

why this happen??? any andvice for me? please help, i cant use it

```
Exception in thread Thread-4:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/root/wifiphisher/wifiphisher/common/recon.py", line 364, in _sniff_packets
    store=0)
  File "/usr/local/lib/python2.7/dist-packages/scapy/sendrecv.py", line 577, in sniff
    p = s.recv(MTU)
  File "/usr/local/lib/python2.7/dist-packages/scapy/arch/linux.py", line 493, in recv
    pkt, sa_ll = self.ins.recvfrom(x)
error: [Errno 100] Network is down
```

**Comment by MinePro120** [comment]
What wireless adapter do you use?

**Comment by christmex** [comment]
> What wireless adapter do you use?

i use the lates version of wifiphisher

**Comment by christmex** [comment]
> What wireless adapter do you use?

and i use the lates version ubuntu 18.04

**Comment by christmex** [comment]
i have been use wifiphisher in kali linux before, with the same laptop, and then now i change the os from kali linux to ubuntu

**Comment by MinePro120** [comment]
chistmex that wasn't my question. So, your wireless adapter supports monitor mode and packet injection?

**Comment by christmex** [comment]
> chistmex that wasn't my question. So, your wireless adapter supports monitor mode and packet injection?
how to i know? but i think yes , im sorry

**Comment by JetseVerschuren** [comment]
Try the solution in #142. The problem seems similar.

**Comment by MinePro120** [comment]
Not exactly I'm afraid. In my case airmon-ng check kill (which is a necessity when attacking Wi-Fi networks) doesn't help with this issue.

**Comment by christmex** [comment]
> Use sudo airmon-ng and post the output.

in imy ubuntu 18.04 the output like this = "sudo: airmon-ng: command not found"
i think this the problem ? i must to install aircrak before?

**Comment by christmex** [comment]
> Try the solution in #142. The problem seems similar.
okay thnks ... i will see and try

**Comment by christmex** [comment]
> I thought you were using Kali linux, which is the officially supported distro by wifiphisher. I don't know about Ubuntu. Maybe you could try on kali. Try a live usb. Also, it is recommended to use a Wi-Fi card that supports monitor mode and packet injection : goo.gl/TD9oEA.
its oky .. thnks for your attention and your help. God bless you

**Comment by algisju** [comment]
Dunno; tried re-compiling the driver... Nothing does.
airodump-ng spit out all clients tho....

![image](https://user-images.githubusercontent.com/69957906/130612413-a6f685cb-22b4-43e4-a65a-12b593679495.png)
